/**
 * StudyBuddy sprint tracker — static task definitions.
 *
 * The list itself never changes. Only per-task STATUS lives in Supabase
 * (table: studybuddy_task_status, keyed by `id`). Keep this file as a
 * plain data export so it tree-shakes cleanly into the client bundle.
 */

export type Role = 'PM' | 'KI' | 'FE' | 'QA' | 'BE'
export type Person = 'Leon' | 'Taycir' | 'Ayoub' | 'Sara' | 'Abder'
export type Status = 'todo' | 'wip' | 'help' | 'done'
export type Week = 'W1' | 'W2' | 'W3' | 'W4'

export type Task = {
  id: string
  w: Week
  who: Person
  role: Role
  text: string
}

export type Sprint = {
  num: string // "01" .. "09"
  month: string
  title: string
  subtitle: string
  dod: string
  tasks: Task[]
}

export const PERSONS: Person[] = ['Leon', 'Taycir', 'Ayoub', 'Sara', 'Abder']

export const ROLE_COLOR: Record<Role, string> = {
  PM: '#3b6fb5',
  KI: '#e07a3f',
  FE: '#2f8f6e',
  QA: '#b8533a',
  BE: '#5f4a8a',
}

export const STATUSES: Array<{ key: Status; emoji: string; label: string; color: string }> = [
  { key: 'todo', emoji: '⚪', label: 'Noch nicht',    color: '#6f6a5e' },
  { key: 'wip',  emoji: '🟡', label: 'In Arbeit',     color: '#d6a635' },
  { key: 'help', emoji: '🔴', label: 'Brauche Hilfe', color: '#b8533a' },
  { key: 'done', emoji: '🟢', label: 'Erledigt',      color: '#2f8f6e' },
]

export const SPRINTS: Sprint[] = [
  {
    num: '01',
    month: 'Mai 2026',
    title: 'Projektinitialisierung & Technische Grundlagen',
    subtitle: 'Repository, Frameworks, erstes Deployment & UI-Prototyp',
    dod: 'Repo öffentlich · CI läuft · „Hello StudyBuddy"-Seite live auf Vercel · Supabase-DB erreichbar',
    tasks: [
      { id: 's1-w1-01', w: 'W1', who: 'Leon',   role: 'PM', text: 'GitLab-Repository anlegen und Branch Protection für main & develop einrichten' },
      { id: 's1-w1-02', w: 'W1', who: 'Leon',   role: 'KI', text: 'Preise, Modellvarianten und Limits von Claude Sonnet recherchieren' },
      { id: 's1-w1-03', w: 'W1', who: 'Taycir', role: 'KI', text: 'Anthropic-Account erstellen, API-Key generieren und Setup dokumentieren' },
      { id: 's1-w1-04', w: 'W1', who: 'Taycir', role: 'PM', text: 'Sprint-1-Backlog mit allen Tickets vorbereiten' },
      { id: 's1-w1-05', w: 'W1', who: 'Ayoub',  role: 'FE', text: 'Next.js 14 mit TypeScript und Tailwind initialisieren und ins Repo pushen' },
      { id: 's1-w1-06', w: 'W1', who: 'Ayoub',  role: 'QA', text: 'Teststrategie-Dokument verfassen (welche Tests, welche Tools, welches Ziel)' },
      { id: 's1-w1-07', w: 'W1', who: 'Sara',   role: 'QA', text: 'GitLab-Wiki-Struktur und einheitliches Bug-Label-System anlegen' },
      { id: 's1-w1-08', w: 'W1', who: 'Sara',   role: 'FE', text: 'Landing-Page als Low-Fi-Wireframe entwerfen' },
      { id: 's1-w1-09', w: 'W1', who: 'Abder',  role: 'BE', text: 'Supabase-Projekt in EU-Region Frankfurt anlegen und Zugänge sicher teilen' },

      { id: 's1-w2-01', w: 'W2', who: 'Leon',   role: 'PM', text: 'GitLab-Kanban-Board einrichten und Sprint-1-Tickets verteilen' },
      { id: 's1-w2-02', w: 'W2', who: 'Leon',   role: 'KI', text: 'Token-Limits und Kontextfenster der Claude-Modelle dokumentieren' },
      { id: 's1-w2-03', w: 'W2', who: 'Taycir', role: 'PM', text: 'Wöchentliche Team-Meetings planen und Dozent offiziell vorstellen' },
      { id: 's1-w2-04', w: 'W2', who: 'Taycir', role: 'KI', text: 'Prompt-Engineering-Grundlagen für das gesamte Team aufbereiten' },
      { id: 's1-w2-05', w: 'W2', who: 'Ayoub',  role: 'FE', text: 'Root-Layout sowie Button- und Input-Primitive in Tailwind bauen' },
      { id: 's1-w2-06', w: 'W2', who: 'Ayoub',  role: 'QA', text: 'ESLint- und Prettier-Konfiguration im Repo verankern' },
      { id: 's1-w2-07', w: 'W2', who: 'Sara',   role: 'QA', text: 'GitLab-CI-Pipeline (.gitlab-ci.yml) mit Lint, Typecheck, Build aufsetzen' },
      { id: 's1-w2-08', w: 'W2', who: 'Sara',   role: 'FE', text: 'Tailwind-Design-Tokens definieren (Farben, Abstände, Typografie)' },
      { id: 's1-w2-09', w: 'W2', who: 'Abder',  role: 'BE', text: 'Supabase-Client (client.ts), .env.example und Tabellen-Stubs anlegen' },

      { id: 's1-w3-01', w: 'W3', who: 'Leon',   role: 'PM', text: 'Code-Reviews aller Merge Requests organisieren und Dozenten-Update halten' },
      { id: 's1-w3-02', w: 'W3', who: 'Leon',   role: 'KI', text: 'Mit Taycir erste Prompt-Entwürfe für Themen-Extraktion ausarbeiten' },
      { id: 's1-w3-03', w: 'W3', who: 'Taycir', role: 'KI', text: 'Ersten Themen-Extraktions-Prompt entwerfen (Konzept, noch ohne Code)' },
      { id: 's1-w3-04', w: 'W3', who: 'Taycir', role: 'PM', text: 'Initiales Risiko-Log mit konkreten Gegenmaßnahmen erstellen' },
      { id: 's1-w3-05', w: 'W3', who: 'Ayoub',  role: 'FE', text: 'Landing-Page bauen (Hero, Call-to-Action, Footer, responsives Layout)' },
      { id: 's1-w3-06', w: 'W3', who: 'Ayoub',  role: 'QA', text: 'Snapshot-Tests für die ersten Tailwind-Komponenten aufsetzen' },
      { id: 's1-w3-07', w: 'W3', who: 'Sara',   role: 'FE', text: 'Login-Seite als statisches Formular bauen (noch ohne Auth-Logik)' },
      { id: 's1-w3-08', w: 'W3', who: 'Sara',   role: 'QA', text: 'Merge-Request-Template und erste README-Version schreiben' },
      { id: 's1-w3-09', w: 'W3', who: 'Abder',  role: 'BE', text: 'Health-Check-Endpoint bauen und Dokumenten-Schema in der DB entwerfen' },

      { id: 's1-w4-01', w: 'W4', who: 'Leon',   role: 'PM', text: 'Folien für Sprint-Review vorbereiten und Retrospektive moderieren' },
      { id: 's1-w4-02', w: 'W4', who: 'Leon',   role: 'KI', text: 'Pair-Programming-Session mit Ayoub zur Einarbeitung in den UI-Code' },
      { id: 's1-w4-03', w: 'W4', who: 'Taycir', role: 'PM', text: 'Demo-Skript für die Sprint-Review-Präsentation schreiben' },
      { id: 's1-w4-04', w: 'W4', who: 'Taycir', role: 'KI', text: 'Erste DSGVO-Notizen zur Nutzung der Anthropic-API zusammenstellen' },
      { id: 's1-w4-05', w: 'W4', who: 'Ayoub',  role: 'QA', text: 'CI-Pipeline auf allen Merge Requests verifizieren (alles grün)' },
      { id: 's1-w4-06', w: 'W4', who: 'Ayoub',  role: 'FE', text: 'Landing-Page polieren und Responsive-Check auf Mobile durchführen' },
      { id: 's1-w4-07', w: 'W4', who: 'Sara',   role: 'FE', text: 'Login-Seite auf Smartphone und Tablet visuell prüfen' },
      { id: 's1-w4-08', w: 'W4', who: 'Sara',   role: 'QA', text: 'Sprint-1-Testbericht verfassen (Coverage, offene Bugs, Fazit)' },
      { id: 's1-w4-09', w: 'W4', who: 'Abder',  role: 'BE', text: 'Vercel-Projekt einrichten, Auto-Deploy aktivieren, Custom-Domain konfigurieren' },
    ],
  },
  {
    num: '02',
    month: 'Juni 2026',
    title: 'KI-Konzept & Dokumentenverarbeitung',
    subtitle: 'PDF rein, strukturierter Text raus, erste KI-Antworten',
    dod: 'PDF-Upload funktioniert · Text wird extrahiert & gespeichert · Claude beantwortet erste Testfrage',
    tasks: [
      { id: 's2-w1-01', w: 'W1', who: 'Leon',   role: 'PM', text: 'Sprint-Planung moderieren und detaillierten User-Journey-Workshop durchführen' },
      { id: 's2-w1-02', w: 'W1', who: 'Leon',   role: 'KI', text: 'Anthropic-SDK-Setup mit Taycir Schritt für Schritt durchgehen' },
      { id: 's2-w1-03', w: 'W1', who: 'Taycir', role: 'KI', text: 'Anthropic-SDK ins Next.js-Projekt integrieren und ersten API-Call zeigen' },
      { id: 's2-w1-04', w: 'W1', who: 'Taycir', role: 'PM', text: 'Architektur-Entscheidung zur KI-Anbindung dokumentieren (ADR)' },
      { id: 's2-w1-05', w: 'W1', who: 'Ayoub',  role: 'FE', text: 'PDF-Upload-Komponente mit Drag-and-Drop und Datei-Auswahl bauen' },
      { id: 's2-w1-06', w: 'W1', who: 'Ayoub',  role: 'QA', text: 'Test-Fixtures: 5 repräsentative Beispiel-PDFs sammeln und versionieren' },
      { id: 's2-w1-07', w: 'W1', who: 'Sara',   role: 'FE', text: 'Upload-Fortschrittsanzeige und Loading-States für den Upload-Flow' },
      { id: 's2-w1-08', w: 'W1', who: 'Sara',   role: 'QA', text: 'Unit-Tests für die Upload-Komponente schreiben (Validierung, Fehler)' },
      { id: 's2-w1-09', w: 'W1', who: 'Abder',  role: 'BE', text: 'Supabase-Storage-Bucket „pdfs" anlegen und Upload-API-Route bauen' },

      { id: 's2-w2-01', w: 'W2', who: 'Leon',   role: 'KI', text: 'Mit Taycir erstes Prompt-Template für „Frage zum Text" entwerfen' },
      { id: 's2-w2-02', w: 'W2', who: 'Leon',   role: 'PM', text: 'Budget-Tracking-Dashboard für API-Kosten aufsetzen (Tagesgrenzen)' },
      { id: 's2-w2-03', w: 'W2', who: 'Taycir', role: 'PM', text: 'Integration zwischen Frontend, Backend und KI täglich koordinieren' },
      { id: 's2-w2-04', w: 'W2', who: 'Taycir', role: 'KI', text: 'Mehrere Prompt-Varianten testen und Token-Counting-Helper schreiben' },
      { id: 's2-w2-05', w: 'W2', who: 'Ayoub',  role: 'FE', text: 'Dokumenten-Listenansicht bauen (alle hochgeladenen PDFs des Nutzers)' },
      { id: 's2-w2-06', w: 'W2', who: 'Ayoub',  role: 'QA', text: 'Test-Stage in der CI-Pipeline ergänzen (Jest läuft auf jeden MR)' },
      { id: 's2-w2-07', w: 'W2', who: 'Sara',   role: 'QA', text: 'Bug-Triage-Prozess dokumentieren (Wer, wann, nach welchen Kriterien?)' },
      { id: 's2-w2-08', w: 'W2', who: 'Sara',   role: 'FE', text: 'Wiederverwendbare Error-State-UI-Komponenten für API-Fehler bauen' },
      { id: 's2-w2-09', w: 'W2', who: 'Abder',  role: 'BE', text: 'PDF-Textextraktion mit pdf-parse umsetzen und Text in DB speichern' },

      { id: 's2-w3-01', w: 'W3', who: 'Leon',   role: 'PM', text: 'API-Kosten täglich monitoren und Wochenstatus an Dozent kommunizieren' },
      { id: 's2-w3-02', w: 'W3', who: 'Leon',   role: 'KI', text: 'Mit Taycir Ende-zu-Ende-Manual-Test durchführen (Upload bis Antwort)' },
      { id: 's2-w3-03', w: 'W3', who: 'Taycir', role: 'KI', text: 'End-to-End-Flow live zeigen: PDF → Text → Claude-Antwort im UI' },
      { id: 's2-w3-04', w: 'W3', who: 'Taycir', role: 'PM', text: 'Risiko-Update: OCR-Fallback-Entscheidung für gescannte PDFs treffen' },
      { id: 's2-w3-05', w: 'W3', who: 'Ayoub',  role: 'FE', text: 'Dokumenten-Detailseite mit Text-Preview und Lade-/Fehlerzuständen' },
      { id: 's2-w3-06', w: 'W3', who: 'Ayoub',  role: 'QA', text: 'Playwright-Smoke-Test einrichten (Browser öffnet App, Hauptpfad)' },
      { id: 's2-w3-07', w: 'W3', who: 'Sara',   role: 'QA', text: 'End-to-End-Test des kompletten Upload-Flows in Playwright schreiben' },
      { id: 's2-w3-08', w: 'W3', who: 'Sara',   role: 'FE', text: 'Responsive-Layout der neuen Seiten für Mobile prüfen und anpassen' },
      { id: 's2-w3-09', w: 'W3', who: 'Abder',  role: 'BE', text: '/api/extract-Route mit sauberer Fehlerbehandlung und OCR-Recherche' },

      { id: 's2-w4-01', w: 'W4', who: 'Leon',   role: 'PM', text: 'Sprint-Review mit Live-Demo halten und Retrospektive moderieren' },
      { id: 's2-w4-02', w: 'W4', who: 'Leon',   role: 'KI', text: 'Bericht „Kosten pro Upload" mit Taycir erstellen (Tokens, Euro)' },
      { id: 's2-w4-03', w: 'W4', who: 'Taycir', role: 'KI', text: 'Bewährte Prompt-Patterns im Repo unter docs/prompts/ dokumentieren' },
      { id: 's2-w4-04', w: 'W4', who: 'Taycir', role: 'PM', text: 'Sprint-Demo final vorbereiten (Drehbuch, Demo-Daten, Backup-Plan)' },
      { id: 's2-w4-05', w: 'W4', who: 'Ayoub',  role: 'FE', text: 'Upload-UX polieren: Empty-States, klare Fehlermeldungen, Bestätigungen' },
      { id: 's2-w4-06', w: 'W4', who: 'Ayoub',  role: 'QA', text: 'Regressions-Checkliste für die Demo-Day-Tests erstellen' },
      { id: 's2-w4-07', w: 'W4', who: 'Sara',   role: 'QA', text: 'Sprint-2-Testbericht schreiben (was wurde getestet, was fehlt noch?)' },
      { id: 's2-w4-08', w: 'W4', who: 'Sara',   role: 'FE', text: 'Letzte visuelle Politur vor der Sprint-Demo' },
      { id: 's2-w4-09', w: 'W4', who: 'Abder',  role: 'BE', text: 'Performance-Test mit großen PDFs (50+ Seiten) und Token-Helper finalisieren' },
    ],
  },
  {
    num: '03',
    month: 'Juli 2026',
    title: 'Themenextraktion & Fragegenerierung',
    subtitle: 'Aus Skripten werden lernbare Einheiten – das Herzstück',
    dod: 'Mind. 10 sinnvolle Fragen pro Hauptthema generiert · manuelle Qualitätsbewertung dokumentiert',
    tasks: [
      { id: 's3-w1-01', w: 'W1', who: 'Leon',   role: 'PM', text: 'Sprint-Planung mit Workshop zur Bloom\'schen Taxonomie für Fragetypen leiten' },
      { id: 's3-w1-02', w: 'W1', who: 'Leon',   role: 'KI', text: 'Themen-Clustering-Prompt gemeinsam mit Taycir entwerfen' },
      { id: 's3-w1-03', w: 'W1', who: 'Taycir', role: 'KI', text: 'Themen-Clustering-Prompt schreiben und Chunking-Strategie für lange PDFs' },
      { id: 's3-w1-04', w: 'W1', who: 'Taycir', role: 'PM', text: 'Team-Kapazität in der Klausurphase prüfen und Scope ggf. anpassen' },
      { id: 's3-w1-05', w: 'W1', who: 'Ayoub',  role: 'FE', text: 'Dashboard-Layout bauen (Sidebar links, Hauptbereich rechts)' },
      { id: 's3-w1-06', w: 'W1', who: 'Ayoub',  role: 'QA', text: 'Eval-Set anlegen: 5 Beispiel-PDFs mit erwarteten Soll-Themen' },
      { id: 's3-w1-07', w: 'W1', who: 'Sara',   role: 'QA', text: 'Manuelles Bewertungs-Framework und Rubric für Frage-Qualität definieren' },
      { id: 's3-w1-08', w: 'W1', who: 'Sara',   role: 'FE', text: 'Themen-Karten-Komponente mit Anzahl Fragen und Fortschritt bauen' },
      { id: 's3-w1-09', w: 'W1', who: 'Abder',  role: 'BE', text: 'DB-Schema für topics und questions inkl. API-Routen erstellen' },

      { id: 's3-w2-01', w: 'W2', who: 'Leon',   role: 'KI', text: 'Fragegenerierungs-Prompt mit Taycir entwickeln (offen und Multiple Choice)' },
      { id: 's3-w2-02', w: 'W2', who: 'Leon',   role: 'PM', text: 'Dozenten-Update halten und Qualitäts-Reviews der KI-Ausgaben organisieren' },
      { id: 's3-w2-03', w: 'W2', who: 'Taycir', role: 'KI', text: 'Bloom-Level explizit im Prompt (Verstehen, Anwenden, Analysieren)' },
      { id: 's3-w2-04', w: 'W2', who: 'Taycir', role: 'PM', text: 'Backlog für die nächsten Wochen pflegen und Tickets priorisieren' },
      { id: 's3-w2-05', w: 'W2', who: 'Ayoub',  role: 'FE', text: 'Frageanzeige bauen: offene Eingabe und Multiple-Choice-Auswahl' },
      { id: 's3-w2-06', w: 'W2', who: 'Ayoub',  role: 'QA', text: 'Snapshot-Tests für die neuen Frage-Komponenten schreiben' },
      { id: 's3-w2-07', w: 'W2', who: 'Sara',   role: 'QA', text: 'Eval-Set gegen Generator laufen lassen und Qualitätsscores loggen' },
      { id: 's3-w2-08', w: 'W2', who: 'Sara',   role: 'FE', text: 'Themen-Detailseite mit Liste aller generierten Fragen bauen' },
      { id: 's3-w2-09', w: 'W2', who: 'Abder',  role: 'BE', text: 'Endpunkte /api/topics und /api/questions/generate implementieren' },

      { id: 's3-w3-01', w: 'W3', who: 'Leon',   role: 'PM', text: 'Backlog für Sprint 4 (Dialogsystem) gemeinsam mit dem Team groomen' },
      { id: 's3-w3-02', w: 'W3', who: 'Leon',   role: 'KI', text: 'Ergebnisse von Chain-of-Thought-Prompting mit Taycir evaluieren' },
      { id: 's3-w3-03', w: 'W3', who: 'Taycir', role: 'KI', text: 'Chain-of-Thought vs. direktes Prompting vergleichen und Sieger wählen' },
      { id: 's3-w3-04', w: 'W3', who: 'Taycir', role: 'PM', text: 'Risiko-Log aktualisieren (insbesondere Fragequalität und API-Kosten)' },
      { id: 's3-w3-05', w: 'W3', who: 'Ayoub',  role: 'FE', text: 'Frage-Navigation mit Tastatur-Shortcuts (Pfeiltasten, Enter) bauen' },
      { id: 's3-w3-06', w: 'W3', who: 'Ayoub',  role: 'QA', text: 'Accessibility-Scan des kompletten Dashboards durchführen' },
      { id: 's3-w3-07', w: 'W3', who: 'Sara',   role: 'FE', text: 'Themenliste polieren mit ansprechenden Empty-States' },
      { id: 's3-w3-08', w: 'W3', who: 'Sara',   role: 'QA', text: 'Regressions-Tests für die Themen-Extraktion schreiben' },
      { id: 's3-w3-09', w: 'W3', who: 'Abder',  role: 'BE', text: 'Fragen persistieren und Prompt-Version pro Eintrag in DB speichern' },

      { id: 's3-w4-01', w: 'W4', who: 'Leon',   role: 'PM', text: 'Sprint-Review mit Demo (Upload → Themen → 10 Fragen) und Retrospektive' },
      { id: 's3-w4-02', w: 'W4', who: 'Leon',   role: 'KI', text: 'Finale Prompts gemeinsam mit Taycir dokumentieren und versionieren' },
      { id: 's3-w4-03', w: 'W4', who: 'Taycir', role: 'KI', text: 'Prompt-Versionierung in docs/prompts/ formal etablieren (Changelog)' },
      { id: 's3-w4-04', w: 'W4', who: 'Taycir', role: 'PM', text: 'Demo-Skript final ausformulieren und mit dem Team rehearsalen' },
      { id: 's3-w4-05', w: 'W4', who: 'Ayoub',  role: 'FE', text: 'Dashboard polieren und Responsive-QA auf Tablet und Smartphone' },
      { id: 's3-w4-06', w: 'W4', who: 'Ayoub',  role: 'QA', text: 'Sprint-3-Testbericht inklusive Coverage-Werten verfassen' },
      { id: 's3-w4-07', w: 'W4', who: 'Sara',   role: 'QA', text: 'Qualitätsbericht der generierten Fragen schreiben und live testen' },
      { id: 's3-w4-08', w: 'W4', who: 'Sara',   role: 'FE', text: 'Letzte visuelle Politur für die Themen-Dashboard-Demo' },
      { id: 's3-w4-09', w: 'W4', who: 'Abder',  role: 'BE', text: 'Themen-Extraktion cachen und API-Kosten dauerhaft optimieren' },
    ],
  },
  {
    num: '04',
    month: 'August 2026',
    title: 'Interaktive Lernlogik & Dialogsystem',
    subtitle: 'Echter Lerndialog – Referenz: Dijkstra-Algorithmus',
    dod: 'Komplette Lernsession Frage → Antwort → Bewertung → Rückfrage → Abschluss · Fortschritt gespeichert',
    tasks: [
      { id: 's4-w1-01', w: 'W1', who: 'Leon',   role: 'PM', text: 'Sprint-Planung leiten und Dijkstra-Algorithmus als Referenz-Demo festlegen' },
      { id: 's4-w1-02', w: 'W1', who: 'Leon',   role: 'KI', text: 'Antwort-Analyse-Prompt gemeinsam mit Taycir entwerfen' },
      { id: 's4-w1-03', w: 'W1', who: 'Taycir', role: 'KI', text: 'Antwort-Analyse-Prompt schreiben (Klassifikation richtig/teilweise/falsch)' },
      { id: 's4-w1-04', w: 'W1', who: 'Taycir', role: 'PM', text: 'Synchronisations-Meeting zwischen UX und KI organisieren' },
      { id: 's4-w1-05', w: 'W1', who: 'Ayoub',  role: 'FE', text: 'Chat-UI-Grundgerüst bauen (Bubbles, Eingabefeld, Auto-Scroll)' },
      { id: 's4-w1-06', w: 'W1', who: 'Ayoub',  role: 'QA', text: 'Test-Szenarien für den gesamten Dialog-Flow definieren' },
      { id: 's4-w1-07', w: 'W1', who: 'Sara',   role: 'QA', text: 'Edge-Case-Szenarien sammeln (leere Antwort, Off-Topic, sehr lang)' },
      { id: 's4-w1-08', w: 'W1', who: 'Sara',   role: 'FE', text: 'Wiederverwendbare Message-Komponente in mehreren Varianten gestalten' },
      { id: 's4-w1-09', w: 'W1', who: 'Abder',  role: 'BE', text: 'DB-Schema für sessions, messages und progress anlegen' },

      { id: 's4-w2-01', w: 'W2', who: 'Leon',   role: 'KI', text: 'Pair-Programming mit Taycir an der Follow-up-Frage-Logik' },
      { id: 's4-w2-02', w: 'W2', who: 'Leon',   role: 'PM', text: 'Integration zwischen KI-Backend und Chat-Frontend täglich koordinieren' },
      { id: 's4-w2-03', w: 'W2', who: 'Taycir', role: 'KI', text: 'Rückfragen-Generierung bei erkannten Wissenslücken implementieren' },
      { id: 's4-w2-04', w: 'W2', who: 'Taycir', role: 'PM', text: 'Wöchentliches Dozenten-Update mit Live-Demo des aktuellen Stands' },
      { id: 's4-w2-05', w: 'W2', who: 'Ayoub',  role: 'FE', text: 'Streaming-Anzeige für Claude-Antworten und Typing-Animation einbauen' },
      { id: 's4-w2-06', w: 'W2', who: 'Ayoub',  role: 'QA', text: 'Unit-Tests für die Antwortbewertungs-Logik schreiben' },
      { id: 's4-w2-07', w: 'W2', who: 'Sara',   role: 'QA', text: 'End-to-End-Test einer kurzen Dialog-Session schreiben' },
      { id: 's4-w2-08', w: 'W2', who: 'Sara',   role: 'FE', text: 'Loading-States für laufende KI-Anfragen klar darstellen' },
      { id: 's4-w2-09', w: 'W2', who: 'Abder',  role: 'BE', text: 'Endpunkte /api/session/start und /api/session/answer mit Persistenz' },

      { id: 's4-w3-01', w: 'W3', who: 'Leon',   role: 'PM', text: 'UX-Feedback-Loop mit Team aufsetzen und Risiko Dialog-Qualität bewerten' },
      { id: 's4-w3-02', w: 'W3', who: 'Leon',   role: 'KI', text: 'Abbruchkriterien des Dialogs gemeinsam mit Taycir tunen' },
      { id: 's4-w3-03', w: 'W3', who: 'Taycir', role: 'KI', text: 'Mehrstufige Dialoglogik implementieren mit klarer Terminierungs-Bedingung' },
      { id: 's4-w3-04', w: 'W3', who: 'Taycir', role: 'PM', text: 'Backlog für Sprint 5 vorbereiten (Authentifizierung und DSGVO)' },
      { id: 's4-w3-05', w: 'W3', who: 'Ayoub',  role: 'FE', text: 'Fortschrittsbalken und Session-Zusammenfassung am Ende der Session' },
      { id: 's4-w3-06', w: 'W3', who: 'Ayoub',  role: 'QA', text: 'Accessibility-Check der Chat-UI (Screenreader, Tastatur-Nav)' },
      { id: 's4-w3-07', w: 'W3', who: 'Sara',   role: 'QA', text: 'Vollständigen E2E-Test der Dijkstra-Lernsession schreiben' },
      { id: 's4-w3-08', w: 'W3', who: 'Sara',   role: 'FE', text: 'Chat-Layout für Mobile optimieren (Tastatur, Scroll-Verhalten)' },
      { id: 's4-w3-09', w: 'W3', who: 'Abder',  role: 'BE', text: 'Session-State-Machine bauen und unterbrochene Sessions fortsetzen' },

      { id: 's4-w4-01', w: 'W4', who: 'Leon',   role: 'PM', text: 'Sprint-Review mit Live-Demo der vollständigen Dijkstra-Session halten' },
      { id: 's4-w4-02', w: 'W4', who: 'Leon',   role: 'KI', text: 'Finale Evaluation der Dijkstra-Demo (welche Fälle laufen, welche nicht?)' },
      { id: 's4-w4-03', w: 'W4', who: 'Taycir', role: 'KI', text: 'Prompts gezielt gegen die Dijkstra-Demo final tunen' },
      { id: 's4-w4-04', w: 'W4', who: 'Taycir', role: 'PM', text: 'Retrospektive moderieren und nächste Sprints justieren' },
      { id: 's4-w4-05', w: 'W4', who: 'Ayoub',  role: 'FE', text: 'Animationen und Mobile-Polish abschließen und Demo vorbereiten' },
      { id: 's4-w4-06', w: 'W4', who: 'Ayoub',  role: 'QA', text: 'Regressions-Suite für alle bisherigen Features laufen lassen' },
      { id: 's4-w4-07', w: 'W4', who: 'Sara',   role: 'QA', text: 'Sprint-4-Testbericht schreiben und Bugs für Sprint 5 triagieren' },
      { id: 's4-w4-08', w: 'W4', who: 'Sara',   role: 'FE', text: 'Letzte visuelle Politur vor dem Demo-Day' },
      { id: 's4-w4-09', w: 'W4', who: 'Abder',  role: 'BE', text: 'Fortschritt nutzerübergreifend speichern und Themen-Statistiken berechnen' },
    ],
  },
  {
    num: '05',
    month: 'September 2026',
    title: 'Nutzerkonten & Personalisierung (Erweiterung)',
    subtitle: 'Persönliche Plattform mit Lernverlauf & Mobile',
    dod: 'Registrierung & Login funktionieren · Lernverlauf bleibt nach Logout erhalten · UI vollständig Mobile-tauglich',
    tasks: [
      { id: 's5-w1-01', w: 'W1', who: 'Leon',   role: 'PM', text: 'Sprint-Planung leiten und DSGVO-Workshop mit Sara durchführen' },
      { id: 's5-w1-02', w: 'W1', who: 'Leon',   role: 'KI', text: 'Empfehlungs-Prompt gemeinsam mit Taycir entwerfen' },
      { id: 's5-w1-03', w: 'W1', who: 'Taycir', role: 'KI', text: 'Prompt für personalisierte Lern-Vorschläge auf Basis der User-Historie' },
      { id: 's5-w1-04', w: 'W1', who: 'Taycir', role: 'PM', text: 'Klausurphasen-Scope prüfen und Aufgaben falls nötig reduzieren' },
      { id: 's5-w1-05', w: 'W1', who: 'Ayoub',  role: 'FE', text: 'Registrierungs- und Login-Formulare an Supabase Auth anbinden' },
      { id: 's5-w1-06', w: 'W1', who: 'Ayoub',  role: 'QA', text: 'Test-Szenarien für den kompletten Auth-Flow definieren' },
      { id: 's5-w1-07', w: 'W1', who: 'Sara',   role: 'QA', text: 'DSGVO-Checkliste v1 erstellen und Cookie-Anforderungen sammeln' },
      { id: 's5-w1-08', w: 'W1', who: 'Sara',   role: 'FE', text: 'Layout der Profilseite entwerfen und in Tailwind bauen' },
      { id: 's5-w1-09', w: 'W1', who: 'Abder',  role: 'BE', text: 'Supabase-Auth aktivieren und Row-Level-Security-Policies einrichten' },

      { id: 's5-w2-01', w: 'W2', who: 'Leon',   role: 'PM', text: 'Dozenten-Update halten und mit allen Stakeholdern abstimmen' },
      { id: 's5-w2-02', w: 'W2', who: 'Leon',   role: 'KI', text: 'Empfehlungslogik gemeinsam mit Taycir programmieren' },
      { id: 's5-w2-03', w: 'W2', who: 'Taycir', role: 'KI', text: 'Empfehlungslogik: schwache Themen zur Wiederholung vorschlagen' },
      { id: 's5-w2-04', w: 'W2', who: 'Taycir', role: 'PM', text: 'Risiko-Bewertung speziell für Datenschutz und Cookie-Recht durchführen' },
      { id: 's5-w2-05', w: 'W2', who: 'Ayoub',  role: 'FE', text: 'Avatar-Upload und Fach-Auswahl im Profil bauen' },
      { id: 's5-w2-06', w: 'W2', who: 'Ayoub',  role: 'QA', text: 'Testfälle für das Cookie-Banner schreiben (Annehmen, Ablehnen, Anpassen)' },
      { id: 's5-w2-07', w: 'W2', who: 'Sara',   role: 'FE', text: 'Einstellungsseite mit Account-Optionen und Theme-Wahl bauen' },
      { id: 's5-w2-08', w: 'W2', who: 'Sara',   role: 'QA', text: 'End-to-End-Tests für den Cookie-Consent-Flow umsetzen' },
      { id: 's5-w2-09', w: 'W2', who: 'Abder',  role: 'BE', text: 'Auth-Middleware, geschützte Routen und Profil-API implementieren' },

      { id: 's5-w3-01', w: 'W3', who: 'Leon',   role: 'PM', text: 'Backlog für Sprint 6 (UI-Redesign und Quiz-Modus) groomen' },
      { id: 's5-w3-02', w: 'W3', who: 'Leon',   role: 'KI', text: 'Prompts so anpassen, dass sie den Nutzerkontext kennen' },
      { id: 's5-w3-03', w: 'W3', who: 'Taycir', role: 'KI', text: 'User-Historie in Prompts integrieren (was war gut, was schwach?)' },
      { id: 's5-w3-04', w: 'W3', who: 'Taycir', role: 'PM', text: 'Freigabe der DSGVO-Dokumente koordinieren' },
      { id: 's5-w3-05', w: 'W3', who: 'Ayoub',  role: 'FE', text: 'Layouts für Smartphone-Breakpoints umsetzen (< 640 px)' },
      { id: 's5-w3-06', w: 'W3', who: 'Ayoub',  role: 'QA', text: 'Mobile-Tests auf echten Geräten (iOS Safari, Android Chrome)' },
      { id: 's5-w3-07', w: 'W3', who: 'Sara',   role: 'QA', text: 'Accessibility-Scan und WCAG-2.1-AA-Audit der ganzen App' },
      { id: 's5-w3-08', w: 'W3', who: 'Sara',   role: 'FE', text: 'Layouts für Tablet-Breakpoints (640–1024 px) umsetzen' },
      { id: 's5-w3-09', w: 'W3', who: 'Abder',  role: 'BE', text: 'Account-Löschung und vollständigen Daten-Export (DSGVO Art. 20)' },

      { id: 's5-w4-01', w: 'W4', who: 'Leon',   role: 'PM', text: 'Sprint-Review mit Demo der Nutzerkonten und Retrospektive durchführen' },
      { id: 's5-w4-02', w: 'W4', who: 'Leon',   role: 'KI', text: 'Qualität der personalisierten Empfehlungen mit Taycir testen' },
      { id: 's5-w4-03', w: 'W4', who: 'Taycir', role: 'KI', text: 'Empfehlungsqualität evaluieren (sinnvolle Vorschläge? Treffsicherheit?)' },
      { id: 's5-w4-04', w: 'W4', who: 'Taycir', role: 'PM', text: 'Sprint-Demo inhaltlich und visuell vorbereiten' },
      { id: 's5-w4-05', w: 'W4', who: 'Ayoub',  role: 'FE', text: 'Responsive-Politur über alle Seiten der App ziehen' },
      { id: 's5-w4-06', w: 'W4', who: 'Ayoub',  role: 'QA', text: 'Cross-Browser-Regressionstests in Chrome, Firefox und Safari' },
      { id: 's5-w4-07', w: 'W4', who: 'Sara',   role: 'QA', text: 'DSGVO v1 als Dokument fertigstellen und Sprint-5-Testbericht schreiben' },
      { id: 's5-w4-08', w: 'W4', who: 'Sara',   role: 'FE', text: 'Letzte visuelle Politur vor dem Demo-Day' },
      { id: 's5-w4-09', w: 'W4', who: 'Abder',  role: 'BE', text: 'Lernhistorie zuverlässig sessionsübergreifend persistieren' },
    ],
  },
  {
    num: '06',
    month: 'Oktober 2026',
    title: 'UI/UX & Erweiterte Features (Erweiterung)',
    subtitle: 'Redesign, Dark Mode, Quiz-Modus & erstes User-Testing',
    dod: 'Designsystem dokumentiert · Dark Mode toggelbar · Quiz-Modus nutzbar · Testbericht aus User-Testing liegt vor',
    tasks: [
      { id: 's6-w1-01', w: 'W1', who: 'Leon',   role: 'PM', text: '8 bis 10 Test-Nutzer aus dem Studiengang rekrutieren und Planung leiten' },
      { id: 's6-w1-02', w: 'W1', who: 'Leon',   role: 'KI', text: 'Quiz-Frage-Prompt gemeinsam mit Taycir entwerfen' },
      { id: 's6-w1-03', w: 'W1', who: 'Taycir', role: 'KI', text: 'Prompt für Quiz-Fragen schreiben (kompakt, Zeitlimit-tauglich)' },
      { id: 's6-w1-04', w: 'W1', who: 'Taycir', role: 'PM', text: 'Zeitplan für die User-Testing-Sessions aufstellen' },
      { id: 's6-w1-05', w: 'W1', who: 'Ayoub',  role: 'FE', text: 'Style-Guide v1 dokumentieren und Design-Tokens verfeinern' },
      { id: 's6-w1-06', w: 'W1', who: 'Ayoub',  role: 'QA', text: 'Strukturiertes Usability-Test-Skript mit klaren Aufgaben verfassen' },
      { id: 's6-w1-07', w: 'W1', who: 'Sara',   role: 'QA', text: 'Konkrete Test-Aufgaben für die Teilnehmenden vorbereiten' },
      { id: 's6-w1-08', w: 'W1', who: 'Sara',   role: 'FE', text: 'Komponenten-Bibliothek auditieren und ungenutzte Varianten aufräumen' },
      { id: 's6-w1-09', w: 'W1', who: 'Abder',  role: 'BE', text: 'DB-Schema für Quizze (quizzes, quiz_attempts) anlegen' },

      { id: 's6-w2-01', w: 'W2', who: 'Leon',   role: 'PM', text: 'User-Testing-Sessions vor Ort und per Zoom koordinieren' },
      { id: 's6-w2-02', w: 'W2', who: 'Leon',   role: 'KI', text: 'Pair-Programming mit Taycir zur Beschleunigung der Quiz-Bewertung' },
      { id: 's6-w2-03', w: 'W2', who: 'Taycir', role: 'KI', text: 'Antwort-Evaluation für Quiz-Tempo optimieren (schnellere Antwortzeiten)' },
      { id: 's6-w2-04', w: 'W2', who: 'Taycir', role: 'PM', text: 'Wöchentliches Dozenten-Update mit Status User-Testing' },
      { id: 's6-w2-05', w: 'W2', who: 'Ayoub',  role: 'FE', text: 'UI-Redesign ausrollen: neue Typografie und konsistente Komponenten' },
      { id: 's6-w2-06', w: 'W2', who: 'Ayoub',  role: 'QA', text: 'Usability-Tests mit 4–5 Teilnehmenden durchführen und protokollieren' },
      { id: 's6-w2-07', w: 'W2', who: 'Sara',   role: 'QA', text: 'Usability-Tests mit den restlichen Teilnehmenden durchführen' },
      { id: 's6-w2-08', w: 'W2', who: 'Sara',   role: 'FE', text: 'Spacing- und Farbsystem in allen Screens vereinheitlichen' },
      { id: 's6-w2-09', w: 'W2', who: 'Abder',  role: 'BE', text: 'Quiz-API mit Timer-Logik und Scoring-Berechnung bauen' },

      { id: 's6-w3-01', w: 'W3', who: 'Leon',   role: 'PM', text: 'Workshop zur Priorisierung des User-Feedbacks moderieren' },
      { id: 's6-w3-02', w: 'W3', who: 'Leon',   role: 'KI', text: 'Qualität der Quiz-Fragen gemeinsam mit Taycir evaluieren' },
      { id: 's6-w3-03', w: 'W3', who: 'Taycir', role: 'KI', text: 'Quiz-Fragen-Qualität systematisch evaluieren und verfeinern' },
      { id: 's6-w3-04', w: 'W3', who: 'Taycir', role: 'PM', text: 'Backlog neu sortieren basierend auf Test-Feedback und Aufwand' },
      { id: 's6-w3-05', w: 'W3', who: 'Ayoub',  role: 'FE', text: 'Dark-Mode implementieren mit Theme-Toggle in den Einstellungen' },
      { id: 's6-w3-06', w: 'W3', who: 'Ayoub',  role: 'QA', text: 'Übrige Usability-Tests durchführen und Beobachtungen zusammenführen' },
      { id: 's6-w3-07', w: 'W3', who: 'Sara',   role: 'QA', text: 'Usability-Bericht inkl. Priorisierung der Findings zusammenstellen' },
      { id: 's6-w3-08', w: 'W3', who: 'Sara',   role: 'FE', text: 'Theme-Präferenz persistent in der DB pro Nutzer speichern' },
      { id: 's6-w3-09', w: 'W3', who: 'Abder',  role: 'BE', text: 'Statistik-Endpunkte für Lernverhalten (Zeit, Streaks, Quote) bauen' },

      { id: 's6-w4-01', w: 'W4', who: 'Leon',   role: 'PM', text: 'Sprint-Review mit Demo (Redesign, Dark Mode, Quiz) und Retrospektive' },
      { id: 's6-w4-02', w: 'W4', who: 'Leon',   role: 'KI', text: 'Finale Evaluations-Runde aller Prompts mit Taycir' },
      { id: 's6-w4-03', w: 'W4', who: 'Taycir', role: 'KI', text: 'Prompt-Aufräumarbeiten und finale Bewertung der Antwort-Qualität' },
      { id: 's6-w4-04', w: 'W4', who: 'Taycir', role: 'PM', text: 'Sprint-Demo final vorbereiten und Drehbuch testen' },
      { id: 's6-w4-05', w: 'W4', who: 'Ayoub',  role: 'FE', text: 'Statistik-Dashboard mit Charts (Recharts) bauen' },
      { id: 's6-w4-06', w: 'W4', who: 'Ayoub',  role: 'QA', text: 'Sprint-6-Testbericht inkl. User-Testing-Ergebnissen schreiben' },
      { id: 's6-w4-07', w: 'W4', who: 'Sara',   role: 'QA', text: 'User-Feedback in den Backlog überführen und Regressions-Suite ausführen' },
      { id: 's6-w4-08', w: 'W4', who: 'Sara',   role: 'FE', text: 'Letzte visuelle Politur für den Demo-Day' },
      { id: 's6-w4-09', w: 'W4', who: 'Abder',  role: 'BE', text: 'Performance der Statistik-Queries optimieren (Indizes, Aggregate)' },
    ],
  },
  {
    num: '07',
    month: 'November 2026',
    title: 'Qualitätssicherung & Sicherheit',
    subtitle: 'Tests, Performance, Security & DSGVO-Konformität',
    dod: 'Testabdeckung > 60 % · 0 kritische Bugs · DSGVO-Checkliste vollständig · Lighthouse > 90',
    tasks: [
      { id: 's7-w1-01', w: 'W1', who: 'Leon',   role: 'PM', text: 'Sprint-Planung und vollständiges Risiko-Audit mit dem Team durchführen' },
      { id: 's7-w1-02', w: 'W1', who: 'Leon',   role: 'KI', text: 'Schutz vor Prompt-Injection mit Taycir konzipieren' },
      { id: 's7-w1-03', w: 'W1', who: 'Taycir', role: 'KI', text: 'Prompt-Injection-Schutz und Input-Sanitization für KI-Aufrufe implementieren' },
      { id: 's7-w1-04', w: 'W1', who: 'Taycir', role: 'PM', text: 'Internen Pen-Test organisieren (Termine, Scope, Tools)' },
      { id: 's7-w1-05', w: 'W1', who: 'Ayoub',  role: 'FE', text: 'Lighthouse-Audit fahren und Accessibility-Findings beheben' },
      { id: 's7-w1-06', w: 'W1', who: 'Ayoub',  role: 'QA', text: 'Test-Coverage-Gap-Analyse: welche Bereiche sind unter 60 %?' },
      { id: 's7-w1-07', w: 'W1', who: 'Sara',   role: 'QA', text: 'Konkreten Coverage-Plan erstellen um über 60 % zu kommen' },
      { id: 's7-w1-08', w: 'W1', who: 'Sara',   role: 'FE', text: 'ARIA-Attribute, Farbkontraste und Keyboard-Navigation fixen' },
      { id: 's7-w1-09', w: 'W1', who: 'Abder',  role: 'BE', text: 'Rate-Limiting-Middleware mit fairen Quoten pro Nutzer implementieren' },

      { id: 's7-w2-01', w: 'W2', who: 'Leon',   role: 'PM', text: 'Internen Pen-Test mit Sara koordinieren und Ergebnisse priorisieren' },
      { id: 's7-w2-02', w: 'W2', who: 'Leon',   role: 'KI', text: 'API-Kosten-Monitoring gemeinsam mit Taycir final aufsetzen' },
      { id: 's7-w2-03', w: 'W2', who: 'Taycir', role: 'KI', text: 'API-Kosten-Monitoring mit klaren Alert-Schwellen produktiv schalten' },
      { id: 's7-w2-04', w: 'W2', who: 'Taycir', role: 'PM', text: 'Wöchentliches Dozenten-Update zu Tests und Sicherheit' },
      { id: 's7-w2-05', w: 'W2', who: 'Ayoub',  role: 'FE', text: 'Performance optimieren: Bildgrößen, Lazy-Loading, Bundle-Splitting' },
      { id: 's7-w2-06', w: 'W2', who: 'Ayoub',  role: 'QA', text: 'Fehlende Unit- und Integrations-Tests gezielt nachziehen' },
      { id: 's7-w2-07', w: 'W2', who: 'Sara',   role: 'QA', text: 'Playwright-E2E-Tests für alle kritischen Nutzerpfade abdecken' },
      { id: 's7-w2-08', w: 'W2', who: 'Sara',   role: 'FE', text: 'Bundle-Analyse-Findings beheben und unnötige Abhängigkeiten entfernen' },
      { id: 's7-w2-09', w: 'W2', who: 'Abder',  role: 'BE', text: 'PDF-Speicherung at-rest verschlüsseln und Schlüssel-Management dokumentieren' },

      { id: 's7-w3-01', w: 'W3', who: 'Leon',   role: 'PM', text: 'DSGVO-Checkliste final abschließen und AVV mit Anthropic prüfen' },
      { id: 's7-w3-02', w: 'W3', who: 'Leon',   role: 'KI', text: 'KI-Edge-Case-Bugs gemeinsam mit Taycir fixen' },
      { id: 's7-w3-03', w: 'W3', who: 'Taycir', role: 'KI', text: 'Letzte Bugs in Dialog-Edge-Cases beheben (Leerantworten, Schleifen)' },
      { id: 's7-w3-04', w: 'W3', who: 'Taycir', role: 'PM', text: 'Security-Report zusammenstellen und Maßnahmen ableiten' },
      { id: 's7-w3-05', w: 'W3', who: 'Ayoub',  role: 'FE', text: 'Bugfixes aus QA- und User-Testing-Backlog systematisch abarbeiten' },
      { id: 's7-w3-06', w: 'W3', who: 'Ayoub',  role: 'QA', text: 'Internen Pen-Test ausführen und Findings dokumentieren' },
      { id: 's7-w3-07', w: 'W3', who: 'Sara',   role: 'QA', text: 'Security-Tests und Schwachstellen-Scan (npm audit, Snyk) durchführen' },
      { id: 's7-w3-08', w: 'W3', who: 'Sara',   role: 'FE', text: 'Fehlerseiten (404, 500) klar und freundlich gestalten' },
      { id: 's7-w3-09', w: 'W3', who: 'Abder',  role: 'BE', text: 'Backup-Strategie definieren und DB-Recovery-Verfahren testen' },

      { id: 's7-w4-01', w: 'W4', who: 'Leon',   role: 'PM', text: 'Sprint-Review, DoD-Verifikation und Retrospektive moderieren' },
      { id: 's7-w4-02', w: 'W4', who: 'Leon',   role: 'KI', text: 'Finalen KI-Qualitätsbericht mit Taycir schreiben' },
      { id: 's7-w4-03', w: 'W4', who: 'Taycir', role: 'KI', text: 'Finalen Evaluations-Bericht der KI über alle Use Cases schreiben' },
      { id: 's7-w4-04', w: 'W4', who: 'Taycir', role: 'PM', text: 'Risiko-Register abschließen und offene Punkte für Sprint 8 sammeln' },
      { id: 's7-w4-05', w: 'W4', who: 'Ayoub',  role: 'FE', text: 'Finale UI-Politur und Lighthouse-Score > 90 verifizieren' },
      { id: 's7-w4-06', w: 'W4', who: 'Ayoub',  role: 'QA', text: 'Verifizieren, dass keine kritischen Bugs mehr offen sind' },
      { id: 's7-w4-07', w: 'W4', who: 'Sara',   role: 'QA', text: 'Vollständigen Security- und DSGVO-Bericht für die Abgabe schreiben' },
      { id: 's7-w4-08', w: 'W4', who: 'Sara',   role: 'FE', text: 'Finalen QA-Durchlauf gemeinsam mit Sara durchführen' },
      { id: 's7-w4-09', w: 'W4', who: 'Abder',  role: 'BE', text: 'Production-Hardening abschließen (Monitoring, Alerting, Health-Checks)' },
    ],
  },
  {
    num: '08',
    month: 'Dezember 2026',
    title: 'Finalisierung & Dokumentation',
    subtitle: 'Feinschliff, Benutzerhandbuch, Abschluss-Präsentation',
    dod: 'README & Doku vollständig · Benutzerhandbuch als PDF · Präsentationsfolien fertig',
    tasks: [
      { id: 's8-w1-01', w: 'W1', who: 'Leon',   role: 'PM', text: 'Finale Gliederung der Abschluss-Präsentation entwerfen' },
      { id: 's8-w1-02', w: 'W1', who: 'Leon',   role: 'KI', text: 'KI-Architektur gemeinsam mit Taycir dokumentieren' },
      { id: 's8-w1-03', w: 'W1', who: 'Taycir', role: 'KI', text: 'Alle Prompts dokumentieren und KI-Architektur-Diagramm zeichnen' },
      { id: 's8-w1-04', w: 'W1', who: 'Taycir', role: 'PM', text: 'Inhalte der Präsentation mit dem Dozent abstimmen' },
      { id: 's8-w1-05', w: 'W1', who: 'Ayoub',  role: 'FE', text: 'Finale UI-Politur und freundliche Empty-States überall einbauen' },
      { id: 's8-w1-06', w: 'W1', who: 'Ayoub',  role: 'QA', text: 'Handbuch-Entwurf mit aussagekräftigen Screenshots erstellen' },
      { id: 's8-w1-07', w: 'W1', who: 'Sara',   role: 'QA', text: 'Erste Version des Benutzerhandbuchs schreiben (Step-by-Step)' },
      { id: 's8-w1-08', w: 'W1', who: 'Sara',   role: 'FE', text: 'Fehlerseiten (404, 500) visuell aufwerten' },
      { id: 's8-w1-09', w: 'W1', who: 'Abder',  role: 'BE', text: 'API-Dokumentation (OpenAPI) und DB-Schema-Doku erstellen' },

      { id: 's8-w2-01', w: 'W2', who: 'Leon',   role: 'PM', text: 'Dozenten-Update halten und ersten Probedurchlauf moderieren' },
      { id: 's8-w2-02', w: 'W2', who: 'Leon',   role: 'KI', text: 'Finalen Evaluations-Bericht mit Taycir abschließen' },
      { id: 's8-w2-03', w: 'W2', who: 'Taycir', role: 'KI', text: 'Finale KI-Qualitäts-Metriken zusammentragen und visualisieren' },
      { id: 's8-w2-04', w: 'W2', who: 'Taycir', role: 'PM', text: 'Probedurchlauf vorbereiten (Folien, Zeit-Mapping, Backup-Plan)' },
      { id: 's8-w2-05', w: 'W2', who: 'Ayoub',  role: 'FE', text: 'Loading-Skeletons und Mikro-Animationen für Polish ergänzen' },
      { id: 's8-w2-06', w: 'W2', who: 'Ayoub',  role: 'QA', text: 'Version 2 des Benutzerhandbuchs schreiben und Tech-Doku reviewen' },
      { id: 's8-w2-07', w: 'W2', who: 'Sara',   role: 'QA', text: 'Komplette technische Dokumentation auf Konsistenz reviewen' },
      { id: 's8-w2-08', w: 'W2', who: 'Sara',   role: 'FE', text: 'Erneuter Accessibility-Check der gesamten App' },
      { id: 's8-w2-09', w: 'W2', who: 'Abder',  role: 'BE', text: 'Production-Environment reviewen (Skalierung, Limits, Kostenbericht)' },

      { id: 's8-w3-01', w: 'W3', who: 'Leon',   role: 'PM', text: 'Zweiten Probedurchlauf moderieren und finales Demo-Skript schreiben' },
      { id: 's8-w3-02', w: 'W3', who: 'Leon',   role: 'KI', text: 'Prompt-Freeze gemeinsam mit Taycir koordinieren' },
      { id: 's8-w3-03', w: 'W3', who: 'Taycir', role: 'KI', text: 'Prompt-Freeze etablieren und finale Versionierung dokumentieren' },
      { id: 's8-w3-04', w: 'W3', who: 'Taycir', role: 'PM', text: 'Letztes inhaltliches Feedback vom Dozent einholen' },
      { id: 's8-w3-05', w: 'W3', who: 'Ayoub',  role: 'FE', text: 'Letzte Bugfix-Runde und UI-Snapshot-Tests final laufen lassen' },
      { id: 's8-w3-06', w: 'W3', who: 'Ayoub',  role: 'QA', text: 'README final überarbeiten und Contributor-Guide schreiben' },
      { id: 's8-w3-07', w: 'W3', who: 'Sara',   role: 'QA', text: 'Architektur-Doku reviewen und finale Regressions-Suite ausführen' },
      { id: 's8-w3-08', w: 'W3', who: 'Sara',   role: 'FE', text: 'UI-Snapshot-Tests verifizieren und einfrieren' },
      { id: 's8-w3-09', w: 'W3', who: 'Abder',  role: 'BE', text: 'Finale Bugfixes umsetzen und Datenbank-Migrationen einfrieren' },

      { id: 's8-w4-01', w: 'W4', who: 'Leon',   role: 'PM', text: 'Sprint-Review und Retrospektive durchführen' },
      { id: 's8-w4-02', w: 'W4', who: 'Leon',   role: 'KI', text: 'KI-Architektur-Übergabedokument schreiben' },
      { id: 's8-w4-03', w: 'W4', who: 'Taycir', role: 'KI', text: 'KI-Übergabedokumentation (Architektur, Prompts, Modelle) finalisieren' },
      { id: 's8-w4-04', w: 'W4', who: 'Taycir', role: 'PM', text: 'Abgabepaket vorbereiten (Repo, Doku, Folien, Handbuch)' },
      { id: 's8-w4-05', w: 'W4', who: 'Ayoub',  role: 'FE', text: 'UI einfrieren und finale visuelle QA mit Sara durchführen' },
      { id: 's8-w4-06', w: 'W4', who: 'Ayoub',  role: 'QA', text: 'Finaler Testdurchlauf und formelle Übergabe der Tests' },
      { id: 's8-w4-07', w: 'W4', who: 'Sara',   role: 'QA', text: 'Dokumentation übergeben und schriftlich Sign-off geben' },
      { id: 's8-w4-08', w: 'W4', who: 'Sara',   role: 'FE', text: 'Letzte visuelle QA-Runde vor dem Code-Freeze' },
      { id: 's8-w4-09', w: 'W4', who: 'Abder',  role: 'BE', text: 'Code-Freeze auf develop und Release-Candidate-Tag setzen' },
    ],
  },
  {
    num: '09',
    month: 'Januar 2027',
    title: 'Deployment & Abschlusspräsentation',
    subtitle: 'Go-Live, Abgabe & Live-Demo',
    dod: 'Produktiv-URL live · Repo eingefroren · Präsentation gehalten · Note steht',
    tasks: [
      { id: 's9-w1-01', w: 'W1', who: 'Leon',   role: 'PM', text: 'Finales Präsentations-Skript schreiben und kompletten Probelauf moderieren' },
      { id: 's9-w1-02', w: 'W1', who: 'Leon',   role: 'KI', text: 'Smoke-Test der KI-Flows in Produktion vorbereiten' },
      { id: 's9-w1-03', w: 'W1', who: 'Taycir', role: 'KI', text: 'Production-Smoke-Test der KI-Flows ausführen (alle Hauptpfade)' },
      { id: 's9-w1-04', w: 'W1', who: 'Taycir', role: 'PM', text: 'Probelauf der Live-Demo mit Zeit-Messung durchführen' },
      { id: 's9-w1-05', w: 'W1', who: 'Ayoub',  role: 'FE', text: 'Finale visuelle QA direkt auf der Produktiv-URL' },
      { id: 's9-w1-06', w: 'W1', who: 'Ayoub',  role: 'QA', text: 'Finale Regressions-Suite gegen Produktion fahren' },
      { id: 's9-w1-07', w: 'W1', who: 'Sara',   role: 'QA', text: 'Production-Smoke-Tests ausführen und Ergebnisse dokumentieren' },
      { id: 's9-w1-08', w: 'W1', who: 'Sara',   role: 'FE', text: 'Cross-Browser-Check auf Chrome, Firefox, Safari, Edge' },
      { id: 's9-w1-09', w: 'W1', who: 'Abder',  role: 'BE', text: 'Production-Deployment: Custom-Domain, DNS und SSL aktivieren' },

      { id: 's9-w2-01', w: 'W2', who: 'Leon',   role: 'PM', text: 'Abgabepaket vollständig finalisieren (alle Dateien, alle Links)' },
      { id: 's9-w2-02', w: 'W2', who: 'Leon',   role: 'KI', text: 'Kostenprognose für den Live-Betrieb mit Taycir erstellen' },
      { id: 's9-w2-03', w: 'W2', who: 'Taycir', role: 'KI', text: 'Kostenprognose und API-Monitoring-Plan dokumentieren' },
      { id: 's9-w2-04', w: 'W2', who: 'Taycir', role: 'PM', text: 'Vollständige Readiness-Check-Liste vor der Abgabe durchgehen' },
      { id: 's9-w2-05', w: 'W2', who: 'Ayoub',  role: 'FE', text: 'Standby für eventuelle Blocker-Fixes im Frontend' },
      { id: 's9-w2-06', w: 'W2', who: 'Ayoub',  role: 'QA', text: 'Finalen Testbericht für die Abgabe schreiben' },
      { id: 's9-w2-07', w: 'W2', who: 'Sara',   role: 'QA', text: 'Finalen DSGVO-Sign-off geben und dokumentieren' },
      { id: 's9-w2-08', w: 'W2', who: 'Sara',   role: 'FE', text: 'Standby für letzte Politur-Aufgaben' },
      { id: 's9-w2-09', w: 'W2', who: 'Abder',  role: 'BE', text: 'Production-Monitoring, Uptime-Checks und Backups verifizieren' },

      { id: 's9-w3-01', w: 'W3', who: 'Leon',   role: 'PM', text: 'Projekt offiziell an Dozent abgeben und finales Meeting halten' },
      { id: 's9-w3-02', w: 'W3', who: 'Leon',   role: 'KI', text: 'Standby für eventuelle KI-Issues' },
      { id: 's9-w3-03', w: 'W3', who: 'Taycir', role: 'KI', text: 'Bereitschaft für KI-Issues während der Abgabe-Woche' },
      { id: 's9-w3-04', w: 'W3', who: 'Taycir', role: 'PM', text: 'Vollständigkeit der Abgabe gegen Anforderungen verifizieren' },
      { id: 's9-w3-05', w: 'W3', who: 'Ayoub',  role: 'FE', text: 'Frontend-Standby und Screenshot-Bibliothek für die Präsentation' },
      { id: 's9-w3-06', w: 'W3', who: 'Ayoub',  role: 'QA', text: 'Abgabe-Checkliste Punkt für Punkt verifizieren' },
      { id: 's9-w3-07', w: 'W3', who: 'Sara',   role: 'QA', text: 'Bug-Freiheit verifizieren und Vollständigkeit aller Deliverables prüfen' },
      { id: 's9-w3-08', w: 'W3', who: 'Sara',   role: 'FE', text: 'Visuelle Inhalte für die Präsentation vorbereiten' },
      { id: 's9-w3-09', w: 'W3', who: 'Abder',  role: 'BE', text: '7-Tage-Stabilitätslauf der Produktion abschließen und Monitoring prüfen' },

      { id: 's9-w4-01', w: 'W4', who: 'Leon',   role: 'PM', text: 'Abschluss-Präsentation halten, Retrospektive und Projekt-Archivierung leiten' },
      { id: 's9-w4-02', w: 'W4', who: 'Leon',   role: 'KI', text: 'KI-Live-Demo-Support während der Präsentation' },
      { id: 's9-w4-03', w: 'W4', who: 'Taycir', role: 'KI', text: 'Live-Demo-Support für alle KI-Funktionen sicherstellen' },
      { id: 's9-w4-04', w: 'W4', who: 'Taycir', role: 'PM', text: 'Retrospektive-Notizen für Team-Lessons-Learned dokumentieren' },
      { id: 's9-w4-05', w: 'W4', who: 'Ayoub',  role: 'FE', text: 'Frontend-Support während der Live-Demo (Fallbacks bereit)' },
      { id: 's9-w4-06', w: 'W4', who: 'Ayoub',  role: 'QA', text: 'Alle Test-Artefakte für die Archivierung sichern' },
      { id: 's9-w4-07', w: 'W4', who: 'Sara',   role: 'QA', text: 'Finale Retrospektive-Notizen aus QA-Sicht festhalten' },
      { id: 's9-w4-08', w: 'W4', who: 'Sara',   role: 'FE', text: 'Begleit-Support während der Live-Demo' },
      { id: 's9-w4-09', w: 'W4', who: 'Abder',  role: 'BE', text: 'Backend-Support, Produktion während Live-Demo stabil halten' },
    ],
  },
]
