// Lightweight per-locale strings for the live-classes feature. It targets a
// Moroccan audience, so we cover ar/fr/en/de inline instead of adding a key to
// all 12 message files; anything else falls back to English.
export type ClassesStrings = typeof EN

const EN = {
  title: 'Live German classes',
  subtitle: 'Join a small A1 group taught live online.',
  level: 'Level A1',
  perMonth: 'MAD/month',
  seatsLeft: 'seats',
  full: 'Full',
  starting: 'Full — starting',
  book: 'Reserve my seat',
  booking: 'Reserving…',
  yourGroup: 'You are enrolled',
  enterClass: 'Enter the classroom',
  cancel: 'Cancel my seat',
  loginToBook: 'Log in to reserve',
  payNote: 'Payment is arranged off-site after you reserve (450 MAD/month).',
  enrolledNote: 'Seat reserved! You will receive the payment instructions (450 MAD/month) on WhatsApp. Unpaid seats are released.',
  payWhatsapp: 'Arrange payment on WhatsApp',
  waLabel: 'Your WhatsApp number — so we can send you the payment instructions',
  waRequired: 'Please add your WhatsApp number first.',
  alreadyMsg: 'You already hold a seat in another group — cancel it first.',
  fullMsg: 'This group just filled up. Pick another.',
  errMsg: 'Something went wrong. Try again.',
  features: [
    { icon: 'play', title: 'Live classes every week', desc: 'Classic: 3 sessions of 1h30 (Mon/Wed/Fri) — or Intensive: 2 sessions of 3h (Tue/Thu or Sat/Sun). Small group (10 max), with a teacher.' },
    { icon: 'bar-chart', title: 'Graded dashboard', desc: 'Continuous grading, progress per lesson, and vocabulary mastered — you always know where you stand.' },
    { icon: 'pen', title: 'Corrected homework', desc: 'Lesen, Hören, Schreiben, and grammar — auto-graded, with detailed feedback on your writing.' },
    { icon: 'flag', title: 'Goal: Germany', desc: 'A program built for Ausbildung, studies, and the visa — by the #1 Morocco → Germany platform.' },
  ],
  steps: [
    { title: 'Reserve your seat', desc: 'Choose the level and schedule that works for you below.' },
    { title: 'Confirm on WhatsApp', desc: 'You receive the payment instructions (450 MAD/month, no commitment).' },
    { title: 'Start learning', desc: 'Immediate access to the course, the dashboard, and your group’s live sessions.' },
  ],
  faq: [
    { q: 'I don’t know my level — how do I choose?', a: 'Take our free level test (12 questions, 5 minutes): it recommends the right A1, A2, or B1 group directly.' },
    { q: 'How does payment work?', a: 'After reserving, you receive instructions on WhatsApp. It’s a monthly subscription (450 MAD), no commitment — cancel anytime.' },
    { q: 'What if I miss a class?', a: 'Each lesson’s program, vocabulary, and homework stay available 24/7 on your dashboard — catch up at your own pace.' },
    { q: 'What do I need?', a: 'A phone or computer with a browser and a microphone. The video call opens in one click, no install needed.' },
    { q: 'Do the classes prepare for the Goethe-Zertifikat?', a: 'Yes — the program follows the CEFR levels (A1→B1) and the platform includes prep for the Lesen, Hören, and Schreiben exam sections.' },
  ],
  placementCta: 'Not sure of your level? Take the free test (5 min)',
  placementCtaBtn: 'Test →',
  chooseGroupHeading: 'Choose your group',
  faqHeading: 'Frequently asked questions',
  myCourseLink: 'My course',
  accessActiveUntil: 'Active access until {date}',
  renewSoonSuffix: ' · renew soon ({d} d)',
  accessActiveNoDate: 'Your course access is active.',
  accessExpiredNoDate: 'Your access has expired. Renew to continue (450 MAD/month).',
  accessExpiredWithDate: 'Your access expired on {date}. Renew to continue (450 MAD/month).',
  renew: 'Renew',
  waitingPayment: 'Awaiting payment',
  payMsgTemplate: 'Hello, I reserved a seat ({group}) for the online German classes. I’d like to pay the 450 MAD/month.',
  adminPreviewBadge: 'ADMIN PREVIEW',
}

const FR: ClassesStrings = {
  title: 'Cours d’allemand en direct',
  subtitle: 'Rejoignez un petit groupe A1 en cours direct en ligne.',
  level: 'Niveau A1',
  perMonth: 'DH/mois',
  seatsLeft: 'places',
  full: 'Complet',
  starting: 'Complet — démarre',
  book: 'Réserver ma place',
  booking: 'Réservation…',
  yourGroup: 'Vous êtes inscrit',
  enterClass: 'Accéder à la classe',
  cancel: 'Annuler ma place',
  loginToBook: 'Connectez-vous pour réserver',
  payNote: 'Le paiement se fait hors site après réservation (450 DH/mois).',
  enrolledNote: 'Place réservée ! Vous recevrez les instructions de paiement (450 DH/mois) par WhatsApp. Les places non payées sont libérées.',
  payWhatsapp: 'Régler via WhatsApp',
  waLabel: 'Votre numéro WhatsApp — pour recevoir les instructions de paiement',
  waRequired: 'Veuillez d’abord indiquer votre numéro WhatsApp.',
  alreadyMsg: 'Vous avez déjà une place dans un autre groupe — annulez-la d’abord.',
  fullMsg: 'Ce groupe vient d’être complet. Choisissez-en un autre.',
  errMsg: 'Une erreur est survenue. Réessayez.',
  features: [
    { icon: 'play', title: 'Cours en direct chaque semaine', desc: 'Classique : 3 séances de 1h30 (lun/mer/ven) — ou Intensif : 2 séances de 3h (mar/jeu ou sam/dim). Petit groupe (10 max), avec un prof.' },
    { icon: 'bar-chart', title: 'Tableau de bord noté', desc: 'Note en continu, progression par leçon et vocabulaire maîtrisé — vous savez toujours où vous en êtes.' },
    { icon: 'pen', title: 'Devoirs corrigés', desc: 'Lesen, Hören, Schreiben et grammaire — corrigés automatiquement, avec retour détaillé sur vos rédactions.' },
    { icon: 'flag', title: 'Objectif Allemagne', desc: 'Un programme pensé pour l’Ausbildung, les études et le visa — par la plateforme n°1 du parcours Maroc → Allemagne.' },
  ],
  steps: [
    { title: 'Réservez votre place', desc: 'Choisissez le niveau et l’horaire qui vous conviennent ci-dessous.' },
    { title: 'Confirmez par WhatsApp', desc: 'Vous recevez les instructions de paiement (450 DH/mois, sans engagement).' },
    { title: 'Commencez à apprendre', desc: 'Accès immédiat au cours, au tableau de bord et aux séances en direct de votre groupe.' },
  ],
  faq: [
    { q: 'Je ne connais pas mon niveau — comment choisir ?', a: 'Faites notre test de niveau gratuit (12 questions, 5 minutes) : il vous recommande directement le bon groupe A1, A2 ou B1.' },
    { q: 'Comment se passe le paiement ?', a: 'Après la réservation, vous recevez les instructions par WhatsApp. L’abonnement est mensuel (450 DH), sans engagement — vous arrêtez quand vous voulez.' },
    { q: 'Et si je rate un cours ?', a: 'Le programme, le vocabulaire et les devoirs de chaque leçon restent disponibles 24h/24 sur votre tableau de bord — vous rattrapez à votre rythme.' },
    { q: 'De quoi ai-je besoin ?', a: 'Un téléphone ou un ordinateur avec un navigateur et un micro. L’appel vidéo s’ouvre en un clic, sans installation.' },
    { q: 'Les cours préparent-ils au Goethe-Zertifikat ?', a: 'Oui — le programme suit les niveaux CECR (A1→B1) et la plateforme inclut la préparation aux épreuves Lesen, Hören et Schreiben.' },
  ],
  placementCta: 'Pas sûr de votre niveau ? Faites le test gratuit (5 min)',
  placementCtaBtn: 'Tester →',
  chooseGroupHeading: 'Choisissez votre groupe',
  faqHeading: 'Questions fréquentes',
  myCourseLink: 'Mon cours',
  accessActiveUntil: "Accès actif jusqu'au {date}",
  renewSoonSuffix: ' · à renouveler ({d} j)',
  accessActiveNoDate: 'Votre accès au cours est activé.',
  accessExpiredNoDate: 'Votre accès a expiré. Renouvelez pour continuer (450 DH/mois).',
  accessExpiredWithDate: 'Votre accès a expiré le {date}. Renouvelez pour continuer (450 DH/mois).',
  renew: 'Renouveler',
  waitingPayment: 'En attente de paiement',
  payMsgTemplate: "Bonjour, j'ai réservé une place ({group}) pour les cours d'allemand en ligne. Je souhaite régler les 450 DH/mois.",
  adminPreviewBadge: 'APERÇU ADMIN',
}

const AR: ClassesStrings = {
  title: 'دروس الألمانية المباشرة',
  subtitle: 'انضم إلى مجموعة صغيرة من المستوى A1 في دروس مباشرة عبر الإنترنت.',
  level: 'المستوى A1',
  perMonth: 'درهم/شهر',
  seatsLeft: 'مقاعد',
  full: 'مكتمل',
  starting: 'مكتمل — يبدأ',
  book: 'احجز مقعدي',
  booking: 'جارٍ الحجز…',
  yourGroup: 'أنت مسجَّل',
  enterClass: 'ادخل إلى الحصة',
  cancel: 'إلغاء مقعدي',
  loginToBook: 'سجّل الدخول للحجز',
  payNote: 'يتم الدفع خارج الموقع بعد الحجز (450 درهم/شهر).',
  enrolledNote: 'تم حجز المقعد! ستصلك تعليمات الدفع (450 درهم/شهر) عبر واتساب. المقاعد غير المدفوعة تُحرَّر.',
  payWhatsapp: 'الدفع عبر واتساب',
  waLabel: 'رقم الواتساب الخاص بك — لإرسال تعليمات الدفع',
  waRequired: 'يرجى إدخال رقم الواتساب أولاً.',
  alreadyMsg: 'لديك مقعد في مجموعة أخرى — ألغِه أولاً.',
  fullMsg: 'اكتملت هذه المجموعة للتو. اختر مجموعة أخرى.',
  errMsg: 'حدث خطأ ما. حاول مرة أخرى.',
  features: [
    { icon: 'play', title: 'دروس مباشرة كل أسبوع', desc: 'كلاسيكي: 3 حصص من 1س30 (إثنين/أربعاء/جمعة) — أو مكثف: حصتان من 3 ساعات (ثلاثاء/خميس أو سبت/أحد). مجموعة صغيرة (10 كحد أقصى)، مع أستاذ.' },
    { icon: 'bar-chart', title: 'لوحة تحكم بالنقاط', desc: 'تنقيط مستمر، تقدّم لكل درس، ومفردات محفوظة — تعرف دائمًا أين وصلت.' },
    { icon: 'pen', title: 'واجبات مصحَّحة', desc: 'Lesen وHören وSchreiben والقواعد — تُصحَّح آليًا، مع ملاحظات مفصّلة على كتاباتك.' },
    { icon: 'flag', title: 'الهدف: ألمانيا', desc: 'برنامج مصمَّم للـ Ausbildung والدراسة والتأشيرة — من طرف المنصة رقم 1 لمسار المغرب ← ألمانيا.' },
  ],
  steps: [
    { title: 'احجز مقعدك', desc: 'اختر المستوى والتوقيت المناسبين لك أدناه.' },
    { title: 'أكّد عبر واتساب', desc: 'ستصلك تعليمات الدفع (450 درهم/شهر، بدون التزام).' },
    { title: 'ابدأ التعلّم', desc: 'وصول فوري إلى الدورة، لوحة التحكم، والحصص المباشرة لمجموعتك.' },
  ],
  faq: [
    { q: 'لا أعرف مستواي — كيف أختار؟', a: 'أجرِ اختبار المستوى المجاني (12 سؤالاً، 5 دقائق): يقترح عليك مباشرة المجموعة المناسبة A1 أو A2 أو B1.' },
    { q: 'كيف يتم الدفع؟', a: 'بعد الحجز، ستصلك التعليمات عبر واتساب. الاشتراك شهري (450 درهم)، بدون التزام — يمكنك التوقف متى شئت.' },
    { q: 'ماذا لو فاتني درس؟', a: 'يبقى برنامج ومفردات وواجبات كل درس متاحة على مدار الساعة في لوحة التحكم — تلحق بالركب حسب وتيرتك.' },
    { q: 'ماذا أحتاج؟', a: 'هاتف أو حاسوب مزوَّد بمتصفح وميكروفون. تُفتح المكالمة المرئية بنقرة واحدة، بدون تثبيت.' },
    { q: 'هل تحضّر الدروس لشهادة Goethe-Zertifikat؟', a: 'نعم — يتبع البرنامج مستويات CECR (من A1 إلى B1) وتتضمّن المنصة تحضيرًا لاختبارات Lesen وHören وSchreiben.' },
  ],
  placementCta: 'لست متأكدًا من مستواك؟ أجرِ الاختبار المجاني (5 دقائق)',
  placementCtaBtn: '← اختبر',
  chooseGroupHeading: 'اختر مجموعتك',
  faqHeading: 'الأسئلة الشائعة',
  myCourseLink: 'دورتي',
  accessActiveUntil: 'الوصول فعّال حتى {date}',
  renewSoonSuffix: ' · يجب التجديد قريبًا ({d} ي)',
  accessActiveNoDate: 'وصولك إلى الدورة مفعَّل.',
  accessExpiredNoDate: 'انتهى وصولك. جدِّد للمتابعة (450 درهم/شهر).',
  accessExpiredWithDate: 'انتهى وصولك بتاريخ {date}. جدِّد للمتابعة (450 درهم/شهر).',
  renew: 'تجديد',
  waitingPayment: 'في انتظار الدفع',
  payMsgTemplate: 'مرحبًا، لقد حجزت مقعدًا ({group}) في دروس الألمانية عبر الإنترنت. أرغب في تسديد 450 درهم/شهر.',
  adminPreviewBadge: 'معاينة المسؤول',
}

const DE: ClassesStrings = {
  title: 'Deutschkurse live',
  subtitle: 'Tritt einer kleinen A1-Gruppe im Live-Onlinekurs bei.',
  level: 'Niveau A1',
  perMonth: 'MAD/Monat',
  seatsLeft: 'Plätze',
  full: 'Ausgebucht',
  starting: 'Ausgebucht — startet',
  book: 'Platz reservieren',
  booking: 'Reservierung…',
  yourGroup: 'Du bist angemeldet',
  enterClass: 'Zum Klassenraum',
  cancel: 'Platz stornieren',
  loginToBook: 'Zum Reservieren anmelden',
  payNote: 'Die Zahlung erfolgt nach der Reservierung außerhalb der Website (450 MAD/Monat).',
  enrolledNote: 'Platz reserviert! Die Zahlungsanweisungen (450 MAD/Monat) erhältst du per WhatsApp. Unbezahlte Plätze werden freigegeben.',
  payWhatsapp: 'Zahlung über WhatsApp',
  waLabel: 'Deine WhatsApp-Nummer — für die Zahlungsanweisungen',
  waRequired: 'Bitte zuerst deine WhatsApp-Nummer angeben.',
  alreadyMsg: 'Du hast bereits einen Platz in einer anderen Gruppe — storniere ihn zuerst.',
  fullMsg: 'Diese Gruppe ist gerade voll geworden. Wähle eine andere.',
  errMsg: 'Etwas ist schiefgelaufen. Bitte erneut versuchen.',
  features: [
    { icon: 'play', title: 'Live-Unterricht jede Woche', desc: 'Klassisch: 3 Einheiten à 1,5 Std. (Mo/Mi/Fr) — oder Intensiv: 2 Einheiten à 3 Std. (Di/Do oder Sa/So). Kleine Gruppe (max. 10), mit Lehrer.' },
    { icon: 'bar-chart', title: 'Benotetes Dashboard', desc: 'Laufende Benotung, Fortschritt pro Lektion und gelernter Wortschatz — du weißt immer, wo du stehst.' },
    { icon: 'pen', title: 'Korrigierte Hausaufgaben', desc: 'Lesen, Hören, Schreiben und Grammatik — automatisch korrigiert, mit ausführlichem Feedback zu deinen Texten.' },
    { icon: 'flag', title: 'Ziel: Deutschland', desc: 'Ein Programm für Ausbildung, Studium und Visum — von der Nr. 1 Plattform für den Weg Marokko → Deutschland.' },
  ],
  steps: [
    { title: 'Reserviere deinen Platz', desc: 'Wähle unten das Niveau und den Zeitplan, der zu dir passt.' },
    { title: 'Bestätige per WhatsApp', desc: 'Du erhältst die Zahlungsanweisungen (450 MAD/Monat, ohne Verpflichtung).' },
    { title: 'Beginne zu lernen', desc: 'Sofortiger Zugang zum Kurs, zum Dashboard und zu den Live-Sitzungen deiner Gruppe.' },
  ],
  faq: [
    { q: 'Ich kenne mein Niveau nicht — wie wähle ich?', a: 'Mach unseren kostenlosen Einstufungstest (12 Fragen, 5 Minuten): er empfiehlt dir direkt die passende Gruppe A1, A2 oder B1.' },
    { q: 'Wie funktioniert die Zahlung?', a: 'Nach der Reservierung erhältst du die Anweisungen per WhatsApp. Es ist ein monatliches Abo (450 MAD), ohne Verpflichtung — jederzeit kündbar.' },
    { q: 'Was, wenn ich eine Stunde verpasse?', a: 'Programm, Wortschatz und Hausaufgaben jeder Lektion bleiben 24/7 in deinem Dashboard verfügbar — hol in deinem Tempo nach.' },
    { q: 'Was brauche ich?', a: 'Ein Handy oder einen Computer mit Browser und Mikrofon. Der Videoanruf öffnet sich mit einem Klick, keine Installation nötig.' },
    { q: 'Bereiten die Kurse auf das Goethe-Zertifikat vor?', a: 'Ja — das Programm folgt den GER-Niveaus (A1→B1) und die Plattform enthält Vorbereitung auf die Prüfungsteile Lesen, Hören und Schreiben.' },
  ],
  placementCta: 'Unsicher bei deinem Niveau? Mach den kostenlosen Test (5 Min.)',
  placementCtaBtn: 'Testen →',
  chooseGroupHeading: 'Wähle deine Gruppe',
  faqHeading: 'Häufig gestellte Fragen',
  myCourseLink: 'Mein Kurs',
  accessActiveUntil: 'Zugang aktiv bis {date}',
  renewSoonSuffix: ' · bald verlängern ({d} T.)',
  accessActiveNoDate: 'Dein Kurszugang ist aktiv.',
  accessExpiredNoDate: 'Dein Zugang ist abgelaufen. Verlängere, um fortzufahren (450 MAD/Monat).',
  accessExpiredWithDate: 'Dein Zugang ist am {date} abgelaufen. Verlängere, um fortzufahren (450 MAD/Monat).',
  renew: 'Verlängern',
  waitingPayment: 'Zahlung ausstehend',
  payMsgTemplate: 'Hallo, ich habe einen Platz ({group}) für den Online-Deutschkurs reserviert. Ich möchte die 450 MAD/Monat bezahlen.',
  adminPreviewBadge: 'ADMIN-VORSCHAU',
}

const MAP: Record<string, ClassesStrings> = { en: EN, fr: FR, ar: AR, de: DE }

export function classesStrings(locale: string): ClassesStrings {
  return MAP[locale] ?? EN
}
