const fs = require('fs')
const path = require('path')

const ar = {
  metaTitle: 'الأوزبيلدونغ في ألمانيا — دليل كامل',
  metaDesc: '20 مقالاً حول التدريب المهني المزدوج، أفضل المهن، الأجور، التقديم، والفرص بعد التخرّج.',
  eyebrow: 'التدريب المهني',
  title: 'الأوزبيلدونغ في ألمانيا',
  subtitle: 'التدريب المهني المزدوج — طريقك إلى سوق العمل الألماني بدون جامعة، براتب من اليوم الأول.',
  intro: '20 مقالاً للإجابة على كل ما يسأل عنه المغاربة حول الأوزبيلدونغ: الأهلية، التقديم، أفضل القطاعات، الأجور، وكيف تبني مسيرة عمل طويلة.',
  cta: {
    title: '🔍 هل تبحث عن عروض Ausbildung حقيقية الآن؟',
    description: '',
    buttonLabel: 'تصفح العروض ←',
    href: '/ausbildung-jobs',
  },
  items: [
    { num: 1, title: 'ما هو الأوزبيلدونغ فعلياً؟', summary: 'نظام فريد من نوعه: شركة + مدرسة مهنية في الوقت نفسه، تتعلّم بالعمل وتقبض راتباً. ركيزة الاقتصاد الألماني.', tag: 'أساسيات',
      bullets: [
        'المدة: من سنتين إلى ثلاث سنوات ونصف حسب المهنة.',
        'التقسيم الأسبوعي: 2–4 أيام في الشركة + 1–2 يوم في Berufsschule.',
        'عقد Ausbildungsvertrag موقّع مع الشركة ومسجّل في IHK أو HWK.',
        'الراتب (Ausbildungsvergütung) إلزامي ويتزايد كل سنة.',
        'ينتهي بامتحان IHK Abschlussprüfung وشهادة معترف بها في كل ألمانيا.',
      ] },
    { num: 2, title: 'Duale vs Schulische Ausbildung', summary: 'نوعان من التدريب المهني، بنتائج مادية مختلفة جداً. الأول هو ما يسعى إليه معظم المغاربة.', tag: 'أنواع',
      bullets: [
        '**Duale Ausbildung:** شركة + مدرسة، براتب، الأكثر شيوعاً.',
        '**Schulische Ausbildung:** في مدرسة مهنية فقط، غالباً بدون راتب (التمريض، العلاج الطبيعي).',
        'الأوزبيلدونغ المدرسية أحياناً مدفوعة الرسوم (200–400€/شهر).',
        'بعد 2020، قطاع التمريض دخل Duale وأصبح براتب جيد.',
      ] },
    { num: 3, title: 'أكثر 10 مهن طلباً للمغاربة', summary: 'هذه المهن تقبل بنسبة عالية وتوظّف فوراً بعد التخرّج.', tag: 'قطاعات',
      bullets: [
        '**Pflegefachkraft:** تمريض — الأعلى طلباً وأجراً (~1300€/شهر كبداية).',
        '**Fachkraft für Lagerlogistik:** لوجستيات المستودعات.',
        '**Elektroniker:** تقني كهرباء.',
        '**Kfz-Mechatroniker:** ميكانيكا سيارات.',
        '**Fachinformatiker:** تقنيات المعلومات (تطبيقات / نظم).',
        '**Kaufmann für Büromanagement:** إدارة مكتبية.',
        '**Koch / Köchin:** طهي واحتراف مطاعم.',
        '**Anlagenmechaniker (SHK):** تركيبات صحية وتدفئة.',
        '**Industriemechaniker:** ميكانيكا صناعية.',
        '**Fachverkäufer:** البيع المتخصّص (مخابز، لحوم، صيدلة...).',
      ] },
    { num: 4, title: 'الأجور خلال سنوات الأوزبيلدونغ', summary: 'الراتب يتزايد كل سنة. القطاع المالي والصناعي أعلى بكثير من قطاع الفندقة مثلاً.', tag: 'أجور',
      bullets: [
        'السنة الأولى: 620–1100€ متوسّط.',
        'السنة الثانية: 720–1200€.',
        'السنة الثالثة: 850–1400€.',
        'قطاعات مميزة (بنوك، صناعة): تصل 1600€ في السنة الأخيرة.',
        'قطاعات منخفضة (فندقة، بيع): قريبة من الحد الأدنى.',
      ],
      tip: 'الراتب يكفي معيشة متواضعة في مدن متوسطة (Leipzig, Dortmund)، لكن صعب جداً في München أو Hamburg بدون دعم.' },
    { num: 5, title: 'مستوى اللغة المطلوب', summary: 'B1 هو الحد الأدنى النظري، لكن الواقع مختلف. B2 هو ما تحتاجه فعلاً لتنجح.', tag: 'لغة',
      bullets: [
        'B1: تفهم التعليمات الأساسية، تتواصل بصعوبة.',
        'B2: مستوى معقول لقراءة الكتب المهنية وفهم الأستاذ في المدرسة.',
        'C1: مثالي للمهن الصحية والإدارية.',
        'شهادة Goethe B2 أو telc B2 أو TestDaF مقبولة عند كل الشركات.',
      ],
      tip: 'قبل التقديم، شاهد فيديو YouTube لـ Berufsschule في تخصّصك — إن فهمته، لغتك جاهزة.' },
    { num: 6, title: 'من أين تبحث عن الأوزبيلدونغ؟', summary: 'عشرات المنصّات، لكن الأكثر فعالية قليلة. ركّز طاقتك عليها.', tag: 'بحث',
      bullets: [
        '**Make-it-in-Germany.com:** المنصة الرسمية للهجرة المهنية.',
        '**Ausbildung.de:** الأكبر تخصّصاً.',
        '**Arbeitsagentur.de:** بنك وظائف الدولة، دقيق جداً.',
        '**AZUBIYO.de:** مناسب لتحديد المهنة المناسبة.',
        '**LinkedIn:** مفاجئ أنه يعمل للأوزبيلدونغ أيضاً.',
        'التقديم المباشر عبر موقع الشركة: أعلى نسبة قبول.',
      ] },
    { num: 7, title: 'كتابة Bewerbung مقنعة', summary: 'ملف التقديم الألماني يختلف تماماً عن المغربي. هذه عناصره الأساسية.', tag: 'ملف',
      bullets: [
        '**Anschreiben:** صفحة واحدة، تشرح لماذا أنت لهذه المهنة وهذه الشركة بالذات.',
        '**Lebenslauf:** CV ألماني: تعليم + خبرة + لغات + مهارات، صورة مهنية.',
        '**Zeugnisse:** شهادات الباكالوريا وأي تدريب سابق، مترجمة.',
        '**Zertifikate:** شهادات اللغة + أي دورات.',
      ],
      tip: 'اجعل ملفك PDF واحد منظّم، لا 10 ملفات منفصلة. الاسم يجب أن يكون: Bewerbung_VorName_Nachname.pdf' },
    { num: 8, title: 'Lebenslauf الألماني — النموذج الصحيح', summary: 'لا صورة سيلفي، لا ألوان مبهرجة. بساطة وتنظيم صارم.', tag: 'ملف',
      bullets: [
        'الرأس: اسم، عنوان، هاتف، إيميل، تاريخ الميلاد، الجنسية.',
        'الصورة: احترافية، خلفية بيضاء، ملابس رسمية.',
        'ترتيب زمني عكسي: الأحدث أولاً.',
        'حجم: صفحة أو صفحتين فقط.',
        'التوقيع والتاريخ في الأسفل.',
      ] },
    { num: 9, title: 'Vorstellungsgespräch — المقابلة الشخصية', summary: 'إذا وصلت لهذه المرحلة، فرصتك 50%. التحضير الجيد يضاعفها.', tag: 'مقابلة',
      bullets: [
        'اعرف كل شيء عن الشركة: سنة التأسيس، المنتجات، القيم.',
        'حضّر إجابات لأسئلة كلاسيكية: لماذا نحن؟ لماذا ألمانيا؟ لماذا هذه المهنة؟',
        'لباس رسمي (Business Casual كحد أدنى).',
        'الوصول 10 دقائق قبل الموعد، لا أقل ولا أكثر.',
        'اسأل أسئلة في النهاية — يدل على اهتمامك.',
      ],
      tip: 'كثير من الشركات تبدأ بمكالمة فيديو قصيرة قبل المقابلة الحضورية. عاملها بجدية كاملة.' },
    { num: 10, title: 'Ausbildungsvisum — تأشيرة التدريب', summary: 'تأشيرة مخصّصة للأوزبيلدونغ. شروطها أوضح من تأشيرات أخرى.', tag: 'تأشيرة',
      bullets: [
        'وثائق: عقد Ausbildungsvertrag موقّع + شهادة لغة B1 + سكن.',
        'لا تحتاج Sperrkonto إذا كان راتب التدريب يكفي (~934€/شهر).',
        'الرسم 75€.',
        'تُصدر لسنة كاملة وتُجدّد حتى نهاية التدريب.',
      ] },
    { num: 11, title: 'كارت الفرص (Chancenkarte) للبحث عن Ausbildung', summary: 'منذ 2024، يمكنك المجيء لألمانيا 12 شهراً للبحث عن تدريب، إن استوفيت نقاطاً كافية.', tag: 'جديد',
      bullets: [
        'نظام نقاط: لغة + عمر + تعليم + خبرة.',
        'شهادة ألمانية A1 كحدّ أدنى + 6 نقاط.',
        'يسمح بعمل 20 ساعة/أسبوع أثناء البحث.',
        'تُحوَّل إلى Ausbildungsvisum فور إيجاد التدريب.',
      ] },
    { num: 12, title: 'Einstiegsqualifizierung (EQ) — الجسر قبل الأوزبيلدونغ', summary: 'برنامج 6–12 شهراً للعمل التجريبي قبل الأوزبيلدونغ، لمن ليس مستعداً تماماً.', tag: 'تحضيري',
      bullets: [
        'راتب جزئي (~250–300€/شهر) من Arbeitsagentur.',
        'يمنح الشركة الفرصة لتقييمك قبل عقد 3 سنوات.',
        '70% من مَن يكمل EQ يحصل على Ausbildung في نفس الشركة.',
        'خيار ممتاز لمن لغته ضعيفة نسبياً.',
      ] },
    { num: 13, title: 'الأوزبيلدونغ في التمريض', summary: 'القطاع الأكثر طلباً للمغاربة. راتب عالٍ، قبول سريع، وطريق مباشر للإقامة.', tag: 'تمريض',
      bullets: [
        'Pflegefachkraft: المسمى الجديد منذ 2020، يجمع الثلاث شُعَب القديمة.',
        '3 سنوات تدريب، راتب ~1300€ في السنة الأولى.',
        'معظم المستشفيات توفّر سكناً مدعوماً.',
        'بعد التخرّج: ~2800–3200€ شهرياً إجمالي.',
        'طلب دائم على الموظفين — نادراً بطالة في هذا القطاع.',
      ] },
    { num: 14, title: 'الأوزبيلدونغ في IT', summary: 'Fachinformatiker هو المسار الأشهر. تخرّج براتب ابتدائي 3000€+ في سوق متعطّش.', tag: 'IT',
      bullets: [
        'ثلاث تخصّصات: Anwendungsentwicklung (تطوير)، Systemintegration (شبكات)، Daten- und Prozessanalyse.',
        'راتب التدريب ~1100€ بداية، ~1300€ نهاية.',
        'القبول يفضّل من لديهم مهارات مسبقة (HTML/Python/Linux).',
        'بعد التخرّج: 3200–4500€ شهرياً، مع إمكانية الانتقال للبرمجة الكاملة.',
      ] },
    { num: 15, title: 'الأوزبيلدونغ في الميكانيكا والصناعة', summary: 'ألمانيا = صناعة. كل شركة كبرى (BMW, Bosch, Siemens, Mercedes) تقبل متدرّبين سنوياً.', tag: 'صناعة',
      bullets: [
        'Industriemechaniker, Mechatroniker, Elektroniker هي الأكثر شيوعاً.',
        'عقود مع شركات كبرى = رواتب أعلى + مزايا (قطار مجاني، طعام مدعوم).',
        'القبول في Mercedes و BMW يبدأ قبل سنة تقريباً.',
        'بعد التدريب: 3000–4000€ ابتدائي، مع تطوّر سريع.',
      ] },
    { num: 16, title: 'الحياة اليومية كـ Azubi', summary: 'تحدّيات نمطية يعيشها كل متدرّب مغربي. استعد لها ذهنياً.', tag: 'حياة',
      bullets: [
        'ضغط الدوام (40 ساعة) + الدراسة + الفروض المدرسية = إرهاق أول شهرين.',
        'الزملاء الألمان أصغر سناً عادة (18–20) — الفجوة الثقافية حقيقية.',
        'الأكل الحلال في Kantine نادر — جهّز طعامك.',
        'الأعياد الإسلامية ليست رسمية — خطّط إجازاتك مسبقاً.',
      ],
      tip: 'ابحث عن جالية مغربية في المدينة قبل الوصول. الجمعات أسبوعياً تحمي صحتك النفسية أكثر من أي شيء.' },
    { num: 17, title: 'حقوق المتدرّب (Azubi-Rechte)', summary: 'قانون ألمانيا يحمي المتدرّب بشدة. لا تقبل استغلالاً — لك حقوق واضحة.', tag: 'حقوق',
      bullets: [
        'إجازة مدفوعة: 24–30 يوماً سنوياً.',
        'ساعات العمل: حتى 8/يوم كحد أقصى، مع استراحة 30 دقيقة بعد 6 ساعات.',
        'لا عمل ليلي ولا أعياد إذا كان سنّك أقل من 18.',
        'لا يحق لصاحب العمل تكليفك بأعمال لا علاقة لها بالتدريب.',
        'من حقك الحصول على شهادة عمل (Zeugnis) نهائية.',
      ] },
    { num: 18, title: 'امتحان IHK النهائي (Abschlussprüfung)', summary: 'الامتحان الذي يمنحك الشهادة. نظري + عملي + شفهي أحياناً. الرسوب ممكن لكن يمكن الإعادة.', tag: 'امتحان',
      bullets: [
        'يُعقد عبر IHK (غرفة الصناعة) أو HWK (الحرف).',
        'جزءان: نصفي (نهاية السنة الثانية) + نهائي.',
        'معدل النجاح الوطني ~ 90%.',
        'يمكن إعادة الامتحان مرتين.',
        'الشركة ملزمة بإعطائك وقتاً للمراجعة.',
      ] },
    { num: 19, title: 'بعد الأوزبيلدونغ — ماذا يحدث؟', summary: '70% من المتدرّبين يحصلون على عقد دائم في نفس الشركة. الآخرون يجدون عملاً خلال أشهر.', tag: 'ما بعد',
      bullets: [
        '**Übernahme:** التعيين المباشر بعقد دائم في نفس الشركة.',
        '**Meister:** شهادة تدريبية عليا (1–3 سنوات)، تمكّنك من فتح مشروعك.',
        '**Weiterbildung:** تخصّص تقني مكمّل.',
        '**Studium:** يمكنك دخول الجامعة بدون Abitur بعد 3 سنوات عمل.',
        'تأشيرتك تُحوَّل إلى إقامة عمل، ثم إلى دائمة بعد سنتين فقط (بدل 5).',
      ] },
    { num: 20, title: 'أخطاء شائعة يقع فيها المغاربة', summary: 'تكرّرت في تجارب عشرات المغاربة. تعلّم منهم ولا تعدها.', tag: 'تحذيرات',
      bullets: [
        'التقديم لمهنة لا يحبها فقط لأنها تقبل أسرع — مسار 3 سنوات يصعب إلغاؤه.',
        'التقديم بـ CV مغربي غير معدّل للنموذج الألماني — رفض فوري.',
        'ترك اللغة الألمانية عند مستوى B1 — المدرسة المهنية ستسحقك.',
        'عدم قراءة العقد قبل التوقيع — بعض الشركات تضع شروطاً غير عادلة.',
        'عدم الاحتفاظ بنسخة Anmeldung و Aufenthaltstitel في كل تحرّك — الشرطة تطلبها.',
        'إهمال الفروض في Berufsschule — ستُرسَب في الامتحان الرسمي.',
      ],
      tip: 'اشترك في مجموعات "Ausbildung für Marokkaner" على فيسبوك وتيليغرام — المعلومة الصحيحة تأتي من تجربة حقيقية.' },
  ],
}

const fr = {
  metaTitle: 'L\'Ausbildung en Allemagne — guide complet',
  metaDesc: '20 articles sur la formation professionnelle duale : meilleurs métiers, salaires, candidature et perspectives après le diplôme.',
  eyebrow: 'Formation professionnelle',
  title: 'L\'Ausbildung en Allemagne',
  subtitle: 'La formation professionnelle duale — ton chemin vers le marché du travail allemand sans université, avec un salaire dès le premier jour.',
  intro: '20 articles pour répondre à tout ce que se demandent les Marocains sur l\'Ausbildung : éligibilité, candidature, meilleurs secteurs, salaires, et comment bâtir une longue carrière.',
  cta: {
    title: '🔍 Tu cherches de vraies offres d\'Ausbildung dès maintenant ?',
    description: '',
    buttonLabel: 'Parcourir les offres ←',
    href: '/ausbildung-jobs',
  },
  items: [
    { num: 1, title: 'L\'Ausbildung, c\'est quoi au juste ?', summary: 'Un système unique : entreprise + école professionnelle en même temps, tu apprends en travaillant et touches un salaire. Pilier de l\'économie allemande.', tag: 'Bases',
      bullets: [
        'Durée : de deux à trois ans et demi selon le métier.',
        'Répartition hebdomadaire : 2–4 jours en entreprise + 1–2 jours à la Berufsschule.',
        'Contrat Ausbildungsvertrag signé avec l\'entreprise et enregistré à l\'IHK ou la HWK.',
        'Le salaire (Ausbildungsvergütung) est obligatoire et augmente chaque année.',
        'S\'achève par l\'examen IHK Abschlussprüfung et un diplôme reconnu dans toute l\'Allemagne.',
      ] },
    { num: 2, title: 'Duale vs Schulische Ausbildung', summary: 'Deux types de formation professionnelle, aux retombées financières très différentes. Le premier est ce que visent la plupart des Marocains.', tag: 'Types',
      bullets: [
        '**Duale Ausbildung :** entreprise + école, avec salaire, la plus courante.',
        '**Schulische Ausbildung :** uniquement en école professionnelle, souvent sans salaire (soins infirmiers, kinésithérapie).',
        'L\'Ausbildung scolaire est parfois payante (200–400 €/mois).',
        'Depuis 2020, le secteur infirmier est passé en duale et offre désormais un bon salaire.',
      ] },
    { num: 3, title: 'Les 10 métiers les plus demandés pour les Marocains', summary: 'Ces métiers acceptent à un taux élevé et recrutent immédiatement après l\'obtention du diplôme.', tag: 'Secteurs',
      bullets: [
        '**Pflegefachkraft :** infirmier — le plus demandé et le mieux payé (~1 300 €/mois au départ).',
        '**Fachkraft für Lagerlogistik :** logistique d\'entrepôt.',
        '**Elektroniker :** technicien électricien.',
        '**Kfz-Mechatroniker :** mécanique automobile.',
        '**Fachinformatiker :** informatique (applications / systèmes).',
        '**Kaufmann für Büromanagement :** gestion de bureau.',
        '**Koch / Köchin :** cuisine et restauration professionnelle.',
        '**Anlagenmechaniker (SHK) :** installations sanitaires et chauffage.',
        '**Industriemechaniker :** mécanique industrielle.',
        '**Fachverkäufer :** vente spécialisée (boulangerie, boucherie, pharmacie…).',
      ] },
    { num: 4, title: 'Les salaires pendant les années d\'Ausbildung', summary: 'Le salaire augmente chaque année. Les secteurs financier et industriel paient bien plus que l\'hôtellerie, par exemple.', tag: 'Salaires',
      bullets: [
        'Première année : 620–1 100 € en moyenne.',
        'Deuxième année : 720–1 200 €.',
        'Troisième année : 850–1 400 €.',
        'Secteurs privilégiés (banques, industrie) : jusqu\'à 1 600 € la dernière année.',
        'Secteurs bas (hôtellerie, vente) : proches du minimum.',
      ],
      tip: 'Le salaire permet une vie modeste dans les villes moyennes (Leipzig, Dortmund), mais c\'est très difficile à Munich ou Hambourg sans soutien.' },
    { num: 5, title: 'Le niveau de langue requis', summary: 'B1 est le minimum théorique, mais la réalité est autre. B2 est ce qu\'il te faut vraiment pour réussir.', tag: 'Langue',
      bullets: [
        'B1 : tu comprends les instructions de base, tu communiques avec difficulté.',
        'B2 : niveau raisonnable pour lire les manuels professionnels et comprendre le prof à l\'école.',
        'C1 : idéal pour les métiers de santé et d\'administration.',
        'Les certificats Goethe B2, telc B2 ou TestDaF sont acceptés par toutes les entreprises.',
      ],
      tip: 'Avant de candidater, regarde une vidéo YouTube de Berufsschule dans ta spécialité — si tu comprends, ta langue est prête.' },
    { num: 6, title: 'Où chercher une Ausbildung ?', summary: 'Des dizaines de plateformes, mais peu sont vraiment efficaces. Concentre ton énergie dessus.', tag: 'Recherche',
      bullets: [
        '**Make-it-in-Germany.com :** la plateforme officielle de l\'immigration professionnelle.',
        '**Ausbildung.de :** la plus grande plateforme spécialisée.',
        '**Arbeitsagentur.de :** la banque d\'emploi de l\'État, très précise.',
        '**AZUBIYO.de :** idéale pour cibler le métier qui te convient.',
        '**LinkedIn :** étonnamment, ça marche aussi pour l\'Ausbildung.',
        'Candidature directe via le site de l\'entreprise : le taux d\'acceptation le plus élevé.',
      ] },
    { num: 7, title: 'Rédiger une Bewerbung convaincante', summary: 'Le dossier de candidature allemand diffère totalement du marocain. Voici ses éléments essentiels.', tag: 'Dossier',
      bullets: [
        '**Anschreiben :** une page expliquant pourquoi toi pour ce métier et cette entreprise précisément.',
        '**Lebenslauf :** le CV allemand : formation + expérience + langues + compétences, photo professionnelle.',
        '**Zeugnisse :** diplôme du bac et toute formation antérieure, traduits.',
        '**Zertifikate :** certificats de langue + tout autre cours suivi.',
      ],
      tip: 'Fais-en un seul PDF bien organisé, pas 10 fichiers séparés. Le nom doit être : Bewerbung_Prenom_Nom.pdf' },
    { num: 8, title: 'Le Lebenslauf allemand — le bon modèle', summary: 'Pas de selfie, pas de couleurs criardes. Sobriété et rigueur absolues.', tag: 'Dossier',
      bullets: [
        'En-tête : nom, adresse, téléphone, e-mail, date de naissance, nationalité.',
        'Photo : professionnelle, fond blanc, tenue formelle.',
        'Ordre chronologique inversé : le plus récent en premier.',
        'Format : une à deux pages maximum.',
        'Signature et date en bas.',
      ] },
    { num: 9, title: 'Vorstellungsgespräch — l\'entretien d\'embauche', summary: 'Arrivé à cette étape, tes chances sont de 50 %. Une bonne préparation les double.', tag: 'Entretien',
      bullets: [
        'Renseigne-toi sur tout : année de fondation, produits, valeurs de l\'entreprise.',
        'Prépare des réponses aux classiques : pourquoi nous ? pourquoi l\'Allemagne ? pourquoi ce métier ?',
        'Tenue formelle (Business Casual au minimum).',
        'Arrive 10 minutes avant l\'heure, ni plus, ni moins.',
        'Pose des questions à la fin — ça montre ton intérêt.',
      ],
      tip: 'Beaucoup d\'entreprises commencent par un court appel vidéo avant l\'entretien en personne. Prends-le très au sérieux.' },
    { num: 10, title: 'Ausbildungsvisum — le visa de formation', summary: 'Un visa spécifique à l\'Ausbildung. Ses conditions sont plus claires que celles d\'autres visas.', tag: 'Visa',
      bullets: [
        'Documents : Ausbildungsvertrag signé + certificat de langue B1 + logement.',
        'Pas besoin de Sperrkonto si le salaire de la formation suffit (~934 €/mois).',
        'Frais : 75 €.',
        'Délivré pour un an puis renouvelable jusqu\'à la fin de la formation.',
      ] },
    { num: 11, title: 'La Chancenkarte pour chercher une Ausbildung', summary: 'Depuis 2024, tu peux venir en Allemagne 12 mois pour chercher une formation, si tu réunis assez de points.', tag: 'Nouveau',
      bullets: [
        'Système de points : langue + âge + formation + expérience.',
        'Certificat d\'allemand A1 au minimum + 6 points.',
        'Te permet de travailler 20 h/semaine pendant ta recherche.',
        'Se convertit en Ausbildungsvisum dès que tu trouves une formation.',
      ] },
    { num: 12, title: 'Einstiegsqualifizierung (EQ) — le pont avant l\'Ausbildung', summary: 'Programme de 6–12 mois d\'essai avant l\'Ausbildung, pour ceux qui ne sont pas tout à fait prêts.', tag: 'Préparatoire',
      bullets: [
        'Salaire partiel (~250–300 €/mois) versé par l\'Arbeitsagentur.',
        'Donne à l\'entreprise l\'occasion de t\'évaluer avant un contrat de 3 ans.',
        '70 % de ceux qui terminent l\'EQ obtiennent une Ausbildung dans la même entreprise.',
        'Excellent choix pour ceux dont la langue est relativement faible.',
      ] },
    { num: 13, title: 'L\'Ausbildung en soins infirmiers', summary: 'Le secteur le plus demandé pour les Marocains. Salaire élevé, acceptation rapide, et voie directe vers la résidence.', tag: 'Soins',
      bullets: [
        'Pflegefachkraft : intitulé unifié depuis 2020, regroupe les trois anciennes branches.',
        '3 ans de formation, salaire ~1 300 € la première année.',
        'La plupart des hôpitaux offrent un logement subventionné.',
        'Après le diplôme : ~2 800–3 200 € brut mensuel.',
        'Demande constante — quasi aucun chômage dans ce secteur.',
      ] },
    { num: 14, title: 'L\'Ausbildung en IT', summary: 'Fachinformatiker est la filière la plus populaire. Tu en sors à 3 000 €+ de salaire de départ dans un marché avide de profils.', tag: 'IT',
      bullets: [
        'Trois spécialités : Anwendungsentwicklung (développement), Systemintegration (réseaux), Daten- und Prozessanalyse.',
        'Salaire de formation ~1 100 € au début, ~1 300 € à la fin.',
        'L\'acceptation privilégie ceux qui ont déjà des compétences (HTML/Python/Linux).',
        'Après le diplôme : 3 200–4 500 € mensuels, avec possibilité de basculer vers le développement complet.',
      ] },
    { num: 15, title: 'L\'Ausbildung en mécanique et industrie', summary: 'Allemagne = industrie. Toutes les grandes entreprises (BMW, Bosch, Siemens, Mercedes) prennent des apprentis chaque année.', tag: 'Industrie',
      bullets: [
        'Industriemechaniker, Mechatroniker et Elektroniker sont les plus répandus.',
        'Contrats avec les grands groupes = meilleurs salaires + avantages (train gratuit, repas subventionnés).',
        'Chez Mercedes et BMW, les admissions démarrent environ un an à l\'avance.',
        'Après la formation : 3 000–4 000 € de départ, avec progression rapide.',
      ] },
    { num: 16, title: 'La vie quotidienne en tant qu\'Azubi', summary: 'Des défis classiques que vit chaque apprenti marocain. Prépare-toi mentalement.', tag: 'Vie',
      bullets: [
        'La pression du travail (40 h) + cours + devoirs = épuisement les deux premiers mois.',
        'Les collègues allemands sont souvent plus jeunes (18–20) — l\'écart culturel est réel.',
        'La nourriture halal à la Kantine est rare — prépare tes repas.',
        'Les fêtes musulmanes ne sont pas fériées — planifie tes congés à l\'avance.',
      ],
      tip: 'Cherche une communauté marocaine dans ta ville avant d\'arriver. Les rassemblements hebdomadaires protègent ta santé mentale plus que tout.' },
    { num: 17, title: 'Droits de l\'apprenti (Azubi-Rechte)', summary: 'La loi allemande protège fortement l\'apprenti. N\'accepte aucune exploitation — tu as des droits clairs.', tag: 'Droits',
      bullets: [
        'Congés payés : 24–30 jours par an.',
        'Horaires : max 8 h/jour, avec une pause de 30 min après 6 h.',
        'Pas de travail de nuit ni les jours fériés si tu as moins de 18 ans.',
        'L\'employeur n\'a pas le droit de te confier des tâches sans rapport avec la formation.',
        'Tu as droit à un certificat de travail final (Zeugnis).',
      ] },
    { num: 18, title: 'L\'examen final IHK (Abschlussprüfung)', summary: 'L\'examen qui te donne le diplôme. Théorique + pratique + parfois oral. L\'échec est possible, mais rattrapable.', tag: 'Examen',
      bullets: [
        'Organisé par l\'IHK (chambre d\'industrie) ou la HWK (artisanat).',
        'Deux parties : intermédiaire (fin de deuxième année) + finale.',
        'Taux de réussite national : ~90 %.',
        'Tu peux repasser l\'examen deux fois.',
        'L\'entreprise est tenue de te laisser du temps pour réviser.',
      ] },
    { num: 19, title: 'Après l\'Ausbildung — que se passe-t-il ?', summary: '70 % des apprentis obtiennent un CDI dans la même entreprise. Les autres trouvent un emploi en quelques mois.', tag: 'Après',
      bullets: [
        '**Übernahme :** embauche directe en CDI dans la même entreprise.',
        '**Meister :** diplôme supérieur (1–3 ans), qui te permet d\'ouvrir ta propre activité.',
        '**Weiterbildung :** spécialisation technique complémentaire.',
        '**Studium :** tu peux entrer à l\'université sans Abitur après 3 ans d\'expérience.',
        'Ton visa se convertit en titre de séjour de travail, puis permanent au bout de 2 ans seulement (au lieu de 5).',
      ] },
    { num: 20, title: 'Erreurs fréquentes des Marocains', summary: 'Répétées dans des dizaines d\'expériences marocaines. Apprends d\'eux et ne refais pas les mêmes.', tag: 'Avertissements',
      bullets: [
        'Candidater à un métier qu\'on n\'aime pas juste parce qu\'il accepte plus vite — un parcours de 3 ans est difficile à annuler.',
        'Candidater avec un CV marocain non adapté au modèle allemand — rejet immédiat.',
        'Laisser l\'allemand au niveau B1 — l\'école professionnelle va t\'écraser.',
        'Ne pas lire le contrat avant de signer — certaines entreprises y glissent des clauses injustes.',
        'Ne pas garder une copie de l\'Anmeldung et de l\'Aufenthaltstitel sur toi — la police les demande.',
        'Négliger les devoirs à la Berufsschule — tu échoueras à l\'examen officiel.',
      ],
      tip: 'Rejoins les groupes « Ausbildung für Marokkaner » sur Facebook et Telegram — la bonne info vient d\'une vraie expérience.' },
  ],
}

const en = {
  metaTitle: 'Ausbildung in Germany — complete guide',
  metaDesc: '20 articles on dual vocational training: top professions, wages, applications, and post-graduation opportunities.',
  eyebrow: 'Vocational training',
  title: 'Ausbildung in Germany',
  subtitle: 'Dual vocational training — your route into the German job market without a university degree, earning a salary from day one.',
  intro: '20 articles answering everything Moroccans ask about the Ausbildung: eligibility, applications, best sectors, wages, and how to build a long career.',
  cta: {
    title: '🔍 Looking for real Ausbildung offers right now?',
    description: '',
    buttonLabel: 'Browse offers ←',
    href: '/ausbildung-jobs',
  },
  items: [
    { num: 1, title: 'What is the Ausbildung, really?', summary: 'A unique system: company plus vocational school at the same time, you learn by working and get paid. A pillar of the German economy.', tag: 'Basics',
      bullets: [
        'Duration: two to three and a half years depending on the profession.',
        'Weekly split: 2–4 days at the company + 1–2 days at the Berufsschule.',
        'Ausbildungsvertrag signed with the company and registered with the IHK or HWK.',
        'The salary (Ausbildungsvergütung) is mandatory and rises every year.',
        'Ends with the IHK Abschlussprüfung exam and a qualification recognised across Germany.',
      ] },
    { num: 2, title: 'Duale vs Schulische Ausbildung', summary: 'Two types of vocational training, with very different financial outcomes. The first is what most Moroccans aim for.', tag: 'Types',
      bullets: [
        '**Duale Ausbildung:** company + school, with salary — by far the most common.',
        '**Schulische Ausbildung:** at a vocational school only, often unpaid (nursing, physiotherapy).',
        'The schulische Ausbildung sometimes charges fees (€200–400/month).',
        'Since 2020, nursing moved into the duale model and now pays well.',
      ] },
    { num: 3, title: 'The 10 most in-demand professions for Moroccans', summary: 'These professions accept at a high rate and hire you straight after graduation.', tag: 'Sectors',
      bullets: [
        '**Pflegefachkraft:** nursing — highest demand and pay (~€1,300/month starting).',
        '**Fachkraft für Lagerlogistik:** warehouse logistics.',
        '**Elektroniker:** electrical technician.',
        '**Kfz-Mechatroniker:** car mechanics.',
        '**Fachinformatiker:** IT (applications / systems).',
        '**Kaufmann für Büromanagement:** office management.',
        '**Koch / Köchin:** professional cooking and restaurant work.',
        '**Anlagenmechaniker (SHK):** sanitary and heating installation.',
        '**Industriemechaniker:** industrial mechanics.',
        '**Fachverkäufer:** specialist sales (bakery, butcher, pharmacy…).',
      ] },
    { num: 4, title: 'Wages during the Ausbildung years', summary: 'The salary rises every year. Banking and industry pay far more than hospitality, for example.', tag: 'Wages',
      bullets: [
        'First year: €620–1,100 on average.',
        'Second year: €720–1,200.',
        'Third year: €850–1,400.',
        'Premium sectors (banks, industry): up to €1,600 in the final year.',
        'Low sectors (hospitality, retail): close to minimum.',
      ],
      tip: 'The salary supports a modest life in mid-sized cities (Leipzig, Dortmund), but is very hard to manage in Munich or Hamburg without support.' },
    { num: 5, title: 'The required language level', summary: 'B1 is the theoretical minimum, but reality differs. B2 is what you actually need to succeed.', tag: 'Language',
      bullets: [
        'B1: you grasp basic instructions, communicate with difficulty.',
        'B2: solid enough to read professional textbooks and follow the teacher at school.',
        'C1: ideal for healthcare and administrative professions.',
        'Goethe B2, telc B2 or TestDaF certificates are accepted by all companies.',
      ],
      tip: 'Before applying, watch a YouTube video of a Berufsschule class in your field — if you understand it, your language is ready.' },
    { num: 6, title: 'Where to search for an Ausbildung', summary: 'Dozens of platforms, but only a few are genuinely effective. Focus your energy there.', tag: 'Search',
      bullets: [
        '**Make-it-in-Germany.com:** the official platform for skilled migration.',
        '**Ausbildung.de:** the biggest specialised platform.',
        '**Arbeitsagentur.de:** the state job bank, very accurate.',
        '**AZUBIYO.de:** good for identifying the right profession for you.',
        '**LinkedIn:** surprisingly, it works for the Ausbildung too.',
        'Applying directly via a company website: the highest acceptance rate.',
      ] },
    { num: 7, title: 'Writing a convincing Bewerbung', summary: 'The German application file differs completely from the Moroccan one. Here are the essential elements.', tag: 'File',
      bullets: [
        '**Anschreiben:** a single page, explaining why you fit this specific profession and this specific company.',
        '**Lebenslauf:** German CV: education + experience + languages + skills, professional photo.',
        '**Zeugnisse:** Baccalauréat certificate and any prior training, translated.',
        '**Zertifikate:** language certificates + any courses taken.',
      ],
      tip: 'Make it one well-organised PDF, not 10 separate files. The filename must be: Bewerbung_FirstName_LastName.pdf' },
    { num: 8, title: 'The German Lebenslauf — the right template', summary: 'No selfies, no flashy colours. Simplicity and strict order.', tag: 'File',
      bullets: [
        'Header: name, address, phone, email, date of birth, nationality.',
        'Photo: professional, white background, formal attire.',
        'Reverse chronological order: most recent first.',
        'Length: one or two pages only.',
        'Signature and date at the bottom.',
      ] },
    { num: 9, title: 'Vorstellungsgespräch — the job interview', summary: 'If you reach this stage, your chances are 50%. Good preparation doubles them.', tag: 'Interview',
      bullets: [
        'Know everything about the company: founding year, products, values.',
        'Prepare answers to the classics: why us? why Germany? why this profession?',
        'Formal dress (Business Casual at minimum).',
        'Arrive 10 minutes before the appointment, no earlier, no later.',
        'Ask questions at the end — it shows genuine interest.',
      ],
      tip: 'Many companies start with a short video call before the in-person interview. Take it just as seriously.' },
    { num: 10, title: 'Ausbildungsvisum — the training visa', summary: 'A visa dedicated to the Ausbildung. Its conditions are clearer than those of other visas.', tag: 'Visa',
      bullets: [
        'Documents: signed Ausbildungsvertrag + B1 language certificate + housing.',
        'No Sperrkonto required if the training salary is enough (~€934/month).',
        'Fee: €75.',
        'Issued for one year and renewable until the end of the training.',
      ] },
    { num: 11, title: 'The Chancenkarte (opportunity card) to search for an Ausbildung', summary: 'Since 2024, you can come to Germany for 12 months to search for training, if you meet enough points.', tag: 'New',
      bullets: [
        'Points system: language + age + education + experience.',
        'German A1 certificate at minimum + 6 points.',
        'Lets you work 20 hours/week while searching.',
        'Converts to an Ausbildungsvisum as soon as you find training.',
      ] },
    { num: 12, title: 'Einstiegsqualifizierung (EQ) — the bridge before the Ausbildung', summary: 'A 6–12 month trial programme before the Ausbildung, for those not quite ready yet.', tag: 'Preparatory',
      bullets: [
        'Partial salary (~€250–300/month) from the Arbeitsagentur.',
        'Gives the company a chance to evaluate you before a 3-year contract.',
        '70% of those who complete the EQ get an Ausbildung at the same company.',
        'An excellent option for those whose language is still relatively weak.',
      ] },
    { num: 13, title: 'The Ausbildung in nursing', summary: 'The most in-demand sector for Moroccans. High salary, fast acceptance, and a direct route to residency.', tag: 'Nursing',
      bullets: [
        'Pflegefachkraft: the unified title since 2020, combining the three old branches.',
        '3 years of training, salary ~€1,300 in the first year.',
        'Most hospitals offer subsidised housing.',
        'After graduation: ~€2,800–3,200 gross monthly.',
        'Constant demand — unemployment in this sector is rare.',
      ] },
    { num: 14, title: 'The Ausbildung in IT', summary: 'Fachinformatiker is the most popular path. You graduate at €3,000+ starting salary into a hungry market.', tag: 'IT',
      bullets: [
        'Three specialisations: Anwendungsentwicklung (development), Systemintegration (networks), Daten- und Prozessanalyse.',
        'Training salary ~€1,100 at the start, ~€1,300 at the end.',
        'Admissions favour those with prior skills (HTML/Python/Linux).',
        'After graduation: €3,200–4,500 monthly, with the option to move into full-time development.',
      ] },
    { num: 15, title: 'The Ausbildung in mechanics and industry', summary: 'Germany = industry. Every major company (BMW, Bosch, Siemens, Mercedes) takes on apprentices every year.', tag: 'Industry',
      bullets: [
        'Industriemechaniker, Mechatroniker, Elektroniker are the most common.',
        'Contracts with big groups = higher salaries + perks (free train, subsidised meals).',
        'At Mercedes and BMW, applications open about a year in advance.',
        'After training: €3,000–4,000 starting, with rapid progression.',
      ] },
    { num: 16, title: 'Daily life as an Azubi', summary: 'Typical challenges every Moroccan apprentice lives through. Prepare yourself mentally.', tag: 'Life',
      bullets: [
        'Work pressure (40 hours) + study + homework = exhaustion in the first two months.',
        'German colleagues tend to be younger (18–20) — the cultural gap is real.',
        'Halal food at the Kantine is rare — bring your own meals.',
        'Islamic holidays are not official holidays — plan your leave in advance.',
      ],
      tip: 'Find a Moroccan community in your city before you arrive. Weekly gatherings protect your mental health more than anything else.' },
    { num: 17, title: 'Apprentice rights (Azubi-Rechte)', summary: 'German law strongly protects the apprentice. Don\'t accept exploitation — you have clear rights.', tag: 'Rights',
      bullets: [
        'Paid leave: 24–30 days per year.',
        'Working hours: max 8/day, with a 30-minute break after 6 hours.',
        'No night shifts or public holiday work if you\'re under 18.',
        'Your employer may not assign you tasks unrelated to the training.',
        'You are entitled to a final work certificate (Zeugnis).',
      ] },
    { num: 18, title: 'The final IHK exam (Abschlussprüfung)', summary: 'The exam that gives you the qualification. Theoretical + practical + sometimes oral. Failure is possible, but you can retake it.', tag: 'Exam',
      bullets: [
        'Organised by the IHK (chamber of industry) or HWK (crafts).',
        'Two parts: interim (end of second year) + final.',
        'National pass rate: ~90%.',
        'You can retake the exam twice.',
        'The company is required to give you time to revise.',
      ] },
    { num: 19, title: 'After the Ausbildung — what happens?', summary: '70% of apprentices get a permanent contract at the same company. The others find work within months.', tag: 'After',
      bullets: [
        '**Übernahme:** direct hire on a permanent contract at the same company.',
        '**Meister:** higher-level qualification (1–3 years), enabling you to open your own business.',
        '**Weiterbildung:** complementary technical specialisation.',
        '**Studium:** you can enter university without Abitur after 3 years of work.',
        'Your visa converts to a work residence permit, then to permanent after just 2 years (instead of 5).',
      ] },
    { num: 20, title: 'Common mistakes Moroccans make', summary: 'Repeated across dozens of Moroccan stories. Learn from them and don\'t repeat them.', tag: 'Warnings',
      bullets: [
        'Applying to a profession you don\'t like just because it accepts faster — a 3-year path is hard to cancel.',
        'Applying with a Moroccan CV not adapted to the German template — instant rejection.',
        'Leaving your German at B1 — the vocational school will crush you.',
        'Not reading the contract before signing — some companies slip in unfair clauses.',
        'Not keeping a copy of the Anmeldung and Aufenthaltstitel on you at all times — the police ask for them.',
        'Neglecting homework at the Berufsschule — you\'ll fail the official exam.',
      ],
      tip: 'Join the "Ausbildung für Marokkaner" groups on Facebook and Telegram — the right info comes from real experience.' },
  ],
}

const de = {
  metaTitle: 'Die Ausbildung in Deutschland — kompletter Guide',
  metaDesc: '20 Artikel zur dualen Berufsausbildung: beste Berufe, Vergütung, Bewerbung und Perspektiven nach dem Abschluss.',
  eyebrow: 'Berufsausbildung',
  title: 'Die Ausbildung in Deutschland',
  subtitle: 'Die duale Ausbildung — dein Weg in den deutschen Arbeitsmarkt ohne Studium, mit Vergütung ab dem ersten Tag.',
  intro: '20 Artikel, die alles beantworten, was Marokkaner zur Ausbildung fragen: Voraussetzungen, Bewerbung, beste Branchen, Vergütung und wie du eine lange Karriere aufbaust.',
  cta: {
    title: '🔍 Suchst du gerade echte Ausbildungsangebote?',
    description: '',
    buttonLabel: 'Angebote durchstöbern ←',
    href: '/ausbildung-jobs',
  },
  items: [
    { num: 1, title: 'Was ist die Ausbildung eigentlich?', summary: 'Ein einzigartiges System: Betrieb + Berufsschule gleichzeitig — du lernst beim Arbeiten und bekommst eine Vergütung. Eine Säule der deutschen Wirtschaft.', tag: 'Grundlagen',
      bullets: [
        'Dauer: zwei bis dreieinhalb Jahre, je nach Beruf.',
        'Wochenaufteilung: 2–4 Tage im Betrieb + 1–2 Tage in der Berufsschule.',
        'Ausbildungsvertrag mit dem Betrieb, eingetragen bei der IHK oder HWK.',
        'Die Ausbildungsvergütung ist verpflichtend und steigt jedes Jahr.',
        'Abschluss mit der IHK-Abschlussprüfung und einem deutschlandweit anerkannten Zeugnis.',
      ] },
    { num: 2, title: 'Duale vs. schulische Ausbildung', summary: 'Zwei Arten der Berufsausbildung mit sehr unterschiedlichen finanziellen Folgen. Die erste ist das Ziel der meisten Marokkaner.', tag: 'Arten',
      bullets: [
        '**Duale Ausbildung:** Betrieb + Schule, mit Vergütung — die mit Abstand häufigste Form.',
        '**Schulische Ausbildung:** nur an einer Berufsschule, oft ohne Vergütung (Pflege, Physiotherapie).',
        'Die schulische Ausbildung ist manchmal kostenpflichtig (200–400 €/Monat).',
        'Seit 2020 ist die Pflege in die duale Form gewechselt und wird jetzt gut vergütet.',
      ] },
    { num: 3, title: 'Die 10 gefragtesten Berufe für Marokkaner', summary: 'Diese Berufe haben eine hohe Annahmequote und stellen direkt nach dem Abschluss ein.', tag: 'Branchen',
      bullets: [
        '**Pflegefachkraft:** Pflege — am stärksten nachgefragt und am besten bezahlt (~1.300 €/Monat zu Beginn).',
        '**Fachkraft für Lagerlogistik:** Lagerlogistik.',
        '**Elektroniker:** Elektrotechnik.',
        '**Kfz-Mechatroniker:** Kfz-Technik.',
        '**Fachinformatiker:** IT (Anwendungen / Systeme).',
        '**Kaufmann für Büromanagement:** Büromanagement.',
        '**Koch / Köchin:** Gastronomie.',
        '**Anlagenmechaniker (SHK):** Sanitär-, Heizungs- und Klimatechnik.',
        '**Industriemechaniker:** industrielle Mechanik.',
        '**Fachverkäufer:** Fachverkauf (Bäckerei, Fleischerei, Apotheke …).',
      ] },
    { num: 4, title: 'Die Vergütung während der Ausbildungsjahre', summary: 'Die Vergütung steigt jedes Jahr. Finanz- und Industriebereiche zahlen deutlich besser als etwa die Gastronomie.', tag: 'Vergütung',
      bullets: [
        'Erstes Jahr: durchschnittlich 620–1.100 €.',
        'Zweites Jahr: 720–1.200 €.',
        'Drittes Jahr: 850–1.400 €.',
        'Spitzenbranchen (Banken, Industrie): bis 1.600 € im letzten Jahr.',
        'Niedrige Branchen (Gastronomie, Einzelhandel): nahe am Mindestsatz.',
      ],
      tip: 'Die Vergütung reicht für ein bescheidenes Leben in mittelgroßen Städten (Leipzig, Dortmund), ist aber in München oder Hamburg ohne Unterstützung sehr schwierig.' },
    { num: 5, title: 'Das erforderliche Sprachniveau', summary: 'B1 ist das theoretische Minimum, die Realität sieht anders aus. B2 ist das, was du wirklich brauchst, um erfolgreich zu sein.', tag: 'Sprache',
      bullets: [
        'B1: du verstehst Grundanweisungen, kommunizierst aber nur mühsam.',
        'B2: solides Niveau, um Fachbücher zu lesen und den Lehrer in der Schule zu verstehen.',
        'C1: ideal für Gesundheits- und Verwaltungsberufe.',
        'Goethe B2, telc B2 oder TestDaF werden von allen Betrieben akzeptiert.',
      ],
      tip: 'Schau dir vor der Bewerbung ein YouTube-Video einer Berufsschulstunde in deinem Bereich an — verstehst du es, ist dein Deutsch bereit.' },
    { num: 6, title: 'Wo suchst du nach einer Ausbildung?', summary: 'Dutzende Plattformen, aber nur wenige sind wirklich wirksam. Konzentriere dich auf diese.', tag: 'Suche',
      bullets: [
        '**Make-it-in-Germany.com:** die offizielle Plattform der Fachkräfteeinwanderung.',
        '**Ausbildung.de:** die größte spezialisierte Plattform.',
        '**Arbeitsagentur.de:** die staatliche Jobbörse, sehr präzise.',
        '**AZUBIYO.de:** gut, um den passenden Beruf zu finden.',
        '**LinkedIn:** funktioniert überraschenderweise auch für die Ausbildung.',
        'Direktbewerbung über die Unternehmensseite: die höchste Annahmequote.',
      ] },
    { num: 7, title: 'Eine überzeugende Bewerbung schreiben', summary: 'Die deutsche Bewerbungsmappe unterscheidet sich völlig von der marokkanischen. Das sind die wichtigsten Bestandteile.', tag: 'Unterlagen',
      bullets: [
        '**Anschreiben:** eine Seite, die erklärt, warum du zu genau diesem Beruf und diesem Betrieb passt.',
        '**Lebenslauf:** der deutsche CV: Ausbildung + Erfahrung + Sprachen + Kompetenzen, mit Bewerbungsfoto.',
        '**Zeugnisse:** Abiturzeugnis und frühere Ausbildungen, übersetzt.',
        '**Zertifikate:** Sprachzertifikate + belegte Kurse.',
      ],
      tip: 'Eine gut sortierte PDF, keine 10 Einzeldateien. Der Dateiname sollte lauten: Bewerbung_Vorname_Nachname.pdf' },
    { num: 8, title: 'Der deutsche Lebenslauf — die richtige Vorlage', summary: 'Keine Selfies, keine grellen Farben. Schlicht und strikt geordnet.', tag: 'Unterlagen',
      bullets: [
        'Kopf: Name, Adresse, Telefon, E-Mail, Geburtsdatum, Staatsangehörigkeit.',
        'Foto: professionell, weißer Hintergrund, formelle Kleidung.',
        'Antichronologisch: das Aktuellste zuerst.',
        'Umfang: ein bis zwei Seiten, nicht mehr.',
        'Unterschrift und Datum unten.',
      ] },
    { num: 9, title: 'Vorstellungsgespräch', summary: 'Wer hier angekommen ist, hat 50 % Chancen. Gute Vorbereitung verdoppelt sie.', tag: 'Gespräch',
      bullets: [
        'Informiere dich umfassend über den Betrieb: Gründungsjahr, Produkte, Werte.',
        'Bereite Antworten auf die Klassiker vor: Warum wir? Warum Deutschland? Warum dieser Beruf?',
        'Formelle Kleidung (mindestens Business Casual).',
        '10 Minuten vor dem Termin da sein — nicht früher, nicht später.',
        'Stelle am Ende Fragen — das zeigt echtes Interesse.',
      ],
      tip: 'Viele Betriebe starten mit einem kurzen Videocall vor dem Präsenzgespräch. Nimm ihn genauso ernst.' },
    { num: 10, title: 'Ausbildungsvisum', summary: 'Ein Visum speziell für die Ausbildung. Seine Voraussetzungen sind klarer als bei anderen Visa.', tag: 'Visum',
      bullets: [
        'Unterlagen: unterschriebener Ausbildungsvertrag + B1-Sprachzertifikat + Wohnung.',
        'Kein Sperrkonto nötig, wenn die Ausbildungsvergütung ausreicht (~934 €/Monat).',
        'Gebühr: 75 €.',
        'Wird für ein Jahr ausgestellt und bis zum Ende der Ausbildung verlängert.',
      ] },
    { num: 11, title: 'Die Chancenkarte für die Ausbildungssuche', summary: 'Seit 2024 kannst du 12 Monate nach Deutschland kommen, um eine Ausbildung zu suchen — wenn du genug Punkte hast.', tag: 'Neu',
      bullets: [
        'Punktesystem: Sprache + Alter + Bildung + Erfahrung.',
        'Deutschzertifikat A1 als Minimum + 6 Punkte.',
        'Erlaubt 20 Stunden Arbeit pro Woche während der Suche.',
        'Wird in ein Ausbildungsvisum umgewandelt, sobald du eine Ausbildung gefunden hast.',
      ] },
    { num: 12, title: 'Einstiegsqualifizierung (EQ) — die Brücke vor der Ausbildung', summary: 'Ein 6–12-monatiges Probeprogramm vor der Ausbildung, für alle, die noch nicht ganz bereit sind.', tag: 'Vorbereitung',
      bullets: [
        'Teilvergütung (~250–300 €/Monat) von der Arbeitsagentur.',
        'Gibt dem Betrieb die Gelegenheit, dich vor einem 3-Jahres-Vertrag zu prüfen.',
        '70 % derjenigen, die die EQ abschließen, erhalten eine Ausbildung im selben Betrieb.',
        'Eine hervorragende Option für alle mit relativ schwachen Sprachkenntnissen.',
      ] },
    { num: 13, title: 'Ausbildung in der Pflege', summary: 'Die gefragteste Branche für Marokkaner. Hohe Vergütung, schnelle Zusagen und ein direkter Weg zum Aufenthaltstitel.', tag: 'Pflege',
      bullets: [
        'Pflegefachkraft: der neue Titel seit 2020, fasst die drei alten Sparten zusammen.',
        '3 Jahre Ausbildung, ~1.300 € Vergütung im ersten Jahr.',
        'Die meisten Krankenhäuser bieten subventionierte Wohnungen.',
        'Nach dem Abschluss: ~2.800–3.200 € brutto monatlich.',
        'Dauerhafte Nachfrage — Arbeitslosigkeit ist in dieser Branche selten.',
      ] },
    { num: 14, title: 'Ausbildung in der IT', summary: 'Fachinformatiker ist der bekannteste Weg. Du steigst mit 3.000 €+ Einstiegsgehalt in einen hungrigen Markt ein.', tag: 'IT',
      bullets: [
        'Drei Fachrichtungen: Anwendungsentwicklung, Systemintegration, Daten- und Prozessanalyse.',
        'Ausbildungsvergütung: ~1.100 € am Anfang, ~1.300 € am Ende.',
        'Bei der Annahme werden Bewerber mit Vorkenntnissen bevorzugt (HTML/Python/Linux).',
        'Nach dem Abschluss: 3.200–4.500 € monatlich, mit der Möglichkeit, in die Vollzeitentwicklung zu wechseln.',
      ] },
    { num: 15, title: 'Ausbildung in Mechanik und Industrie', summary: 'Deutschland = Industrie. Jeder große Konzern (BMW, Bosch, Siemens, Mercedes) nimmt jedes Jahr Azubis auf.', tag: 'Industrie',
      bullets: [
        'Industriemechaniker, Mechatroniker und Elektroniker sind am häufigsten.',
        'Verträge bei Großkonzernen = höhere Vergütung + Vorteile (Gratiszug, Essenszuschuss).',
        'Bei Mercedes und BMW starten die Bewerbungen rund ein Jahr vorher.',
        'Nach der Ausbildung: 3.000–4.000 € Einstieg, mit schneller Entwicklung.',
      ] },
    { num: 16, title: 'Der Alltag als Azubi', summary: 'Typische Herausforderungen, die jeder marokkanische Azubi erlebt. Stelle dich mental darauf ein.', tag: 'Alltag',
      bullets: [
        'Arbeitsdruck (40 Stunden) + Schule + Hausaufgaben = Erschöpfung in den ersten zwei Monaten.',
        'Deutsche Kollegen sind meist jünger (18–20) — die kulturelle Lücke ist real.',
        'Halal-Essen in der Kantine ist selten — bring dir was mit.',
        'Islamische Feiertage sind keine gesetzlichen Feiertage — plane deinen Urlaub im Voraus.',
      ],
      tip: 'Finde vor deiner Ankunft die marokkanische Community in deiner Stadt. Wöchentliche Treffen schützen deine mentale Gesundheit mehr als alles andere.' },
    { num: 17, title: 'Rechte der Azubis (Azubi-Rechte)', summary: 'Das deutsche Recht schützt Azubis sehr stark. Lass dich nicht ausnutzen — du hast klare Rechte.', tag: 'Rechte',
      bullets: [
        'Bezahlter Urlaub: 24–30 Tage pro Jahr.',
        'Arbeitszeit: maximal 8 Stunden/Tag, mit 30 Minuten Pause nach 6 Stunden.',
        'Keine Nachtarbeit und keine Feiertagsarbeit, wenn du unter 18 bist.',
        'Der Ausbildungsbetrieb darf dir keine ausbildungsfremden Aufgaben zuweisen.',
        'Du hast Anspruch auf ein Abschlusszeugnis.',
      ] },
    { num: 18, title: 'Die IHK-Abschlussprüfung', summary: 'Die Prüfung, die dir das Zeugnis bringt. Theorie + Praxis + manchmal mündlich. Durchfallen ist möglich, aber wiederholbar.', tag: 'Prüfung',
      bullets: [
        'Wird über die IHK (Industrie- und Handelskammer) oder HWK (Handwerkskammer) abgelegt.',
        'Zwei Teile: Zwischenprüfung (Ende zweites Jahr) + Abschlussprüfung.',
        'Bundesweite Bestehensquote: ~90 %.',
        'Du kannst die Prüfung zweimal wiederholen.',
        'Der Betrieb ist verpflichtet, dir Zeit zum Lernen zu geben.',
      ] },
    { num: 19, title: 'Nach der Ausbildung — was passiert?', summary: '70 % der Azubis bekommen einen unbefristeten Vertrag im selben Betrieb. Die anderen finden innerhalb weniger Monate eine Stelle.', tag: 'Danach',
      bullets: [
        '**Übernahme:** direkte Übernahme in ein unbefristetes Arbeitsverhältnis im selben Betrieb.',
        '**Meister:** höherer Abschluss (1–3 Jahre), mit dem du dich selbstständig machen kannst.',
        '**Weiterbildung:** ergänzende fachliche Spezialisierung.',
        '**Studium:** du kannst ohne Abitur nach 3 Jahren Berufserfahrung studieren.',
        'Dein Visum wird in eine Aufenthaltserlaubnis zur Beschäftigung umgewandelt, dann schon nach 2 Jahren (statt 5) in eine Niederlassungserlaubnis.',
      ] },
    { num: 20, title: 'Häufige Fehler von Marokkanern', summary: 'In dutzenden marokkanischen Erfahrungen immer wieder aufgetaucht. Lerne daraus und mach sie nicht noch einmal.', tag: 'Warnungen',
      bullets: [
        'Sich auf einen Beruf bewerben, den man nicht mag, nur weil er schneller zusagt — ein 3-Jahres-Weg lässt sich schwer abbrechen.',
        'Mit einem marokkanischen CV ohne Anpassung an die deutsche Vorlage bewerben — sofortige Absage.',
        'Das Deutsch auf B1 stehen lassen — die Berufsschule wird dich plattmachen.',
        'Den Vertrag nicht vor der Unterschrift lesen — manche Betriebe bauen unfaire Klauseln ein.',
        'Keine Kopie der Anmeldung und des Aufenthaltstitels dabei haben — die Polizei fragt danach.',
        'Hausaufgaben in der Berufsschule vernachlässigen — du fällst in der offiziellen Prüfung durch.',
      ],
      tip: 'Tritt den Gruppen „Ausbildung für Marokkaner" auf Facebook und Telegram bei — die richtigen Infos kommen aus echter Erfahrung.' },
  ],
}

const byLoc = { ar, fr, en, de }

// Ensure `common.tipLabel` key exists
const tipLabel = { ar: 'نصيحة', fr: 'Astuce', en: 'Tip', de: 'Tipp' }

for (const loc of ['ar', 'fr', 'en', 'de']) {
  const p = path.join(__dirname, '..', 'messages', `${loc}.json`)
  const j = JSON.parse(fs.readFileSync(p, 'utf8'))
  j.static = j.static || {}
  j.static.ausbildung = byLoc[loc]
  j.common = j.common || {}
  j.common.tipLabel = tipLabel[loc]
  fs.writeFileSync(p, JSON.stringify(j, null, 2) + '\n', 'utf8')
  console.log(`✓ ${loc}.json`)
}
