const fs = require('fs')
const path = require('path')

const ar = {
  metaTitle: 'البنوك والحسابات في ألمانيا — دليلك الشامل',
  metaDesc: '20 مقالاً يشرحان كل ما تحتاجه لفتح حساب بنكي وإدارة أموالك في ألمانيا.',
  eyebrow: 'الأموال والبنوك',
  title: 'البنوك والحسابات في ألمانيا',
  subtitle: 'كل ما يحتاجه المغربي لبدء حياته المالية في ألمانيا — من اختيار البنك إلى التحويلات والرسوم.',
  intro: '20 مقالاً مكثّفاً مبني على تجارب حقيقية، يغطّي كل مرحلة: قبل الوصول، عند الوصول، وخلال السنوات الأولى في ألمانيا.',
  items: [
    { num: 1, title: 'لماذا تحتاج حساباً بنكياً ألمانياً؟', summary: 'الحساب البنكي ليس رفاهية في ألمانيا — بدونه لن تستلم راتبك، لن تدفع إيجارك، ولن تتمكّن من إتمام أي إجراء رسمي تقريباً.', tag: 'أساسيات',
      paragraph: 'ألمانيا بلد تحويلات مصرفية (Überweisung) قبل أي شيء. الراتب يُصرف بتحويل، الإيجار يُخصم آلياً عبر خصم مباشر (Lastschrift)، الفواتير كلها تمر عبر الحساب، حتى المنح والضمان الاجتماعي تحتاج IBAN ألمانياً.',
      bullets: ['صاحب العمل يطلب IBAN ألمانياً قبل أول راتب.', 'مالك الشقة يحتاج حساباً لإعداد Lastschrift للإيجار.', 'التأمين الصحي، الضرائب، الكهرباء، الإنترنت — كلها تعمل بالخصم المباشر.'],
      tip: 'افتح حساباً رقمياً قبل مغادرة المغرب إن أمكن، أو في أول أسبوع بعد الوصول كحدّ أقصى.' },
    { num: 2, title: 'الفرق بين Girokonto و Sparkonto و Tagesgeld', summary: 'ثلاثة أنواع من الحسابات في ألمانيا، كلٌّ لغرض مختلف. اختر الخطأ وستخسر ربحاً أو تجد مالك محجوزاً.', tag: 'أنواع الحسابات',
      bullets: ['**Girokonto:** الحساب الجاري — لاستقبال الراتب ودفع الفواتير. هو ما تحتاجه أولاً.', '**Sparkonto:** حساب ادّخار تقليدي بفائدة ضعيفة، يمكن السحب منه أي وقت.', '**Tagesgeldkonto:** حساب يومي بفائدة أعلى (2–4% حالياً)، سيولة كاملة، مثالي للاحتياطي.', '**Festgeld:** وديعة ثابتة لمدة محددة بفائدة أعلى، لكن المال مقفل.'] },
    { num: 3, title: 'N26 — الخيار الأول للوافد الجديد', summary: 'بنك رقمي 100%، يُفتح من الهاتف خلال 15 دقيقة، بدون Schufa ولا زيارة فرع. مثالي لأول أسابيعك في ألمانيا.', tag: 'بنك رقمي',
      bullets: ['بدون رسوم شهرية في الخطة المجانية.', 'لا يحتاج Anmeldung في بعض الحالات — يكفي جواز السفر وعنوان ألماني.', 'التحقق من الهوية عبر VideoIdent بالعربية غير متاح — لكنه بالإنجليزية أو الألمانية.', 'بطاقة Maestro/Debit Mastercard تصل بالبريد خلال 5–10 أيام.', 'التطبيق ممتاز: إشعارات فورية، تصنيف تلقائي، أهداف ادخار.'],
      tip: 'بعض الشركات الألمانية القديمة لا تقبل IBAN يبدأ بـ DE من N26 (لأن IBAN أحياناً يبدأ بـ FR أو ES). تحقق قبل إعطائه لصاحب العمل.' },
    { num: 4, title: 'DKB — المجانية مع بطاقة ائتمان فعلية', summary: 'من أفضل البنوك المجانية. يقدّم بطاقة ائتمان Visa حقيقية (ليست فقط Debit) مع ميزات سحب نقدي مجاناً.', tag: 'بنك مجاني',
      paragraph: 'DKB مناسب جداً لمن يسافر كثيراً أو يشتري أونلاين بالعملات الأجنبية. البطاقة الائتمانية تتيح سحباً مجاناً من أي صرّاف حول العالم (بعد تحويل رصيد إليها).',
      bullets: ['Girokonto مجاني دون شروط راتب أدنى.', 'تطبيق جيّد لكن أقل حداثة من N26.', 'يحتاج Anmeldung مكتملة للتسجيل.', 'خدمة عملاء بالألمانية أو الإنجليزية.'] },
    { num: 5, title: 'Sparkasse — البنك المحلي الأقرب إليك', summary: 'شبكة ضخمة من البنوك الإقليمية. كل مدينة لها Sparkasse خاصة بها. ليس الأرخص، لكن الأكثر أماناً اجتماعياً.', tag: 'بنك تقليدي',
      paragraph: 'إذا طلب منك عقد إيجار أو صاحب عمل حساباً في بنك "حقيقي" بفرع فيزيائي، Sparkasse هي الحل الأنسب. لكن انتبه: معظم الفروع تفرض رسوماً شهرية (5–10 يورو) على الحساب الجاري.',
      bullets: ['فروع منتشرة حتى في القرى الصغيرة.', 'مكاتب صرّافات آلية مجانية ضمن شبكة Sparkasse.', 'معاملات Counter (شخصية) متاحة لمن يحتاج الخدمة الحضورية.', 'يحتاج Anmeldung ومقابلة شخصية لفتح الحساب.'] },
    { num: 6, title: 'Commerzbank و Deutsche Bank — البنوك الكبرى', summary: 'مناسبة لمن يحتاج قروضاً أو خدمات استثمار متقدّمة. تقدّمان حسابات مجانية للطلاب ولمن يحوّل راتباً كافياً.', tag: 'بنوك كبرى',
      bullets: ['Commerzbank: حساب مجاني مع تحويل راتب ≥ 700€ شهرياً.', 'Deutsche Bank: مناسب للعلاقات الدولية والاستثمار.', 'بعض الفروع بها موظفون يتكلمون الإنجليزية أو الفرنسية.', 'رسوم مرتفعة نسبياً إذا لم تحقّق شروط الإعفاء.'] },
    { num: 7, title: 'ING و Comdirect — بدائل رقمية ممتازة', summary: 'بنكان رقميان بفروع افتراضية لكن مدعومة من مجموعات كبيرة (ING DiBa و Commerzbank).', tag: 'بنوك رقمية',
      bullets: ['ING: Girokonto مجاني بشرط دخول شهري ≥ 700€، سحب مجاني من أي صرّاف داخل الاتحاد.', 'Comdirect: مجاني أول 3 سنوات، ثم بشرط دخل شهري.', 'كلاهما يدعم Apple Pay و Google Pay.', 'الدعم بالألمانية بشكل أساسي.'] },
    { num: 8, title: 'الوثائق المطلوبة لفتح حساب', summary: 'قائمة مرجعية دقيقة لما يطلبه أي بنك ألماني. جمّعها قبل التقديم لتوفّر الوقت.', tag: 'وثائق',
      bullets: ['جواز السفر أو بطاقة الإقامة (Aufenthaltstitel).', 'Anmeldebestätigung (وثيقة تسجيل البلدية).', 'عنوان سكن كامل في ألمانيا.', 'Steuer-ID (رقم الضريبة) إن توفّر.', 'رقم هاتف ألماني للتأكيد.', 'بعض البنوك: إثبات دخل أو عقد عمل/دراسة.'],
      tip: 'البنوك الرقمية (N26, Vivid) قد تقبلك بدون Anmeldung في البداية، لكن ستطلبها لاحقاً للتحقق الكامل.' },
    { num: 9, title: 'VideoIdent و PostIdent — كيف يتم التحقق من هويتك', summary: 'لا يمكن فتح حساب دون التحقق من هويتك. هذان الخياران الأكثر شيوعاً.', tag: 'تحقق هوية',
      bullets: ['**VideoIdent:** مكالمة فيديو مع موظف، مدتها 5–10 دقائق، متاحة من أي مكان. الأسرع.', '**PostIdent:** تذهب إلى أقرب مكتب بريد (Deutsche Post) مع نموذج مطبوع وجوازك. مجاني.', 'كلاهما مجاني إذا طلبه البنك.', 'اختر VideoIdent إذا كنت في المغرب أو عند الوصول الحديث.'] },
    { num: 10, title: 'Schufa — السجل الائتماني الألماني', summary: 'سجلّ يحدّد ثقتك المالية. يؤثّر على استئجار الشقة، فتح بعض الحسابات، والحصول على القروض.', tag: 'ائتمان',
      paragraph: 'Schufa يُحسب تلقائياً من نشاطك المالي في ألمانيا. عند الوصول حديثاً، سجلّك "فارغ" — وهذا ليس سيئاً، لكن بعض الشركات تعتبره مخاطرة. يتحسّن تلقائياً بمرور الوقت ودفع فواتيرك في الوقت المحدد.',
      bullets: ['أول Schufa Auskunft (نسخة مجانية) من حقك سنوياً عبر meineschufa.de.', 'لا تأخذ قروضاً غير ضرورية لبناء السجلّ — يكفي استخدام Girokonto بانتظام.', 'دفعات الإيجار في الوقت والفواتير ترفع نقاطك.'],
      tip: 'بعض ملّاك الشقق يطلبون Schufa-Bonitätscheck — احصل على النسخة المختصرة للإيجار مقابل 30 يورو.' },
    { num: 11, title: 'IBAN و SEPA — لغة التحويلات الأوروبية', summary: 'IBAN هو رقم حسابك الدولي. SEPA هي شبكة التحويلات الأوروبية التي تجعل التحويل الداخلي مجانياً وفوريّاً.', tag: 'تحويلات',
      bullets: ['IBAN الألماني يبدأ بـ DE ويتكوّن من 22 رقماً.', 'تحويل SEPA داخل الاتحاد الأوروبي: مجاني، يصل خلال 1–2 يوم عمل.', 'SEPA Instant: تحويل فوري (10 ثوانٍ)، بعض البنوك يفرض رسماً صغيراً.', 'BIC مطلوب فقط في بعض الحالات الدولية؛ IBAN وحده يكفي عادةً.'] },
    { num: 12, title: 'الخصم المباشر (Lastschrift) — كيف يعمل ومتى ترفضه', summary: 'Lastschrift يسمح لأي شركة بسحب المال مباشرة من حسابك بعد تصريحك. أداة ممتازة لكن يجب الحذر.', tag: 'مدفوعات',
      bullets: ['تعطي الشركة Mandat (تصريح) مرة واحدة، ثم تسحب تلقائياً (إيجار، إنترنت، تأمين...).', 'من حقك استرجاع أي خصم خلال 8 أسابيع بسبب أو بدون سبب.', 'راجع كشف حسابك شهرياً — خصومات غير مشروعة تحدث.', 'لإلغاء Mandat: أرسل إيميلاً للشركة + بلّغ البنك.'] },
    { num: 13, title: 'الأوامر الدائمة (Dauerauftrag) — لدفع الإيجار تلقائياً', summary: 'عكس Lastschrift — أنت من يُصدر الأمر بتحويل مبلغ ثابت في تاريخ محدّد كل شهر. مثالي للإيجار.', tag: 'مدفوعات',
      bullets: ['يُضبط من تطبيق البنك في دقيقة.', 'يمكن تعديله أو إيقافه في أي وقت.', 'الأفضل لدفع الإيجار لصاحب البيت.', 'بعض البنوك تحاسب على إعداد Dauerauftrag ورقياً، ومجاناً رقمياً.'] },
    { num: 14, title: 'EC-Karte (Girocard) وبطاقات الائتمان في ألمانيا', summary: 'ألمانيا ما زالت بلد EC-Karte (Girocard). كثير من المحلات لا تقبل Visa/Mastercard. افهم الفرق.', tag: 'بطاقات',
      bullets: ['Girocard (EC): بطاقة خصم محلية، مقبولة في كل محل تقريباً.', 'Debit Mastercard/Visa: تعمل دولياً لكن قد تُرفض في بعض المخابز والأسواق.', 'Credit Card (بطاقة ائتمان حقيقية): للسفر والحجوزات الدولية.', 'كثير من المحلات ما زالت تفضّل النقد — احمل نقوداً دائماً.'],
      tip: 'اطلب إصدار Girocard إضافية من بنكك الرقمي إن أمكن، أو افتح حساباً ثانياً في Sparkasse لهذا الغرض.' },
    { num: 15, title: 'سحب النقود — شبكات الصرّافات وكيف تتجنّب الرسوم', summary: 'ليست كل الصرّافات مجانية. السحب من صرّاف مختلف قد يكلّفك 5 يورو لعملية واحدة.', tag: 'صرّافات',
      bullets: ['**Cash Group:** Deutsche Bank + Commerzbank + Postbank + HypoVereinsbank — مجاني لعملائها.', '**Cash Pool:** يشمل Santander + Sparda + Targobank وغيرها.', '**Sparkassen:** شبكتها الخاصة، مجانية لبطاقات Sparkasse.', 'DKB و ING: سحب مجاني من معظم الصرّافات داخل الاتحاد.', 'الحل الأبسط: استخدم Cashback في السوبرماركت (Rewe, Lidl) — مجاني.'] },
    { num: 16, title: 'التحويل من وإلى المغرب — أرخص الطرق', summary: 'الرسوم البنكية على التحويل الدولي مرتفعة جداً. استخدم خدمات متخصّصة لتوفير عشرات اليوروهات.', tag: 'تحويلات دولية',
      bullets: ['**Wise (TransferWise):** سعر صرف شبه وسطي، رسم شفّاف، أسرع خيار.', '**Revolut:** جيد للتحويلات الصغيرة المتكرّرة.', '**Western Union / MoneyGram:** سريع لكن غالي جداً (5–8%).', 'التحويل المصرفي المباشر (SWIFT): 15–40 يورو رسم + سعر صرف سيّئ.', 'احذر العروض المغرية عبر "صديق" — غالباً غسيل أموال.'],
      tip: 'قارن دائماً سعر الصرف الفعلي على Google قبل أي تحويل، لأن معظم الرسوم تكون مخبّأة في السعر.' },
    { num: 17, title: 'الضرائب والحساب البنكي — ما يجب أن تعرفه', summary: 'Finanzamt مرتبط بحسابك. أي فائدة أو أرباح تُبلّغ تلقائياً. افهم أساسيات الاحتساب.', tag: 'ضرائب',
      bullets: ['Freistellungsauftrag: إعفاء تلقائي لأول 1,000 يورو من فوائد الحساب سنوياً (2,000 للزوجين).', 'بدونه، البنك يخصم 25% (Abgeltungssteuer) من أي فائدة مباشرة.', 'Steuer-ID (رقم الضريبة) مطلوب لفتح أي حساب منذ 2024.', 'بنوك الادّخار ترسل Steuerbescheinigung سنوياً لتصريحك الضريبي.'] },
    { num: 18, title: 'الأمان على الإنترنت — حماية حسابك', summary: 'الاحتيال البنكي الإلكتروني منتشر. اتبع هذه القواعد الذهبية لتحمي نفسك.', tag: 'أمان',
      bullets: ['لا تدخل بيانات بنكك إلا على الموقع/التطبيق الرسمي.', 'لا يطلب أي بنك كلمة المرور عبر الهاتف أو البريد — أبداً.', 'فعّل 2FA (رسالة SMS أو تطبيق TAN) على كل العمليات.', 'راجع كشف الحساب أسبوعياً — الاستراحة شهراً كاملاً خطر.', 'رسائل "بنك" تطلب تحديث البيانات = محاولة تصيّد (Phishing).'] },
    { num: 19, title: 'حساب مشترك (Gemeinschaftskonto) للزوجين', summary: 'نوعان من الحسابات المشتركة في ألمانيا، ولكل منهما نتائج قانونية مختلفة عند الوفاة أو الطلاق.', tag: 'شراكة',
      bullets: ['**Oder-Konto:** كل شريك يتصرّف مستقلاً (الأكثر شيوعاً).', '**Und-Konto:** يتطلّب توقيع الطرفين لأي عملية.', 'Oder-Konto أسهل يومياً، لكن يفتح الباب لمخاطر الثقة.', 'عند الانفصال، المال يُعتبر مملوكاً مناصفة افتراضياً.', 'احتفظ دائماً بحساب شخصي مستقل إلى جانبه.'] },
    { num: 20, title: 'إغلاق الحساب عند المغادرة النهائية', summary: 'إغلاق حسابك من المغرب شبه مستحيل. نفّذ الإجراءات قبل السفر لتتجنّب مشاكل لاحقة.', tag: 'إغلاق',
      bullets: ['ألغِ كل Lastschrift و Dauerauftrag قبل الإغلاق.', 'احصل على Kontoauszug نهائي وخطاب إغلاق (Kontoauflösungsbestätigung).', 'أبلغ Finanzamt و Einwohnermeldeamt بعنوانك الجديد.', 'بعض البنوك يفرض رسم إغلاق (10–30 يورو).', 'احتفظ بجميع المراسلات 10 سنوات على الأقل.'],
      tip: 'لا تُغلق الحساب إلا بعد استلام آخر راتب ودفع آخر إيجار. انتظار شهر إضافي يوفّر عليك مشاكل ضخمة.' },
  ],
}

const fr = {
  metaTitle: 'Banques et comptes en Allemagne — ton guide complet',
  metaDesc: '20 articles qui expliquent tout ce qu\'il faut pour ouvrir un compte bancaire et gérer ton argent en Allemagne.',
  eyebrow: 'Argent & banques',
  title: 'Banques et comptes en Allemagne',
  subtitle: 'Tout ce qu\'un Marocain doit savoir pour démarrer sa vie financière en Allemagne — du choix de la banque aux virements et aux frais.',
  intro: '20 articles denses basés sur des expériences réelles, couvrant chaque étape : avant l\'arrivée, à l\'arrivée, et pendant les premières années en Allemagne.',
  items: [
    { num: 1, title: 'Pourquoi as-tu besoin d\'un compte bancaire allemand ?', summary: 'En Allemagne, le compte bancaire n\'est pas un luxe — sans lui tu ne recevras pas ton salaire, tu ne paieras pas ton loyer, et tu ne pourras quasiment accomplir aucune démarche officielle.', tag: 'Bases',
      paragraph: 'L\'Allemagne est avant tout un pays de virements bancaires (Überweisung). Le salaire arrive par virement, le loyer est prélevé automatiquement par prélèvement direct (Lastschrift), toutes les factures passent par le compte, même les bourses et la sécurité sociale exigent un IBAN allemand.',
      bullets: ['L\'employeur demande un IBAN allemand avant le premier salaire.', 'Le propriétaire a besoin d\'un compte pour mettre en place un Lastschrift pour le loyer.', 'Assurance santé, impôts, électricité, internet — tout fonctionne par prélèvement.'],
      tip: 'Ouvre un compte en ligne avant de quitter le Maroc si possible, ou au plus tard dans la première semaine après ton arrivée.' },
    { num: 2, title: 'La différence entre Girokonto, Sparkonto et Tagesgeld', summary: 'Trois types de comptes en Allemagne, chacun pour un usage différent. Mauvais choix = gain perdu ou argent bloqué.', tag: 'Types de comptes',
      bullets: ['**Girokonto :** compte courant — pour recevoir le salaire et payer les factures. C\'est ce qu\'il te faut d\'abord.', '**Sparkonto :** compte d\'épargne classique à faible taux, retirable à tout moment.', '**Tagesgeldkonto :** compte à taux plus élevé (2–4 % actuellement), totalement liquide, idéal pour une réserve.', '**Festgeld :** dépôt à terme à taux plus élevé, mais l\'argent est bloqué pour une durée fixe.'] },
    { num: 3, title: 'N26 — le premier choix pour un nouvel arrivant', summary: 'Banque 100 % numérique, ouverte depuis le téléphone en 15 minutes, sans Schufa ni visite en agence. Parfaite pour tes premières semaines.', tag: 'Banque en ligne',
      bullets: ['Aucuns frais mensuels dans le plan gratuit.', 'Ne nécessite pas toujours d\'Anmeldung — passeport et adresse allemande suffisent souvent.', 'Vérification d\'identité via VideoIdent non disponible en arabe — mais en anglais ou allemand, oui.', 'La carte Maestro/Debit Mastercard arrive par courrier en 5–10 jours.', 'L\'appli est excellente : notifications instantanées, catégorisation automatique, objectifs d\'épargne.'],
      tip: 'Certaines vieilles entreprises allemandes refusent les IBAN non-DE de N26 (ils commencent parfois par FR ou ES). Vérifie avant de le donner à ton employeur.' },
    { num: 4, title: 'DKB — gratuite avec une vraie carte de crédit', summary: 'L\'une des meilleures banques gratuites. Offre une vraie carte Visa (pas seulement Debit) avec retraits d\'espèces gratuits.', tag: 'Banque gratuite',
      paragraph: 'DKB est idéale si tu voyages beaucoup ou achètes en ligne en devises étrangères. La carte de crédit permet des retraits gratuits dans n\'importe quel distributeur dans le monde (après y avoir transféré du solde).',
      bullets: ['Girokonto gratuit sans condition de salaire minimum.', 'Appli correcte mais moins moderne que N26.', 'Nécessite un Anmeldung complet pour l\'inscription.', 'Service client en allemand ou en anglais.'] },
    { num: 5, title: 'Sparkasse — la banque locale la plus proche de toi', summary: 'Immense réseau de banques régionales. Chaque ville a sa propre Sparkasse. Pas la moins chère, mais la plus rassurante socialement.', tag: 'Banque classique',
      paragraph: 'Si un bail ou un employeur te demande un compte dans une banque « réelle » avec agence physique, Sparkasse est la meilleure option. Attention cependant : la plupart des agences facturent des frais mensuels (5–10 €) sur le compte courant.',
      bullets: ['Agences partout, même dans les petits villages.', 'Distributeurs gratuits au sein du réseau Sparkasse.', 'Opérations au guichet disponibles pour ceux qui ont besoin de service en présentiel.', 'Ouverture : Anmeldung + entretien en personne requis.'] },
    { num: 6, title: 'Commerzbank et Deutsche Bank — les grandes banques', summary: 'Adaptées à ceux qui ont besoin de prêts ou de services d\'investissement avancés. Elles offrent des comptes gratuits aux étudiants et à ceux qui virent un salaire suffisant.', tag: 'Grandes banques',
      bullets: ['Commerzbank : compte gratuit avec virement de salaire ≥ 700 €/mois.', 'Deutsche Bank : adaptée aux relations internationales et à l\'investissement.', 'Certaines agences ont du personnel parlant anglais ou français.', 'Frais assez élevés si tu ne remplis pas les conditions d\'exonération.'] },
    { num: 7, title: 'ING et Comdirect — excellentes alternatives en ligne', summary: 'Deux banques en ligne à agences virtuelles, mais adossées à de grands groupes (ING DiBa et Commerzbank).', tag: 'Banques en ligne',
      bullets: ['ING : Girokonto gratuit avec entrée mensuelle ≥ 700 €, retraits gratuits dans toute l\'UE.', 'Comdirect : gratuit les 3 premières années, puis sous condition de revenus mensuels.', 'Les deux supportent Apple Pay et Google Pay.', 'Support principalement en allemand.'] },
    { num: 8, title: 'Documents requis pour ouvrir un compte', summary: 'Check-list précise de ce que toute banque allemande demande. Rassemble-les avant de déposer pour gagner du temps.', tag: 'Documents',
      bullets: ['Passeport ou titre de séjour (Aufenthaltstitel).', 'Anmeldebestätigung (attestation d\'inscription à la mairie).', 'Adresse complète en Allemagne.', 'Steuer-ID (numéro fiscal) si disponible.', 'Numéro de téléphone allemand pour confirmation.', 'Certaines banques : justificatif de revenu ou contrat de travail/études.'],
      tip: 'Les banques en ligne (N26, Vivid) peuvent t\'accepter sans Anmeldung au début, mais l\'exigeront plus tard pour la vérification complète.' },
    { num: 9, title: 'VideoIdent et PostIdent — comment vérifier ton identité', summary: 'Impossible d\'ouvrir un compte sans vérification d\'identité. Voici les deux options les plus courantes.', tag: 'Vérification d\'identité',
      bullets: ['**VideoIdent :** appel vidéo avec un agent, 5–10 min, depuis n\'importe où. Le plus rapide.', '**PostIdent :** tu vas au bureau de poste (Deutsche Post) le plus proche avec un formulaire imprimé et ton passeport. Gratuit.', 'Les deux sont gratuits s\'ils sont demandés par la banque.', 'Choisis VideoIdent si tu es au Maroc ou fraîchement arrivé.'] },
    { num: 10, title: 'Schufa — le dossier de crédit allemand', summary: 'Dossier qui définit ta fiabilité financière. Il influe sur la location d\'appartement, l\'ouverture de certains comptes et l\'obtention de prêts.', tag: 'Crédit',
      paragraph: 'La Schufa se calcule automatiquement à partir de ton activité financière en Allemagne. À l\'arrivée, ton dossier est « vide » — ce n\'est pas mauvais, mais certaines entreprises voient ça comme un risque. Il s\'améliore avec le temps et le paiement ponctuel de tes factures.',
      bullets: ['Une première Schufa Auskunft (copie gratuite) est ton droit chaque année via meineschufa.de.', 'Ne prends pas de prêts inutiles pour bâtir ton dossier — utiliser un Girokonto régulièrement suffit.', 'Loyers payés à temps et factures régulières font monter ton score.'],
      tip: 'Certains propriétaires exigent un Schufa-Bonitätscheck — prends la version courte pour la location à environ 30 €.' },
    { num: 11, title: 'IBAN et SEPA — la langue des virements européens', summary: 'L\'IBAN est ton numéro de compte international. SEPA est le réseau européen qui rend les virements internes gratuits et rapides.', tag: 'Virements',
      bullets: ['L\'IBAN allemand commence par DE et compte 22 caractères.', 'Virement SEPA dans l\'UE : gratuit, arrive en 1–2 jours ouvrés.', 'SEPA Instant : virement instantané (10 secondes), certaines banques facturent un petit frais.', 'Le BIC n\'est nécessaire que dans certains cas internationaux ; l\'IBAN seul suffit généralement.'] },
    { num: 12, title: 'Prélèvement direct (Lastschrift) — comment ça marche et quand le refuser', summary: 'Le Lastschrift permet à une entreprise de prélever directement sur ton compte après autorisation. Outil pratique mais à manier avec prudence.', tag: 'Paiements',
      bullets: ['Tu donnes un Mandat (autorisation) à l\'entreprise une fois, puis elle prélève automatiquement (loyer, internet, assurance…).', 'Tu as le droit de récupérer tout prélèvement pendant 8 semaines, avec ou sans raison.', 'Relève ton compte mensuellement — des prélèvements abusifs arrivent.', 'Pour annuler un Mandat : envoie un e-mail à l\'entreprise et préviens la banque.'] },
    { num: 13, title: 'Virements permanents (Dauerauftrag) — pour payer le loyer automatiquement', summary: 'L\'inverse du Lastschrift — c\'est toi qui ordonnes un virement d\'un montant fixe à une date précise chaque mois. Idéal pour le loyer.', tag: 'Paiements',
      bullets: ['Se règle depuis l\'appli bancaire en une minute.', 'Modifiable ou arrêtable à tout moment.', 'La meilleure méthode pour payer le loyer au propriétaire.', 'Certaines banques facturent la mise en place papier, mais c\'est gratuit en ligne.'] },
    { num: 14, title: 'EC-Karte (Girocard) et cartes de crédit en Allemagne', summary: 'L\'Allemagne reste le pays de l\'EC-Karte (Girocard). Beaucoup de commerces n\'acceptent pas Visa/Mastercard. Comprends la différence.', tag: 'Cartes',
      bullets: ['Girocard (EC) : carte de débit locale, acceptée presque partout.', 'Debit Mastercard/Visa : fonctionne à l\'international, mais parfois refusée en boulangerie ou au marché.', 'Carte de crédit (réelle) : pour les voyages et réservations internationales.', 'Beaucoup de commerces préfèrent encore le cash — aie toujours des espèces sur toi.'],
      tip: 'Demande une Girocard supplémentaire à ta banque en ligne si possible, ou ouvre un second compte chez Sparkasse à cet effet.' },
    { num: 15, title: 'Retraits d\'espèces — réseaux de DAB et comment éviter les frais', summary: 'Tous les distributeurs ne sont pas gratuits. Un retrait sur un DAB étranger peut te coûter 5 € par opération.', tag: 'Distributeurs',
      bullets: ['**Cash Group :** Deutsche Bank + Commerzbank + Postbank + HypoVereinsbank — gratuit pour leurs clients.', '**Cash Pool :** inclut Santander + Sparda + Targobank et d\'autres.', '**Sparkassen :** réseau propre, gratuit pour les cartes Sparkasse.', 'DKB et ING : retrait gratuit dans la plupart des DAB de l\'UE.', 'La solution la plus simple : utilise le Cashback au supermarché (Rewe, Lidl) — gratuit.'] },
    { num: 16, title: 'Transférer de et vers le Maroc — les options les moins chères', summary: 'Les frais bancaires sur les virements internationaux sont très élevés. Utilise des services spécialisés pour économiser des dizaines d\'euros.', tag: 'Virements internationaux',
      bullets: ['**Wise (TransferWise) :** taux de change quasi-médian, frais transparents, l\'option la plus rapide.', '**Revolut :** bon pour de petits virements réguliers.', '**Western Union / MoneyGram :** rapide mais très cher (5–8 %).', 'Virement bancaire direct (SWIFT) : 15–40 € de frais + mauvais taux.', 'Méfie-toi des offres alléchantes via « un ami » — souvent du blanchiment.'],
      tip: 'Compare toujours le taux réel sur Google avant un transfert — la plupart des frais sont cachés dans le taux.' },
    { num: 17, title: 'Impôts et compte bancaire — ce que tu dois savoir', summary: 'Le Finanzamt est lié à ton compte. Tout intérêt ou bénéfice est déclaré automatiquement. Comprends les bases.', tag: 'Impôts',
      bullets: ['Freistellungsauftrag : exonération automatique des 1 000 premiers euros d\'intérêts annuels (2 000 pour un couple).', 'Sans lui, la banque retient 25 % (Abgeltungssteuer) sur tout intérêt directement.', 'Steuer-ID requis pour ouvrir un compte depuis 2024.', 'Les banques d\'épargne envoient un Steuerbescheinigung annuel pour ta déclaration.'] },
    { num: 18, title: 'Sécurité en ligne — protéger ton compte', summary: 'La fraude bancaire électronique est répandue. Suis ces règles d\'or pour te protéger.', tag: 'Sécurité',
      bullets: ['N\'entre tes données bancaires que sur le site/l\'appli officiel.', 'Aucune banque ne demande jamais ton mot de passe par téléphone ou e-mail — jamais.', 'Active la 2FA (SMS ou appli TAN) sur toutes les opérations.', 'Vérifie ton relevé chaque semaine — attendre un mois entier est risqué.', 'Les e-mails « banque » qui demandent une mise à jour = phishing.'] },
    { num: 19, title: 'Compte joint (Gemeinschaftskonto) pour les couples', summary: 'Deux types de comptes joints en Allemagne, avec des conséquences juridiques différentes en cas de décès ou divorce.', tag: 'Association',
      bullets: ['**Oder-Konto :** chaque partenaire agit indépendamment (le plus courant).', '**Und-Konto :** nécessite la signature des deux pour chaque opération.', 'Oder-Konto plus pratique au quotidien, mais ouvre la porte à des risques de confiance.', 'En cas de séparation, l\'argent est présumé partagé à 50/50 par défaut.', 'Garde toujours un compte personnel séparé en parallèle.'] },
    { num: 20, title: 'Fermer le compte lors du départ définitif', summary: 'Fermer ton compte depuis le Maroc est quasi impossible. Fais-le avant de partir pour éviter des problèmes plus tard.', tag: 'Clôture',
      bullets: ['Annule tous les Lastschrift et Dauerauftrag avant la clôture.', 'Obtiens un Kontoauszug final et un courrier de clôture (Kontoauflösungsbestätigung).', 'Informe le Finanzamt et l\'Einwohnermeldeamt de ta nouvelle adresse.', 'Certaines banques facturent des frais de clôture (10–30 €).', 'Conserve toute la correspondance au moins 10 ans.'],
      tip: 'Ne ferme le compte qu\'après avoir reçu ton dernier salaire et payé ton dernier loyer. Un mois d\'attente en plus t\'évitera d\'énormes problèmes.' },
  ],
}

const en = {
  metaTitle: 'Banking in Germany — your complete guide',
  metaDesc: '20 articles covering everything you need to open a bank account and manage your money in Germany.',
  eyebrow: 'Money & banking',
  title: 'Banking and accounts in Germany',
  subtitle: 'Everything a Moroccan needs to start their financial life in Germany — from picking a bank to transfers and fees.',
  intro: '20 dense articles based on real experience, covering every stage: before arrival, at arrival, and during your first years in Germany.',
  items: [
    { num: 1, title: 'Why do you need a German bank account?', summary: 'A bank account is not a luxury in Germany — without one you won\'t receive your salary, pay your rent, or complete almost any official process.', tag: 'Basics',
      paragraph: 'Germany is a country of bank transfers (Überweisung) above all. Salaries arrive by transfer, rent is pulled automatically via direct debit (Lastschrift), every bill goes through your account, even scholarships and social security need a German IBAN.',
      bullets: ['Your employer asks for a German IBAN before your first salary.', 'Your landlord needs an account to set up a Lastschrift for rent.', 'Health insurance, taxes, electricity, internet — all run on direct debit.'],
      tip: 'Open an online account before leaving Morocco if possible, or within your first week after arrival at the latest.' },
    { num: 2, title: 'The difference between Girokonto, Sparkonto and Tagesgeld', summary: 'Three account types in Germany, each for a different purpose. Pick wrong and you either lose yield or find your money locked up.', tag: 'Account types',
      bullets: ['**Girokonto:** current account — for receiving salary and paying bills. This is what you need first.', '**Sparkonto:** traditional savings account at low interest, withdrawable any time.', '**Tagesgeldkonto:** daily-access account at higher interest (2–4% currently), fully liquid, ideal for a reserve.', '**Festgeld:** fixed-term deposit at higher interest, but your money is locked.'] },
    { num: 3, title: 'N26 — the first choice for new arrivals', summary: '100% digital bank, opens from your phone in 15 minutes, no Schufa or branch visit needed. Perfect for your first weeks in Germany.', tag: 'Digital bank',
      bullets: ['No monthly fees on the free plan.', 'Does not always require Anmeldung — passport and a German address are often enough.', 'VideoIdent identity check not available in Arabic — but English or German works.', 'Maestro/Debit Mastercard arrives by post in 5–10 days.', 'Great app: instant notifications, auto-categorization, savings goals.'],
      tip: 'Some older German companies reject non-DE IBANs from N26 (they sometimes start with FR or ES). Check before giving it to your employer.' },
    { num: 4, title: 'DKB — free with a real credit card', summary: 'One of the best free banks. Offers a real Visa credit card (not just Debit) with free cash withdrawals.', tag: 'Free bank',
      paragraph: 'DKB is ideal if you travel a lot or shop online in foreign currencies. The credit card enables free withdrawals from any ATM worldwide (after transferring balance to it).',
      bullets: ['Free Girokonto with no minimum-salary requirement.', 'Decent app, though less polished than N26.', 'Requires a completed Anmeldung to sign up.', 'Customer service in German or English.'] },
    { num: 5, title: 'Sparkasse — the local bank closest to you', summary: 'A huge network of regional banks. Every city has its own Sparkasse. Not the cheapest, but socially the most reassuring.', tag: 'Traditional bank',
      paragraph: 'If a lease or employer asks for an account at a "real" bank with a physical branch, Sparkasse is the fit. Warning though: most branches charge monthly fees (€5–10) on the current account.',
      bullets: ['Branches everywhere, even in small villages.', 'Free ATMs within the Sparkasse network.', 'Counter (in-person) transactions for those who need face-to-face service.', 'Requires Anmeldung and an in-person appointment to open.'] },
    { num: 6, title: 'Commerzbank and Deutsche Bank — the big banks', summary: 'Suitable if you need loans or advanced investment services. Both offer free accounts for students and for those transferring a large enough salary.', tag: 'Big banks',
      bullets: ['Commerzbank: free account with salary transfer ≥ €700/month.', 'Deutsche Bank: good for international relationships and investment.', 'Some branches have staff who speak English or French.', 'Fees are relatively high if you don\'t meet the waiver conditions.'] },
    { num: 7, title: 'ING and Comdirect — excellent digital alternatives', summary: 'Two digital banks with virtual branches, backed by big groups (ING DiBa and Commerzbank).', tag: 'Digital banks',
      bullets: ['ING: free Girokonto with monthly income ≥ €700, free withdrawals from any ATM in the EU.', 'Comdirect: free for the first 3 years, then subject to monthly income.', 'Both support Apple Pay and Google Pay.', 'Support primarily in German.'] },
    { num: 8, title: 'Documents required to open an account', summary: 'Precise checklist of what every German bank asks for. Gather them before applying to save time.', tag: 'Documents',
      bullets: ['Passport or residence permit (Aufenthaltstitel).', 'Anmeldebestätigung (municipal registration confirmation).', 'Full residential address in Germany.', 'Steuer-ID (tax number) if available.', 'German phone number for verification.', 'Some banks: proof of income or a work/study contract.'],
      tip: 'Digital banks (N26, Vivid) may accept you without Anmeldung at first, but will ask for it later for full verification.' },
    { num: 9, title: 'VideoIdent and PostIdent — how your identity gets verified', summary: 'You cannot open an account without identity verification. These are the two most common options.', tag: 'Identity check',
      bullets: ['**VideoIdent:** 5–10 min video call with an agent, available from anywhere. The fastest.', '**PostIdent:** go to the nearest post office (Deutsche Post) with a printed form and your passport. Free.', 'Both are free if requested by the bank.', 'Pick VideoIdent if you\'re in Morocco or recently arrived.'] },
    { num: 10, title: 'Schufa — the German credit record', summary: 'A record that defines your financial trust. It affects renting an apartment, opening some accounts, and getting loans.', tag: 'Credit',
      paragraph: 'Schufa is computed automatically from your financial activity in Germany. On arrival, your record is "empty" — not bad in itself, but some companies view it as risk. It improves over time as you pay your bills on time.',
      bullets: ['Your first Schufa Auskunft (free copy) is your right each year via meineschufa.de.', 'Don\'t take unnecessary loans to build your record — regular Girokonto use is enough.', 'On-time rent and bill payments raise your score.'],
      tip: 'Some landlords ask for a Schufa-Bonitätscheck — get the short rental version for about €30.' },
    { num: 11, title: 'IBAN and SEPA — the language of European transfers', summary: 'IBAN is your international account number. SEPA is the European transfer network that makes internal transfers free and fast.', tag: 'Transfers',
      bullets: ['A German IBAN starts with DE and is 22 characters long.', 'SEPA transfer within the EU: free, arrives in 1–2 business days.', 'SEPA Instant: instant transfer (10 seconds), some banks charge a small fee.', 'BIC is only needed in certain international cases; IBAN alone usually suffices.'] },
    { num: 12, title: 'Direct debit (Lastschrift) — how it works and when to reject it', summary: 'Lastschrift lets a company pull money directly from your account after your authorization. A great tool — but handle with care.', tag: 'Payments',
      bullets: ['You give the company a Mandat (authorization) once, then it pulls automatically (rent, internet, insurance…).', 'You have the right to reverse any debit within 8 weeks, with or without reason.', 'Review your statement monthly — bogus charges happen.', 'To cancel a Mandat: email the company and notify the bank.'] },
    { num: 13, title: 'Standing orders (Dauerauftrag) — to pay rent automatically', summary: 'The opposite of Lastschrift — you are the one ordering a fixed-amount transfer on a set date each month. Ideal for rent.', tag: 'Payments',
      bullets: ['Set up in a minute from the bank app.', 'Editable or cancellable at any time.', 'Best way to pay rent to the landlord.', 'Some banks charge for setting up a Dauerauftrag on paper, but it\'s free online.'] },
    { num: 14, title: 'EC-Karte (Girocard) and credit cards in Germany', summary: 'Germany is still an EC-Karte (Girocard) country. Many shops don\'t accept Visa/Mastercard. Understand the difference.', tag: 'Cards',
      bullets: ['Girocard (EC): local debit card, accepted in nearly every shop.', 'Debit Mastercard/Visa: works internationally but may be refused in some bakeries and markets.', 'Credit Card (real credit card): for travel and international bookings.', 'Many shops still prefer cash — always carry some.'],
      tip: 'Ask your digital bank for an additional Girocard if possible, or open a second account at Sparkasse for this purpose.' },
    { num: 15, title: 'Withdrawing cash — ATM networks and how to avoid fees', summary: 'Not every ATM is free. Using a foreign ATM can cost you €5 per withdrawal.', tag: 'ATMs',
      bullets: ['**Cash Group:** Deutsche Bank + Commerzbank + Postbank + HypoVereinsbank — free for their customers.', '**Cash Pool:** includes Santander + Sparda + Targobank and others.', '**Sparkassen:** their own network, free for Sparkasse cards.', 'DKB and ING: free withdrawals at most ATMs inside the EU.', 'Simplest solution: use Cashback at the supermarket (Rewe, Lidl) — free.'] },
    { num: 16, title: 'Transferring to and from Morocco — the cheapest routes', summary: 'Bank fees on international transfers are very high. Use specialized services to save dozens of euros.', tag: 'International transfers',
      bullets: ['**Wise (TransferWise):** near-mid-market exchange rate, transparent fees, fastest option.', '**Revolut:** good for small recurring transfers.', '**Western Union / MoneyGram:** fast but very expensive (5–8%).', 'Direct bank transfer (SWIFT): €15–40 fee + bad exchange rate.', 'Beware of tempting offers via "a friend" — often money laundering.'],
      tip: 'Always compare the real rate on Google before any transfer — most fees are hidden in the rate.' },
    { num: 17, title: 'Taxes and your bank account — what you must know', summary: 'The Finanzamt is linked to your account. Any interest or profit is reported automatically. Understand the basics.', tag: 'Taxes',
      bullets: ['Freistellungsauftrag: automatic exemption on the first €1,000 of annual interest (€2,000 for couples).', 'Without it, the bank withholds 25% (Abgeltungssteuer) on any interest directly.', 'Steuer-ID (tax number) required to open any account since 2024.', 'Savings banks send a yearly Steuerbescheinigung for your tax return.'] },
    { num: 18, title: 'Online safety — protecting your account', summary: 'Online banking fraud is widespread. Follow these golden rules to protect yourself.', tag: 'Security',
      bullets: ['Only enter your banking details on the official website/app.', 'No bank ever asks for your password by phone or email — never.', 'Enable 2FA (SMS or TAN app) on every operation.', 'Review your statement weekly — going a whole month is risky.', '"Bank" emails asking to update your details = phishing attempt.'] },
    { num: 19, title: 'Joint account (Gemeinschaftskonto) for couples', summary: 'Two types of joint accounts in Germany, each with different legal consequences in case of death or divorce.', tag: 'Partnership',
      bullets: ['**Oder-Konto:** each partner acts independently (the most common).', '**Und-Konto:** requires both signatures for every operation.', 'Oder-Konto is easier day to day, but opens the door to trust risks.', 'In a separation, the money is presumed 50/50 owned by default.', 'Always keep a separate personal account alongside it.'] },
    { num: 20, title: 'Closing the account when leaving for good', summary: 'Closing your account from Morocco is nearly impossible. Handle it before leaving to avoid problems down the line.', tag: 'Closing',
      bullets: ['Cancel every Lastschrift and Dauerauftrag before closing.', 'Get a final Kontoauszug and a closing letter (Kontoauflösungsbestätigung).', 'Notify the Finanzamt and Einwohnermeldeamt of your new address.', 'Some banks charge a closing fee (€10–30).', 'Keep all correspondence for at least 10 years.'],
      tip: 'Don\'t close the account until after your last salary is received and your last rent is paid. Waiting an extra month saves huge problems.' },
  ],
}

const de = {
  metaTitle: 'Banken und Konten in Deutschland — dein umfassender Leitfaden',
  metaDesc: '20 Artikel, die alles erklären, was du brauchst, um ein Bankkonto zu eröffnen und dein Geld in Deutschland zu verwalten.',
  eyebrow: 'Geld & Banken',
  title: 'Banken und Konten in Deutschland',
  subtitle: 'Alles, was ein Marokkaner braucht, um sein Finanzleben in Deutschland zu starten — von der Bankwahl bis zu Überweisungen und Gebühren.',
  intro: '20 dichte, auf echten Erfahrungen basierende Artikel, die jede Phase abdecken: vor der Ankunft, bei der Ankunft und in den ersten Jahren in Deutschland.',
  items: [
    { num: 1, title: 'Warum brauchst du ein deutsches Bankkonto?', summary: 'Ein Bankkonto ist in Deutschland kein Luxus — ohne es bekommst du kein Gehalt, zahlst keine Miete und kannst fast keine offiziellen Angelegenheiten erledigen.', tag: 'Grundlagen',
      paragraph: 'Deutschland ist vor allem ein Land der Überweisungen. Das Gehalt kommt per Überweisung, die Miete wird automatisch per Lastschrift abgebucht, alle Rechnungen laufen über das Konto, sogar Stipendien und Sozialleistungen brauchen eine deutsche IBAN.',
      bullets: ['Der Arbeitgeber verlangt eine deutsche IBAN vor dem ersten Gehalt.', 'Der Vermieter braucht ein Konto, um eine Lastschrift für die Miete einzurichten.', 'Krankenversicherung, Steuern, Strom, Internet — alles läuft per Lastschrift.'],
      tip: 'Eröffne wenn möglich ein Online-Konto, bevor du Marokko verlässt, oder spätestens in der ersten Woche nach der Ankunft.' },
    { num: 2, title: 'Der Unterschied zwischen Girokonto, Sparkonto und Tagesgeld', summary: 'Drei Kontoarten in Deutschland, jede für einen anderen Zweck. Die falsche Wahl kostet dich Zinsen oder blockiert dein Geld.', tag: 'Kontoarten',
      bullets: ['**Girokonto:** laufendes Konto — für Gehaltseingang und Rechnungen. Das brauchst du zuerst.', '**Sparkonto:** klassisches Sparkonto mit niedrigem Zins, jederzeit verfügbar.', '**Tagesgeldkonto:** Tageszinskonto mit höherem Zins (aktuell 2–4 %), voll liquide, ideal als Rücklage.', '**Festgeld:** Festgeldanlage mit höherem Zins, aber Geld für feste Laufzeit gebunden.'] },
    { num: 3, title: 'N26 — die erste Wahl für Neuankömmlinge', summary: '100 % digitale Bank, in 15 Minuten vom Handy aus eröffnet, ohne Schufa und ohne Filialbesuch. Perfekt für deine ersten Wochen in Deutschland.', tag: 'Digitalbank',
      bullets: ['Keine monatlichen Gebühren im kostenlosen Plan.', 'Braucht in manchen Fällen keine Anmeldung — Reisepass und deutsche Adresse reichen oft.', 'Identitätsprüfung per VideoIdent auf Arabisch nicht verfügbar — auf Englisch oder Deutsch aber schon.', 'Maestro/Debit-Mastercard kommt per Post in 5–10 Tagen.', 'Top-App: Echtzeit-Benachrichtigungen, automatische Kategorisierung, Sparziele.'],
      tip: 'Manche alten deutschen Firmen akzeptieren keine Nicht-DE-IBANs von N26 (sie beginnen manchmal mit FR oder ES). Prüfe es, bevor du sie dem Arbeitgeber gibst.' },
    { num: 4, title: 'DKB — kostenlos mit echter Kreditkarte', summary: 'Eine der besten kostenlosen Banken. Bietet eine echte Visa-Kreditkarte (nicht nur Debit) mit kostenlosen Bargeldabhebungen.', tag: 'Kostenlose Bank',
      paragraph: 'DKB eignet sich gut für Vielreisende oder Online-Shopper in Fremdwährung. Die Kreditkarte erlaubt kostenlose Abhebungen an jedem Geldautomaten weltweit (nach Guthaben-Übertragung darauf).',
      bullets: ['Girokonto kostenlos ohne Mindestgehalt.', 'App ist solide, aber weniger modern als N26.', 'Vollständige Anmeldung erforderlich für die Registrierung.', 'Kundenservice auf Deutsch oder Englisch.'] },
    { num: 5, title: 'Sparkasse — die lokale Bank in deiner Nähe', summary: 'Riesiges Netzwerk regionaler Banken. Jede Stadt hat ihre eigene Sparkasse. Nicht die billigste, aber sozial die vertrauenswürdigste.', tag: 'Klassische Bank',
      paragraph: 'Wenn ein Mietvertrag oder Arbeitgeber ein Konto bei einer „echten" Bank mit Filiale verlangt, ist die Sparkasse die passende Wahl. Achtung: Die meisten Filialen erheben monatliche Gebühren (5–10 €) auf dem Girokonto.',
      bullets: ['Filialen auch in kleinen Dörfern.', 'Kostenlose Geldautomaten im Sparkassen-Netzwerk.', 'Schaltergeschäfte (persönlich) für alle, die persönliche Betreuung brauchen.', 'Zur Eröffnung: Anmeldung und persönliches Gespräch nötig.'] },
    { num: 6, title: 'Commerzbank und Deutsche Bank — die Großbanken', summary: 'Passend für Kredite oder anspruchsvolle Anlageprodukte. Beide bieten kostenlose Konten für Studierende und für ausreichende Gehaltseingänge.', tag: 'Großbanken',
      bullets: ['Commerzbank: kostenloses Konto bei Gehaltseingang ≥ 700 €/Monat.', 'Deutsche Bank: gut für internationale Beziehungen und Geldanlage.', 'Einige Filialen haben englisch- oder französischsprachige Mitarbeiter.', 'Gebühren vergleichsweise hoch, wenn Befreiungsbedingungen nicht erfüllt sind.'] },
    { num: 7, title: 'ING und Comdirect — ausgezeichnete Online-Alternativen', summary: 'Zwei Online-Banken mit virtuellen Filialen, unterstützt von Großkonzernen (ING DiBa und Commerzbank).', tag: 'Online-Banken',
      bullets: ['ING: Girokonto kostenlos ab monatlichem Geldeingang ≥ 700 €, kostenlose Abhebungen EU-weit.', 'Comdirect: kostenlos in den ersten 3 Jahren, danach abhängig vom monatlichen Eingang.', 'Beide unterstützen Apple Pay und Google Pay.', 'Support überwiegend auf Deutsch.'] },
    { num: 8, title: 'Erforderliche Unterlagen zur Kontoeröffnung', summary: 'Präzise Checkliste, was jede deutsche Bank verlangt. Stelle sie vor dem Antrag zusammen, um Zeit zu sparen.', tag: 'Unterlagen',
      bullets: ['Reisepass oder Aufenthaltstitel.', 'Anmeldebestätigung (Meldebehörde).', 'Vollständige Wohnadresse in Deutschland.', 'Steuer-ID, falls vorhanden.', 'Deutsche Telefonnummer zur Bestätigung.', 'Manche Banken: Einkommensnachweis oder Arbeits-/Studienvertrag.'],
      tip: 'Digitalbanken (N26, Vivid) akzeptieren dich anfangs eventuell ohne Anmeldung, verlangen sie aber später zur vollständigen Verifizierung.' },
    { num: 9, title: 'VideoIdent und PostIdent — wie deine Identität geprüft wird', summary: 'Ohne Identitätsprüfung lässt sich kein Konto eröffnen. Das sind die beiden gängigsten Optionen.', tag: 'Identitätsprüfung',
      bullets: ['**VideoIdent:** Videoanruf mit einem Mitarbeiter, 5–10 Min., von überall möglich. Am schnellsten.', '**PostIdent:** zur nächsten Postfiliale (Deutsche Post) mit ausgedrucktem Formular und Reisepass. Kostenlos.', 'Beide sind kostenlos, wenn von der Bank angefordert.', 'Wähle VideoIdent, wenn du in Marokko bist oder gerade angekommen bist.'] },
    { num: 10, title: 'Schufa — die deutsche Kreditakte', summary: 'Eine Akte, die deine finanzielle Vertrauenswürdigkeit definiert. Sie beeinflusst Wohnungsmiete, einige Kontoeröffnungen und Kreditvergaben.', tag: 'Bonität',
      paragraph: 'Die Schufa wird automatisch aus deiner Finanzaktivität in Deutschland berechnet. Bei Ankunft ist deine Akte „leer" — an sich nicht schlecht, aber manche Firmen werten das als Risiko. Sie verbessert sich mit der Zeit und pünktlicher Zahlung.',
      bullets: ['Eine erste kostenlose Schufa-Auskunft steht dir jährlich zu, unter meineschufa.de.', 'Nimm keine unnötigen Kredite auf, nur um deine Akte aufzubauen — regelmäßige Girokonto-Nutzung reicht.', 'Pünktliche Miet- und Rechnungszahlungen erhöhen deinen Score.'],
      tip: 'Manche Vermieter verlangen einen Schufa-Bonitätscheck — die kurze Mietversion kostet rund 30 €.' },
    { num: 11, title: 'IBAN und SEPA — die Sprache europäischer Überweisungen', summary: 'IBAN ist deine internationale Kontonummer. SEPA ist das europäische Überweisungsnetz, das Inlandsüberweisungen kostenlos und schnell macht.', tag: 'Überweisungen',
      bullets: ['Die deutsche IBAN beginnt mit DE und hat 22 Zeichen.', 'SEPA-Überweisung innerhalb der EU: kostenlos, dauert 1–2 Werktage.', 'SEPA Instant: Echtzeitüberweisung (10 Sekunden), manche Banken erheben eine kleine Gebühr.', 'BIC wird nur in bestimmten internationalen Fällen gebraucht; meist reicht die IBAN.'] },
    { num: 12, title: 'Lastschrift — wie sie funktioniert und wann du sie ablehnst', summary: 'Die Lastschrift erlaubt Unternehmen, nach deiner Genehmigung direkt Geld vom Konto abzubuchen. Starkes Werkzeug — aber mit Vorsicht zu nutzen.', tag: 'Zahlungen',
      bullets: ['Du erteilst dem Unternehmen einmal ein Mandat, danach wird automatisch abgebucht (Miete, Internet, Versicherung …).', 'Du darfst jede Abbuchung innerhalb von 8 Wochen zurückbuchen, mit oder ohne Grund.', 'Prüfe deinen Kontoauszug monatlich — unberechtigte Abbuchungen kommen vor.', 'Mandat widerrufen: E-Mail ans Unternehmen + Bank informieren.'] },
    { num: 13, title: 'Daueraufträge — um die Miete automatisch zu zahlen', summary: 'Das Gegenteil der Lastschrift — du erteilst den Auftrag, einen festen Betrag zu einem festen Termin monatlich zu überweisen. Ideal für die Miete.', tag: 'Zahlungen',
      bullets: ['In der Banking-App in einer Minute eingerichtet.', 'Jederzeit änder- oder stornierbar.', 'Beste Methode, um die Miete an den Vermieter zu zahlen.', 'Manche Banken berechnen die Einrichtung auf Papier, online ist sie kostenlos.'] },
    { num: 14, title: 'EC-Karte (Girocard) und Kreditkarten in Deutschland', summary: 'Deutschland ist noch ein EC-Karte-Land (Girocard). Viele Läden akzeptieren kein Visa/Mastercard. Verstehe den Unterschied.', tag: 'Karten',
      bullets: ['Girocard (EC): lokale Debitkarte, fast überall akzeptiert.', 'Debit-Mastercard/Visa: international nutzbar, aber in manchen Bäckereien und Märkten abgelehnt.', 'Kreditkarte (echte Kreditkarte): für Reisen und internationale Buchungen.', 'Viele Läden bevorzugen weiterhin Bargeld — habe immer welches dabei.'],
      tip: 'Frage bei deiner Digitalbank nach einer zusätzlichen Girocard, oder eröffne zusätzlich ein Konto bei der Sparkasse.' },
    { num: 15, title: 'Bargeld abheben — Automatennetze und wie du Gebühren vermeidest', summary: 'Nicht jeder Automat ist kostenlos. Eine Abhebung an einem fremden Automaten kann 5 € pro Vorgang kosten.', tag: 'Geldautomaten',
      bullets: ['**Cash Group:** Deutsche Bank + Commerzbank + Postbank + HypoVereinsbank — kostenlos für deren Kunden.', '**Cash Pool:** umfasst Santander + Sparda + Targobank und andere.', '**Sparkassen:** eigenes Netz, kostenlos für Sparkassenkarten.', 'DKB und ING: kostenlose Abhebung an den meisten Automaten EU-weit.', 'Einfachste Lösung: Cashback im Supermarkt (Rewe, Lidl) — kostenlos.'] },
    { num: 16, title: 'Überweisungen nach/aus Marokko — die günstigsten Wege', summary: 'Bankgebühren bei internationalen Überweisungen sind sehr hoch. Nutze spezialisierte Dienste und spare dutzende Euros.', tag: 'Auslandsüberweisungen',
      bullets: ['**Wise (TransferWise):** Wechselkurs nahe Mittelkurs, transparente Gebühren, schnellste Option.', '**Revolut:** gut für kleine, wiederkehrende Überweisungen.', '**Western Union / MoneyGram:** schnell, aber sehr teuer (5–8 %).', 'Direkte Banküberweisung (SWIFT): 15–40 € Gebühr + schlechter Kurs.', 'Vorsicht bei verlockenden Angeboten über „einen Freund" — oft Geldwäsche.'],
      tip: 'Vergleiche den realen Kurs immer auf Google vor einer Überweisung — die meisten Gebühren sind im Kurs versteckt.' },
    { num: 17, title: 'Steuern und das Bankkonto — was du wissen musst', summary: 'Das Finanzamt ist mit deinem Konto verbunden. Jeder Zins oder Gewinn wird automatisch gemeldet. Lerne die Grundlagen.', tag: 'Steuern',
      bullets: ['Freistellungsauftrag: automatische Befreiung der ersten 1.000 € Zinsen pro Jahr (2.000 € für Ehepaare).', 'Ohne ihn zieht die Bank 25 % (Abgeltungssteuer) von jedem Zins direkt ab.', 'Steuer-ID seit 2024 Pflicht für jede Kontoeröffnung.', 'Sparkassen schicken jährlich eine Steuerbescheinigung für deine Steuererklärung.'] },
    { num: 18, title: 'Online-Sicherheit — dein Konto schützen', summary: 'Online-Banking-Betrug ist verbreitet. Halte dich an diese goldenen Regeln, um dich zu schützen.', tag: 'Sicherheit',
      bullets: ['Gib deine Bankdaten nur auf der offiziellen Website/App ein.', 'Keine Bank fragt dein Passwort am Telefon oder per E-Mail ab — niemals.', 'Aktiviere 2FA (SMS oder TAN-App) für jede Aktion.', 'Prüfe deinen Kontoauszug wöchentlich — einen ganzen Monat zu warten ist riskant.', '„Bank"-E-Mails, die Datenaktualisierungen verlangen = Phishing.'] },
    { num: 19, title: 'Gemeinschaftskonto für Paare', summary: 'Zwei Arten von Gemeinschaftskonten in Deutschland, mit unterschiedlichen rechtlichen Folgen bei Tod oder Scheidung.', tag: 'Partnerschaft',
      bullets: ['**Oder-Konto:** jeder Partner handelt unabhängig (am verbreitetsten).', '**Und-Konto:** erfordert beide Unterschriften für jede Aktion.', 'Oder-Konto ist alltagstauglicher, öffnet aber Tür für Vertrauensrisiken.', 'Bei Trennung gilt das Geld standardmäßig als je zur Hälfte geteilt.', 'Behalte immer zusätzlich ein eigenes Konto.'] },
    { num: 20, title: 'Konto schließen beim endgültigen Umzug', summary: 'Dein Konto aus Marokko zu schließen ist fast unmöglich. Regle alles vor der Ausreise, um spätere Probleme zu vermeiden.', tag: 'Auflösung',
      bullets: ['Kündige alle Lastschriften und Daueraufträge vor der Auflösung.', 'Hol dir einen finalen Kontoauszug und ein Auflösungsschreiben (Kontoauflösungsbestätigung).', 'Informiere Finanzamt und Einwohnermeldeamt über deine neue Adresse.', 'Manche Banken erheben eine Auflösungsgebühr (10–30 €).', 'Bewahre alle Korrespondenz mindestens 10 Jahre auf.'],
      tip: 'Schließe das Konto erst, nachdem dein letztes Gehalt eingegangen und deine letzte Miete bezahlt ist. Ein Monat extra erspart dir enorme Probleme.' },
  ],
}

const byLoc = { ar, fr, en, de }

// Ensure `common.tipLabel` key exists
const tipLabel = { ar: 'نصيحة', fr: 'Astuce', en: 'Tip', de: 'Tipp' }

for (const loc of ['ar', 'fr', 'en', 'de']) {
  const p = path.join(__dirname, '..', 'messages', `${loc}.json`)
  const j = JSON.parse(fs.readFileSync(p, 'utf8'))
  j.static = j.static || {}
  j.static.banking = byLoc[loc]
  j.common = j.common || {}
  j.common.tipLabel = tipLabel[loc]
  fs.writeFileSync(p, JSON.stringify(j, null, 2) + '\n', 'utf8')
  console.log(`✓ ${loc}.json`)
}
