const fs = require('fs')
const path = require('path')

const ar = {
  metaTitle: 'شرائح SIM والإنترنت في ألمانيا — دليل المغاربة',
  metaDesc: '20 مقالاً عن شرائح الاتصال، الإنترنت المنزلي، العروض، وتفادي النصب في ألمانيا.',
  eyebrow: 'الاتصالات والإنترنت',
  title: 'شرائح SIM والإنترنت في ألمانيا',
  subtitle: 'رقم ألماني ليس خياراً بل ضرورة. هنا كيف تختار الشركة المناسبة، والعرض المناسب، والحلول لكل وضع.',
  intro: '20 مقالاً يجيب عن كل أسئلتك: Prepaid أم Vertrag؟ Telekom أم O2؟ eSIM أم بطاقة فعلية؟ وكيف تتجنّب فخاخ العقود طويلة الأمد.',
  items: [
    { num: 1, title: 'لماذا تحتاج رقماً ألمانياً منذ اليوم الأول؟', summary: 'لن تستطيع التسجيل البنكي، التسجيل البلدي، البحث عن شقة، أو حتى تسلّم طرد بدون رقم ألماني فعّال.', tag: 'أساسيات',
      bullets: ['البنوك تتحقق من هويتك برسالة SMS إلى رقم ألماني فقط.', 'طلبات الشقق تُرفض دون رقم ألماني يُتصل به.', 'Ausländerbehörde يراسلك عبر الهاتف لبعض المواعيد.', 'Anmeldung في بعض المدن تتطلب رقم اتصال محلي.'],
      tip: 'احتفظ برقمك المغربي مفعّلاً عبر الأرقام الافتراضية (WhatsApp/Google Voice) لمدة شهرين على الأقل بعد الوصول.' },
    { num: 2, title: 'Prepaid مقابل Vertrag — الاختيار الأول', summary: 'قرار يحدّد مرونتك ومصاريفك طوال سنتين. اختر بناء على استقرارك، لا على السعر الظاهري.', tag: 'مقارنة',
      bullets: ['**Prepaid:** دفع مسبق، لا عقد، لا Schufa، يُفعَّل فوراً.', '**Vertrag:** عقد 24 شهراً، أسعار أقل، يتطلّب Schufa + حساب بنكي.', 'كطالب جديد: ابدأ Prepaid ثم انقُل الرقم لاحقاً إلى Vertrag.', 'Vertrag مع iPhone/هاتف جديد: غالباً أغلى من شراء الهاتف منفصلاً.'] },
    { num: 3, title: 'الشبكات الثلاث الكبرى في ألمانيا', summary: 'ثلاث شبكات فيزيائية، وعشرات العلامات التي تستخدمها. الشبكة الفعلية مهمّة أكثر من الاسم.', tag: 'شبكات',
      bullets: ['**Deutsche Telekom (D1):** التغطية الأفضل خصوصاً في الريف.', '**Vodafone (D2):** الأسرع في المدن الكبرى، جيدة في القرى.', '**O2 (Telefónica):** الأرخص، تغطية جيدة في المدن، ضعيفة في الريف.', 'أي شركة صغيرة (Aldi Talk, Lidl Connect, Congstar...) تستخدم إحدى هذه الشبكات.'],
      tip: 'قبل اختيار الشركة، افحص التغطية في منطقتك عبر breitbandmessung.de أو netzabdeckung.o2online.de.' },
    { num: 4, title: 'Telekom (Magenta) — الأغلى والأفضل تغطية', summary: 'إذا كنت في قرية أو تسافر كثيراً بالقطار، Telekom هي الخيار الأكيد. السعر عالٍ لكن يستحق.', tag: 'Telekom',
      bullets: ['MagentaMobil Start: 30€/شهر، 20GB، اتصالات مفتوحة.', 'خيارات عائلية (MagentaEins) ممتازة إن كان لديك إنترنت منزلي منها.', 'الشبكة الوحيدة المستقرة في القطارات السريعة (ICE).', '5G متوفّر في أغلب المدن الكبرى.'] },
    { num: 5, title: 'Vodafone — منافس متوازن', summary: 'شركة كبيرة بشبكة قوية وعروض تنافسية. مثالية لمن يعيش في مدن كبرى أو متوسطة.', tag: 'Vodafone',
      bullets: ['GigaMobil S: ~25€/شهر، 15GB.', 'عروض Unlimited متاحة بسعر معقول.', '5G منتشر جيداً في Hamburg, München, Köln, Berlin.', 'تغطية Unterwegs جيدة في الطرق السيارة.'] },
    { num: 6, title: 'O2 — الأرخص في المدن', summary: 'إن كنت في مدينة كبرى وتستهلك كثيراً، O2 أفضل قيمة. لكن تجنّبها في الريف.', tag: 'O2',
      bullets: ['o2 Mobile M: ~20€/شهر، 20GB.', 'عروض Free Unlimited حقيقية (30–40€).', 'تغطية ضعيفة في القرى وبعض القطارات الإقليمية.', 'خدمة عملاء متوسطة — بالألمانية فقط غالباً.'] },
    { num: 7, title: 'Aldi Talk — أشهر خيار Prepaid', summary: 'يستخدمه مئات الآلاف. سعر منخفض، تفعيل سهل، شبكة O2 فعلياً.', tag: 'Aldi Talk',
      bullets: ['Paket S: 7.99€/أسبوعين، 5GB + اتصالات مفتوحة.', 'Paket M: 12.99€/4 أسابيع، 12GB + مكالمات مفتوحة.', 'تفعيل عبر PostIdent أو VideoIdent في بضع دقائق.', 'متوفّر في كل فرع Aldi Süd و Aldi Nord.'],
      tip: 'تحتاج NFC لهاتفك لاستعمال تفعيل Online. إن لم يتوفّر، اذهب إلى فرع Aldi مع جوازك.' },
    { num: 8, title: 'Lidl Connect — بديل Aldi Talk', summary: 'يعمل على شبكة Vodafone، لذا يغطّي مناطق ريفية أفضل من Aldi Talk.', tag: 'Lidl',
      bullets: ['Smart S: 7.99€/4 أسابيع، 5GB.', 'Smart L: 17.99€/4 أسابيع، 25GB.', 'يُباع في فروع Lidl والإنترنت.', 'تفعيل عبر VideoIdent أو في الفرع.'] },
    { num: 9, title: 'Congstar — Telekom بأسعار أقل', summary: 'علامة Telekom الرخيصة. تحصل على نفس الشبكة الممتازة بثمن أقل بـ 30–40%.', tag: 'Congstar',
      bullets: ['Allnet Flat M: 17€/شهر، 10GB.', 'عقد 24 شهراً أو شهرياً (أغلى قليلاً).', 'جودة مكالمات متطابقة مع Telekom.', 'خدمة عملاء ألمانية جيدة.'] },
    { num: 10, title: 'Blau — Vodafone بسعر مخفّض', summary: 'علامة Vodafone الرخيصة. مثالية لمن يريد شبكة قوية دون سعر Vodafone الرسمي.', tag: 'Blau',
      bullets: ['Blau Allnet L: 15€/4 أسابيع، 15GB.', 'خيار شهري بدون عقد.', 'Roaming مجاني كامل الاتحاد الأوروبي.', 'تفعيل سريع عبر التطبيق.'] },
    { num: 11, title: 'التحقق من الهوية (PostIdent / VideoIdent)', summary: 'لا يمكنك شراء SIM دون إثبات هوية. ألمانيا تأخذ ذلك بجدية منذ 2017.', tag: 'تحقق',
      bullets: ['VideoIdent: مكالمة فيديو 5 دقائق، جواز + إضاءة جيّدة، متاح لأغلب الشركات.', 'PostIdent: زيارة مكتب بريد مع نموذج مطبوع، مجاني للشركة.', 'في المحلات: اذهب بجوازك، ينتهي التفعيل في 10 دقائق.', 'الرقم المغربي غير مقبول للتحقق — تحتاج إيميل.'] },
    { num: 12, title: 'نقل الرقم بين الشركات (Rufnummermitnahme)', summary: 'يمكنك الاحتفاظ برقمك عند تبديل الشركة. العملية مجانية تقريباً.', tag: 'نقل رقم',
      bullets: ['أعطِ الشركة الجديدة: رقمك القديم + Kundennummer + Kündigungstermin.', 'الشركة الجديدة تتكفّل بكل شيء تقريباً.', 'مدة النقل: 1–7 أيام.', 'منذ 2020، الرسم 6.82€ كحد أقصى قانوناً.'],
      tip: 'انقل الرقم قبل نهاية العقد بـ 3 أشهر لتضمن عدم انقطاعه وخسارته.' },
    { num: 13, title: 'eSIM — البديل الرقمي الحديث', summary: 'eSIM متوفّرة في ألمانيا من أغلب الشركات. مثالية للهواتف الحديثة والسفر.', tag: 'eSIM',
      bullets: ['Telekom, Vodafone, O2, Congstar, 1&1 تدعم eSIM.', 'Aldi Talk بدأت تدعمها 2024.', 'هواتف iPhone XS+ و Samsung Galaxy S20+ تدعم eSIM.', 'يمكن تفعيل خطين (SIM فعلية + eSIM) معاً.'] },
    { num: 14, title: 'Roaming في الاتحاد الأوروبي', summary: 'منذ 2017، الـ Roaming داخل الاتحاد مجاني مع أي SIM ألمانية. لكن هناك قيود.', tag: 'Roaming',
      bullets: ['Fair Use: إذا قضيت وقتاً طويلاً خارج ألمانيا، الشركة قد تحدّد الاستهلاك.', 'الاستعمال اليومي في فرنسا/إسبانيا/إيطاليا كما في ألمانيا دون رسم.', 'المغرب = خارج الاتحاد = Roaming مدفوع (10–20€/ميجا).', 'للسفر للمغرب: اشترِ eSIM سفر مؤقتة (Holafly, Airalo).'] },
    { num: 15, title: 'الإنترنت المنزلي (DSL, Kabel, Glasfaser)', summary: 'ثلاث تقنيات، وأسعار متباينة، وعقود تربطك 24 شهراً. تأنَّ قبل التوقيع.', tag: 'إنترنت منزلي',
      bullets: ['**DSL:** الأكثر انتشاراً، سرعات 50–250Mbit.', '**Kabel:** Vodafone + Pyur، سرعات 100–1000Mbit.', '**Glasfaser:** الألياف، الأسرع (1GB+)، لكن غير متوفّر في كل الأحياء.', 'تحقّق من العنوان على verfügbarkeit-check.de قبل التوقيع.', 'وقت التفعيل: 2–8 أسابيع — لا تتأخر في الطلب.'] },
    { num: 16, title: 'حلول الإنترنت المؤقّتة (LTE Router)', summary: 'إن كنت تنتظر توصيل DSL، راوتر LTE مع SIM يُشغّلك فوراً. مفيد للسكن الطلابي.', tag: 'LTE',
      bullets: ['راوتر محمول (MiFi) + SIM بـ 50GB شهرياً: ~30€/شهر.', 'Congstar Homespot و Telekom SpeedStick حلول معروفة.', 'مناسب للإقامات القصيرة (شهر Airbnb، فندق طويل).', 'لا يصلح كحل دائم — أغلى من DSL على المدى البعيد.'] },
    { num: 17, title: 'كيفية إلغاء العقد (Kündigung)', summary: 'كل عقد في ألمانيا ينتظر Kündigung كتابي. دون رسالة رسمية، يتجدّد تلقائياً.', tag: 'إلغاء',
      bullets: ['المدة القانونية للإلغاء: 3 أشهر قبل نهاية العقد (الحد الأقصى).', 'أرسل Kündigung كتابياً عبر Einschreiben (بريد مسجّل) أو عبر موقع الشركة.', 'اطلب تأكيد كتابي (Kündigungsbestätigung).', 'منذ 2022، يجب على الشركات توفير زرّ إلغاء مباشر على الموقع.'],
      tip: 'موقع kuendigung.org يولّد رسالة رسمية قانونية ويرسلها نيابة عنك — موثوق جداً.' },
    { num: 18, title: 'عروض الطلاب والشباب', summary: 'شركات كثيرة تقدّم خصومات لحاملي بطاقة طالب أو لمن أعمارهم تحت 28.', tag: 'خصومات',
      bullets: ['Telekom MagentaMobil Young: خصم 30% حتى سنّ 28.', 'Vodafone Young: 10GB بـ 15€ بدل 25€.', 'O2 My Young: شروط مماثلة.', 'اطلب الخصم عبر موقع الشركة مع رفع Studierendenausweis.', 'الخصم يبقى حتى يوم ميلادك الـ 28.'] },
    { num: 19, title: 'شرائح بدون عنوان ألماني', summary: 'ما تفعله لو وصلت ألمانيا ولا عنوان ثابت بعد. خيارات محدودة لكنها ممكنة.', tag: 'دون عنوان',
      bullets: ['Lycamobile و Lebara Prepaid: تقبل التسجيل بعنوان فندق أو Airbnb.', 'Aldi Talk: قد تقبل عنوان مؤقت ثم تحدّثه لاحقاً.', 'Vodafone CallYa: اشتر من المحل بجواز السفر فقط.', 'بمجرد Anmeldung، حدّث عنوانك في التطبيق.'] },
    { num: 20, title: 'احذر النصب والاحتيال', summary: 'محلات الاتصالات في المحطات وبعض المواقع تبيع عقوداً تعبر بشروط مخفية. خطر حقيقي.', tag: 'تحذيرات',
      bullets: ['لا توقّع ورقة باللغة الألمانية لا تفهمها 100%.', 'تجنّب محلات الهاتف في محطات القطار الكبرى — أسعار مبالغ فيها.', 'احذر مكالمات باسم "الشركة" تطلب بيانات — الاحتيال منتشر.', 'اعرض العقد على صديق ألماني قبل التوقيع.', 'احتفظ بالعقد وأي إيصالات لمدة 3 سنوات على الأقل.'],
      tip: 'أفضل طريقة: افتح العقد أونلاين في موقع الشركة الرسمي. لا وسيط، لا مشاكل لاحقة.' },
  ],
}

const fr = {
  metaTitle: 'Cartes SIM et internet en Allemagne — le guide des Marocains',
  metaDesc: '20 articles sur les cartes SIM, l\'internet à la maison, les offres et comment éviter les arnaques en Allemagne.',
  eyebrow: 'Télécoms & internet',
  title: 'Cartes SIM et internet en Allemagne',
  subtitle: 'Un numéro allemand n\'est pas un choix, c\'est une nécessité. Voici comment choisir le bon opérateur, la bonne offre, et les solutions pour chaque situation.',
  intro: '20 articles qui répondent à toutes tes questions : Prepaid ou Vertrag ? Telekom ou O2 ? eSIM ou carte physique ? Et comment éviter les pièges des contrats longue durée.',
  items: [
    { num: 1, title: 'Pourquoi as-tu besoin d\'un numéro allemand dès le premier jour ?', summary: 'Sans numéro allemand actif, impossible de t\'inscrire à la banque, à la mairie, de chercher un appartement, ou même de réceptionner un colis.', tag: 'Bases',
      bullets: ['Les banques vérifient ton identité par SMS, uniquement vers un numéro allemand.', 'Les demandes d\'appartement sont rejetées sans numéro allemand joignable.', 'L\'Ausländerbehörde te contacte par téléphone pour certains rendez-vous.', 'L\'Anmeldung dans certaines villes exige un numéro local.'],
      tip: 'Garde ton numéro marocain actif via des numéros virtuels (WhatsApp/Google Voice) pendant au moins deux mois après l\'arrivée.' },
    { num: 2, title: 'Prepaid vs Vertrag — le premier choix', summary: 'Une décision qui fixe ta flexibilité et tes dépenses sur deux ans. Choisis selon ta stabilité, pas selon le prix affiché.', tag: 'Comparaison',
      bullets: ['**Prepaid :** paiement à l\'avance, sans contrat, sans Schufa, activation immédiate.', '**Vertrag :** contrat de 24 mois, tarifs plus bas, nécessite Schufa + compte bancaire.', 'En tant que nouvel étudiant : commence en Prepaid puis porte ton numéro vers un Vertrag plus tard.', 'Vertrag avec iPhone/nouveau téléphone : souvent plus cher que d\'acheter le téléphone séparément.'] },
    { num: 3, title: 'Les trois grands réseaux en Allemagne', summary: 'Trois réseaux physiques, et des dizaines de marques qui les utilisent. Le réseau réel compte plus que le nom.', tag: 'Réseaux',
      bullets: ['**Deutsche Telekom (D1) :** la meilleure couverture, surtout à la campagne.', '**Vodafone (D2) :** le plus rapide dans les grandes villes, correct dans les villages.', '**O2 (Telefónica) :** le moins cher, bonne couverture en ville, faible à la campagne.', 'Tout petit opérateur (Aldi Talk, Lidl Connect, Congstar…) utilise l\'un de ces trois réseaux.'],
      tip: 'Avant de choisir, vérifie la couverture chez toi sur breitbandmessung.de ou netzabdeckung.o2online.de.' },
    { num: 4, title: 'Telekom (Magenta) — le plus cher, la meilleure couverture', summary: 'Si tu vis dans un village ou voyages souvent en train, Telekom est le choix sûr. C\'est cher, mais ça vaut le coup.', tag: 'Telekom',
      bullets: ['MagentaMobil Start : 30 €/mois, 20 Go, appels illimités.', 'Offres famille (MagentaEins) excellentes si tu as aussi l\'internet fixe chez eux.', 'Seul réseau stable dans les trains rapides (ICE).', '5G disponible dans la plupart des grandes villes.'] },
    { num: 5, title: 'Vodafone — un concurrent équilibré', summary: 'Grand opérateur avec un réseau solide et des offres compétitives. Idéal pour qui vit dans une grande ou moyenne ville.', tag: 'Vodafone',
      bullets: ['GigaMobil S : ~25 €/mois, 15 Go.', 'Offres Unlimited disponibles à un prix raisonnable.', '5G bien déployée à Hamburg, München, Köln, Berlin.', 'Couverture « Unterwegs » bonne sur les autoroutes.'] },
    { num: 6, title: 'O2 — le moins cher en ville', summary: 'Si tu vis en grande ville et consommes beaucoup, O2 offre le meilleur rapport qualité-prix. Mais évite-le à la campagne.', tag: 'O2',
      bullets: ['o2 Mobile M : ~20 €/mois, 20 Go.', 'Offres Free Unlimited réelles (30–40 €).', 'Couverture faible dans les villages et certains trains régionaux.', 'Service client moyen — souvent en allemand uniquement.'] },
    { num: 7, title: 'Aldi Talk — le Prepaid le plus populaire', summary: 'Utilisé par des centaines de milliers de personnes. Prix bas, activation facile, réseau O2 en réalité.', tag: 'Aldi Talk',
      bullets: ['Paket S : 7,99 €/2 semaines, 5 Go + appels illimités.', 'Paket M : 12,99 €/4 semaines, 12 Go + appels illimités.', 'Activation par PostIdent ou VideoIdent en quelques minutes.', 'Disponible dans toutes les filiales Aldi Süd et Aldi Nord.'],
      tip: 'Ton téléphone doit avoir le NFC pour l\'activation en ligne. Sinon, passe en magasin Aldi avec ton passeport.' },
    { num: 8, title: 'Lidl Connect — l\'alternative à Aldi Talk', summary: 'Fonctionne sur le réseau Vodafone, donc meilleure couverture en zone rurale qu\'Aldi Talk.', tag: 'Lidl',
      bullets: ['Smart S : 7,99 €/4 semaines, 5 Go.', 'Smart L : 17,99 €/4 semaines, 25 Go.', 'Vendu dans les magasins Lidl et en ligne.', 'Activation par VideoIdent ou en magasin.'] },
    { num: 9, title: 'Congstar — Telekom à prix réduit', summary: 'Marque low-cost de Telekom. Tu as le même excellent réseau pour 30–40 % moins cher.', tag: 'Congstar',
      bullets: ['Allnet Flat M : 17 €/mois, 10 Go.', 'Contrat 24 mois ou mensuel (un peu plus cher).', 'Qualité d\'appel identique à Telekom.', 'Service client allemand de qualité.'] },
    { num: 10, title: 'Blau — Vodafone à prix réduit', summary: 'Marque low-cost de Vodafone. Parfaite pour qui veut un réseau solide sans payer le prix officiel Vodafone.', tag: 'Blau',
      bullets: ['Blau Allnet L : 15 €/4 semaines, 15 Go.', 'Option mensuelle sans contrat.', 'Roaming gratuit dans toute l\'Union européenne.', 'Activation rapide via l\'application.'] },
    { num: 11, title: 'Vérification d\'identité (PostIdent / VideoIdent)', summary: 'Impossible d\'acheter une SIM sans prouver ton identité. L\'Allemagne prend ça au sérieux depuis 2017.', tag: 'Vérification',
      bullets: ['VideoIdent : appel vidéo de 5 minutes, passeport + bon éclairage, disponible chez la plupart des opérateurs.', 'PostIdent : visite d\'un bureau de poste avec un formulaire imprimé, gratuit pour l\'opérateur.', 'En magasin : viens avec ton passeport, activation en 10 minutes.', 'Un numéro marocain n\'est pas accepté pour la vérification — il faut un e-mail.'] },
    { num: 12, title: 'Portage du numéro entre opérateurs (Rufnummermitnahme)', summary: 'Tu peux garder ton numéro en changeant d\'opérateur. L\'opération est quasiment gratuite.', tag: 'Portage',
      bullets: ['Donne au nouvel opérateur : ton ancien numéro + Kundennummer + Kündigungstermin.', 'Le nouvel opérateur s\'occupe de presque tout.', 'Durée du portage : 1 à 7 jours.', 'Depuis 2020, les frais sont plafonnés à 6,82 € par la loi.'],
      tip: 'Porte ton numéro 3 mois avant la fin du contrat pour éviter toute coupure et sa perte.' },
    { num: 13, title: 'eSIM — l\'alternative numérique moderne', summary: 'L\'eSIM est disponible en Allemagne chez la plupart des opérateurs. Idéale pour les smartphones récents et les voyages.', tag: 'eSIM',
      bullets: ['Telekom, Vodafone, O2, Congstar, 1&1 prennent en charge l\'eSIM.', 'Aldi Talk s\'y est mis en 2024.', 'iPhone XS+ et Samsung Galaxy S20+ supportent l\'eSIM.', 'Tu peux activer deux lignes (SIM physique + eSIM) en même temps.'] },
    { num: 14, title: 'Roaming dans l\'Union européenne', summary: 'Depuis 2017, le roaming dans l\'UE est gratuit avec toute SIM allemande. Mais il y a des limites.', tag: 'Roaming',
      bullets: ['Fair Use : si tu passes trop de temps hors d\'Allemagne, l\'opérateur peut limiter ta consommation.', 'Usage quotidien en France/Espagne/Italie comme en Allemagne, sans frais.', 'Maroc = hors UE = roaming payant (10–20 €/Mo).', 'Pour un voyage au Maroc : achète une eSIM de voyage temporaire (Holafly, Airalo).'] },
    { num: 15, title: 'Internet à la maison (DSL, Kabel, Glasfaser)', summary: 'Trois technologies, des prix variables, et des contrats qui te lient pour 24 mois. Prends ton temps avant de signer.', tag: 'Internet fixe',
      bullets: ['**DSL :** le plus répandu, vitesses 50–250 Mbit.', '**Kabel :** Vodafone + Pyur, vitesses 100–1000 Mbit.', '**Glasfaser :** la fibre, la plus rapide (1 Go+), mais pas disponible partout.', 'Vérifie ton adresse sur verfügbarkeit-check.de avant de signer.', 'Délai d\'activation : 2–8 semaines — ne tarde pas à faire la demande.'] },
    { num: 16, title: 'Solutions internet temporaires (routeur LTE)', summary: 'Si tu attends le raccordement DSL, un routeur LTE avec SIM te connecte tout de suite. Utile pour le logement étudiant.', tag: 'LTE',
      bullets: ['Routeur mobile (MiFi) + SIM de 50 Go/mois : ~30 €/mois.', 'Congstar Homespot et Telekom SpeedStick sont des solutions connues.', 'Adapté aux séjours courts (Airbnb d\'un mois, long séjour à l\'hôtel).', 'Pas une solution durable — plus cher que le DSL sur la durée.'] },
    { num: 17, title: 'Comment résilier le contrat (Kündigung)', summary: 'Chaque contrat en Allemagne attend une Kündigung écrite. Sans lettre officielle, il se renouvelle automatiquement.', tag: 'Résiliation',
      bullets: ['Délai légal de résiliation : 3 mois avant la fin du contrat (maximum).', 'Envoie la Kündigung par écrit via Einschreiben (courrier recommandé) ou depuis le site de l\'opérateur.', 'Demande une confirmation écrite (Kündigungsbestätigung).', 'Depuis 2022, les entreprises doivent fournir un bouton de résiliation direct sur leur site.'],
      tip: 'Le site kuendigung.org génère une lettre officielle et légale et l\'envoie à ta place — très fiable.' },
    { num: 18, title: 'Offres étudiants et jeunes', summary: 'De nombreux opérateurs offrent des réductions aux détenteurs d\'une carte étudiante ou aux moins de 28 ans.', tag: 'Réductions',
      bullets: ['Telekom MagentaMobil Young : 30 % de remise jusqu\'à 28 ans.', 'Vodafone Young : 10 Go à 15 € au lieu de 25 €.', 'O2 My Young : conditions similaires.', 'Demande la remise via le site de l\'opérateur en téléversant ta Studierendenausweis.', 'La remise reste valable jusqu\'au jour de tes 28 ans.'] },
    { num: 19, title: 'Cartes SIM sans adresse allemande', summary: 'Que faire si tu arrives en Allemagne sans adresse fixe. Les options sont limitées mais possibles.', tag: 'Sans adresse',
      bullets: ['Lycamobile et Lebara Prepaid : acceptent l\'inscription avec une adresse d\'hôtel ou Airbnb.', 'Aldi Talk : accepte parfois une adresse temporaire, à mettre à jour plus tard.', 'Vodafone CallYa : à acheter en magasin avec seulement ton passeport.', 'Dès l\'Anmeldung faite, mets à jour ton adresse dans l\'application.'] },
    { num: 20, title: 'Méfie-toi des arnaques et de la fraude', summary: 'Les boutiques télécoms des gares et certains sites vendent des contrats aux conditions cachées. Danger réel.', tag: 'Avertissements',
      bullets: ['Ne signe pas un papier en allemand que tu ne comprends pas à 100 %.', 'Évite les boutiques de téléphones des grandes gares — prix excessifs.', 'Méfie-toi des appels au nom de « l\'opérateur » qui réclament tes données — la fraude est courante.', 'Fais relire le contrat par un ami allemand avant de signer.', 'Conserve le contrat et tous les reçus pendant au moins 3 ans.'],
      tip: 'La meilleure méthode : ouvre ton contrat en ligne sur le site officiel de l\'opérateur. Pas d\'intermédiaire, pas de soucis ensuite.' },
  ],
}

const en = {
  metaTitle: 'SIM cards and internet in Germany — a Moroccan\'s guide',
  metaDesc: '20 articles on SIM cards, home internet, plans, and how to avoid scams in Germany.',
  eyebrow: 'Telecom & internet',
  title: 'SIM cards and internet in Germany',
  subtitle: 'A German number isn\'t optional, it\'s a necessity. Here\'s how to pick the right carrier, the right plan, and solutions for every situation.',
  intro: '20 articles answering every question: Prepaid or Vertrag? Telekom or O2? eSIM or physical card? And how to avoid long-term contract traps.',
  items: [
    { num: 1, title: 'Why you need a German number from day one', summary: 'Without an active German number you can\'t register at a bank, register at the town hall, look for a flat, or even receive a parcel.', tag: 'Basics',
      bullets: ['Banks verify your identity via SMS, only to a German number.', 'Flat applications get rejected without a reachable German number.', 'The Ausländerbehörde phones you for certain appointments.', 'In some cities, Anmeldung requires a local phone number.'],
      tip: 'Keep your Moroccan number active via virtual numbers (WhatsApp/Google Voice) for at least two months after arrival.' },
    { num: 2, title: 'Prepaid vs Vertrag — the first choice', summary: 'A decision that sets your flexibility and costs for two years. Choose based on your stability, not on the headline price.', tag: 'Comparison',
      bullets: ['**Prepaid:** pay upfront, no contract, no Schufa, activated instantly.', '**Vertrag:** 24-month contract, lower rates, requires Schufa + a bank account.', 'As a new student: start on Prepaid, then port your number to a Vertrag later.', 'Vertrag with an iPhone/new phone: usually pricier than buying the phone separately.'] },
    { num: 3, title: 'The three big networks in Germany', summary: 'Three physical networks, and dozens of brands running on them. The actual network matters more than the name.', tag: 'Networks',
      bullets: ['**Deutsche Telekom (D1):** best coverage, especially in rural areas.', '**Vodafone (D2):** fastest in big cities, decent in villages.', '**O2 (Telefónica):** cheapest, good coverage in cities, weak in the countryside.', 'Any small carrier (Aldi Talk, Lidl Connect, Congstar…) runs on one of these networks.'],
      tip: 'Before picking a carrier, check coverage at your address on breitbandmessung.de or netzabdeckung.o2online.de.' },
    { num: 4, title: 'Telekom (Magenta) — priciest, best coverage', summary: 'If you live in a village or travel often by train, Telekom is the safe bet. High price, but worth it.', tag: 'Telekom',
      bullets: ['MagentaMobil Start: €30/month, 20 GB, unlimited calls.', 'Family plans (MagentaEins) excellent if you also have home internet with them.', 'The only network stable on fast trains (ICE).', '5G available in most large cities.'] },
    { num: 5, title: 'Vodafone — a balanced challenger', summary: 'A large carrier with a strong network and competitive plans. Ideal if you live in a large or medium-sized city.', tag: 'Vodafone',
      bullets: ['GigaMobil S: ~€25/month, 15 GB.', 'Unlimited plans available at reasonable prices.', '5G well rolled out in Hamburg, München, Köln, Berlin.', 'Good "Unterwegs" coverage on the motorway.'] },
    { num: 6, title: 'O2 — cheapest in cities', summary: 'If you live in a big city and use a lot of data, O2 is the best value. Avoid it in the countryside.', tag: 'O2',
      bullets: ['o2 Mobile M: ~€20/month, 20 GB.', 'Genuine Free Unlimited plans (€30–40).', 'Weak coverage in villages and on some regional trains.', 'Average customer service — usually German only.'] },
    { num: 7, title: 'Aldi Talk — the most popular Prepaid option', summary: 'Used by hundreds of thousands. Low price, easy activation, runs on O2 in practice.', tag: 'Aldi Talk',
      bullets: ['Paket S: €7.99/2 weeks, 5 GB + unlimited calls.', 'Paket M: €12.99/4 weeks, 12 GB + unlimited calls.', 'Activation via PostIdent or VideoIdent in a few minutes.', 'Available in every Aldi Süd and Aldi Nord store.'],
      tip: 'Your phone needs NFC for online activation. If it doesn\'t have it, walk into an Aldi store with your passport.' },
    { num: 8, title: 'Lidl Connect — the Aldi Talk alternative', summary: 'Runs on the Vodafone network, so better rural coverage than Aldi Talk.', tag: 'Lidl',
      bullets: ['Smart S: €7.99/4 weeks, 5 GB.', 'Smart L: €17.99/4 weeks, 25 GB.', 'Sold in Lidl stores and online.', 'Activation via VideoIdent or in-store.'] },
    { num: 9, title: 'Congstar — Telekom at lower prices', summary: 'Telekom\'s budget brand. You get the same excellent network for 30–40% less.', tag: 'Congstar',
      bullets: ['Allnet Flat M: €17/month, 10 GB.', '24-month or monthly contract (slightly pricier).', 'Call quality identical to Telekom.', 'Good German-language customer service.'] },
    { num: 10, title: 'Blau — Vodafone at a discount', summary: 'Vodafone\'s budget brand. Ideal for anyone who wants a strong network without paying Vodafone\'s list price.', tag: 'Blau',
      bullets: ['Blau Allnet L: €15/4 weeks, 15 GB.', 'Monthly option available without a contract.', 'Free roaming across the whole European Union.', 'Fast activation via the app.'] },
    { num: 11, title: 'Identity verification (PostIdent / VideoIdent)', summary: 'You can\'t buy a SIM without proving your identity. Germany has taken this seriously since 2017.', tag: 'Verification',
      bullets: ['VideoIdent: 5-minute video call, passport + good lighting, available with most carriers.', 'PostIdent: visit a post office with a printed form — free for the carrier.', 'In-store: bring your passport, activation is done in 10 minutes.', 'A Moroccan number isn\'t accepted for verification — you need an email.'] },
    { num: 12, title: 'Porting your number between carriers (Rufnummermitnahme)', summary: 'You can keep your number when switching carriers. The process is almost free.', tag: 'Porting',
      bullets: ['Give the new carrier: your old number + Kundennummer + Kündigungstermin.', 'The new carrier handles almost everything.', 'Port time: 1–7 days.', 'Since 2020, the legal fee is capped at €6.82.'],
      tip: 'Port your number 3 months before the contract ends to avoid any break or loss of the number.' },
    { num: 13, title: 'eSIM — the modern digital alternative', summary: 'eSIM is available in Germany from most carriers. Ideal for recent phones and for travel.', tag: 'eSIM',
      bullets: ['Telekom, Vodafone, O2, Congstar, 1&1 all support eSIM.', 'Aldi Talk started supporting it in 2024.', 'iPhone XS+ and Samsung Galaxy S20+ support eSIM.', 'You can activate two lines at once (physical SIM + eSIM).'] },
    { num: 14, title: 'Roaming in the European Union', summary: 'Since 2017, roaming within the EU is free on any German SIM. But there are limits.', tag: 'Roaming',
      bullets: ['Fair Use: if you spend too long outside Germany, the carrier can throttle your usage.', 'Daily use in France/Spain/Italy works just like in Germany, at no extra cost.', 'Morocco = outside the EU = paid roaming (€10–20 per MB).', 'Travelling to Morocco: buy a temporary travel eSIM (Holafly, Airalo).'] },
    { num: 15, title: 'Home internet (DSL, Kabel, Glasfaser)', summary: 'Three technologies, a wide range of prices, and contracts that lock you in for 24 months. Take your time before signing.', tag: 'Home internet',
      bullets: ['**DSL:** the most widespread, speeds 50–250 Mbit.', '**Kabel:** Vodafone + Pyur, speeds 100–1000 Mbit.', '**Glasfaser:** fibre, the fastest (1 GB+), but not available in every neighbourhood.', 'Check your address on verfügbarkeit-check.de before signing.', 'Activation time: 2–8 weeks — don\'t delay the order.'] },
    { num: 16, title: 'Temporary internet solutions (LTE router)', summary: 'If you\'re waiting for DSL hookup, an LTE router with a SIM gets you online right away. Handy for student housing.', tag: 'LTE',
      bullets: ['Mobile router (MiFi) + 50 GB/month SIM: ~€30/month.', 'Congstar Homespot and Telekom SpeedStick are well-known options.', 'Suitable for short stays (one-month Airbnb, long hotel stay).', 'Not a long-term fix — more expensive than DSL over time.'] },
    { num: 17, title: 'How to cancel the contract (Kündigung)', summary: 'Every contract in Germany waits for a written Kündigung. Without an official letter, it renews automatically.', tag: 'Cancellation',
      bullets: ['Legal notice period: 3 months before the contract ends (maximum).', 'Send the Kündigung in writing via Einschreiben (registered mail) or through the carrier\'s website.', 'Ask for written confirmation (Kündigungsbestätigung).', 'Since 2022, companies must provide a direct cancel button on their website.'],
      tip: 'The site kuendigung.org generates a legal, official letter and sends it on your behalf — very reliable.' },
    { num: 18, title: 'Student and youth deals', summary: 'Many carriers offer discounts to student card holders or to anyone under 28.', tag: 'Discounts',
      bullets: ['Telekom MagentaMobil Young: 30% off until age 28.', 'Vodafone Young: 10 GB for €15 instead of €25.', 'O2 My Young: similar terms.', 'Apply for the discount via the carrier\'s website and upload your Studierendenausweis.', 'The discount lasts until the day you turn 28.'] },
    { num: 19, title: 'SIM cards without a German address', summary: 'What to do if you arrive in Germany without a fixed address yet. Limited options, but they exist.', tag: 'No address',
      bullets: ['Lycamobile and Lebara Prepaid: accept registration with a hotel or Airbnb address.', 'Aldi Talk: may accept a temporary address, to be updated later.', 'Vodafone CallYa: buy in-store with just your passport.', 'Once Anmeldung is done, update your address in the app.'] },
    { num: 20, title: 'Watch out for scams and fraud', summary: 'Telecom shops in train stations and some websites sell contracts with hidden terms. A real risk.', tag: 'Warnings',
      bullets: ['Never sign a document in German that you don\'t understand 100%.', 'Avoid phone shops in big train stations — inflated prices.', 'Beware calls from "the carrier" asking for personal data — fraud is widespread.', 'Have a German friend read the contract before you sign.', 'Keep the contract and any receipts for at least 3 years.'],
      tip: 'Best approach: open the contract online on the carrier\'s official site. No middleman, no trouble down the line.' },
  ],
}

const de = {
  metaTitle: 'SIM-Karten und Internet in Deutschland — der Leitfaden für Marokkaner',
  metaDesc: '20 Artikel zu SIM-Karten, Heim-Internet, Tarifen und wie du Abzocke in Deutschland vermeidest.',
  eyebrow: 'Telekom & Internet',
  title: 'SIM-Karten und Internet in Deutschland',
  subtitle: 'Eine deutsche Nummer ist keine Option, sondern eine Notwendigkeit. So wählst du den passenden Anbieter, den richtigen Tarif und findest Lösungen für jede Lage.',
  intro: '20 Artikel, die all deine Fragen beantworten: Prepaid oder Vertrag? Telekom oder O2? eSIM oder physische Karte? Und wie du Langzeitvertrag-Fallen vermeidest.',
  items: [
    { num: 1, title: 'Warum du ab dem ersten Tag eine deutsche Nummer brauchst', summary: 'Ohne aktive deutsche Nummer kannst du dich nicht bei der Bank anmelden, keine Anmeldung machen, keine Wohnung suchen und nicht einmal ein Paket annehmen.', tag: 'Grundlagen',
      bullets: ['Banken prüfen deine Identität per SMS — nur an eine deutsche Nummer.', 'Wohnungsanfragen werden ohne erreichbare deutsche Nummer abgelehnt.', 'Die Ausländerbehörde kontaktiert dich für manche Termine per Telefon.', 'Die Anmeldung verlangt in manchen Städten eine lokale Telefonnummer.'],
      tip: 'Halte deine marokkanische Nummer über virtuelle Nummern (WhatsApp/Google Voice) mindestens zwei Monate nach Ankunft aktiv.' },
    { num: 2, title: 'Prepaid gegen Vertrag — die erste Wahl', summary: 'Eine Entscheidung, die deine Flexibilität und Kosten für zwei Jahre bestimmt. Wähle nach deiner Stabilität, nicht nach dem Lockpreis.', tag: 'Vergleich',
      bullets: ['**Prepaid:** Vorauszahlung, kein Vertrag, keine Schufa, sofort aktiviert.', '**Vertrag:** 24 Monate Laufzeit, günstigere Preise, Schufa + Bankkonto erforderlich.', 'Als Studi-Neuling: starte mit Prepaid und portiere die Nummer später in einen Vertrag.', 'Vertrag mit iPhone/neuem Handy: meist teurer, als das Handy separat zu kaufen.'] },
    { num: 3, title: 'Die drei großen Netze in Deutschland', summary: 'Drei physische Netze und dutzende Marken, die sie nutzen. Das tatsächliche Netz zählt mehr als der Name.', tag: 'Netze',
      bullets: ['**Deutsche Telekom (D1):** beste Abdeckung, vor allem auf dem Land.', '**Vodafone (D2):** am schnellsten in Großstädten, ordentlich in Dörfern.', '**O2 (Telefónica):** am günstigsten, gute Abdeckung in Städten, schwach auf dem Land.', 'Jeder kleine Anbieter (Aldi Talk, Lidl Connect, Congstar …) nutzt eins dieser Netze.'],
      tip: 'Prüfe vor der Anbieterwahl die Abdeckung bei dir über breitbandmessung.de oder netzabdeckung.o2online.de.' },
    { num: 4, title: 'Telekom (Magenta) — am teuersten, beste Abdeckung', summary: 'Wenn du im Dorf lebst oder viel Bahn fährst, ist die Telekom die sichere Wahl. Hoher Preis, aber es lohnt sich.', tag: 'Telekom',
      bullets: ['MagentaMobil Start: 30 €/Monat, 20 GB, Flat in alle Netze.', 'MagentaEins-Familienoptionen top, wenn du auch Festnetz-Internet bei ihnen hast.', 'Das einzig stabile Netz in den Schnellzügen (ICE).', '5G in den meisten Großstädten verfügbar.'] },
    { num: 5, title: 'Vodafone — ausgewogener Herausforderer', summary: 'Großer Anbieter mit starkem Netz und konkurrenzfähigen Tarifen. Ideal, wenn du in einer Groß- oder Mittelstadt lebst.', tag: 'Vodafone',
      bullets: ['GigaMobil S: ~25 €/Monat, 15 GB.', 'Unlimited-Tarife zu vernünftigen Preisen verfügbar.', '5G gut ausgebaut in Hamburg, München, Köln, Berlin.', 'Gute „Unterwegs"-Abdeckung auf der Autobahn.'] },
    { num: 6, title: 'O2 — am günstigsten in der Stadt', summary: 'Wenn du in einer Großstadt lebst und viel verbrauchst, bietet O2 das beste Preis-Leistungs-Verhältnis. Auf dem Land aber meiden.', tag: 'O2',
      bullets: ['o2 Mobile M: ~20 €/Monat, 20 GB.', 'Echte Free-Unlimited-Tarife (30–40 €).', 'Schwache Abdeckung in Dörfern und in einigen Regionalzügen.', 'Durchschnittlicher Kundenservice — oft nur auf Deutsch.'] },
    { num: 7, title: 'Aldi Talk — die bekannteste Prepaid-Option', summary: 'Wird von Hunderttausenden genutzt. Niedriger Preis, einfache Aktivierung, läuft faktisch im O2-Netz.', tag: 'Aldi Talk',
      bullets: ['Paket S: 7,99 €/2 Wochen, 5 GB + Telefonie-Flat.', 'Paket M: 12,99 €/4 Wochen, 12 GB + Telefonie-Flat.', 'Aktivierung per PostIdent oder VideoIdent in wenigen Minuten.', 'In jeder Aldi-Süd- und Aldi-Nord-Filiale erhältlich.'],
      tip: 'Dein Handy braucht NFC für die Online-Aktivierung. Fehlt das, geh mit dem Reisepass in eine Aldi-Filiale.' },
    { num: 8, title: 'Lidl Connect — die Alternative zu Aldi Talk', summary: 'Läuft im Vodafone-Netz, deckt ländliche Gebiete also besser ab als Aldi Talk.', tag: 'Lidl',
      bullets: ['Smart S: 7,99 €/4 Wochen, 5 GB.', 'Smart L: 17,99 €/4 Wochen, 25 GB.', 'Verkauft in Lidl-Filialen und online.', 'Aktivierung per VideoIdent oder in der Filiale.'] },
    { num: 9, title: 'Congstar — Telekom zum kleineren Preis', summary: 'Die günstige Marke der Telekom. Du bekommst das gleiche exzellente Netz für 30–40 % weniger.', tag: 'Congstar',
      bullets: ['Allnet Flat M: 17 €/Monat, 10 GB.', 'Laufzeit 24 Monate oder monatlich (etwas teurer).', 'Gesprächsqualität identisch mit der Telekom.', 'Guter deutschsprachiger Kundenservice.'] },
    { num: 10, title: 'Blau — Vodafone zum Sparpreis', summary: 'Die günstige Marke von Vodafone. Perfekt, wenn du ein starkes Netz willst, ohne den Vodafone-Listenpreis zu zahlen.', tag: 'Blau',
      bullets: ['Blau Allnet L: 15 €/4 Wochen, 15 GB.', 'Monatliche Option ohne Vertragsbindung.', 'Kostenloses Roaming in der gesamten EU.', 'Schnelle Aktivierung über die App.'] },
    { num: 11, title: 'Identitätsprüfung (PostIdent / VideoIdent)', summary: 'Ohne Identitätsnachweis bekommst du keine SIM. Deutschland nimmt das seit 2017 ernst.', tag: 'Verifizierung',
      bullets: ['VideoIdent: 5-minütiger Videoanruf, Reisepass + gute Beleuchtung, bei den meisten Anbietern möglich.', 'PostIdent: Besuch einer Postfiliale mit ausgedrucktem Formular, für den Anbieter kostenlos.', 'Im Laden: mit dem Reisepass hingehen, Aktivierung in 10 Minuten erledigt.', 'Eine marokkanische Nummer wird für die Verifizierung nicht akzeptiert — du brauchst eine E-Mail-Adresse.'] },
    { num: 12, title: 'Rufnummermitnahme zwischen Anbietern', summary: 'Du kannst deine Nummer beim Anbieterwechsel behalten. Der Vorgang ist praktisch kostenlos.', tag: 'Rufnummer-Portierung',
      bullets: ['Gib dem neuen Anbieter: deine alte Nummer + Kundennummer + Kündigungstermin.', 'Der neue Anbieter kümmert sich um fast alles.', 'Portierungsdauer: 1–7 Tage.', 'Seit 2020 ist die Gebühr gesetzlich auf 6,82 € gedeckelt.'],
      tip: 'Portiere die Nummer 3 Monate vor Vertragsende, damit sie weder unterbrochen noch verloren geht.' },
    { num: 13, title: 'eSIM — die moderne digitale Alternative', summary: 'Die eSIM ist in Deutschland bei den meisten Anbietern verfügbar. Ideal für aktuelle Smartphones und Reisen.', tag: 'eSIM',
      bullets: ['Telekom, Vodafone, O2, Congstar, 1&1 unterstützen eSIM.', 'Aldi Talk unterstützt sie seit 2024.', 'iPhone XS+ und Samsung Galaxy S20+ können eSIM.', 'Du kannst zwei Leitungen parallel aktivieren (physische SIM + eSIM).'] },
    { num: 14, title: 'Roaming in der Europäischen Union', summary: 'Seit 2017 ist Roaming innerhalb der EU mit jeder deutschen SIM kostenlos. Es gibt aber Grenzen.', tag: 'Roaming',
      bullets: ['Fair Use: Wenn du zu lange außerhalb Deutschlands bist, kann der Anbieter den Verbrauch drosseln.', 'Alltagsnutzung in Frankreich/Spanien/Italien wie in Deutschland, ohne Zusatzkosten.', 'Marokko = außerhalb der EU = Roaming kostet (10–20 €/MB).', 'Für die Reise nach Marokko: hol dir eine temporäre Reise-eSIM (Holafly, Airalo).'] },
    { num: 15, title: 'Heim-Internet (DSL, Kabel, Glasfaser)', summary: 'Drei Technologien, unterschiedliche Preise und Verträge, die dich 24 Monate binden. Lass dir Zeit vor der Unterschrift.', tag: 'Heim-Internet',
      bullets: ['**DSL:** am weitesten verbreitet, Geschwindigkeiten 50–250 Mbit.', '**Kabel:** Vodafone + Pyur, Geschwindigkeiten 100–1000 Mbit.', '**Glasfaser:** die schnellste (1 GB+), aber nicht in jedem Viertel verfügbar.', 'Prüfe deine Adresse auf verfügbarkeit-check.de vor der Unterschrift.', 'Aktivierungszeit: 2–8 Wochen — bestelle rechtzeitig.'] },
    { num: 16, title: 'Temporäre Internet-Lösungen (LTE-Router)', summary: 'Wenn du auf den DSL-Anschluss wartest, bringt dich ein LTE-Router mit SIM sofort online. Praktisch für WG-Zimmer.', tag: 'LTE',
      bullets: ['Mobiler Router (MiFi) + SIM mit 50 GB/Monat: ~30 €/Monat.', 'Congstar Homespot und Telekom SpeedStick sind bekannte Lösungen.', 'Passt für kurze Aufenthalte (Monats-Airbnb, längerer Hotelaufenthalt).', 'Keine Dauerlösung — auf lange Sicht teurer als DSL.'] },
    { num: 17, title: 'Vertrag kündigen (Kündigung)', summary: 'Jeder Vertrag in Deutschland wartet auf eine schriftliche Kündigung. Ohne offizielles Schreiben verlängert er sich automatisch.', tag: 'Kündigung',
      bullets: ['Gesetzliche Kündigungsfrist: maximal 3 Monate vor Vertragsende.', 'Schicke die Kündigung schriftlich per Einschreiben oder über die Website des Anbieters.', 'Fordere eine schriftliche Kündigungsbestätigung an.', 'Seit 2022 müssen Unternehmen einen direkten Kündigungsbutton auf der Website anbieten.'],
      tip: 'Die Seite kuendigung.org erstellt ein rechtlich sauberes Schreiben und versendet es für dich — sehr zuverlässig.' },
    { num: 18, title: 'Angebote für Studierende und Junge', summary: 'Viele Anbieter geben Rabatte für Studierendenausweise oder unter 28 Jahren.', tag: 'Rabatte',
      bullets: ['Telekom MagentaMobil Young: 30 % Rabatt bis zum 28. Lebensjahr.', 'Vodafone Young: 10 GB für 15 € statt 25 €.', 'O2 My Young: ähnliche Konditionen.', 'Beantrage den Rabatt über die Anbieter-Website und lade deinen Studierendenausweis hoch.', 'Der Rabatt gilt bis zu deinem 28. Geburtstag.'] },
    { num: 19, title: 'SIM-Karten ohne deutsche Adresse', summary: 'Was tun, wenn du in Deutschland ankommst und noch keine feste Adresse hast. Die Optionen sind begrenzt, aber machbar.', tag: 'Ohne Adresse',
      bullets: ['Lycamobile und Lebara Prepaid: akzeptieren die Registrierung mit Hotel- oder Airbnb-Adresse.', 'Aldi Talk: akzeptiert teils eine temporäre Adresse, die du später aktualisierst.', 'Vodafone CallYa: im Laden nur mit Reisepass zu kaufen.', 'Nach der Anmeldung aktualisierst du deine Adresse in der App.'] },
    { num: 20, title: 'Vorsicht vor Abzocke und Betrug', summary: 'Handyläden in Bahnhöfen und manche Websites verkaufen Verträge mit versteckten Bedingungen. Eine reale Gefahr.', tag: 'Warnungen',
      bullets: ['Unterschreibe nie ein deutsches Dokument, das du nicht zu 100 % verstehst.', 'Meide Handyläden in großen Bahnhöfen — übertriebene Preise.', 'Vorsicht bei Anrufen im Namen „des Anbieters", die Daten abfragen — Betrug ist verbreitet.', 'Lass den Vertrag vor der Unterschrift von einem deutschen Freund gegenlesen.', 'Bewahre den Vertrag und alle Belege mindestens 3 Jahre auf.'],
      tip: 'Am besten: schließe den Vertrag online auf der offiziellen Website des Anbieters ab. Kein Zwischenhändler, keine späteren Probleme.' },
  ],
}

const byLoc = { ar, fr, en, de }

// Ensure `common.tipLabel` key exists
const tipLabel = { ar: 'نصيحة', fr: 'Astuce', en: 'Tip', de: 'Tipp' }

for (const loc of ['ar', 'fr', 'en', 'de']) {
  const p = path.join(__dirname, '..', 'messages', `${loc}.json`)
  const j = JSON.parse(fs.readFileSync(p, 'utf8'))
  j.static = j.static || {}
  j.static.simcards = byLoc[loc]
  j.common = j.common || {}
  j.common.tipLabel = tipLabel[loc]
  fs.writeFileSync(p, JSON.stringify(j, null, 2) + '\n', 'utf8')
  console.log(`✓ ${loc}.json`)
}
