/* eslint-disable */
const fs = require('fs')
const path = require('path')

const LOCALES = ['ar', 'fr', 'en', 'de']

const SHELL = {
  ar: {
    sidebar: {
      myProfile: 'ملفي',
      tapToComplete: 'اضغط للإكمال',
      sectionMarketplace: 'الفرص',
      sectionPreparation: 'التحضير',
      sectionTools: 'الأدوات',
      browse: 'تصفح الفرص',
      saved: 'الفرص المحفوظة',
      applyForMe: 'قدّم نيابة عني',
      newBadge: 'جديد',
      dashboard: 'لوحة التحكم',
      germanLearning: 'تعلم الألمانية',
      interviewPrep: 'تدريب المقابلات',
      videoStudio: 'استوديو الفيديو',
      culture: 'الثقافة',
      eligibility: 'الأهلية',
      timeline: 'الجدول الزمني',
      cvBuilder: 'منشئ السيرة',
      coverLetter: 'رسالة التحفيز',
      whatsappSupport: 'دعم واتساب',
      services: 'الخدمات',
      help: 'المساعدة',
    },
    topbar: {
      help: 'مساعدة',
      whatsapp: 'واتساب',
      notifications: 'الإشعارات',
      account: 'حسابي',
    },
    profile: {
      heroBannerTitle: 'ملفك الشخصي {pct}٪ مكتمل',
      heroBannerSub: 'أكمل الحقول أدناه لرفع نسبة إنجاز ملفك.',
      unlockNext: '{pct}٪ إضافية لفتح:',
      unlockTargetGerman: 'تعلم الألمانية',
      quickUpdate: 'تحديث سريع عبر السيرة',
      updateManually: 'تحديث يدوي',
      goalPct: 'الهدف: 100٪',
      completionLabel: 'إنجاز الملف: {pct}٪',
      completeness: 'اكتمال الملف',
      completenessCompleteSuffix: 'مكتمل',
      strength: 'قوة الملف',
      strengthPoints: 'نقاط',
      strengthComparison: 'أقوى من 50٪ من المرشحين',
      tier: 'المستوى',
      incomplete: 'غير مكتمل',
      weak: 'ضعيف',
      good: 'جيد',
      strong: 'قوي',
      mostFieldsEmpty: 'معظم الحقول فارغة',
      gettingThere: '25٪ — تقدّم جيد',
      nextGoal: 'الهدف التالي',
      tierWeak: 'ملف ضعيف',
      tierFair: 'ملف متوسط',
      tierStrong: 'ملف قوي',
      missing: {
        photo: 'أضف صورة الملف الشخصي',
        phone: 'أضف رقم هاتفك',
        dob: 'أضف تاريخ الميلاد',
        status: 'حدد وضعك الحالي',
        cv: 'أنشئ سيرتك الذاتية',
        letter: 'أنشئ رسالة تحفيزية',
      },
      sections: {
        education: 'التعليم',
        experience: 'الخبرة',
        languages: 'اللغات',
        skills: 'المهارات',
        personal: 'المعلومات الشخصية',
        contact: 'معلومات الاتصال',
        add: 'إضافة',
        comingSoon: 'قريباً',
      },
      promo: {
        title: 'دع فريقنا يتولى تقديم الطلبات',
        body: 'خدمة «قدّم نيابة عني» ترسل طلباتك لعشرات الفرص تلقائياً.',
        cta: 'اكتشف الخدمة',
      },
    },
    stubs: {
      savedTitle: 'الفرص المحفوظة',
      savedEmpty: 'لم تحفظ أي فرص بعد. تصفّح الفرص واضغط على أيقونة الحفظ لتجميعها هنا.',
      applyTitle: 'قدّم نيابة عني',
      applyBody: 'سنقدم طلباتك لعشرات الفرص المطابقة لملفك. الخدمة قيد الإطلاق.',
      lockedTitle: '{feature} — قريباً',
      lockedBody: 'هذه الميزة قيد التطوير. سنخبرك بمجرد توفرها.',
      browseCta: 'تصفح الفرص',
    },
  },
  fr: {
    sidebar: {
      myProfile: 'Mon profil',
      tapToComplete: 'Cliquez pour compléter',
      sectionMarketplace: 'Marketplace',
      sectionPreparation: 'Préparation',
      sectionTools: 'Outils',
      browse: 'Parcourir les opportunités',
      saved: 'Opportunités sauvegardées',
      applyForMe: 'Postulez pour moi',
      newBadge: 'Nouveau',
      dashboard: 'Tableau de bord',
      germanLearning: 'Apprendre l’allemand',
      interviewPrep: 'Préparation entretien',
      videoStudio: 'Studio vidéo',
      culture: 'Culture',
      eligibility: 'Éligibilité',
      timeline: 'Chronologie',
      cvBuilder: 'Créateur de CV',
      coverLetter: 'Lettre de motivation',
      whatsappSupport: 'Support WhatsApp',
      services: 'Services',
      help: 'Aide',
    },
    topbar: {
      help: 'Aide',
      whatsapp: 'WhatsApp',
      notifications: 'Notifications',
      account: 'Mon compte',
    },
    profile: {
      heroBannerTitle: 'Votre profil est complété à {pct}%',
      heroBannerSub: 'Complétez les champs ci-dessous pour progresser.',
      unlockNext: '{pct}% de plus pour débloquer :',
      unlockTargetGerman: 'Apprentissage de l’allemand',
      quickUpdate: 'Mise à jour via CV',
      updateManually: 'Mise à jour manuelle',
      goalPct: 'Objectif : 100%',
      completionLabel: 'Complétion : {pct}%',
      completeness: 'Complétude du profil',
      completenessCompleteSuffix: 'complet',
      strength: 'Force du profil',
      strengthPoints: 'points',
      strengthComparison: 'Plus fort que 50% des candidats',
      tier: 'Niveau',
      incomplete: 'Incomplet',
      weak: 'Faible',
      good: 'Bon',
      strong: 'Fort',
      mostFieldsEmpty: 'La plupart des champs sont vides',
      gettingThere: '25% — En bonne voie',
      nextGoal: 'Prochain objectif',
      tierWeak: 'Profil faible',
      tierFair: 'Profil moyen',
      tierStrong: 'Profil fort',
      missing: {
        photo: 'Ajoutez une photo de profil',
        phone: 'Ajoutez votre numéro',
        dob: 'Ajoutez votre date de naissance',
        status: 'Définissez votre statut',
        cv: 'Créez votre CV',
        letter: 'Créez votre lettre de motivation',
      },
      sections: {
        education: 'Formation',
        experience: 'Expérience',
        languages: 'Langues',
        skills: 'Compétences',
        personal: 'Informations personnelles',
        contact: 'Coordonnées',
        add: 'Ajouter',
        comingSoon: 'Bientôt',
      },
      promo: {
        title: 'Laissez-nous postuler à votre place',
        body: 'Notre service « Postulez pour moi » envoie vos candidatures automatiquement.',
        cta: 'Découvrir le service',
      },
    },
    stubs: {
      savedTitle: 'Opportunités sauvegardées',
      savedEmpty: 'Aucune opportunité sauvegardée. Parcourez les offres et cliquez sur l’icône de sauvegarde.',
      applyTitle: 'Postulez pour moi',
      applyBody: 'Nous envoyons vos candidatures pour les opportunités correspondant à votre profil. Bientôt disponible.',
      lockedTitle: '{feature} — Bientôt',
      lockedBody: 'Cette fonctionnalité est en cours de développement.',
      browseCta: 'Parcourir les opportunités',
    },
  },
  en: {
    sidebar: {
      myProfile: 'My Profile',
      tapToComplete: 'Tap to complete',
      sectionMarketplace: 'Marketplace',
      sectionPreparation: 'Preparation',
      sectionTools: 'Tools',
      browse: 'Browse Opportunities',
      saved: 'Saved Opportunities',
      applyForMe: 'Apply For Me',
      newBadge: 'New',
      dashboard: 'Dashboard',
      germanLearning: 'German Learning',
      interviewPrep: 'Interview Prep',
      videoStudio: 'Video Studio',
      culture: 'Culture',
      eligibility: 'Eligibility',
      timeline: 'Timeline',
      cvBuilder: 'CV Builder',
      coverLetter: 'Cover Letter',
      whatsappSupport: 'WhatsApp Support',
      services: 'Services',
      help: 'Help & Docs',
    },
    topbar: {
      help: 'Help',
      whatsapp: 'WhatsApp',
      notifications: 'Notifications',
      account: 'Account',
    },
    profile: {
      heroBannerTitle: 'Your profile is {pct}% complete',
      heroBannerSub: 'Fill the missing fields below to increase your completion.',
      unlockNext: '{pct}% more to unlock:',
      unlockTargetGerman: 'German Learning',
      quickUpdate: 'Quick Update via CV',
      updateManually: 'Update Manually',
      goalPct: 'Goal: 100%',
      completionLabel: 'Profile Completion: {pct}%',
      completeness: 'Profile Completeness',
      completenessCompleteSuffix: 'complete',
      strength: 'Profile Strength',
      strengthPoints: 'points',
      strengthComparison: 'Stronger than 50% of candidates',
      tier: 'Tier',
      incomplete: 'Incomplete',
      weak: 'Weak',
      good: 'Good',
      strong: 'Strong',
      mostFieldsEmpty: 'Most fields empty',
      gettingThere: '25% — Getting there',
      nextGoal: 'Next Goal',
      tierWeak: 'Weak Profile',
      tierFair: 'Fair Profile',
      tierStrong: 'Strong Profile',
      missing: {
        photo: 'Upload a profile photo',
        phone: 'Add your phone number',
        dob: 'Add date of birth',
        status: 'Set your current status',
        cv: 'Build your CV',
        letter: 'Generate a motivation letter',
      },
      sections: {
        education: 'Education',
        experience: 'Experience',
        languages: 'Languages',
        skills: 'Skills',
        personal: 'Personal Information',
        contact: 'Contact Information',
        add: 'Add',
        comingSoon: 'Coming soon',
      },
      promo: {
        title: 'Let our team apply for you',
        body: 'Our Apply-For-Me service sends applications to dozens of matching opportunities automatically.',
        cta: 'Discover the service',
      },
    },
    stubs: {
      savedTitle: 'Saved Opportunities',
      savedEmpty: 'You haven’t saved any opportunities yet. Browse the marketplace and click the bookmark icon to collect them here.',
      applyTitle: 'Apply For Me',
      applyBody: 'We’ll send applications to opportunities matching your profile. Launching soon.',
      lockedTitle: '{feature} — Coming soon',
      lockedBody: 'This feature is under development. We’ll let you know when it’s available.',
      browseCta: 'Browse Opportunities',
    },
  },
  de: {
    sidebar: {
      myProfile: 'Mein Profil',
      tapToComplete: 'Zum Vervollständigen tippen',
      sectionMarketplace: 'Marktplatz',
      sectionPreparation: 'Vorbereitung',
      sectionTools: 'Werkzeuge',
      browse: 'Angebote durchsuchen',
      saved: 'Gespeicherte Angebote',
      applyForMe: 'Für mich bewerben',
      newBadge: 'Neu',
      dashboard: 'Dashboard',
      germanLearning: 'Deutsch lernen',
      interviewPrep: 'Interview-Vorbereitung',
      videoStudio: 'Video-Studio',
      culture: 'Kultur',
      eligibility: 'Berechtigung',
      timeline: 'Zeitplan',
      cvBuilder: 'Lebenslauf-Builder',
      coverLetter: 'Anschreiben',
      whatsappSupport: 'WhatsApp-Support',
      services: 'Dienste',
      help: 'Hilfe & Docs',
    },
    topbar: {
      help: 'Hilfe',
      whatsapp: 'WhatsApp',
      notifications: 'Benachrichtigungen',
      account: 'Konto',
    },
    profile: {
      heroBannerTitle: 'Dein Profil ist zu {pct}% vollständig',
      heroBannerSub: 'Fülle die fehlenden Felder aus, um dein Profil zu vervollständigen.',
      unlockNext: '{pct}% mehr zum Freischalten:',
      unlockTargetGerman: 'Deutsch lernen',
      quickUpdate: 'Schnell-Update per Lebenslauf',
      updateManually: 'Manuell aktualisieren',
      goalPct: 'Ziel: 100%',
      completionLabel: 'Profilvollständigkeit: {pct}%',
      completeness: 'Profilvollständigkeit',
      completenessCompleteSuffix: 'vollständig',
      strength: 'Profilstärke',
      strengthPoints: 'Punkte',
      strengthComparison: 'Stärker als 50% der Kandidaten',
      tier: 'Stufe',
      incomplete: 'Unvollständig',
      weak: 'Schwach',
      good: 'Gut',
      strong: 'Stark',
      mostFieldsEmpty: 'Die meisten Felder sind leer',
      gettingThere: '25% — auf gutem Weg',
      nextGoal: 'Nächstes Ziel',
      tierWeak: 'Schwaches Profil',
      tierFair: 'Mittleres Profil',
      tierStrong: 'Starkes Profil',
      missing: {
        photo: 'Profilbild hochladen',
        phone: 'Telefonnummer hinzufügen',
        dob: 'Geburtsdatum hinzufügen',
        status: 'Aktuellen Status festlegen',
        cv: 'Lebenslauf erstellen',
        letter: 'Motivationsschreiben erstellen',
      },
      sections: {
        education: 'Ausbildung',
        experience: 'Erfahrung',
        languages: 'Sprachen',
        skills: 'Fähigkeiten',
        personal: 'Persönliche Informationen',
        contact: 'Kontakt',
        add: 'Hinzufügen',
        comingSoon: 'Bald',
      },
      promo: {
        title: 'Lass unser Team für dich bewerben',
        body: 'Unser „Für mich bewerben"-Service sendet Bewerbungen automatisch an passende Angebote.',
        cta: 'Service entdecken',
      },
    },
    stubs: {
      savedTitle: 'Gespeicherte Angebote',
      savedEmpty: 'Noch keine Angebote gespeichert. Durchsuche den Marktplatz und klicke auf das Lesezeichen-Symbol.',
      applyTitle: 'Für mich bewerben',
      applyBody: 'Wir senden Bewerbungen an passende Angebote. Bald verfügbar.',
      lockedTitle: '{feature} — Bald verfügbar',
      lockedBody: 'Diese Funktion ist in Entwicklung.',
      browseCta: 'Angebote durchsuchen',
    },
  },
}

for (const loc of LOCALES) {
  const p = path.join(__dirname, '..', 'messages', `${loc}.json`)
  const j = JSON.parse(fs.readFileSync(p, 'utf8'))
  j.dashboard = j.dashboard || {}
  j.dashboard.sidebar = SHELL[loc].sidebar
  j.dashboard.topbar = SHELL[loc].topbar
  j.dashboard.profilePage = SHELL[loc].profile
  j.dashboard.stubs = SHELL[loc].stubs
  fs.writeFileSync(p, JSON.stringify(j, null, 2) + '\n', 'utf8')
  console.log(`patched ${loc}`)
}
