const fs = require('fs')
const path = require('path')

const ar = {
  metaTitle: 'التأشيرة والأوراق الرسمية في ألمانيا',
  metaDesc: '20 مقالاً عن أنواع التأشيرات، Anmeldung، Aufenthaltstitel، Blaue Karte، Chancenkarte وكل الأوراق.',
  eyebrow: 'التأشيرة والأوراق',
  title: 'الفيزا والأوراق الرسمية',
  subtitle: 'كل ما تحتاج معرفته عن التأشيرات الألمانية والإجراءات البيروقراطية التي تنتظرك بعد الوصول.',
  intro: '20 مقالاً تحليلياً يغطّيان رحلتك الورقية: من حجز موعد السفارة في الرباط إلى الحصول على الجنسية الألمانية.',
  items: [
    { num: 1, title: 'أنواع التأشيرات الرئيسية لألمانيا', summary: 'التأشيرة الصحيحة تحدّد مستقبلك في ألمانيا. لا تقدّم لأي نوع قبل فهم البدائل.', tag: 'مقدّمة',
      bullets: [
        '**Studienvisum:** للطلاب المقبولين في جامعة.',
        '**Ausbildungsvisum:** للتدريب المهني المزدوج.',
        '**Arbeitsvisum:** لمن لديه عقد عمل مؤكد.',
        '**Blaue Karte EU:** للمهنيين المؤهّلين براتب معيّن.',
        '**Jobsuchevisum:** 6 أشهر للبحث عن عمل (خرّيج جامعة).',
        '**Chancenkarte:** بطاقة الفرص — 12 شهراً بنظام نقاط.',
        '**Familienzusammenführung:** لمّ الشمل العائلي.',
      ] },
    { num: 2, title: 'حجز موعد السفارة في المغرب', summary: 'الخطوة الأصعب عملياً. المواعيد نادرة وتفتح فجأة. اتبع هذه الطريقة لتضمن موعداً في وقت معقول.', tag: 'سفارة',
      bullets: [
        'موقع السفارة الرسمي: maroc.diplo.de — المصدر الوحيد الموثوق.',
        'المواعيد تفتح عادةً بين 8:00 و10:00 صباحاً بتوقيت ألمانيا.',
        'كل نوع تأشيرة له "بوّابة" مختلفة — اقرأ جيداً.',
        'احذر الوسطاء — يبيعون مواعيد بـ 200–500€، وكلها احتيال.',
        'استعمل متصفّحاً نظيفاً (Incognito) وتحقّق كل يوم.',
      ],
      tip: 'إذا حصلت على موعد، أكّد فوراً وسجّل تفاصيل الحجز — تغيير البيانات قد يلغي الحجز.' },
    { num: 3, title: 'Schengen vs National Visa', summary: 'فرق حاسم. الأولى قصيرة الإقامة، الثانية للمعيشة. لا تختلط الأوراق.', tag: 'أساسيات',
      bullets: [
        '**Schengen (نوع C):** لمدة 90 يوم كحد أقصى، سياحة/زيارة/تجارة.',
        '**National (نوع D):** أكثر من 90 يوم، دراسة/عمل/لمّ شمل.',
        'تأشيرة Schengen لا تُحوَّل إلى إقامة داخل ألمانيا.',
        'تأشيرة D تعطيك حق الإقامة 3–12 شهراً، ثم تُبدَّل إلى Aufenthaltstitel.',
      ] },
    { num: 4, title: 'إثبات التمويل (Finanzierungsnachweis)', summary: 'ألمانيا تريد ضماناً أنك قادر على العيش دون عبء على الدولة. الطرق المعتمدة قليلة.', tag: 'تمويل',
      bullets: [
        'Sperrkonto: الطريقة الأشهر. 11,904€ حالياً (2024) تُسحب شهرياً (992€).',
        'Verpflichtungserklärung: شخص في ألمانيا يتعهّد بتغطية مصاريفك.',
        'منحة رسمية (DAAD، Erasmus، صندوق ألماني).',
        'عقد عمل بدخل كافٍ (لتأشيرة العمل).',
        'ضمان بنكي من بنك مغربي (نادراً ما يُقبل).',
      ],
      tip: 'مزوّدو Sperrkonto الأوائل: Expatrio, Fintiba, Coracle, Deutsche Bank. السفارة تقبلهم جميعاً.' },
    { num: 5, title: 'التأمين الصحي الإلزامي قبل السفر', summary: 'بدون تأمين، لا تأشيرة. لكن ليس كل تأمين مقبول، وهناك فرق بين سفر قصير وإقامة طويلة.', tag: 'تأمين',
      bullets: [
        'تأمين السفر (Reiseversicherung) مقبول فقط في أول 3 أشهر.',
        'بعدها إلزامي التأمين القانوني (GKV): TK, AOK, Barmer, DAK.',
        'Dr. Walter, Mawista, Care Concept هي التأمينات الانتقالية الأشهر.',
        'الطلاب تحت 30 = GKV. فوق 30 = تأمين خاص.',
        'التأمين الحكومي للعمال ~15.5% من الراتب، نصفها يدفعها صاحب العمل.',
      ] },
    { num: 6, title: 'ترجمة الوثائق — المترجم المحلَّف', summary: 'السفارة لا تقبل ترجمات عادية. الترجمة يجب أن تكون من مترجم معتمد قضائياً.', tag: 'ترجمة',
      bullets: [
        'Vereidigter Übersetzer في ألمانيا، أو مترجم مسجّل لدى السفارة الألمانية في المغرب.',
        'كل ورقة مترجمة يجب أن تحمل ختم المترجم + رقمه.',
        'الأسعار: 25–60 يورو للصفحة حسب التخصّص.',
        'وثائق أساسية للترجمة: الشهادات، عقد الازدياد، السجل العدلي.',
      ],
      tip: 'بعض السفارات تقبل ترجمات معتمدة من المغرب (مترجم محلّف مغربي)، وأخرى لا. اسأل قبل.' },
    { num: 7, title: 'تصديق الوثائق (Apostille / Legalisation)', summary: 'التصديق إثبات دولي لأصل الوثيقة. مطلوب لكل الأوراق الرسمية تقريباً.', tag: 'تصديق',
      bullets: [
        'المغرب انضم لاتفاقية Apostille منذ 2016 — الإجراء صار أسهل.',
        'Apostille يُصدَّر من وزارة الشؤون الخارجية المغربية.',
        'بعض الوثائق تحتاج تصديق إضافي من السفارة الألمانية (Legalisation).',
        'المدة: 1–3 أسابيع في الحالة العادية.',
      ] },
    { num: 8, title: 'Anmeldung — أول إجراء بعد الوصول', summary: 'خلال 14 يوماً من دخول ألمانيا، يجب أن تسجّل عنوانك في Bürgeramt أو Einwohnermeldeamt. لا شيء يعمل بدونها.', tag: 'تسجيل',
      bullets: [
        'احجز موعداً قبل الوصول — أو في اليوم الأول.',
        'الوثائق: جواز السفر + Wohnungsgeberbestätigung من مالك الشقة.',
        'الوثيقة الصادرة (Anmeldebestätigung) تُستعمل لفتح حساب، الهاتف، الضريبة.',
        'تأخير أكثر من 14 يوماً = غرامة تصل 1000€.',
      ],
      tip: 'إن لم تجد موعداً في Bürgeramt، اذهب صباحاً دون موعد إلى فرع صغير خارج المركز — كثيراً يقبلون.' },
    { num: 9, title: 'Steuer-ID و Sozialversicherungsnummer', summary: 'رقمان يرافقانك طوال حياتك في ألمانيا. بدونهما لن تستلم راتباً.', tag: 'أرقام',
      bullets: [
        '**Steuer-ID:** يصل بالبريد خلال أسبوعين من Anmeldung.',
        '**Sozialversicherungsnummer:** يصل من شركة التأمين الصحي الأولى أو Deutsche Rentenversicherung.',
        'احفظهما في مكان آمن — لن تُطلب نسختان أخريان مجاناً بسهولة.',
        'يُطلبان في كل عقد عمل وتأمين جديد.',
      ] },
    { num: 10, title: 'Aufenthaltstitel — بطاقة الإقامة', summary: 'بعد تأشيرتك الأولى، تُحوَّل إقامتك إلى Aufenthaltstitel (بطاقة مثل كارت الهوية). هنا تبدأ حياتك الرسمية.', tag: 'إقامة',
      bullets: [
        'قدّم الطلب في Ausländerbehörde قبل انتهاء تأشيرتك بـ 6 أسابيع.',
        'وثائق: جواز، Anmeldung، إثبات عمل/دراسة، تأمين صحي، إثبات دخل.',
        'الرسم 100 يورو تقريباً.',
        'البطاقة تصل خلال 4–8 أسابيع.',
        'تُجدّد عادة لسنتين أو ثلاث، حسب وضعك.',
      ] },
    { num: 11, title: 'Blaue Karte EU — للمهنيين المؤهّلين', summary: 'الإقامة الأسرع للوصول إلى الجنسية. شروط صارمة لكن المزايا كبيرة جداً.', tag: 'Blue Card',
      bullets: [
        'شرط الراتب 2024: 45,300€/سنة (38,688€ في قطاعات النقص).',
        'شرط الشهادة: جامعية من جامعة معترف بها في Anabin.',
        'تصل لخمس سنوات، قابلة للتجديد.',
        'إقامة دائمة بعد 27 شهراً فقط (21 بمستوى B1 ألمانية).',
        'تسمح بالسفر الحر داخل الاتحاد الأوروبي والعمل به.',
      ] },
    { num: 12, title: 'Chancenkarte (بطاقة الفرص)', summary: 'جديدة منذ 2024. أسهل طريقة للمغاربة للوصول لألمانيا والبحث عن عمل، حتى دون عقد مسبق.', tag: 'جديد',
      bullets: [
        'نظام نقاط (Punktesystem): تعليم + خبرة + عمر + لغة + صلة بألمانيا.',
        '6 نقاط كحد أدنى + شهادة A1 أو إنجليزية B2.',
        'تأشيرة 12 شهراً، تسمح بـ 20 ساعة عمل/أسبوع.',
        'فور إيجاد عمل، تُحوَّل إلى إقامة عمل عادية أو Blaue Karte.',
        'تحتاج إثبات تمويل: ~12,000€ أو عقد عمل جزئي.',
      ] },
    { num: 13, title: 'Arbeitsvisum — تأشيرة العمل الكلاسيكية', summary: 'إن كنت قد وقّعت عقداً قبل السفر، هذه تأشيرتك. البيروقراطية أسرع مما يُشاع.', tag: 'عمل',
      bullets: [
        'وثائق: عقد عمل + شهادة + Zustimmung der Arbeitsagentur (موافقة وكالة العمل).',
        'المدة العادية 2–3 أشهر من تاريخ الموعد.',
        'الرسم 75 يورو.',
        'تُصدَر لمدة العقد، بحد أقصى 4 سنوات.',
        'قابلة للتجديد طالما استمر العقد.',
      ] },
    { num: 14, title: 'لمّ الشمل العائلي (Familienzusammenführung)', summary: 'للزوج/الزوجة أو الأبناء لمن لديه إقامة في ألمانيا. الشروط دقيقة لكن النتيجة واضحة.', tag: 'عائلة',
      bullets: [
        'الزوج/الزوجة: شهادة ألمانية A1 قبل السفر (إلا بعض الاستثناءات).',
        'الأبناء: أقل من 16 سنة دون شروط لغة.',
        'المقيم يجب أن يُثبت دخلاً كافياً + سكناً ملائماً.',
        'المدة: 2–4 أشهر غالباً.',
        'تأشيرة سنوية، تُحوَّل إلى إقامة كاملة بعد الوصول.',
      ] },
    { num: 15, title: 'تجديد رخصة القيادة المغربية', summary: 'الرخصة المغربية صالحة 6 أشهر من Anmeldung. بعدها يجب استبدالها أو اجتياز امتحان.', tag: 'قيادة',
      bullets: [
        'الاستبدال المباشر غير متاح للمغرب — يجب اجتياز امتحان نظري + عملي.',
        'الامتحان متاح بالعربية والإنجليزية في كثير من الولايات.',
        'تكلفة تقريبية: 1500–2500€ شاملة الدروس.',
        'مدة الإعداد: 2–4 أشهر.',
        'Fahrschule (مدرسة قيادة) في منطقتك هي نقطة البداية.',
      ] },
    { num: 16, title: 'Integrationskurs — دورة الاندماج', summary: 'دورة 600–900 ساعة (لغة + ثقافة مدنية). تسرّع الحصول على الإقامة الدائمة بسنة كاملة.', tag: 'اندماج',
      bullets: [
        '600 ساعة ألمانية (A1 → B1) + 100 ساعة "Orientierungskurs".',
        'مدعومة جزئياً أو كلياً من BAMF — الرسم الرمزي 1.95€/ساعة.',
        'الاندماج قد يكون إلزامياً بحكم الإقامة.',
        'شهادة "Zertifikat Integrationskurs" تُعفيك من بعض شروط الجنسية.',
      ] },
    { num: 17, title: 'Niederlassungserlaubnis (الإقامة الدائمة)', summary: 'بعد سنوات معينة تحصل على إقامة دائمة بدون تجديد. هذا السقف الذي يطمح إليه كل مهاجر.', tag: 'دائمة',
      bullets: [
        'القاعدة العامة: 5 سنوات إقامة قانونية + عمل + دفع Rente ≥ 60 شهراً.',
        'Blaue Karte: 27 شهراً فقط (21 بمستوى لغة B1).',
        'الخريجون الألمان: 24 شهراً فقط.',
        'الأزواج الألمان: 3 سنوات.',
        'شرط أساسي: شهادة B1 + دورة Leben in Deutschland.',
      ] },
    { num: 18, title: 'الجنسية الألمانية (Einbürgerung)', summary: 'تغيير 2024 سرّع الجنسية لأغلب المقيمين. 5 سنوات عادة، 3 للمندمجين تماماً.', tag: 'جنسية',
      bullets: [
        'المدة العادية: 5 سنوات (كانت 8) + شهادة B1 + دخل مستقل.',
        'مسار سريع 3 سنوات لمن لديه C1 + مساهمات اجتماعية (تطوّع...).',
        'لم تعد الجنسية المغربية تُفقد — ازدواج الجنسية صار مسموحاً.',
        'اختبار Leben in Deutschland إجباري (33 سؤالاً، سهل بالمذاكرة).',
        'رسم الطلب ~255€.',
      ] },
    { num: 19, title: 'Ausländerbehörde — التعامل مع مكتب الأجانب', summary: 'علاقتك بهذا المكتب ستستمر سنوات. افهم ثقافته قبل زيارتك الأولى.', tag: 'مكتب الأجانب',
      bullets: [
        'المواعيد صعبة — احجز مبكراً جداً (2–3 أشهر قبل).',
        'الموظفون مشغولون — كن دقيقاً ومختصراً في أوراقك.',
        'التحدث بالألمانية ليس إجبارياً لكنه يُسرّع الأمور.',
        'لا تجادل في قانون لا تعرفه — اسأل عن البديل.',
        'احتفظ بكل مراسلة وصل مكتوب.',
      ],
      tip: 'خذ معك دائماً نسخاً إضافية من كل وثيقة. الأصول + نسخة + نسخة احتياطية — ليس إفراطاً.' },
    { num: 20, title: 'أخطاء ورقية قد تكلّفك كل شيء', summary: 'هذه الأخطاء الستة تتكرّر بين المغاربة وتؤدي إلى رفض الإقامة أو الترحيل.', tag: 'تحذيرات',
      bullets: [
        'تخطي Anmeldung: غرامة + عدم القدرة على فتح حساب = توقف كل شيء.',
        'انتهاء تأشيرتك قبل تقديم تجديد Aufenthaltstitel: وضعك يصبح غير قانوني.',
        'تغيير عنوان دون Ummeldung خلال 14 يوماً: غرامة 500€ وتعطيل بريد رسمي.',
        'فقدان Aufenthaltstitel دون الإبلاغ فوراً: رفض تجديد لاحق.',
        'العمل بشكل غير قانوني (أكثر من الحد المسموح كطالب): ترحيل محتمل.',
        'عدم فتح تأمين صحي فور بداية العمل: ديون ضخمة متراكمة.',
      ] },
  ],
}

const fr = {
  metaTitle: 'Visa et papiers officiels pour l\'Allemagne',
  metaDesc: '20 articles sur les types de visas, Anmeldung, Aufenthaltstitel, Blaue Karte, Chancenkarte et tous les papiers.',
  eyebrow: 'Visa & papiers',
  title: 'Visa et papiers officiels',
  subtitle: 'Tout ce qu\'il faut savoir sur les visas allemands et les démarches administratives qui t\'attendent après l\'arrivée.',
  intro: '20 articles analytiques qui couvrent ton parcours administratif : du rendez-vous à l\'ambassade à Rabat jusqu\'à l\'obtention de la nationalité allemande.',
  items: [
    { num: 1, title: 'Les principaux types de visas pour l\'Allemagne', summary: 'Le bon visa détermine ton avenir en Allemagne. Ne dépose aucune demande avant de connaître toutes les options.', tag: 'Introduction',
      bullets: [
        '**Studienvisum :** pour les étudiants admis dans une université.',
        '**Ausbildungsvisum :** pour la formation professionnelle duale.',
        '**Arbeitsvisum :** pour ceux qui ont un contrat de travail confirmé.',
        '**Blaue Karte EU :** pour les professionnels qualifiés avec un salaire défini.',
        '**Jobsuchevisum :** 6 mois pour chercher un emploi (diplômé universitaire).',
        '**Chancenkarte :** carte d\'opportunité — 12 mois avec système à points.',
        '**Familienzusammenführung :** regroupement familial.',
      ] },
    { num: 2, title: 'Prendre rendez-vous à l\'ambassade au Maroc', summary: 'L\'étape la plus difficile en pratique. Les créneaux sont rares et s\'ouvrent d\'un coup. Suis cette méthode pour décrocher un rendez-vous dans un délai raisonnable.', tag: 'Ambassade',
      bullets: [
        'Site officiel de l\'ambassade : maroc.diplo.de — la seule source fiable.',
        'Les créneaux s\'ouvrent généralement entre 8h00 et 10h00 (heure allemande).',
        'Chaque type de visa a un « portail » différent — lis attentivement.',
        'Méfie-toi des intermédiaires — ils vendent des rendez-vous 200–500 €, toutes des arnaques.',
        'Utilise un navigateur propre (Incognito) et vérifie chaque jour.',
      ],
      tip: 'Si tu obtiens un créneau, confirme immédiatement et note les détails — toute modification peut annuler la réservation.' },
    { num: 3, title: 'Schengen vs visa national', summary: 'Une différence décisive. Le premier est court séjour, le second sert à s\'installer. Ne mélange pas les dossiers.', tag: 'Bases',
      bullets: [
        '**Schengen (type C) :** 90 jours max, tourisme/visite/affaires.',
        '**National (type D) :** plus de 90 jours, études/travail/regroupement.',
        'Un visa Schengen ne se transforme pas en titre de séjour en Allemagne.',
        'Le visa D te donne droit de séjour 3–12 mois, puis se convertit en Aufenthaltstitel.',
      ] },
    { num: 4, title: 'Justificatif de financement (Finanzierungsnachweis)', summary: 'L\'Allemagne veut la garantie que tu peux vivre sans dépendre de l\'État. Les méthodes acceptées sont peu nombreuses.', tag: 'Financement',
      bullets: [
        'Sperrkonto : la méthode la plus courante. 11 904 € actuellement (2024), débloqués mensuellement (992 €).',
        'Verpflichtungserklärung : une personne en Allemagne s\'engage à couvrir tes frais.',
        'Bourse officielle (DAAD, Erasmus, fondation allemande).',
        'Contrat de travail avec revenu suffisant (pour le visa de travail).',
        'Garantie bancaire d\'une banque marocaine (rarement acceptée).',
      ],
      tip: 'Principaux prestataires Sperrkonto : Expatrio, Fintiba, Coracle, Deutsche Bank. L\'ambassade les accepte tous.' },
    { num: 5, title: 'Assurance santé obligatoire avant le départ', summary: 'Sans assurance, pas de visa. Mais toutes les assurances ne sont pas acceptées, et il y a une différence entre court séjour et installation.', tag: 'Assurance',
      bullets: [
        'L\'assurance voyage (Reiseversicherung) n\'est acceptée que les 3 premiers mois.',
        'Ensuite, l\'assurance légale (GKV) est obligatoire : TK, AOK, Barmer, DAK.',
        'Dr. Walter, Mawista, Care Concept sont les assurances transitoires les plus connues.',
        'Étudiants de moins de 30 ans = GKV. Plus de 30 = assurance privée.',
        'L\'assurance publique pour les salariés : ~15,5 % du salaire, dont la moitié payée par l\'employeur.',
      ] },
    { num: 6, title: 'Traduction des documents — le traducteur assermenté', summary: 'L\'ambassade n\'accepte pas les traductions ordinaires. La traduction doit être réalisée par un traducteur assermenté.', tag: 'Traduction',
      bullets: [
        'Vereidigter Übersetzer en Allemagne, ou traducteur inscrit auprès de l\'ambassade allemande au Maroc.',
        'Chaque document traduit doit porter le cachet et le numéro du traducteur.',
        'Tarifs : 25–60 € la page selon la spécialité.',
        'Documents essentiels à traduire : diplômes, acte de naissance, casier judiciaire.',
      ],
      tip: 'Certaines ambassades acceptent les traductions certifiées au Maroc (traducteur assermenté marocain), d\'autres non. Renseigne-toi avant.' },
    { num: 7, title: 'Légalisation des documents (Apostille / Legalisation)', summary: 'La légalisation est la preuve internationale de l\'authenticité d\'un document. Exigée pour presque tous les papiers officiels.', tag: 'Légalisation',
      bullets: [
        'Le Maroc a adhéré à la convention Apostille en 2016 — la procédure est devenue plus simple.',
        'L\'Apostille est délivrée par le ministère marocain des Affaires étrangères.',
        'Certains documents requièrent une légalisation supplémentaire de l\'ambassade allemande (Legalisation).',
        'Délai : 1–3 semaines en temps normal.',
      ] },
    { num: 8, title: 'Anmeldung — la première démarche après l\'arrivée', summary: 'Dans les 14 jours suivant ton entrée en Allemagne, tu dois déclarer ton adresse au Bürgeramt ou Einwohnermeldeamt. Rien ne fonctionne sans elle.', tag: 'Déclaration',
      bullets: [
        'Prends rendez-vous avant ton arrivée — ou dès le premier jour.',
        'Documents : passeport + Wohnungsgeberbestätigung du propriétaire.',
        'Le document délivré (Anmeldebestätigung) sert à ouvrir un compte, un téléphone, pour les impôts.',
        'Retard de plus de 14 jours = amende pouvant atteindre 1 000 €.',
      ],
      tip: 'Si tu ne trouves pas de rendez-vous au Bürgeramt, va tôt le matin sans rendez-vous dans une petite antenne hors du centre — souvent ils acceptent.' },
    { num: 9, title: 'Steuer-ID et Sozialversicherungsnummer', summary: 'Deux numéros qui t\'accompagnent toute ta vie en Allemagne. Sans eux, pas de salaire.', tag: 'Numéros',
      bullets: [
        '**Steuer-ID :** arrive par courrier dans les deux semaines suivant l\'Anmeldung.',
        '**Sozialversicherungsnummer :** envoyé par ta première caisse d\'assurance santé ou par la Deutsche Rentenversicherung.',
        'Garde-les en lieu sûr — obtenir deux autres copies gratuites n\'est pas facile.',
        'Ils sont demandés à chaque nouveau contrat de travail et nouvelle assurance.',
      ] },
    { num: 10, title: 'Aufenthaltstitel — le titre de séjour', summary: 'Après ton premier visa, ton séjour est converti en Aufenthaltstitel (une carte type pièce d\'identité). C\'est là que ta vie officielle commence.', tag: 'Séjour',
      bullets: [
        'Dépose la demande à l\'Ausländerbehörde 6 semaines avant l\'expiration de ton visa.',
        'Documents : passeport, Anmeldung, preuve d\'emploi/études, assurance santé, justificatif de revenu.',
        'Frais d\'environ 100 €.',
        'La carte arrive en 4–8 semaines.',
        'Elle se renouvelle généralement pour deux ou trois ans, selon ta situation.',
      ] },
    { num: 11, title: 'Blaue Karte EU — pour les professionnels qualifiés', summary: 'Le titre de séjour le plus rapide pour accéder à la nationalité. Conditions strictes mais avantages très importants.', tag: 'Blue Card',
      bullets: [
        'Seuil de salaire 2024 : 45 300 €/an (38 688 € dans les secteurs en pénurie).',
        'Diplôme exigé : universitaire, d\'une université reconnue dans Anabin.',
        'Valide 5 ans, renouvelable.',
        'Séjour permanent après seulement 27 mois (21 avec un niveau d\'allemand B1).',
        'Permet la libre circulation et le travail dans toute l\'Union européenne.',
      ] },
    { num: 12, title: 'Chancenkarte (carte d\'opportunité)', summary: 'Nouvelle depuis 2024. Le moyen le plus simple pour les Marocains de venir en Allemagne chercher un emploi, même sans contrat préalable.', tag: 'Nouveau',
      bullets: [
        'Système à points (Punktesystem) : formation + expérience + âge + langue + lien avec l\'Allemagne.',
        '6 points minimum + certificat A1 d\'allemand ou B2 d\'anglais.',
        'Visa de 12 mois, autorise 20 heures de travail/semaine.',
        'Dès qu\'un emploi est trouvé, conversion en titre de séjour travail ou Blaue Karte.',
        'Justificatif de financement requis : ~12 000 € ou contrat de travail à temps partiel.',
      ] },
    { num: 13, title: 'Arbeitsvisum — le visa de travail classique', summary: 'Si tu as signé un contrat avant le départ, c\'est ton visa. La bureaucratie est plus rapide que ce qu\'on raconte.', tag: 'Travail',
      bullets: [
        'Documents : contrat de travail + diplôme + Zustimmung der Arbeitsagentur (accord de l\'agence pour l\'emploi).',
        'Délai habituel : 2–3 mois à partir du rendez-vous.',
        'Frais : 75 €.',
        'Délivré pour la durée du contrat, max 4 ans.',
        'Renouvelable tant que le contrat se poursuit.',
      ] },
    { num: 14, title: 'Regroupement familial (Familienzusammenführung)', summary: 'Pour le conjoint ou les enfants de quelqu\'un qui réside en Allemagne. Les conditions sont précises mais le résultat est clair.', tag: 'Famille',
      bullets: [
        'Conjoint(e) : certificat A1 d\'allemand avant le départ (sauf quelques exceptions).',
        'Enfants : moins de 16 ans, sans exigence linguistique.',
        'Le résident doit prouver un revenu suffisant + un logement convenable.',
        'Délai : 2–4 mois le plus souvent.',
        'Visa d\'un an, converti en titre de séjour complet après l\'arrivée.',
      ] },
    { num: 15, title: 'Échange du permis de conduire marocain', summary: 'Le permis marocain est valable 6 mois à partir de l\'Anmeldung. Après, il faut l\'échanger ou passer un examen.', tag: 'Conduite',
      bullets: [
        'L\'échange direct n\'est pas possible pour le Maroc — il faut passer un examen théorique + pratique.',
        'L\'examen est disponible en arabe et en anglais dans beaucoup de Länder.',
        'Coût approximatif : 1 500–2 500 € leçons incluses.',
        'Durée de préparation : 2–4 mois.',
        'Une Fahrschule (auto-école) dans ton quartier est le point de départ.',
      ] },
    { num: 16, title: 'Integrationskurs — cours d\'intégration', summary: 'Cours de 600–900 heures (langue + culture civique). Accélère l\'obtention du séjour permanent d\'une année entière.', tag: 'Intégration',
      bullets: [
        '600 heures d\'allemand (A1 → B1) + 100 heures de « Orientierungskurs ».',
        'Financé partiellement ou totalement par le BAMF — participation symbolique de 1,95 €/heure.',
        'Le cours peut être obligatoire selon ton titre de séjour.',
        'Le certificat « Zertifikat Integrationskurs » dispense de certaines conditions pour la nationalité.',
      ] },
    { num: 17, title: 'Niederlassungserlaubnis (séjour permanent)', summary: 'Après un certain nombre d\'années, tu obtiens un séjour permanent sans renouvellement. C\'est le plafond auquel aspire tout immigré.', tag: 'Permanent',
      bullets: [
        'Règle générale : 5 ans de séjour légal + travail + cotisations Rente ≥ 60 mois.',
        'Blaue Karte : 27 mois seulement (21 avec niveau B1).',
        'Diplômés allemands : 24 mois seulement.',
        'Conjoints d\'Allemands : 3 ans.',
        'Condition clé : certificat B1 + cours Leben in Deutschland.',
      ] },
    { num: 18, title: 'Nationalité allemande (Einbürgerung)', summary: 'La réforme de 2024 a accéléré la nationalité pour la plupart des résidents. 5 ans en général, 3 pour les parfaitement intégrés.', tag: 'Nationalité',
      bullets: [
        'Durée habituelle : 5 ans (contre 8 auparavant) + certificat B1 + revenus autonomes.',
        'Voie rapide de 3 ans pour ceux qui ont un C1 + engagements sociaux (bénévolat…).',
        'La nationalité marocaine n\'est plus perdue — la double nationalité est désormais autorisée.',
        'Test Leben in Deutschland obligatoire (33 questions, facile avec un peu de révision).',
        'Frais de demande : ~255 €.',
      ] },
    { num: 19, title: 'Ausländerbehörde — gérer le bureau des étrangers', summary: 'Ta relation avec ce bureau durera des années. Comprends sa culture avant ta première visite.', tag: 'Bureau des étrangers',
      bullets: [
        'Les rendez-vous sont difficiles — réserve très tôt (2–3 mois à l\'avance).',
        'Les agents sont débordés — sois précis et concis dans tes papiers.',
        'Parler allemand n\'est pas obligatoire mais ça accélère les choses.',
        'Ne discute pas d\'une loi que tu ne connais pas — demande l\'alternative.',
        'Garde toute correspondance et tout reçu écrit.',
      ],
      tip: 'Emporte toujours des copies supplémentaires de chaque document. Originaux + copie + copie de secours — ce n\'est pas trop.' },
    { num: 20, title: 'Erreurs administratives qui peuvent tout te coûter', summary: 'Ces six erreurs reviennent souvent chez les Marocains et mènent au refus de séjour ou à l\'expulsion.', tag: 'Avertissements',
      bullets: [
        'Sauter l\'Anmeldung : amende + impossibilité d\'ouvrir un compte = tout s\'arrête.',
        'Laisser ton visa expirer avant de déposer le renouvellement de l\'Aufenthaltstitel : ta situation devient irrégulière.',
        'Changer d\'adresse sans Ummeldung dans les 14 jours : amende de 500 € et blocage du courrier officiel.',
        'Perdre ton Aufenthaltstitel sans signaler immédiatement : refus de renouvellement ultérieur.',
        'Travailler illégalement (au-delà de la limite autorisée pour un étudiant) : risque d\'expulsion.',
        'Ne pas ouvrir une assurance santé dès le début du travail : dettes énormes accumulées.',
      ] },
  ],
}

const en = {
  metaTitle: 'Visa and official paperwork for Germany',
  metaDesc: '20 articles on visa types, Anmeldung, Aufenthaltstitel, Blaue Karte, Chancenkarte and every piece of paperwork.',
  eyebrow: 'Visa & paperwork',
  title: 'Visa and official paperwork',
  subtitle: 'Everything you need to know about German visas and the bureaucracy waiting for you after arrival.',
  intro: '20 analytical articles covering your paperwork journey: from booking your embassy appointment in Rabat to obtaining German citizenship.',
  items: [
    { num: 1, title: 'The main visa types for Germany', summary: 'The right visa defines your future in Germany. Do not apply for any type before understanding the alternatives.', tag: 'Introduction',
      bullets: [
        '**Studienvisum:** for students admitted to a university.',
        '**Ausbildungsvisum:** for dual vocational training.',
        '**Arbeitsvisum:** for anyone with a confirmed work contract.',
        '**Blaue Karte EU:** for qualified professionals meeting a salary threshold.',
        '**Jobsuchevisum:** 6 months to search for a job (university graduate).',
        '**Chancenkarte:** opportunity card — 12 months on a points system.',
        '**Familienzusammenführung:** family reunification.',
      ] },
    { num: 2, title: 'Booking the embassy appointment in Morocco', summary: 'Practically the hardest step. Slots are rare and open without warning. Follow this method to secure an appointment in a reasonable time.', tag: 'Embassy',
      bullets: [
        'Official embassy site: maroc.diplo.de — the only reliable source.',
        'Slots usually open between 8:00 and 10:00 (German time).',
        'Each visa type has a different "portal" — read carefully.',
        'Beware of brokers — they sell appointments for 200–500 €, all scams.',
        'Use a clean browser (Incognito) and check every day.',
      ],
      tip: 'If you get a slot, confirm immediately and record the booking details — changing any data can cancel the booking.' },
    { num: 3, title: 'Schengen vs national visa', summary: 'A decisive difference. The first is short-stay, the second is for living. Do not mix up the files.', tag: 'Basics',
      bullets: [
        '**Schengen (type C):** up to 90 days, tourism/visit/business.',
        '**National (type D):** more than 90 days, study/work/reunification.',
        'A Schengen visa cannot be converted into residency inside Germany.',
        'A D visa grants you 3–12 months of stay, then converts into an Aufenthaltstitel.',
      ] },
    { num: 4, title: 'Proof of funds (Finanzierungsnachweis)', summary: 'Germany wants a guarantee that you can live without becoming a burden on the state. The accepted methods are few.', tag: 'Funds',
      bullets: [
        'Sperrkonto: the most common method. Currently 11,904 € (2024), released monthly (992 €).',
        'Verpflichtungserklärung: a person in Germany commits to covering your expenses.',
        'Official scholarship (DAAD, Erasmus, a German foundation).',
        'Work contract with sufficient income (for a work visa).',
        'Bank guarantee from a Moroccan bank (rarely accepted).',
      ],
      tip: 'Leading Sperrkonto providers: Expatrio, Fintiba, Coracle, Deutsche Bank. The embassy accepts them all.' },
    { num: 5, title: 'Mandatory health insurance before travel', summary: 'No insurance, no visa. But not every insurance is accepted, and there is a difference between short travel and long-term stay.', tag: 'Insurance',
      bullets: [
        'Travel insurance (Reiseversicherung) is accepted only for the first 3 months.',
        'After that, statutory insurance (GKV) is compulsory: TK, AOK, Barmer, DAK.',
        'Dr. Walter, Mawista, Care Concept are the most popular transitional insurers.',
        'Students under 30 = GKV. Over 30 = private insurance.',
        'State insurance for employees: ~15.5% of salary, half paid by the employer.',
      ] },
    { num: 6, title: 'Document translation — the sworn translator', summary: 'The embassy does not accept ordinary translations. The translation must be produced by a judicially certified translator.', tag: 'Translation',
      bullets: [
        'Vereidigter Übersetzer in Germany, or a translator registered with the German embassy in Morocco.',
        'Every translated paper must bear the translator\'s stamp and number.',
        'Rates: 25–60 € per page depending on specialisation.',
        'Essential documents to translate: diplomas, birth certificate, criminal record.',
      ],
      tip: 'Some embassies accept translations certified in Morocco (Moroccan sworn translator), others do not. Ask beforehand.' },
    { num: 7, title: 'Document legalisation (Apostille / Legalisation)', summary: 'Legalisation is the international proof of a document\'s authenticity. Required for nearly every official paper.', tag: 'Legalisation',
      bullets: [
        'Morocco joined the Apostille convention in 2016 — the procedure has become easier.',
        'The Apostille is issued by the Moroccan Ministry of Foreign Affairs.',
        'Some documents need additional legalisation from the German embassy (Legalisation).',
        'Turnaround: 1–3 weeks in normal cases.',
      ] },
    { num: 8, title: 'Anmeldung — the first step after arrival', summary: 'Within 14 days of entering Germany, you must register your address at the Bürgeramt or Einwohnermeldeamt. Nothing works without it.', tag: 'Registration',
      bullets: [
        'Book an appointment before arrival — or on your first day.',
        'Documents: passport + Wohnungsgeberbestätigung from your landlord.',
        'The resulting paper (Anmeldebestätigung) is used to open a bank account, a phone line, for taxes.',
        'Delay of more than 14 days = fines of up to 1,000 €.',
      ],
      tip: 'If you cannot find a Bürgeramt slot, go in early without an appointment to a small branch outside the centre — they often accept you.' },
    { num: 9, title: 'Steuer-ID and Sozialversicherungsnummer', summary: 'Two numbers that follow you throughout your life in Germany. Without them you will not receive a salary.', tag: 'Numbers',
      bullets: [
        '**Steuer-ID:** arrives by post within two weeks of the Anmeldung.',
        '**Sozialversicherungsnummer:** sent by your first health insurance provider or by Deutsche Rentenversicherung.',
        'Keep them somewhere safe — getting two more free copies is not easy.',
        'They are requested for every new work contract and every new insurance.',
      ] },
    { num: 10, title: 'Aufenthaltstitel — the residence permit', summary: 'After your first visa, your stay is converted into an Aufenthaltstitel (an ID-card-style residence card). This is where your official life begins.', tag: 'Residence',
      bullets: [
        'Submit the application to the Ausländerbehörde 6 weeks before your visa expires.',
        'Documents: passport, Anmeldung, proof of work/studies, health insurance, proof of income.',
        'Fee: around 100 €.',
        'The card arrives in 4–8 weeks.',
        'It is usually renewed for two or three years depending on your situation.',
      ] },
    { num: 11, title: 'Blaue Karte EU — for qualified professionals', summary: 'The fastest track residence permit to reach citizenship. Strict conditions but very significant benefits.', tag: 'Blue Card',
      bullets: [
        '2024 salary threshold: 45,300 €/year (38,688 € in shortage occupations).',
        'Degree requirement: a university degree from an institution recognised in Anabin.',
        'Valid for five years, renewable.',
        'Permanent residency after just 27 months (21 with German B1 level).',
        'Allows free travel and work throughout the European Union.',
      ] },
    { num: 12, title: 'Chancenkarte (opportunity card)', summary: 'New since 2024. The easiest way for Moroccans to come to Germany and look for work, even without a prior contract.', tag: 'New',
      bullets: [
        'Points system (Punktesystem): education + experience + age + language + connection to Germany.',
        '6 points minimum + A1 German certificate or B2 English.',
        '12-month visa, allows 20 hours of work/week.',
        'As soon as you find work, it converts into a regular work residence permit or Blaue Karte.',
        'Proof of funds required: ~12,000 € or a part-time work contract.',
      ] },
    { num: 13, title: 'Arbeitsvisum — the classic work visa', summary: 'If you signed a contract before travelling, this is your visa. The bureaucracy is faster than people say.', tag: 'Work',
      bullets: [
        'Documents: work contract + degree + Zustimmung der Arbeitsagentur (employment agency approval).',
        'Usual processing: 2–3 months from the appointment date.',
        'Fee: 75 €.',
        'Issued for the duration of the contract, up to 4 years max.',
        'Renewable as long as the contract continues.',
      ] },
    { num: 14, title: 'Family reunification (Familienzusammenführung)', summary: 'For the spouse or children of someone already residing in Germany. The conditions are precise but the outcome is clear.', tag: 'Family',
      bullets: [
        'Spouse: A1 German certificate before travel (with a few exceptions).',
        'Children: under 16 years old, no language requirement.',
        'The resident must prove sufficient income + adequate housing.',
        'Processing: 2–4 months in most cases.',
        'One-year visa, converted into a full residence permit after arrival.',
      ] },
    { num: 15, title: 'Renewing the Moroccan driving licence', summary: 'The Moroccan licence is valid for 6 months from the Anmeldung. After that you must exchange it or pass an exam.', tag: 'Driving',
      bullets: [
        'Direct exchange is not available for Morocco — you must pass a theoretical + practical exam.',
        'The exam is available in Arabic and English in many Länder.',
        'Approximate cost: 1,500–2,500 € including lessons.',
        'Preparation time: 2–4 months.',
        'A Fahrschule (driving school) in your area is the starting point.',
      ] },
    { num: 16, title: 'Integrationskurs — integration course', summary: '600–900-hour course (language + civic culture). Speeds up permanent residency by a full year.', tag: 'Integration',
      bullets: [
        '600 hours of German (A1 → B1) + 100 hours of "Orientierungskurs".',
        'Partially or fully funded by BAMF — a symbolic fee of 1.95 €/hour.',
        'The course can be compulsory depending on your residence permit.',
        'The "Zertifikat Integrationskurs" waives some requirements for citizenship.',
      ] },
    { num: 17, title: 'Niederlassungserlaubnis (permanent residency)', summary: 'After a certain number of years you obtain permanent residency without renewal. This is the ceiling every immigrant aspires to.', tag: 'Permanent',
      bullets: [
        'General rule: 5 years of legal residence + employment + Rente contributions ≥ 60 months.',
        'Blaue Karte: only 27 months (21 with B1 language level).',
        'German graduates: only 24 months.',
        'Spouses of Germans: 3 years.',
        'Key requirement: B1 certificate + Leben in Deutschland course.',
      ] },
    { num: 18, title: 'German citizenship (Einbürgerung)', summary: 'The 2024 reform accelerated citizenship for most residents. 5 years normally, 3 for the fully integrated.', tag: 'Citizenship',
      bullets: [
        'Usual duration: 5 years (was 8) + B1 certificate + independent income.',
        'Fast track of 3 years for those with C1 + social contributions (volunteering…).',
        'Moroccan citizenship is no longer lost — dual nationality is now permitted.',
        'Leben in Deutschland test is mandatory (33 questions, easy with some study).',
        'Application fee: ~255 €.',
      ] },
    { num: 19, title: 'Ausländerbehörde — dealing with the foreigners\' office', summary: 'Your relationship with this office will last for years. Understand its culture before your first visit.', tag: 'Foreigners\' office',
      bullets: [
        'Appointments are hard — book very early (2–3 months in advance).',
        'Staff are overloaded — be precise and concise with your paperwork.',
        'Speaking German is not mandatory but speeds things up.',
        'Do not argue about a law you do not know — ask for the alternative.',
        'Keep every letter and every written receipt.',
      ],
      tip: 'Always bring extra copies of every document. Originals + copy + backup copy — it is not overkill.' },
    { num: 20, title: 'Paperwork mistakes that can cost you everything', summary: 'These six mistakes recur among Moroccans and lead to residency refusal or deportation.', tag: 'Warnings',
      bullets: [
        'Skipping the Anmeldung: fine + inability to open a bank account = everything stops.',
        'Letting your visa expire before filing the Aufenthaltstitel renewal: your status becomes irregular.',
        'Changing address without Ummeldung within 14 days: 500 € fine and blocked official mail.',
        'Losing the Aufenthaltstitel without reporting immediately: later renewal refusal.',
        'Working illegally (beyond the student limit): possible deportation.',
        'Not opening health insurance as soon as work starts: huge accumulated debts.',
      ] },
  ],
}

const de = {
  metaTitle: 'Visum und offizielle Papiere für Deutschland',
  metaDesc: '20 Artikel zu Visaarten, Anmeldung, Aufenthaltstitel, Blaue Karte, Chancenkarte und allen Papieren.',
  eyebrow: 'Visum & Papiere',
  title: 'Visum und offizielle Papiere',
  subtitle: 'Alles, was du über deutsche Visa und die Behördengänge nach deiner Ankunft wissen musst.',
  intro: '20 fundierte Artikel, die deinen Papierweg begleiten: vom Botschaftstermin in Rabat bis zur deutschen Staatsangehörigkeit.',
  items: [
    { num: 1, title: 'Die wichtigsten Visaarten für Deutschland', summary: 'Das richtige Visum bestimmt deine Zukunft in Deutschland. Stell keinen Antrag, bevor du die Alternativen kennst.', tag: 'Einführung',
      bullets: [
        '**Studienvisum:** für an einer Hochschule zugelassene Studierende.',
        '**Ausbildungsvisum:** für die duale Berufsausbildung.',
        '**Arbeitsvisum:** für Personen mit einem bestätigten Arbeitsvertrag.',
        '**Blaue Karte EU:** für qualifizierte Fachkräfte ab einem festgelegten Gehalt.',
        '**Jobsuchevisum:** 6 Monate zur Jobsuche (Hochschulabsolvent).',
        '**Chancenkarte:** 12 Monate nach Punktesystem.',
        '**Familienzusammenführung:** Familiennachzug.',
      ] },
    { num: 2, title: 'Botschaftstermin in Marokko buchen', summary: 'Praktisch der schwierigste Schritt. Termine sind rar und öffnen plötzlich. Folge dieser Methode, um in vernünftiger Zeit einen Termin zu bekommen.', tag: 'Botschaft',
      bullets: [
        'Offizielle Seite der Botschaft: maroc.diplo.de — die einzige verlässliche Quelle.',
        'Termine öffnen meist zwischen 8:00 und 10:00 Uhr (deutsche Zeit).',
        'Jede Visumart hat ein eigenes „Portal" — lies genau.',
        'Vorsicht vor Vermittlern — sie verkaufen Termine für 200–500 €, alles Betrug.',
        'Nutze einen sauberen Browser (Inkognito) und prüfe täglich.',
      ],
      tip: 'Wenn du einen Termin bekommst, bestätige sofort und notiere die Buchungsdaten — eine Datenänderung kann die Buchung stornieren.' },
    { num: 3, title: 'Schengen- vs. nationales Visum', summary: 'Ein entscheidender Unterschied. Das erste ist Kurzaufenthalt, das zweite für das Leben in Deutschland. Verwechsle die Unterlagen nicht.', tag: 'Grundlagen',
      bullets: [
        '**Schengen-Visum (Typ C):** bis zu 90 Tage, Tourismus/Besuch/Geschäft.',
        '**Nationales Visum (Typ D):** über 90 Tage, Studium/Arbeit/Familiennachzug.',
        'Ein Schengen-Visum lässt sich in Deutschland nicht in einen Aufenthaltstitel umwandeln.',
        'Ein D-Visum gibt dir 3–12 Monate Aufenthalt und wird danach in einen Aufenthaltstitel umgewandelt.',
      ] },
    { num: 4, title: 'Finanzierungsnachweis', summary: 'Deutschland will die Garantie, dass du leben kannst, ohne dem Staat zur Last zu fallen. Die anerkannten Wege sind wenige.', tag: 'Finanzen',
      bullets: [
        'Sperrkonto: die häufigste Methode. Aktuell 11.904 € (2024), monatlich ausgezahlt (992 €).',
        'Verpflichtungserklärung: eine Person in Deutschland verpflichtet sich, deine Kosten zu übernehmen.',
        'Offizielles Stipendium (DAAD, Erasmus, deutsche Stiftung).',
        'Arbeitsvertrag mit ausreichendem Einkommen (für das Arbeitsvisum).',
        'Bankbürgschaft einer marokkanischen Bank (selten akzeptiert).',
      ],
      tip: 'Führende Sperrkonto-Anbieter: Expatrio, Fintiba, Coracle, Deutsche Bank. Die Botschaft akzeptiert alle.' },
    { num: 5, title: 'Pflicht-Krankenversicherung vor der Einreise', summary: 'Ohne Versicherung kein Visum. Aber nicht jede Versicherung wird akzeptiert, und es gibt einen Unterschied zwischen Kurzreise und langem Aufenthalt.', tag: 'Versicherung',
      bullets: [
        'Reiseversicherung wird nur für die ersten 3 Monate akzeptiert.',
        'Danach ist die gesetzliche Krankenversicherung (GKV) Pflicht: TK, AOK, Barmer, DAK.',
        'Dr. Walter, Mawista, Care Concept sind die bekanntesten Übergangsversicherungen.',
        'Studierende unter 30 = GKV. Über 30 = private Krankenversicherung.',
        'Gesetzliche Krankenversicherung für Arbeitnehmer: ~15,5 % vom Gehalt, Hälfte vom Arbeitgeber.',
      ] },
    { num: 6, title: 'Dokumentenübersetzung — der vereidigte Übersetzer', summary: 'Die Botschaft akzeptiert keine gewöhnlichen Übersetzungen. Die Übersetzung muss von einem gerichtlich anerkannten Übersetzer stammen.', tag: 'Übersetzung',
      bullets: [
        'Vereidigter Übersetzer in Deutschland oder ein bei der deutschen Botschaft in Marokko registrierter Übersetzer.',
        'Jedes übersetzte Dokument muss den Stempel und die Nummer des Übersetzers tragen.',
        'Preise: 25–60 € pro Seite, je nach Fachgebiet.',
        'Wichtige zu übersetzende Dokumente: Zeugnisse, Geburtsurkunde, Führungszeugnis.',
      ],
      tip: 'Manche Botschaften akzeptieren in Marokko beglaubigte Übersetzungen (marokkanischer vereidigter Übersetzer), andere nicht. Frage vorher nach.' },
    { num: 7, title: 'Beglaubigung der Dokumente (Apostille / Legalisation)', summary: 'Die Beglaubigung ist der internationale Nachweis der Echtheit eines Dokuments. Für fast alle offiziellen Papiere erforderlich.', tag: 'Beglaubigung',
      bullets: [
        'Marokko ist seit 2016 dem Apostille-Übereinkommen beigetreten — das Verfahren ist einfacher geworden.',
        'Die Apostille wird vom marokkanischen Außenministerium ausgestellt.',
        'Manche Dokumente benötigen zusätzlich eine Legalisation der deutschen Botschaft.',
        'Dauer: 1–3 Wochen im Normalfall.',
      ] },
    { num: 8, title: 'Anmeldung — der erste Schritt nach der Ankunft', summary: 'Innerhalb von 14 Tagen nach Einreise musst du deine Adresse im Bürgeramt oder Einwohnermeldeamt anmelden. Ohne sie geht nichts.', tag: 'Anmeldung',
      bullets: [
        'Buche den Termin vor der Ankunft — oder am ersten Tag.',
        'Dokumente: Reisepass + Wohnungsgeberbestätigung vom Vermieter.',
        'Die Anmeldebestätigung brauchst du fürs Konto, den Handyvertrag und die Steuer.',
        'Verzug über 14 Tage = Bußgeld bis 1.000 €.',
      ],
      tip: 'Findest du keinen Termin im Bürgeramt, geh morgens ohne Termin zu einer kleinen Außenstelle — oft wirst du angenommen.' },
    { num: 9, title: 'Steuer-ID und Sozialversicherungsnummer', summary: 'Zwei Nummern, die dich dein ganzes Leben in Deutschland begleiten. Ohne sie bekommst du kein Gehalt.', tag: 'Nummern',
      bullets: [
        '**Steuer-ID:** kommt innerhalb von zwei Wochen nach der Anmeldung per Post.',
        '**Sozialversicherungsnummer:** kommt von deiner ersten Krankenkasse oder von der Deutschen Rentenversicherung.',
        'Bewahre sie sicher auf — zwei weitere Gratiskopien zu bekommen ist nicht einfach.',
        'Sie werden bei jedem neuen Arbeitsvertrag und jeder neuen Versicherung verlangt.',
      ] },
    { num: 10, title: 'Aufenthaltstitel — die Aufenthaltskarte', summary: 'Nach deinem ersten Visum wird dein Aufenthalt in einen Aufenthaltstitel umgewandelt (eine Karte wie ein Ausweis). Hier beginnt dein offizielles Leben.', tag: 'Aufenthalt',
      bullets: [
        'Stelle den Antrag bei der Ausländerbehörde 6 Wochen vor Ablauf deines Visums.',
        'Dokumente: Reisepass, Anmeldung, Arbeits-/Studiennachweis, Krankenversicherung, Einkommensnachweis.',
        'Gebühr: rund 100 €.',
        'Die Karte kommt in 4–8 Wochen.',
        'Sie wird meist für zwei oder drei Jahre verlängert, je nach Situation.',
      ] },
    { num: 11, title: 'Blaue Karte EU — für qualifizierte Fachkräfte', summary: 'Der schnellste Aufenthaltstitel auf dem Weg zur Staatsangehörigkeit. Strenge Bedingungen, aber sehr große Vorteile.', tag: 'Blue Card',
      bullets: [
        'Gehaltsgrenze 2024: 45.300 €/Jahr (38.688 € in Mangelberufen).',
        'Abschluss: Hochschulabschluss einer in Anabin anerkannten Hochschule.',
        'Gültigkeit: fünf Jahre, verlängerbar.',
        'Niederlassungserlaubnis schon nach 27 Monaten (21 mit Deutschkenntnissen B1).',
        'Erlaubt freie Bewegung und Arbeit in der gesamten EU.',
      ] },
    { num: 12, title: 'Chancenkarte', summary: 'Seit 2024 neu. Der einfachste Weg für Marokkaner, nach Deutschland zu kommen und einen Job zu suchen — auch ohne Vorvertrag.', tag: 'Neu',
      bullets: [
        'Punktesystem: Bildung + Erfahrung + Alter + Sprache + Deutschlandbezug.',
        'Mindestens 6 Punkte + Deutsch-A1-Zertifikat oder Englisch B2.',
        '12-Monats-Visum, erlaubt 20 Stunden Arbeit/Woche.',
        'Sobald du einen Job findest, Umwandlung in einen regulären Arbeitstitel oder Blaue Karte.',
        'Finanzierungsnachweis erforderlich: ~12.000 € oder Teilzeitarbeitsvertrag.',
      ] },
    { num: 13, title: 'Arbeitsvisum — das klassische Arbeitsvisum', summary: 'Wenn du schon vor der Ausreise einen Vertrag unterschrieben hast, ist das dein Visum. Die Bürokratie ist schneller, als man sagt.', tag: 'Arbeit',
      bullets: [
        'Dokumente: Arbeitsvertrag + Abschluss + Zustimmung der Arbeitsagentur.',
        'Übliche Dauer: 2–3 Monate ab Termindatum.',
        'Gebühr: 75 €.',
        'Gültig für die Vertragsdauer, maximal 4 Jahre.',
        'Verlängerbar, solange der Vertrag weiterläuft.',
      ] },
    { num: 14, title: 'Familiennachzug (Familienzusammenführung)', summary: 'Für Ehepartner oder Kinder einer Person mit Aufenthalt in Deutschland. Die Bedingungen sind präzise, das Ergebnis klar.', tag: 'Familie',
      bullets: [
        'Ehepartner: Deutschkenntnisse A1 vor der Ausreise (mit wenigen Ausnahmen).',
        'Kinder: unter 16 Jahren, keine Sprachvoraussetzung.',
        'Der Aufenthaltsberechtigte muss ausreichendes Einkommen + angemessenen Wohnraum nachweisen.',
        'Dauer: meist 2–4 Monate.',
        'Einjähriges Visum, nach Ankunft in einen vollen Aufenthaltstitel umgewandelt.',
      ] },
    { num: 15, title: 'Umschreibung des marokkanischen Führerscheins', summary: 'Der marokkanische Führerschein ist 6 Monate ab Anmeldung gültig. Danach musst du ihn umschreiben oder eine Prüfung ablegen.', tag: 'Fahren',
      bullets: [
        'Direkte Umschreibung für Marokko nicht möglich — Theorie- + Praxisprüfung nötig.',
        'Die Prüfung ist in vielen Bundesländern auf Arabisch und Englisch verfügbar.',
        'Ungefähre Kosten: 1.500–2.500 € inklusive Unterricht.',
        'Vorbereitungszeit: 2–4 Monate.',
        'Eine Fahrschule in deiner Gegend ist der Startpunkt.',
      ] },
    { num: 16, title: 'Integrationskurs', summary: '600–900-Stunden-Kurs (Sprache + staatsbürgerliche Bildung). Beschleunigt die Niederlassungserlaubnis um ein ganzes Jahr.', tag: 'Integration',
      bullets: [
        '600 Stunden Deutsch (A1 → B1) + 100 Stunden „Orientierungskurs".',
        'Teilweise oder ganz vom BAMF gefördert — symbolische Gebühr 1,95 €/Stunde.',
        'Je nach Aufenthaltstitel kann die Teilnahme verpflichtend sein.',
        'Das „Zertifikat Integrationskurs" befreit von einigen Voraussetzungen für die Einbürgerung.',
      ] },
    { num: 17, title: 'Niederlassungserlaubnis (unbefristeter Aufenthalt)', summary: 'Nach einer bestimmten Anzahl von Jahren bekommst du einen unbefristeten Aufenthaltstitel. Das ist das Ziel, das jeder Eingewanderte anstrebt.', tag: 'Unbefristet',
      bullets: [
        'Grundregel: 5 Jahre legaler Aufenthalt + Arbeit + Rentenbeiträge ≥ 60 Monate.',
        'Blaue Karte: nur 27 Monate (21 mit Sprachniveau B1).',
        'Deutsche Hochschulabsolventen: nur 24 Monate.',
        'Ehepartner von Deutschen: 3 Jahre.',
        'Kernvoraussetzung: B1-Zertifikat + Kurs Leben in Deutschland.',
      ] },
    { num: 18, title: 'Deutsche Staatsangehörigkeit (Einbürgerung)', summary: 'Die Reform 2024 hat die Einbürgerung für die meisten Einwohner beschleunigt. 5 Jahre im Normalfall, 3 für voll Integrierte.', tag: 'Staatsangehörigkeit',
      bullets: [
        'Übliche Dauer: 5 Jahre (vorher 8) + B1-Zertifikat + eigenständiges Einkommen.',
        '3-Jahres-Schnellweg für Personen mit C1 + sozialem Engagement (Ehrenamt …).',
        'Die marokkanische Staatsangehörigkeit geht nicht mehr verloren — die doppelte Staatsangehörigkeit ist jetzt erlaubt.',
        'Test „Leben in Deutschland" Pflicht (33 Fragen, mit Vorbereitung leicht).',
        'Antragsgebühr: ~255 €.',
      ] },
    { num: 19, title: 'Ausländerbehörde — der Umgang mit der Behörde', summary: 'Deine Beziehung zu dieser Behörde wird Jahre dauern. Versteh ihre Kultur vor deinem ersten Besuch.', tag: 'Ausländerbehörde',
      bullets: [
        'Termine sind schwer — buche sehr früh (2–3 Monate vorher).',
        'Die Mitarbeiter sind überlastet — sei präzise und knapp mit deinen Unterlagen.',
        'Deutsch zu sprechen ist nicht Pflicht, beschleunigt aber alles.',
        'Diskutiere nicht über ein Gesetz, das du nicht kennst — frag nach der Alternative.',
        'Bewahre jeden Brief und jede schriftliche Quittung auf.',
      ],
      tip: 'Nimm immer zusätzliche Kopien jedes Dokuments mit. Originale + Kopie + Sicherungskopie — das ist nicht zu viel.' },
    { num: 20, title: 'Papierfehler, die dich alles kosten können', summary: 'Diese sechs Fehler kommen bei Marokkanern häufig vor und führen zu Ablehnung des Aufenthalts oder Abschiebung.', tag: 'Warnungen',
      bullets: [
        'Anmeldung versäumen: Bußgeld + kein Konto möglich = alles steht still.',
        'Visum läuft ab, bevor du die Verlängerung des Aufenthaltstitels beantragst: dein Status wird illegal.',
        'Adresswechsel ohne Ummeldung binnen 14 Tagen: 500 € Bußgeld und blockierte amtliche Post.',
        'Verlust des Aufenthaltstitels ohne sofortige Meldung: spätere Ablehnung der Verlängerung.',
        'Illegale Arbeit (über das zulässige Studentenlimit hinaus): mögliche Abschiebung.',
        'Keine Krankenversicherung direkt bei Arbeitsbeginn: riesige aufgelaufene Schulden.',
      ] },
  ],
}

const byLoc = { ar, fr, en, de }

// Ensure `common.tipLabel` key exists
const tipLabel = { ar: 'نصيحة', fr: 'Astuce', en: 'Tip', de: 'Tipp' }

for (const loc of ['ar', 'fr', 'en', 'de']) {
  const p = path.join(__dirname, '..', 'messages', `${loc}.json`)
  const j = JSON.parse(fs.readFileSync(p, 'utf8'))
  j.static = j.static || {}
  j.static.visa = byLoc[loc]
  j.common = j.common || {}
  j.common.tipLabel = tipLabel[loc]
  fs.writeFileSync(p, JSON.stringify(j, null, 2) + '\n', 'utf8')
  console.log(`✓ ${loc}.json`)
}
