const fs = require('fs')
const path = require('path')

const ns = {
  ar: {
    dashboard: 'لوحة التحكم',
    login: 'دخول',
    password: 'كلمة المرور',
    site: 'الموقع',
    logout: 'خروج',
    addArticleHeading: 'إضافة مقال جديد',
    titlePh: 'العنوان',
    summaryPh: 'الملخص',
    contentPh: 'المحتوى الكامل',
    selectCategory: 'اختر الفئة',
    imageLabel: 'صورة المقال (اختياري)',
    imageEditLabel: 'صورة المقال (اتركها فارغة للإبقاء على الصورة الحالية)',
    featured: '⭐ مقال مميز (يظهر في أعلى الصفحة الرئيسية)',
    publishArticle: 'نشر المقال',
    articlesHeading: 'المقالات ({n})',
    edit: 'تعديل',
    del: 'حذف',
    listingsHeading: 'الإعلانات ({n})',
    listingsEmpty: 'لا توجد إعلانات.',
    view: 'عرض',
    editArticleTitle: 'تعديل المقال',
    backToDashboard: 'العودة للوحة التحكم',
    save: 'حفظ التعديلات',
  },
  fr: {
    dashboard: 'Tableau de bord',
    login: 'Connexion',
    password: 'Mot de passe',
    site: 'Site',
    logout: 'Déconnexion',
    addArticleHeading: 'Ajouter un nouvel article',
    titlePh: 'Titre',
    summaryPh: 'Résumé',
    contentPh: 'Contenu complet',
    selectCategory: 'Choisir la catégorie',
    imageLabel: 'Image de l\'article (facultatif)',
    imageEditLabel: 'Image de l\'article (laisser vide pour conserver l\'image actuelle)',
    featured: '⭐ Article à la une (affiché en haut de la page d\'accueil)',
    publishArticle: 'Publier l\'article',
    articlesHeading: 'Articles ({n})',
    edit: 'Modifier',
    del: 'Supprimer',
    listingsHeading: 'Annonces ({n})',
    listingsEmpty: 'Aucune annonce.',
    view: 'Voir',
    editArticleTitle: 'Modifier l\'article',
    backToDashboard: 'Retour au tableau de bord',
    save: 'Enregistrer les modifications',
  },
  en: {
    dashboard: 'Dashboard',
    login: 'Log in',
    password: 'Password',
    site: 'Site',
    logout: 'Log out',
    addArticleHeading: 'Add new article',
    titlePh: 'Title',
    summaryPh: 'Summary',
    contentPh: 'Full content',
    selectCategory: 'Select category',
    imageLabel: 'Article image (optional)',
    imageEditLabel: 'Article image (leave empty to keep current image)',
    featured: '⭐ Featured article (shows at top of homepage)',
    publishArticle: 'Publish article',
    articlesHeading: 'Articles ({n})',
    edit: 'Edit',
    del: 'Delete',
    listingsHeading: 'Listings ({n})',
    listingsEmpty: 'No listings.',
    view: 'View',
    editArticleTitle: 'Edit article',
    backToDashboard: 'Back to dashboard',
    save: 'Save changes',
  },
  de: {
    dashboard: 'Dashboard',
    login: 'Anmelden',
    password: 'Passwort',
    site: 'Website',
    logout: 'Abmelden',
    addArticleHeading: 'Neuen Artikel hinzufügen',
    titlePh: 'Titel',
    summaryPh: 'Zusammenfassung',
    contentPh: 'Vollständiger Inhalt',
    selectCategory: 'Kategorie auswählen',
    imageLabel: 'Artikelbild (optional)',
    imageEditLabel: 'Artikelbild (leer lassen, um aktuelles Bild zu behalten)',
    featured: '⭐ Hervorgehobener Artikel (erscheint oben auf der Startseite)',
    publishArticle: 'Artikel veröffentlichen',
    articlesHeading: 'Artikel ({n})',
    edit: 'Bearbeiten',
    del: 'Löschen',
    listingsHeading: 'Anzeigen ({n})',
    listingsEmpty: 'Keine Anzeigen.',
    view: 'Ansehen',
    editArticleTitle: 'Artikel bearbeiten',
    backToDashboard: 'Zurück zum Dashboard',
    save: 'Änderungen speichern',
  },
}

for (const loc of ['ar', 'fr', 'en', 'de']) {
  const p = path.join(__dirname, '..', 'messages', `${loc}.json`)
  const j = JSON.parse(fs.readFileSync(p, 'utf8'))
  j.admin = ns[loc]
  fs.writeFileSync(p, JSON.stringify(j, null, 2) + '\n', 'utf8')
  console.log(`✓ ${loc}.json`)
}
