const fs = require('fs')
const path = require('path')

const ns = {
  ar: {
    pageTitle: 'السكن في ألمانيا',
    addListing: '+ إضافة إعلان',
    backToListings: '→ العودة للإعلانات',
    emptyState: 'لا توجد إعلانات بعد',
    priceSuffix: '€/شهر',
    expires: 'ينتهي {date}',
    notFound: 'الإعلان غير موجود',
    types: { all: 'الكل', room: 'غرفة', apartment: 'شقة' },
    cityAll: 'كل المدن',
    detail: {
      edit: 'تعديل',
      whatsappCta: '💬 تواصل عبر واتساب',
      loginPromptBody: 'سجل دخولك لرؤية رقم واتساب صاحب الإعلان',
      login: 'دخول',
      signup: 'إنشاء حساب',
    },
    del: { confirm: 'هل أنت متأكد من حذف هذا الإعلان؟', button: 'حذف الإعلان' },
    form: {
      title: 'إضافة إعلان سكن',
      whatsappMissing: 'يجب إضافة رقم واتساب في ملفك الشخصي أولاً',
      whatsappBanner: '⚠️ يجب إضافة رقم واتساب في',
      whatsappBannerLink: 'ملفك الشخصي',
      whatsappBannerAfter: 'قبل نشر إعلان.',
      titlePh: 'عنوان الإعلان',
      descPh: 'وصف المكان (الحجم، الأثاث، الإيجار...)',
      selectCity: 'اختر المدينة',
      pricePh: 'السعر الشهري (€)',
      typeRoom: 'غرفة',
      typeApt: 'شقة',
      imagesLabel: 'الصور (من 1 إلى 5 صور)',
      imagesCount: '{n}/5 صور',
      publishing: 'جاري النشر...',
      publish: 'نشر الإعلان',
    },
  },
  fr: {
    pageTitle: 'Logement en Allemagne',
    addListing: '+ Ajouter une annonce',
    backToListings: '← Retour aux annonces',
    emptyState: 'Aucune annonce pour le moment',
    priceSuffix: '€/mois',
    expires: 'Expire le {date}',
    notFound: 'Annonce introuvable',
    types: { all: 'Toutes', room: 'Chambre', apartment: 'Appartement' },
    cityAll: 'Toutes les villes',
    detail: {
      edit: 'Modifier',
      whatsappCta: '💬 Contacter via WhatsApp',
      loginPromptBody: 'Connectez-vous pour voir le numéro WhatsApp du propriétaire',
      login: 'Connexion',
      signup: 'Créer un compte',
    },
    del: { confirm: 'Êtes-vous sûr de vouloir supprimer cette annonce ?', button: 'Supprimer l\'annonce' },
    form: {
      title: 'Ajouter une annonce de logement',
      whatsappMissing: 'Vous devez d\'abord ajouter un numéro WhatsApp à votre profil',
      whatsappBanner: '⚠️ Vous devez ajouter un numéro WhatsApp dans',
      whatsappBannerLink: 'votre profil',
      whatsappBannerAfter: 'avant de publier une annonce.',
      titlePh: 'Titre de l\'annonce',
      descPh: 'Description du logement (taille, meubles, loyer...)',
      selectCity: 'Choisir la ville',
      pricePh: 'Loyer mensuel (€)',
      typeRoom: 'Chambre',
      typeApt: 'Appartement',
      imagesLabel: 'Photos (de 1 à 5 images)',
      imagesCount: '{n}/5 photos',
      publishing: 'Publication...',
      publish: 'Publier l\'annonce',
    },
  },
  en: {
    pageTitle: 'Housing in Germany',
    addListing: '+ Add listing',
    backToListings: '← Back to listings',
    emptyState: 'No listings yet',
    priceSuffix: '€/month',
    expires: 'Expires {date}',
    notFound: 'Listing not found',
    types: { all: 'All', room: 'Room', apartment: 'Apartment' },
    cityAll: 'All cities',
    detail: {
      edit: 'Edit',
      whatsappCta: '💬 Contact via WhatsApp',
      loginPromptBody: 'Log in to see the owner\'s WhatsApp number',
      login: 'Log in',
      signup: 'Sign up',
    },
    del: { confirm: 'Are you sure you want to delete this listing?', button: 'Delete listing' },
    form: {
      title: 'Add a housing listing',
      whatsappMissing: 'You must add a WhatsApp number to your profile first',
      whatsappBanner: '⚠️ You must add a WhatsApp number in',
      whatsappBannerLink: 'your profile',
      whatsappBannerAfter: 'before posting a listing.',
      titlePh: 'Listing title',
      descPh: 'Description (size, furniture, rent...)',
      selectCity: 'Select city',
      pricePh: 'Monthly rent (€)',
      typeRoom: 'Room',
      typeApt: 'Apartment',
      imagesLabel: 'Photos (1 to 5 images)',
      imagesCount: '{n}/5 photos',
      publishing: 'Publishing...',
      publish: 'Publish listing',
    },
  },
  de: {
    pageTitle: 'Wohnen in Deutschland',
    addListing: '+ Anzeige hinzufügen',
    backToListings: '← Zurück zu den Anzeigen',
    emptyState: 'Noch keine Anzeigen',
    priceSuffix: '€/Monat',
    expires: 'Läuft ab am {date}',
    notFound: 'Anzeige nicht gefunden',
    types: { all: 'Alle', room: 'Zimmer', apartment: 'Wohnung' },
    cityAll: 'Alle Städte',
    detail: {
      edit: 'Bearbeiten',
      whatsappCta: '💬 Über WhatsApp kontaktieren',
      loginPromptBody: 'Melde dich an, um die WhatsApp-Nummer des Inserenten zu sehen',
      login: 'Anmelden',
      signup: 'Registrieren',
    },
    del: { confirm: 'Bist du sicher, dass du diese Anzeige löschen möchtest?', button: 'Anzeige löschen' },
    form: {
      title: 'Wohnungsanzeige hinzufügen',
      whatsappMissing: 'Du musst zuerst eine WhatsApp-Nummer in deinem Profil hinzufügen',
      whatsappBanner: '⚠️ Du musst eine WhatsApp-Nummer in',
      whatsappBannerLink: 'deinem Profil',
      whatsappBannerAfter: 'hinzufügen, bevor du eine Anzeige veröffentlichen kannst.',
      titlePh: 'Titel der Anzeige',
      descPh: 'Beschreibung (Größe, Möbel, Miete...)',
      selectCity: 'Stadt auswählen',
      pricePh: 'Monatliche Miete (€)',
      typeRoom: 'Zimmer',
      typeApt: 'Wohnung',
      imagesLabel: 'Fotos (1 bis 5 Bilder)',
      imagesCount: '{n}/5 Fotos',
      publishing: 'Wird veröffentlicht...',
      publish: 'Anzeige veröffentlichen',
    },
  },
}

for (const loc of ['ar', 'fr', 'en', 'de']) {
  const p = path.join(__dirname, '..', 'messages', `${loc}.json`)
  const j = JSON.parse(fs.readFileSync(p, 'utf8'))
  j.listings = ns[loc]
  fs.writeFileSync(p, JSON.stringify(j, null, 2) + '\n', 'utf8')
  console.log(`✓ ${loc}.json`)
}
