const fs = require('fs')
const path = require('path')

const ns = {
  ar: {
    metaTitle: 'Ausbildung Jobs — فرص التدريب المهني | دليلك نحو ألمانيا',
    metaDesc: 'عروض Ausbildung في ألمانيا محدّثة يومياً من Bundesagentur für Arbeit، مصنّفة حسب القطاع.',
    eyebrow: '🔍 فرص Ausbildung',
    title: 'Ausbildung Jobs',
    subtitle: 'آخر عروض التدريب المهني من وكالة العمل الألمانية (Bundesagentur für Arbeit)، مصنّفة حسب القطاع. قدّم مباشرة بإيميل مولّد بالذكاء الاصطناعي.',
    offersCount: '📊 {n} عرض متاح',
    lastUpdated: '🔄 آخر تحديث: {date}',
    all: 'الكل ({n})',
    emptyTitle: 'لا توجد عروض متاحة حالياً.',
    emptyHint: 'يتم تحديث العروض يومياً. عد غداً.',
    catEmpty: 'لا توجد عروض متاحة حالياً في هذا القطاع. تحقق لاحقاً.',
    cats: {
      hospitality: 'الفندقة والمطاعم',
      handwerk: 'الحرف المهنية',
      it: 'المعلوماتية',
      healthcare: 'الرعاية الصحية',
    },
    card: { apply: 'تقديم ←', freshPrefix: '🆕 ' },
    rel: { today: 'اليوم', oneDay: 'منذ يوم', twoDays: 'منذ يومين', fewDays: 'منذ {n} أيام', manyDays: 'منذ {n} يوماً' },
    modal: {
      howTo: '📬 طريقة التقديم',
      noContact: 'لم يُوفّر صاحب العمل إيميل أو رابط تقديم. يمكنك البحث عن الشركة مباشرة.',
      emailLabel: '📧 Email للتقديم',
      copy: '📋 نسخ',
      copied: '✅ تم نسخ الإيميل',
      copyFail: '❌ تعذر النسخ',
      urlLabel: '🌐 رابط التقديم',
      openApply: 'فتح صفحة التقديم',
      tipPrefix: '💡 نصيحة: جهّز سيرتك الذاتية ورسالة الدوافع بالألمانية قبل التواصل مع صاحب العمل. يمكنك استخدام',
      tipLink: 'باني السيرة الذاتية',
      tipSuffix: 'المجاني.',
    },
  },
  fr: {
    metaTitle: 'Ausbildung Jobs — offres de formation professionnelle | Votre guide vers l\'Allemagne',
    metaDesc: 'Offres Ausbildung en Allemagne mises à jour quotidiennement depuis la Bundesagentur für Arbeit, classées par secteur.',
    eyebrow: '🔍 Offres Ausbildung',
    title: 'Ausbildung Jobs',
    subtitle: 'Dernières offres de formation professionnelle de l\'Agence fédérale allemande pour l\'emploi (Bundesagentur für Arbeit), classées par secteur. Postulez directement avec un e-mail généré par IA.',
    offersCount: '📊 {n} offres disponibles',
    lastUpdated: '🔄 Dernière mise à jour : {date}',
    all: 'Toutes ({n})',
    emptyTitle: 'Aucune offre disponible actuellement.',
    emptyHint: 'Les offres sont mises à jour quotidiennement. Reviens demain.',
    catEmpty: 'Aucune offre disponible actuellement dans ce secteur. Reviens plus tard.',
    cats: {
      hospitality: 'Hôtellerie & Restauration',
      handwerk: 'Métiers manuels',
      it: 'Informatique',
      healthcare: 'Santé',
    },
    card: { apply: 'Postuler →', freshPrefix: '🆕 ' },
    rel: { today: 'Aujourd\'hui', oneDay: 'Il y a 1 jour', twoDays: 'Il y a 2 jours', fewDays: 'Il y a {n} jours', manyDays: 'Il y a {n} jours' },
    modal: {
      howTo: '📬 Comment postuler',
      noContact: 'L\'employeur n\'a pas fourni d\'e-mail ni de lien de candidature. Tu peux chercher l\'entreprise directement.',
      emailLabel: '📧 E-mail de candidature',
      copy: '📋 Copier',
      copied: '✅ E-mail copié',
      copyFail: '❌ Échec de la copie',
      urlLabel: '🌐 Lien de candidature',
      openApply: 'Ouvrir la page de candidature',
      tipPrefix: '💡 Conseil : prépare ton CV et ta lettre de motivation en allemand avant de contacter l\'employeur. Tu peux utiliser',
      tipLink: 'le générateur de CV',
      tipSuffix: 'gratuit.',
    },
  },
  en: {
    metaTitle: 'Ausbildung Jobs — Vocational Training Offers | Your Guide to Germany',
    metaDesc: 'Ausbildung offers in Germany updated daily from the Bundesagentur für Arbeit, sorted by sector.',
    eyebrow: '🔍 Ausbildung Offers',
    title: 'Ausbildung Jobs',
    subtitle: 'Latest vocational training offers from the German Federal Employment Agency (Bundesagentur für Arbeit), sorted by sector. Apply directly with an AI-generated email.',
    offersCount: '📊 {n} offers available',
    lastUpdated: '🔄 Last updated: {date}',
    all: 'All ({n})',
    emptyTitle: 'No offers available right now.',
    emptyHint: 'Offers are updated daily. Come back tomorrow.',
    catEmpty: 'No offers available in this sector right now. Check back later.',
    cats: {
      hospitality: 'Hospitality',
      handwerk: 'Skilled Trades',
      it: 'IT',
      healthcare: 'Healthcare',
    },
    card: { apply: 'Apply →', freshPrefix: '🆕 ' },
    rel: { today: 'Today', oneDay: '1 day ago', twoDays: '2 days ago', fewDays: '{n} days ago', manyDays: '{n} days ago' },
    modal: {
      howTo: '📬 How to apply',
      noContact: 'The employer did not provide an email or application link. You can search for the company directly.',
      emailLabel: '📧 Application email',
      copy: '📋 Copy',
      copied: '✅ Email copied',
      copyFail: '❌ Copy failed',
      urlLabel: '🌐 Application link',
      openApply: 'Open application page',
      tipPrefix: '💡 Tip: prepare your CV and cover letter in German before contacting the employer. You can use the free',
      tipLink: 'CV Builder',
      tipSuffix: '.',
    },
  },
  de: {
    metaTitle: 'Ausbildung Jobs — Ausbildungsangebote | Dein Leitfaden nach Deutschland',
    metaDesc: 'Ausbildungsangebote in Deutschland, täglich aktualisiert von der Bundesagentur für Arbeit, nach Branche sortiert.',
    eyebrow: '🔍 Ausbildungsangebote',
    title: 'Ausbildung Jobs',
    subtitle: 'Aktuelle Ausbildungsangebote von der Bundesagentur für Arbeit, nach Branche sortiert. Bewirb dich direkt mit einer KI-generierten E-Mail.',
    offersCount: '📊 {n} Angebote verfügbar',
    lastUpdated: '🔄 Zuletzt aktualisiert: {date}',
    all: 'Alle ({n})',
    emptyTitle: 'Derzeit keine Angebote verfügbar.',
    emptyHint: 'Angebote werden täglich aktualisiert. Komm morgen wieder.',
    catEmpty: 'Derzeit keine Angebote in diesem Bereich verfügbar. Schau später nochmal rein.',
    cats: {
      hospitality: 'Gastgewerbe',
      handwerk: 'Handwerk',
      it: 'IT',
      healthcare: 'Gesundheitswesen',
    },
    card: { apply: 'Bewerben →', freshPrefix: '🆕 ' },
    rel: { today: 'Heute', oneDay: 'Vor 1 Tag', twoDays: 'Vor 2 Tagen', fewDays: 'Vor {n} Tagen', manyDays: 'Vor {n} Tagen' },
    modal: {
      howTo: '📬 Wie bewerben',
      noContact: 'Der Arbeitgeber hat keine E-Mail und keinen Bewerbungslink hinterlegt. Du kannst direkt nach der Firma suchen.',
      emailLabel: '📧 Bewerbungs-E-Mail',
      copy: '📋 Kopieren',
      copied: '✅ E-Mail kopiert',
      copyFail: '❌ Kopieren fehlgeschlagen',
      urlLabel: '🌐 Bewerbungslink',
      openApply: 'Bewerbungsseite öffnen',
      tipPrefix: '💡 Tipp: Bereite deinen Lebenslauf und dein Anschreiben auf Deutsch vor, bevor du den Arbeitgeber kontaktierst. Du kannst den kostenlosen',
      tipLink: 'Lebenslauf-Generator',
      tipSuffix: 'nutzen.',
    },
  },
}

for (const loc of ['ar', 'fr', 'en', 'de']) {
  const p = path.join(__dirname, '..', 'messages', `${loc}.json`)
  const j = JSON.parse(fs.readFileSync(p, 'utf8'))
  j.ausbJobs = ns[loc]
  fs.writeFileSync(p, JSON.stringify(j, null, 2) + '\n', 'utf8')
  console.log(`✓ ${loc}.json`)
}
