// Phase 2: add landing.pathHub.{ausbildung,studium,shared} i18n keys
const fs = require('node:fs')
const path = require('node:path')
const ROOT = path.resolve(__dirname, '..', 'messages')

const DATA = {
  ar: {
    shared: {
      articlesTitle: 'مقالات ودروس',
      articlesCta: 'كل المقالات',
      toolsTitle: 'أدوات بالذكاء الاصطناعي',
      toolsCta: 'اكتشف الأدوات',
      nextStepTitle: 'الخطوة التالية',
      consultTitle: 'احجز استشارة',
      consultSub: 'خبراؤنا يرافقونك خطوة بخطوة — باللغة العربية أو الفرنسية.',
      consultName: 'الاسم الكامل',
      consultEmail: 'البريد الإلكتروني',
      consultPhone: 'رقم الهاتف',
      consultMsg: 'أخبرنا عن مشروعك',
      consultSubmit: 'احجز استشارتي',
      consultSending: 'جاري الإرسال…',
      consultSuccess: 'شكراً! سنتواصل معك قريباً.',
      consultError: 'تعذّر الإرسال، حاول مجدداً.',
    },
    ausbildung: {
      eyebrow: 'مسار Ausbildung',
      title: 'كل ما تحتاجه للتكوين المهني في ألمانيا',
      sub: 'سيرة ذاتية، رسالة تحفيز، تعلم الألمانية، عروض حقيقية واستشارة شخصية — في مكان واحد.',
      ctaOffers: 'تصفّح عروض Ausbildung',
      offersKicker: 'العروض',
      offersTitle: '+5000 عرض Ausbildung حقيقي',
      offersDesc: 'ابحث عن فرص تكوين مع عقد رسمي في جميع أنحاء ألمانيا، محدّثة يومياً.',
      offersCta: 'شوف العروض',
    },
    studium: {
      eyebrow: 'مسار الدراسة',
      title: 'كل ما تحتاجه للدراسة في ألمانيا',
      sub: 'سيرة ذاتية، رسالة تحفيز، دليل الجامعات، تعلم الألمانية واستشارة شخصية — في مكان واحد.',
      ctaUnis: 'اكتشف الجامعات',
      unisKicker: 'الجامعات',
      unisTitle: 'جامعات ألمانية مفتوحة للمغاربة',
      unisDesc: 'دليل شامل للجامعات مع شروط القبول، التخصصات والتكاليف.',
      unisCta: 'اكتشف الدليل',
    },
  },
  fr: {
    shared: {
      articlesTitle: 'Articles & guides',
      articlesCta: 'Tous les articles',
      toolsTitle: 'Outils IA',
      toolsCta: 'Voir tous les outils',
      nextStepTitle: 'Prochaine étape',
      consultTitle: 'Prends un rendez-vous',
      consultSub: 'Nos conseillers t’accompagnent étape par étape — en arabe ou en français.',
      consultName: 'Nom complet',
      consultEmail: 'Email',
      consultPhone: 'Téléphone',
      consultMsg: 'Parle-nous de ton projet',
      consultSubmit: 'Réserver ma consultation',
      consultSending: 'Envoi…',
      consultSuccess: 'Merci ! On te recontacte très vite.',
      consultError: 'Envoi impossible, réessaie.',
    },
    ausbildung: {
      eyebrow: 'Parcours Ausbildung',
      title: 'Tout pour réussir ton Ausbildung en Allemagne',
      sub: 'CV, lettre de motivation, apprentissage de l’allemand, vraies offres et consultation personnalisée — au même endroit.',
      ctaOffers: 'Voir les offres Ausbildung',
      offersKicker: 'Offres',
      offersTitle: '5 000+ vraies offres d’Ausbildung',
      offersDesc: 'Trouve des postes avec contrat officiel partout en Allemagne, mis à jour chaque jour.',
      offersCta: 'Voir les offres',
    },
    studium: {
      eyebrow: 'Parcours études',
      title: 'Tout pour étudier en Allemagne',
      sub: 'CV, lettre de motivation, annuaire des universités, apprentissage de l’allemand et consultation — au même endroit.',
      ctaUnis: 'Voir les universités',
      unisKicker: 'Universités',
      unisTitle: 'Universités allemandes ouvertes aux Marocains',
      unisDesc: 'Annuaire complet avec conditions d’admission, spécialités et coûts.',
      unisCta: 'Voir l’annuaire',
    },
  },
  en: {
    shared: {
      articlesTitle: 'Articles & guides',
      articlesCta: 'All articles',
      toolsTitle: 'AI tools',
      toolsCta: 'See all tools',
      nextStepTitle: 'Next step',
      consultTitle: 'Book a consultation',
      consultSub: 'Our advisors guide you step by step — in Arabic or French.',
      consultName: 'Full name',
      consultEmail: 'Email',
      consultPhone: 'Phone',
      consultMsg: 'Tell us about your project',
      consultSubmit: 'Book my consultation',
      consultSending: 'Sending…',
      consultSuccess: 'Thanks! We’ll be in touch shortly.',
      consultError: 'Couldn’t send, please try again.',
    },
    ausbildung: {
      eyebrow: 'Ausbildung path',
      title: 'Everything for your Ausbildung in Germany',
      sub: 'CV, cover letter, German learning, real offers and personal consultation — all in one place.',
      ctaOffers: 'Browse Ausbildung offers',
      offersKicker: 'Offers',
      offersTitle: '5,000+ real Ausbildung offers',
      offersDesc: 'Find training positions with an official contract across Germany, updated daily.',
      offersCta: 'See offers',
    },
    studium: {
      eyebrow: 'Studium path',
      title: 'Everything to study in Germany',
      sub: 'CV, motivation letter, university directory, German learning and consultation — all in one place.',
      ctaUnis: 'Explore universities',
      unisKicker: 'Universities',
      unisTitle: 'German universities open to Moroccans',
      unisDesc: 'Complete directory with admission requirements, programs and fees.',
      unisCta: 'Explore the directory',
    },
  },
  de: {
    shared: {
      articlesTitle: 'Artikel & Ratgeber',
      articlesCta: 'Alle Artikel',
      toolsTitle: 'KI-Werkzeuge',
      toolsCta: 'Alle Werkzeuge',
      nextStepTitle: 'Nächster Schritt',
      consultTitle: 'Beratung buchen',
      consultSub: 'Unsere Berater begleiten dich Schritt für Schritt — auf Arabisch oder Französisch.',
      consultName: 'Vollständiger Name',
      consultEmail: 'E-Mail',
      consultPhone: 'Telefon',
      consultMsg: 'Erzähl uns von deinem Projekt',
      consultSubmit: 'Beratung reservieren',
      consultSending: 'Senden…',
      consultSuccess: 'Danke! Wir melden uns bald bei dir.',
      consultError: 'Senden nicht möglich, bitte erneut versuchen.',
    },
    ausbildung: {
      eyebrow: 'Ausbildungs-Pfad',
      title: 'Alles für deine Ausbildung in Deutschland',
      sub: 'Lebenslauf, Anschreiben, Deutsch lernen, echte Stellen und persönliche Beratung — an einem Ort.',
      ctaOffers: 'Ausbildungsstellen ansehen',
      offersKicker: 'Stellen',
      offersTitle: '5.000+ echte Ausbildungsstellen',
      offersDesc: 'Finde Ausbildungsplätze mit offiziellem Vertrag in ganz Deutschland, täglich aktualisiert.',
      offersCta: 'Stellen ansehen',
    },
    studium: {
      eyebrow: 'Studium-Pfad',
      title: 'Alles fürs Studium in Deutschland',
      sub: 'Lebenslauf, Motivationsschreiben, Universitätsverzeichnis, Deutsch lernen und Beratung — an einem Ort.',
      ctaUnis: 'Universitäten entdecken',
      unisKicker: 'Universitäten',
      unisTitle: 'Deutsche Universitäten für Marokkaner',
      unisDesc: 'Komplettes Verzeichnis mit Zulassungsbedingungen, Studiengängen und Kosten.',
      unisCta: 'Verzeichnis ansehen',
    },
  },
}

for (const loc of ['ar', 'fr', 'en', 'de']) {
  const p = path.join(ROOT, `${loc}.json`)
  const j = JSON.parse(fs.readFileSync(p, 'utf8'))
  j.landing = j.landing || {}
  j.landing.pathHub = DATA[loc]
  fs.writeFileSync(p, JSON.stringify(j, null, 2) + '\n', 'utf8')
  console.log(`patched ${loc}.json`)
}
