/* eslint-disable */
const fs = require('fs')
const path = require('path')

const LOCALES = ['ar', 'fr', 'en', 'de']
const MESSAGES_DIR = path.join(__dirname, '..', 'messages')

const byLoc = {
  ar: {
    metaTitle: 'الجامعات والدراسة في ألمانيا — الدليل الكامل',
    metaDesc: '20 مقالاً عن التقديم للجامعات الألمانية، المنح، التأشيرة، والحياة الطلابية.',
    eyebrow: 'الدراسة الجامعية',
    title: 'الجامعات في ألمانيا',
    subtitle: 'خارطة طريق كاملة لكل طالب مغربي يفكر في الدراسة الجامعية في ألمانيا — من معادلة الباكالوريا إلى تخرّج الماستر.',
    intro: '20 مقالاً مختصراً يجيبان عن الأسئلة الحقيقية التي يطرحها آلاف المغاربة كل عام: كيف أختار الجامعة؟ كم المدة؟ كيف أموّل نفسي؟ هل لغتي كافية؟',
    items: [
      {
        num: 1,
        title: 'لماذا ألمانيا وليس دولة أوروبية أخرى؟',
        summary: 'الدراسة في ألمانيا شبه مجانية، وسوق العمل يفتح أبوابه للخريّجين مباشرة. لكن يجب أن تعرف ما تنتظره.',
        tag: 'مقدّمة',
        bullets: [
          'الجامعات الحكومية بدون رسوم دراسية (ما عدا Baden-Württemberg للطلاب الأجانب: 1500€/فصل).',
          'رسم الفصل (Semesterbeitrag) بين 150–350 يورو شامل تذكرة نقل مجانية في بعض الولايات.',
          'شهادة معترف بها عالمياً وسوق عمل ألماني متعطّش للمهارات.',
          'إقامة عمل مضمونة لـ 18 شهراً بعد التخرّج للبحث عن وظيفة.',
        ],
        tip: 'كندا وفرنسا أقصر في التقديم، لكن ألمانيا أرخص طوال 5 سنوات من الدراسة.',
      },
      {
        num: 2,
        title: 'Universität vs Fachhochschule (FH/HAW)',
        summary: 'الفرق بينهما جوهري ويؤثّر على مستقبلك المهني. اختر بناءً على تخصّصك وطموحك، لا على الاسم.',
        tag: 'أنواع',
        bullets: [
          '**Universität (Uni):** بحثية، نظرية، تسمح بالدكتوراه، مناسبة للعلوم الأساسية والطب والحقوق.',
          '**Fachhochschule (FH/HAW):** تطبيقية، مشاريع حقيقية، تدريب إلزامي، أسرع لسوق العمل.',
          'Kunsthochschule / Musikhochschule: للفنانين والموسيقيين بامتحان قبول خاص.',
          'Duale Hochschule: تجمع بين الجامعة والشركة (نظام مدفوع الأجر).',
        ],
      },
      {
        num: 3,
        title: 'أشهر الجامعات الألمانية وترتيبها',
        summary: 'قائمة الجامعات الأفضل ليست الأسهل للقبول. اعرف التصنيفات لكن اختر بناءً على برنامجك.',
        tag: 'ترتيب',
        bullets: [
          '**TU München, LMU München:** الأقوى في العلوم والتقنية.',
          '**Heidelberg, Göttingen, Tübingen:** عراقة بحثية في الطب والعلوم الإنسانية.',
          '**RWTH Aachen, KIT Karlsruhe, TU Berlin:** الهندسة والحاسوب.',
          '**Humboldt, FU Berlin:** العلوم الاجتماعية والإنسانية.',
          '**Mannheim, Frankfurt:** الاقتصاد والتمويل.',
        ],
        tip: 'ترتيب Shanghai و THE جيّد للمعلومة، لكن أعضاء لجنة التوظيف الألماني لا يهتمّون به كثيراً.',
      },
      {
        num: 4,
        title: 'معادلة الباكالوريا المغربية (uni-assist)',
        summary: 'قبل أي تقديم، يجب أن تُعادل شهادتك عبر uni-assist أو مباشرة عبر الجامعة. هذه الخطوة الأولى دائماً.',
        tag: 'معادلة',
        bullets: [
          'الباكالوريا المغربية لا تعادل الأبيتور الألماني مباشرة عادة — تحتاج Studienkolleg أو سنة جامعية.',
          'uni-assist يقيّم ملفك ويُصدر VPD (Vorprüfungsdokumentation) يُستخدم في عدة تقديمات.',
          'الرسم 75€ لأول جامعة + 30€ لكل جامعة إضافية في نفس الفصل.',
          'بعض الجامعات (TUM, Heidelberg) تقيّم بنفسها بدون uni-assist.',
        ],
      },
      {
        num: 5,
        title: 'Studienkolleg — السنة التحضيرية الإلزامية',
        summary: 'إذا لم تدخل سنة جامعية في المغرب، ستحتاج Studienkolleg قبل البدء. سنة مكثفة تنتهي بامتحان Feststellungsprüfung.',
        tag: 'تحضيري',
        bullets: [
          'مدتها سنة، مجانية في الجامعات الحكومية.',
          'مسارات: T (تقني), M (طبي), W (اقتصادي), G (لغوي), S (علوم اجتماعية).',
          'تحتاج B1-B2 ألمانية للقبول + امتحان قبول (Aufnahmeprüfung).',
          'بعد النجاح في Feststellungsprüfung، تُعامل شهادتك كأبيتور ألماني.',
        ],
        tip: 'لو أكملت سنة جامعية في المغرب بنجاح، قد تتجاوز Studienkolleg وتدخل مباشرة لبرنامج البكالوريوس.',
      },
      {
        num: 6,
        title: 'متطلبات اللغة: DSH، TestDaF، TELC، Goethe',
        summary: 'B2 لن تكفي عادة لبرامج باللغة الألمانية. ستحتاج C1 معتمدة عبر أحد هذه الاختبارات.',
        tag: 'لغة',
        bullets: [
          '**TestDaF:** الأشهر دولياً، مقبول في كل الجامعات. المستوى المطلوب TDN 4 في كل أجزائه.',
          '**DSH-2 أو DSH-3:** امتحان تُقدّمه الجامعة نفسها، مجاني غالباً.',
          '**Goethe-Zertifikat C1/C2:** معتمد واسعاً، غالٍ نسبياً (230€).',
          '**TELC C1 Hochschule:** بديل جيّد، أرخص.',
          'بعض الجامعات تعفي من الامتحان بشرط شهادة C1 + مستوى معيّن في TOEFL للبرامج المختلطة.',
        ],
      },
      {
        num: 7,
        title: 'البرامج باللغة الإنجليزية — البديل السريع',
        summary: 'أكثر من 2000 برنامج ألماني بالإنجليزية، خصوصاً في الماستر. لا تحتاج الألمانية للقبول.',
        tag: 'إنجليزي',
        bullets: [
          'DAAD.de يحوي قاعدة بيانات كاملة للبرامج الإنجليزية.',
          'IELTS 6.5 أو TOEFL 90 هو الحد الأدنى الشائع.',
          'الماستر بالإنجليزية أكثر بكثير من البكالوريوس.',
          'التخصصات الأكثر توفّراً: الهندسة، الحاسوب، الاقتصاد، العلوم البيئية.',
        ],
        tip: 'حتى لو درست بالإنجليزية، تعلّم الألمانية بالتوازي — ستحتاجها في الحياة اليومية والعمل الجزئي.',
      },
      {
        num: 8,
        title: 'خطوات التقديم — دليل زمني',
        summary: 'خطة زمنية واقعية: ابدأ قبل سنة تقريباً من موعد الدراسة لتجنّب الضغط والأخطاء.',
        tag: 'خطوات',
        bullets: [
          '12 شهراً قبل: ابحث عن البرامج، ابدأ تعلّم اللغة.',
          '9 أشهر قبل: ترجم وثائقك وصدّقها + uni-assist.',
          '6 أشهر قبل: قدّم الطلبات (موعد نهائي Wintersemester: 15 يوليو).',
          '4 أشهر قبل: احجز موعد سفارة + جهّز إثبات التمويل.',
          '2 أشهر قبل: احجز سكن طلابي + تأمين صحي.',
        ],
      },
      {
        num: 9,
        title: 'رسالة التحفيز (Motivationsschreiben)',
        summary: 'الوثيقة الأهم في ملفك. يجب أن تروي قصة واضحة: لماذا أنت، لماذا هذا البرنامج، لماذا هذه الجامعة.',
        tag: 'ملف',
        bullets: [
          'صفحة واحدة (400–500 كلمة) بالألمانية أو الإنجليزية حسب لغة البرنامج.',
          'ابدأ بحدث شخصي جذب اهتمامك للتخصص — لا بـ "I have always been interested".',
          'اربط كل فقرة بمواد محددة في البرنامج.',
          'اختم بخطة 5 سنوات بعد التخرّج.',
        ],
        tip: 'اعرض الرسالة على أستاذ + صديق + ناطق بالألمانية قبل الإرسال — الأخطاء اللغوية قاتلة.',
      },
      {
        num: 10,
        title: 'إثبات التمويل (Finanzierungsnachweis)',
        summary: 'ألمانيا تشترط إثبات قدرتك على العيش سنة كاملة. بدونه لا تأشيرة. هذا مبلغ ثابت يُحدَّث سنوياً.',
        tag: 'تمويل',
        bullets: [
          'المبلغ الحالي: 11,904€ (2024) في حساب Sperrkonto باسمك.',
          'الحساب المقفل يسمح بسحب شهري فقط (~992€/شهر).',
          'بدائل: منحة رسمية، التزام شخص ألماني (Verpflichtungserklärung)، ضمان بنكي.',
          'خدمات Sperrkonto الأشهر: Expatrio, Fintiba, Coracle (كلها معتمدة).',
        ],
      },
      {
        num: 11,
        title: 'منحة DAAD — الأشهر والأكبر',
        summary: 'الهيئة الألمانية للتبادل الأكاديمي تقدّم مئات المنح سنوياً. تنافسية لكن حقيقية وواقعية.',
        tag: 'منح',
        bullets: [
          'منح ماستر كاملة (850€/شهر + رسوم + تأمين + تذكرة).',
          'منح دكتوراه (1200€/شهر + عائلة).',
          'منح قصيرة للبحث (3–6 أشهر) أثناء الدراسة.',
          'التقديم يتم قبل سنة من بداية المنحة عادةً.',
        ],
        tip: 'أهم ملفك في DAAD: خطة البحث (Research Proposal). اقرأ أبحاث المشرف المحتمل قبل كتابتها.',
      },
      {
        num: 12,
        title: 'منح المؤسسات السياسية (Stiftungen)',
        summary: '13 مؤسسة سياسية ألمانية تقدّم منحاً للطلاب الدوليين. أقل تنافسية من DAAD، وبنفس السخاء.',
        tag: 'منح',
        bullets: [
          '**Konrad-Adenauer:** مسيحية ديمقراطية.',
          '**Friedrich-Ebert:** اشتراكية ديمقراطية.',
          '**Heinrich-Böll:** بيئية.',
          '**Rosa-Luxemburg:** يسار.',
          '**Friedrich-Naumann:** ليبرالية.',
          'كل مؤسسة تطلب انسجاماً أيديولوجياً + تميّزاً أكاديمياً + عملاً تطوعياً.',
        ],
      },
      {
        num: 13,
        title: 'تأشيرة الطالب — من التقديم إلى الاستلام',
        summary: 'تأشيرة الدراسة (C أو D) تُصدر من السفارة الألمانية. الانتظار قد يصل إلى 3 أشهر في ذروة الصيف.',
        tag: 'تأشيرة',
        bullets: [
          'نوعان: Visum zur Studienbewerbung (طلب دراسي) و Visum zu Studienzwecken (قبول مؤكد).',
          'احجز الموعد عبر maroc.diplo.de — مبكراً جداً.',
          'وثائق: قبول جامعي، إثبات تمويل، تأمين صحي، ترجمة كل الوثائق.',
          'الرسم 75€. تُصدَر عادة لمدة 3 أشهر ثم تُحوَّل إلى Aufenthaltstitel.',
        ],
      },
      {
        num: 14,
        title: 'التأمين الصحي للطلاب',
        summary: 'التأمين الصحي إلزامي للتسجيل الجامعي. تحت 30 سنة: تأمين حكومي (GKV). فوق 30: خاص (PKV).',
        tag: 'تأمين',
        bullets: [
          'التأمين الحكومي (TK, AOK, Barmer): ~120€/شهر للطلاب، يغطّي كل شيء تقريباً.',
          'التأمين الخاص: أرخص أحياناً لكن محدود.',
          'تأمينات السفر (Mawista, Dr.Walter) مقبولة فقط لشهرين كحد أقصى، ثم يجب التحويل.',
          'TK هو الأشهر بين الطلاب الدوليين — موقع ودعم إنجليزي جيّد.',
        ],
      },
      {
        num: 15,
        title: 'السكن الطلابي (Studentenwohnheim)',
        summary: 'الخيار الأرخص، لكن قوائم الانتظار طويلة. قدّم طلبك فور استلام خطاب القبول.',
        tag: 'سكن',
        bullets: [
          'Studierendenwerk هو المنظّم — موقع كل مدينة مختلف.',
          'إيجار: 180–400 يورو شامل الفواتير.',
          'قوائم الانتظار: 3–12 شهراً في المدن الكبرى.',
          'بدائل: WG (شقة مشاركة) عبر wg-gesucht.de.',
          'احذر النصب — لا تدفع قبل زيارة الشقة أو رؤية العقد.',
        ],
        tip: 'في أسبوعك الأول، احجز Jugendherberge أو Airbnb، ولا تقبل أي شقة بضغط الوقت. القرار السريع = مأساة طويلة.',
      },
      {
        num: 16,
        title: 'التسجيل الفصلي وبطاقة الطالب',
        summary: 'بعد الوصول، يجب إتمام Immatrikulation (التسجيل الرسمي). ستحصل على Studentenausweis وبطاقة نقل.',
        tag: 'تسجيل',
        bullets: [
          'أحضر: جواز، تأشيرة، Anmeldung، إثبات تأمين، وصل دفع Semesterbeitrag.',
          'التسجيل يعطيك Matrikelnummer — احفظه للأبد.',
          'بطاقة الطالب تُعطي خصومات في المتاحف، السينما، الرياضة.',
          'في كثير من الولايات: تذكرة نقل فصلية مجانية داخل المنطقة.',
        ],
      },
      {
        num: 17,
        title: 'العمل أثناء الدراسة — الحدود القانونية',
        summary: 'يُسمح للطالب الأجنبي بالعمل 140 يوماً كاملاً أو 280 يوماً نصفياً في السنة. تجاوز ذلك = مشاكل في تجديد الإقامة.',
        tag: 'عمل',
        bullets: [
          'Werkstudent: عقد طلابي خاص حتى 20 ساعة/أسبوع أثناء الفصل.',
          'Minijob: حتى 538€/شهر بدون ضرائب ولا تأمين.',
          'HiWi (مساعد علمي): أفضل عمل داخل الجامعة، أجر جيّد وخبرة.',
          'في العطل، يمكن العمل Vollzeit لمدة شهرين كاملين.',
        ],
      },
      {
        num: 18,
        title: 'BAföG للطلاب الأجانب',
        summary: 'مساعدة مالية حكومية نصفها منحة ونصفها قرض بدون فوائد. شروط صارمة للأجانب، لكنها ممكنة.',
        tag: 'تمويل',
        bullets: [
          'الطالب الأجنبي مؤهل بعد 5 سنوات عمل في ألمانيا أو بوجود والد مقيم.',
          'اللاجئون والحاصلون على Niederlassungserlaubnis مؤهلون مباشرة.',
          'الحد الأعلى الشهري: ~934€ (2024).',
          'الإرجاع يبدأ بعد 5 سنوات من انتهاء الدراسة.',
        ],
      },
      {
        num: 19,
        title: 'Aufenthaltstitel بعد التخرّج',
        summary: 'بعد إنهاء الدراسة، لك حق في 18 شهراً للبحث عن عمل. استغلّ هذه النافذة جيداً.',
        tag: 'ما بعد التخرّج',
        bullets: [
          'قدّم طلب تحويل الإقامة قبل انتهاء تأشيرة الدراسة بـ 6 أسابيع.',
          'أحضر: شهادة تخرّج، إثبات تمويل (Sperrkonto أو عمل).',
          'أثناء البحث، يمكن العمل بدون قيود (Vollzeit).',
          'بعد إيجاد وظيفة مناسبة لتخصصك، تُحوَّل إلى Blaue Karte EU (شروطها أسهل من العادية).',
        ],
      },
      {
        num: 20,
        title: 'أخطاء قاتلة يجب تجنّبها',
        summary: 'هذه الأخطاء تتكرّر كل سنة وتُنهي حلم الدراسة. تجنّبها بدقة.',
        tag: 'تحذيرات',
        bullets: [
          'ترك تعلّم اللغة لآخر لحظة — ستحتاجها للتسجيل والحياة.',
          'التقديم لجامعة واحدة — يجب 5–10 تقديمات على الأقل.',
          'ترجمة الوثائق من مترجم غير محلَّف — ستُرفض.',
          'تأخير فتح Sperrkonto — لا يمكن حجز موعد السفارة بدونه.',
          'العمل أكثر من 140 يوماً وكشف ذلك للضرائب = رفض تجديد الإقامة.',
          'عدم Anmeldung خلال أسبوعين من الوصول — غرامات تصل 1000€.',
        ],
        tip: 'اشترك في مجموعات فيسبوك للطلاب المغاربة في ألمانيا — 90% من الأخطاء تُكتشف بسؤال واحد قبل ارتكابها.',
      },
    ],
  },
  fr: {
    metaTitle: 'Universités et études en Allemagne — le guide complet',
    metaDesc: '20 articles sur la candidature, les bourses, le visa et la vie étudiante en Allemagne.',
    eyebrow: 'Études universitaires',
    title: 'Les universités en Allemagne',
    subtitle: 'Une feuille de route complète pour tout étudiant marocain qui envisage d\'étudier en Allemagne — de l\'équivalence du bac à l\'obtention du master.',
    intro: '20 articles concis qui répondent aux vraies questions que se posent des milliers de Marocains chaque année : comment choisir son université ? Quelle durée ? Comment se financer ? Mon niveau de langue suffit-il ?',
    items: [
      {
        num: 1,
        title: 'Pourquoi l\'Allemagne plutôt qu\'un autre pays européen ?',
        summary: 'Étudier en Allemagne est quasi gratuit, et le marché du travail ouvre ses portes aux diplômés. Mais il faut savoir à quoi s\'attendre.',
        tag: 'Introduction',
        bullets: [
          'Les universités publiques n\'ont pas de frais de scolarité (sauf le Bade-Wurtemberg pour les étudiants étrangers : 1500 €/semestre).',
          'Le Semesterbeitrag (cotisation semestrielle) est de 150 à 350 € et inclut souvent un abonnement de transport gratuit.',
          'Un diplôme reconnu mondialement et un marché du travail allemand en quête de compétences.',
          'Un titre de séjour de 18 mois garanti après le diplôme pour chercher un emploi.',
        ],
        tip: 'Le Canada et la France demandent des démarches plus courtes, mais l\'Allemagne reste moins chère sur 5 ans d\'études.',
      },
      {
        num: 2,
        title: 'Universität vs Fachhochschule (FH/HAW)',
        summary: 'La différence est essentielle et influence ton avenir professionnel. Choisis selon ta filière et ton ambition, pas selon le nom.',
        tag: 'Types',
        bullets: [
          '**Universität (Uni) :** recherche, théorie, ouvre au doctorat, adaptée aux sciences fondamentales, à la médecine et au droit.',
          '**Fachhochschule (FH/HAW) :** appliquée, vrais projets, stage obligatoire, accès plus rapide au marché du travail.',
          'Kunsthochschule / Musikhochschule : pour les artistes et musiciens, avec un concours d\'admission spécifique.',
          'Duale Hochschule : combine université et entreprise (système rémunéré).',
        ],
      },
      {
        num: 3,
        title: 'Les universités allemandes les plus connues et leur classement',
        summary: 'Les meilleures universités ne sont pas les plus accessibles. Regarde les classements, mais choisis selon ton programme.',
        tag: 'Classement',
        bullets: [
          '**TU München, LMU München :** les plus fortes en sciences et en technologie.',
          '**Heidelberg, Göttingen, Tübingen :** tradition de recherche en médecine et sciences humaines.',
          '**RWTH Aachen, KIT Karlsruhe, TU Berlin :** ingénierie et informatique.',
          '**Humboldt, FU Berlin :** sciences sociales et humaines.',
          '**Mannheim, Frankfurt :** économie et finance.',
        ],
        tip: 'Les classements Shanghai et THE sont intéressants à titre indicatif, mais les recruteurs allemands y accordent peu d\'importance.',
      },
      {
        num: 4,
        title: 'Équivalence du bac marocain (uni-assist)',
        summary: 'Avant toute candidature, tu dois faire évaluer ton diplôme via uni-assist ou directement par l\'université. C\'est toujours la première étape.',
        tag: 'Équivalence',
        bullets: [
          'Le bac marocain n\'équivaut pas automatiquement à l\'Abitur allemand — il faut souvent un Studienkolleg ou une année d\'université.',
          'uni-assist évalue ton dossier et délivre un VPD (Vorprüfungsdokumentation) utilisable pour plusieurs candidatures.',
          'Frais : 75 € pour la première université + 30 € par université supplémentaire du même semestre.',
          'Certaines universités (TUM, Heidelberg) évaluent elles-mêmes sans passer par uni-assist.',
        ],
      },
      {
        num: 5,
        title: 'Studienkolleg — l\'année préparatoire obligatoire',
        summary: 'Si tu n\'as pas fait d\'année universitaire au Maroc, tu devras passer par un Studienkolleg. Une année intensive clôturée par le Feststellungsprüfung.',
        tag: 'Préparatoire',
        bullets: [
          'Durée : un an, gratuit dans les universités publiques.',
          'Filières : T (technique), M (médecine), W (économie), G (langues), S (sciences sociales).',
          'Niveau requis : B1-B2 allemand + examen d\'entrée (Aufnahmeprüfung).',
          'Après la réussite au Feststellungsprüfung, ton diplôme équivaut à un Abitur allemand.',
        ],
        tip: 'Si tu as validé une année d\'université au Maroc, tu peux éventuellement sauter le Studienkolleg et entrer directement en licence.',
      },
      {
        num: 6,
        title: 'Exigences linguistiques : DSH, TestDaF, TELC, Goethe',
        summary: 'Le B2 ne suffit généralement pas pour les programmes en allemand. Il te faut un C1 certifié par l\'un de ces examens.',
        tag: 'Langue',
        bullets: [
          '**TestDaF :** le plus connu à l\'international, accepté partout. Niveau requis : TDN 4 dans chaque épreuve.',
          '**DSH-2 ou DSH-3 :** examen organisé par l\'université elle-même, souvent gratuit.',
          '**Goethe-Zertifikat C1/C2 :** largement reconnu, mais cher (230 €).',
          '**TELC C1 Hochschule :** bonne alternative, moins chère.',
          'Certaines universités dispensent de l\'examen avec un certificat C1 + un niveau TOEFL précis pour les programmes bilingues.',
        ],
      },
      {
        num: 7,
        title: 'Les programmes en anglais — l\'alternative rapide',
        summary: 'Plus de 2000 programmes allemands en anglais, surtout en master. Pas besoin d\'allemand pour l\'admission.',
        tag: 'Anglais',
        bullets: [
          'DAAD.de contient une base de données complète des programmes en anglais.',
          'IELTS 6.5 ou TOEFL 90 est le minimum courant.',
          'Les masters en anglais sont bien plus nombreux que les licences.',
          'Les filières les plus répandues : ingénierie, informatique, économie, sciences environnementales.',
        ],
        tip: 'Même si tu étudies en anglais, apprends l\'allemand en parallèle — tu en auras besoin au quotidien et pour les petits boulots.',
      },
      {
        num: 8,
        title: 'Les étapes de la candidature — un calendrier',
        summary: 'Un planning réaliste : commence environ un an avant la rentrée pour éviter le stress et les erreurs.',
        tag: 'Étapes',
        bullets: [
          '12 mois avant : recherche les programmes, commence à apprendre la langue.',
          '9 mois avant : fais traduire et certifier tes documents + uni-assist.',
          '6 mois avant : envoie les candidatures (date limite Wintersemester : 15 juillet).',
          '4 mois avant : prends rendez-vous à l\'ambassade + prépare ta preuve de financement.',
          '2 mois avant : réserve un logement étudiant + assurance santé.',
        ],
      },
      {
        num: 9,
        title: 'La lettre de motivation (Motivationsschreiben)',
        summary: 'Le document le plus important de ton dossier. Il doit raconter une histoire claire : pourquoi toi, pourquoi ce programme, pourquoi cette université.',
        tag: 'Dossier',
        bullets: [
          'Une page (400 à 500 mots) en allemand ou en anglais selon la langue du programme.',
          'Commence par un événement personnel qui a éveillé ton intérêt — pas par « I have always been interested ».',
          'Relie chaque paragraphe à des matières précises du programme.',
          'Termine avec un plan à 5 ans après le diplôme.',
        ],
        tip: 'Fais relire ta lettre par un professeur + un ami + un germanophone avant l\'envoi — les fautes de langue sont éliminatoires.',
      },
      {
        num: 10,
        title: 'Preuve de financement (Finanzierungsnachweis)',
        summary: 'L\'Allemagne exige la preuve que tu peux vivre une année entière. Sans elle, pas de visa. Le montant est fixe et révisé chaque année.',
        tag: 'Financement',
        bullets: [
          'Montant actuel : 11 904 € (2024) sur un compte bloqué (Sperrkonto) à ton nom.',
          'Le compte bloqué autorise un retrait mensuel uniquement (~992 €/mois).',
          'Alternatives : bourse officielle, engagement d\'un résident allemand (Verpflichtungserklärung), garantie bancaire.',
          'Services Sperrkonto les plus connus : Expatrio, Fintiba, Coracle (tous reconnus).',
        ],
      },
      {
        num: 11,
        title: 'Bourse DAAD — la plus connue et la plus importante',
        summary: 'L\'Office allemand d\'échanges universitaires offre des centaines de bourses chaque année. Compétitif, mais réaliste.',
        tag: 'Bourses',
        bullets: [
          'Bourses de master complètes (850 €/mois + frais + assurance + billet).',
          'Bourses de doctorat (1200 €/mois + famille).',
          'Bourses courtes pour la recherche (3 à 6 mois) pendant les études.',
          'La candidature se fait en général un an avant le début de la bourse.',
        ],
        tip: 'Le point clé de ton dossier DAAD : le projet de recherche. Lis les publications de ton futur encadrant avant de l\'écrire.',
      },
      {
        num: 12,
        title: 'Bourses des fondations politiques (Stiftungen)',
        summary: '13 fondations politiques allemandes offrent des bourses aux étudiants internationaux. Moins concurrentielles que DAAD, tout aussi généreuses.',
        tag: 'Bourses',
        bullets: [
          '**Konrad-Adenauer :** démocrate-chrétienne.',
          '**Friedrich-Ebert :** social-démocrate.',
          '**Heinrich-Böll :** écologiste.',
          '**Rosa-Luxemburg :** gauche.',
          '**Friedrich-Naumann :** libérale.',
          'Chaque fondation exige un alignement idéologique + excellence académique + engagement associatif.',
        ],
      },
      {
        num: 13,
        title: 'Le visa étudiant — de la demande à la délivrance',
        summary: 'Le visa d\'études (C ou D) est délivré par l\'ambassade d\'Allemagne. L\'attente peut atteindre 3 mois en haute saison estivale.',
        tag: 'Visa',
        bullets: [
          'Deux types : Visum zur Studienbewerbung (candidature) et Visum zu Studienzwecken (admission confirmée).',
          'Prends rendez-vous via maroc.diplo.de — très tôt.',
          'Documents : admission universitaire, preuve de financement, assurance santé, traductions de tous les documents.',
          'Frais : 75 €. Délivré généralement pour 3 mois puis converti en Aufenthaltstitel.',
        ],
      },
      {
        num: 14,
        title: 'L\'assurance santé pour étudiants',
        summary: 'L\'assurance santé est obligatoire pour l\'inscription à l\'université. Avant 30 ans : publique (GKV). Après 30 ans : privée (PKV).',
        tag: 'Assurance',
        bullets: [
          'Assurance publique (TK, AOK, Barmer) : ~120 €/mois pour les étudiants, couvre presque tout.',
          'Assurance privée : parfois moins chère, mais limitée.',
          'Les assurances voyage (Mawista, Dr. Walter) ne sont acceptées que pour 2 mois maximum, puis il faut basculer.',
          'TK est la plus populaire chez les étudiants internationaux — site web et support en anglais corrects.',
        ],
      },
      {
        num: 15,
        title: 'Le logement étudiant (Studentenwohnheim)',
        summary: 'L\'option la moins chère, mais les listes d\'attente sont longues. Dépose ta demande dès réception de l\'admission.',
        tag: 'Logement',
        bullets: [
          'Studierendenwerk est l\'organisme responsable — chaque ville a son propre site.',
          'Loyer : 180 à 400 € charges comprises.',
          'Listes d\'attente : 3 à 12 mois dans les grandes villes.',
          'Alternatives : WG (colocation) via wg-gesucht.de.',
          'Méfie-toi des arnaques — ne paie jamais avant d\'avoir visité l\'appartement ou vu le contrat.',
        ],
        tip: 'Pendant la première semaine, réserve une Jugendherberge ou un Airbnb, et n\'accepte aucun logement sous pression. Décision rapide = longue galère.',
      },
      {
        num: 16,
        title: 'L\'inscription semestrielle et la carte étudiante',
        summary: 'Une fois arrivé, tu dois effectuer l\'Immatrikulation (inscription officielle). Tu recevras un Studentenausweis et une carte de transport.',
        tag: 'Inscription',
        bullets: [
          'À apporter : passeport, visa, Anmeldung, preuve d\'assurance, reçu de paiement du Semesterbeitrag.',
          'L\'inscription te donne un Matrikelnummer — garde-le à vie.',
          'La carte étudiante donne des réductions dans les musées, cinémas et clubs sportifs.',
          'Dans beaucoup de Länder : abonnement de transport semestriel gratuit dans la région.',
        ],
      },
      {
        num: 17,
        title: 'Travailler pendant les études — les limites légales',
        summary: 'L\'étudiant étranger peut travailler 140 jours à temps plein ou 280 à mi-temps par an. Au-delà = problèmes au renouvellement du titre de séjour.',
        tag: 'Travail',
        bullets: [
          'Werkstudent : contrat étudiant spécifique, jusqu\'à 20 h/semaine pendant le semestre.',
          'Minijob : jusqu\'à 538 €/mois sans impôts ni cotisations.',
          'HiWi (assistant scientifique) : le meilleur job à l\'université, bien payé et formateur.',
          'Pendant les vacances, on peut travailler à temps plein (Vollzeit) deux mois complets.',
        ],
      },
      {
        num: 18,
        title: 'Le BAföG pour les étudiants étrangers',
        summary: 'Une aide financière publique, moitié bourse, moitié prêt sans intérêts. Conditions strictes pour les étrangers, mais possible.',
        tag: 'Financement',
        bullets: [
          'L\'étudiant étranger y est éligible après 5 ans de travail en Allemagne ou avec un parent résident.',
          'Les réfugiés et titulaires d\'une Niederlassungserlaubnis sont directement éligibles.',
          'Plafond mensuel : ~934 € (2024).',
          'Le remboursement commence 5 ans après la fin des études.',
        ],
      },
      {
        num: 19,
        title: 'Aufenthaltstitel après le diplôme',
        summary: 'À la fin de tes études, tu as droit à 18 mois pour chercher un emploi. Profite bien de cette fenêtre.',
        tag: 'Après le diplôme',
        bullets: [
          'Dépose la demande de conversion de titre de séjour 6 semaines avant la fin du visa d\'études.',
          'À apporter : diplôme, preuve de financement (Sperrkonto ou emploi).',
          'Pendant la recherche, tu peux travailler sans limites (Vollzeit).',
          'Une fois un emploi adapté à ton diplôme trouvé, passage à la Blaue Karte EU (conditions plus souples que celles du titre classique).',
        ],
      },
      {
        num: 20,
        title: 'Erreurs fatales à éviter',
        summary: 'Ces erreurs reviennent chaque année et brisent des rêves d\'études. Évite-les scrupuleusement.',
        tag: 'Avertissements',
        bullets: [
          'Reporter l\'apprentissage de la langue à la dernière minute — elle te sera indispensable pour l\'inscription et la vie quotidienne.',
          'Ne candidater qu\'à une seule université — il en faut 5 à 10 minimum.',
          'Faire traduire tes documents par un traducteur non assermenté — ils seront refusés.',
          'Tarder à ouvrir un Sperrkonto — impossible de prendre rendez-vous à l\'ambassade sans ça.',
          'Travailler plus de 140 jours et le déclarer aux impôts = refus de renouvellement du séjour.',
          'Ne pas faire son Anmeldung dans les 2 semaines suivant l\'arrivée — amende pouvant atteindre 1000 €.',
        ],
        tip: 'Rejoins les groupes Facebook d\'étudiants marocains en Allemagne — 90 % des erreurs se détectent avec une seule question avant de les commettre.',
      },
    ],
  },
  en: {
    metaTitle: 'Universities and studying in Germany — the complete guide',
    metaDesc: '20 articles on applying to German universities, scholarships, visas, and student life.',
    eyebrow: 'University studies',
    title: 'Universities in Germany',
    subtitle: 'A full roadmap for every Moroccan student considering university in Germany — from baccalaureate recognition to master\'s graduation.',
    intro: '20 concise articles answering the real questions thousands of Moroccans ask every year: how do I choose a university? How long does it take? How do I fund myself? Is my language level enough?',
    items: [
      {
        num: 1,
        title: 'Why Germany and not another European country?',
        summary: 'Studying in Germany is nearly free, and the job market opens its doors to graduates straight away. But you need to know what to expect.',
        tag: 'Introduction',
        bullets: [
          'Public universities charge no tuition fees (except Baden-Württemberg for international students: €1500/semester).',
          'The Semesterbeitrag (semester fee) is €150–350 and often includes a free transport pass in some states.',
          'A globally recognised degree and a German job market hungry for skills.',
          'An 18-month residence permit guaranteed after graduation to look for work.',
        ],
        tip: 'Canada and France have shorter application processes, but Germany is cheaper over 5 years of study.',
      },
      {
        num: 2,
        title: 'Universität vs Fachhochschule (FH/HAW)',
        summary: 'The difference is fundamental and affects your career. Choose based on your field and ambition, not on the name.',
        tag: 'Types',
        bullets: [
          '**Universität (Uni):** research-oriented, theoretical, leads to a PhD, suited for fundamental sciences, medicine and law.',
          '**Fachhochschule (FH/HAW):** applied, real projects, compulsory internship, faster route to the job market.',
          'Kunsthochschule / Musikhochschule: for artists and musicians, with a specific entrance exam.',
          'Duale Hochschule: combines university and a company (a paid track).',
        ],
      },
      {
        num: 3,
        title: 'The best-known German universities and their rankings',
        summary: 'The top universities aren\'t the easiest to get into. Check the rankings but choose based on your programme.',
        tag: 'Ranking',
        bullets: [
          '**TU München, LMU München:** strongest in sciences and technology.',
          '**Heidelberg, Göttingen, Tübingen:** deep research tradition in medicine and the humanities.',
          '**RWTH Aachen, KIT Karlsruhe, TU Berlin:** engineering and computer science.',
          '**Humboldt, FU Berlin:** social sciences and humanities.',
          '**Mannheim, Frankfurt:** economics and finance.',
        ],
        tip: 'Shanghai and THE rankings are useful for information, but German hiring panels rarely pay them much attention.',
      },
      {
        num: 4,
        title: 'Recognising the Moroccan baccalaureate (uni-assist)',
        summary: 'Before applying anywhere, you must have your diploma evaluated via uni-assist or directly by the university. This is always the first step.',
        tag: 'Recognition',
        bullets: [
          'The Moroccan baccalaureate usually doesn\'t equal the German Abitur directly — you\'ll need a Studienkolleg or a university year.',
          'uni-assist evaluates your file and issues a VPD (Vorprüfungsdokumentation) you can reuse across applications.',
          'Fees: €75 for the first university + €30 per additional university in the same semester.',
          'Some universities (TUM, Heidelberg) evaluate in-house without uni-assist.',
        ],
      },
      {
        num: 5,
        title: 'Studienkolleg — the mandatory preparatory year',
        summary: 'If you haven\'t done a university year in Morocco, you\'ll need a Studienkolleg first. An intensive year ending in the Feststellungsprüfung exam.',
        tag: 'Preparatory',
        bullets: [
          'Duration: one year, free at public universities.',
          'Tracks: T (technical), M (medical), W (economics), G (languages), S (social sciences).',
          'You need B1-B2 German for admission + an entrance exam (Aufnahmeprüfung).',
          'After passing the Feststellungsprüfung, your diploma is treated as a German Abitur.',
        ],
        tip: 'If you successfully completed a university year in Morocco, you may skip the Studienkolleg and enter a bachelor\'s programme directly.',
      },
      {
        num: 6,
        title: 'Language requirements: DSH, TestDaF, TELC, Goethe',
        summary: 'B2 usually isn\'t enough for German-taught programmes. You\'ll need a certified C1 through one of these tests.',
        tag: 'Language',
        bullets: [
          '**TestDaF:** the most recognised internationally, accepted by every university. Required level: TDN 4 in every section.',
          '**DSH-2 or DSH-3:** an exam run by the university itself, often free.',
          '**Goethe-Zertifikat C1/C2:** broadly accepted, relatively expensive (€230).',
          '**TELC C1 Hochschule:** a good alternative, cheaper.',
          'Some universities waive the exam if you have a C1 certificate + a specified TOEFL level for mixed-language programmes.',
        ],
      },
      {
        num: 7,
        title: 'English-taught programmes — the fast alternative',
        summary: 'Over 2000 German programmes are offered in English, especially at master\'s level. No German required for admission.',
        tag: 'English',
        bullets: [
          'DAAD.de has a full database of English-taught programmes.',
          'IELTS 6.5 or TOEFL 90 is the usual minimum.',
          'There are far more master\'s programmes in English than bachelor\'s.',
          'Most common fields: engineering, computer science, economics, environmental sciences.',
        ],
        tip: 'Even if you study in English, learn German in parallel — you\'ll need it for daily life and part-time work.',
      },
      {
        num: 8,
        title: 'Application steps — a timeline',
        summary: 'A realistic plan: start about a year before classes begin to avoid stress and mistakes.',
        tag: 'Steps',
        bullets: [
          '12 months before: research programmes, start learning the language.',
          '9 months before: translate and certify your documents + uni-assist.',
          '6 months before: submit applications (Wintersemester deadline: 15 July).',
          '4 months before: book your embassy appointment + prepare your financial proof.',
          '2 months before: book student housing + health insurance.',
        ],
      },
      {
        num: 9,
        title: 'The motivation letter (Motivationsschreiben)',
        summary: 'The most important document in your file. It should tell a clear story: why you, why this programme, why this university.',
        tag: 'File',
        bullets: [
          'One page (400–500 words) in German or English, depending on the programme language.',
          'Start with a personal event that sparked your interest — not with "I have always been interested".',
          'Connect every paragraph to specific courses in the programme.',
          'End with a 5-year plan after graduation.',
        ],
        tip: 'Have your letter reviewed by a professor + a friend + a native German speaker before sending — language mistakes are fatal.',
      },
      {
        num: 10,
        title: 'Proof of funding (Finanzierungsnachweis)',
        summary: 'Germany requires proof you can live for a full year. Without it, no visa. The amount is fixed and updated yearly.',
        tag: 'Funding',
        bullets: [
          'Current amount: €11,904 (2024) in a Sperrkonto (blocked account) in your name.',
          'The blocked account allows only monthly withdrawals (~€992/month).',
          'Alternatives: official scholarship, commitment by a German resident (Verpflichtungserklärung), bank guarantee.',
          'Most used Sperrkonto services: Expatrio, Fintiba, Coracle (all approved).',
        ],
      },
      {
        num: 11,
        title: 'The DAAD scholarship — the biggest and best-known',
        summary: 'The German Academic Exchange Service offers hundreds of scholarships every year. Competitive but realistic.',
        tag: 'Scholarships',
        bullets: [
          'Full master\'s scholarships (€850/month + fees + insurance + ticket).',
          'PhD scholarships (€1200/month + family).',
          'Short research grants (3–6 months) during your studies.',
          'You usually apply a year before the scholarship starts.',
        ],
        tip: 'The key to your DAAD file: the research proposal. Read your potential supervisor\'s work before writing it.',
      },
      {
        num: 12,
        title: 'Political foundation scholarships (Stiftungen)',
        summary: '13 German political foundations offer scholarships to international students. Less competitive than DAAD, just as generous.',
        tag: 'Scholarships',
        bullets: [
          '**Konrad-Adenauer:** Christian-democratic.',
          '**Friedrich-Ebert:** social-democratic.',
          '**Heinrich-Böll:** green/ecological.',
          '**Rosa-Luxemburg:** left-wing.',
          '**Friedrich-Naumann:** liberal.',
          'Every foundation expects ideological alignment + academic excellence + volunteer work.',
        ],
      },
      {
        num: 13,
        title: 'The student visa — from application to issue',
        summary: 'The study visa (C or D) is issued by the German embassy. Waiting times can reach 3 months during peak summer.',
        tag: 'Visa',
        bullets: [
          'Two types: Visum zur Studienbewerbung (application-stage) and Visum zu Studienzwecken (admission confirmed).',
          'Book the appointment via maroc.diplo.de — very early.',
          'Documents: university admission, proof of funding, health insurance, translations of every document.',
          'Fee: €75. Usually issued for 3 months, then converted into an Aufenthaltstitel.',
        ],
      },
      {
        num: 14,
        title: 'Student health insurance',
        summary: 'Health insurance is mandatory to enrol at university. Under 30: public (GKV). Over 30: private (PKV).',
        tag: 'Insurance',
        bullets: [
          'Public insurance (TK, AOK, Barmer): ~€120/month for students, covering almost everything.',
          'Private insurance: sometimes cheaper, but limited in scope.',
          'Travel insurances (Mawista, Dr. Walter) are only accepted for up to 2 months, then you must switch.',
          'TK is the most popular among international students — decent English website and support.',
        ],
      },
      {
        num: 15,
        title: 'Student housing (Studentenwohnheim)',
        summary: 'The cheapest option, but waiting lists are long. Apply as soon as you receive your admission letter.',
        tag: 'Housing',
        bullets: [
          'The Studierendenwerk runs it — every city has its own website.',
          'Rent: €180–400 all bills included.',
          'Waiting lists: 3–12 months in big cities.',
          'Alternatives: WG (shared flat) via wg-gesucht.de.',
          'Beware of scams — never pay before visiting the flat or seeing the contract.',
        ],
        tip: 'For your first week, book a Jugendherberge or an Airbnb, and never accept a flat under time pressure. A rushed decision = a long nightmare.',
      },
      {
        num: 16,
        title: 'Semester enrolment and student card',
        summary: 'Once you arrive, you must complete the Immatrikulation (official enrolment). You\'ll receive a Studentenausweis and a transport card.',
        tag: 'Enrolment',
        bullets: [
          'Bring: passport, visa, Anmeldung, insurance proof, Semesterbeitrag payment receipt.',
          'Enrolment gives you a Matrikelnummer — keep it for life.',
          'The student card gives discounts at museums, cinemas and sports clubs.',
          'In many states: free semester transport pass within the region.',
        ],
      },
      {
        num: 17,
        title: 'Working during your studies — the legal limits',
        summary: 'International students can work 140 full days or 280 half-days per year. Going beyond that = problems renewing your residence permit.',
        tag: 'Work',
        bullets: [
          'Werkstudent: a specific student contract, up to 20 hours/week during the semester.',
          'Minijob: up to €538/month with no tax or insurance contributions.',
          'HiWi (research assistant): the best job inside the university, decent pay and experience.',
          'During holidays, you can work Vollzeit (full-time) for up to two full months.',
        ],
      },
      {
        num: 18,
        title: 'BAföG for international students',
        summary: 'A government financial aid — half grant, half interest-free loan. Strict conditions for foreigners, but possible.',
        tag: 'Funding',
        bullets: [
          'International students qualify after 5 years of work in Germany or with a resident parent.',
          'Refugees and holders of a Niederlassungserlaubnis qualify directly.',
          'Monthly ceiling: ~€934 (2024).',
          'Repayment starts 5 years after the end of studies.',
        ],
      },
      {
        num: 19,
        title: 'Aufenthaltstitel after graduation',
        summary: 'After finishing your studies, you\'re entitled to 18 months to find a job. Make the most of that window.',
        tag: 'After graduation',
        bullets: [
          'Submit the residence-permit conversion 6 weeks before your study visa expires.',
          'Bring: diploma, proof of funding (Sperrkonto or job).',
          'During the search, you can work without restrictions (Vollzeit).',
          'Once you find a job matching your field, you switch to a Blaue Karte EU (easier conditions than the standard permit).',
        ],
      },
      {
        num: 20,
        title: 'Fatal mistakes to avoid',
        summary: 'These mistakes repeat every year and end study dreams. Avoid them carefully.',
        tag: 'Warnings',
        bullets: [
          'Leaving language learning until the last minute — you\'ll need it for enrolment and daily life.',
          'Applying to only one university — aim for 5 to 10 at the very least.',
          'Having documents translated by a non-sworn translator — they will be rejected.',
          'Delaying opening a Sperrkonto — no embassy appointment is possible without it.',
          'Working more than 140 days and declaring it on your taxes = permit renewal refused.',
          'Missing the Anmeldung within two weeks of arrival — fines up to €1000.',
        ],
        tip: 'Join Facebook groups for Moroccan students in Germany — 90% of mistakes are spotted with a single question before they happen.',
      },
    ],
  },
  de: {
    metaTitle: 'Universitäten und Studium in Deutschland — der komplette Leitfaden',
    metaDesc: '20 Artikel zu Bewerbung, Stipendien, Visum und Studienalltag an deutschen Universitäten.',
    eyebrow: 'Hochschulstudium',
    title: 'Universitäten in Deutschland',
    subtitle: 'Ein kompletter Fahrplan für jeden marokkanischen Studierenden, der in Deutschland studieren möchte — von der Anerkennung des Abiturs bis zum Masterabschluss.',
    intro: '20 kompakte Artikel mit Antworten auf die echten Fragen, die tausende Marokkaner jedes Jahr stellen: Wie wähle ich meine Uni? Wie lange dauert es? Wie finanziere ich mich? Reichen meine Sprachkenntnisse?',
    items: [
      {
        num: 1,
        title: 'Warum Deutschland und nicht ein anderes europäisches Land?',
        summary: 'Ein Studium in Deutschland ist fast kostenlos, und der Arbeitsmarkt öffnet Absolventen sofort die Türen. Aber du musst wissen, was dich erwartet.',
        tag: 'Einführung',
        bullets: [
          'Staatliche Hochschulen erheben keine Studiengebühren (Ausnahme Baden-Württemberg für internationale Studierende: 1500 €/Semester).',
          'Der Semesterbeitrag liegt zwischen 150–350 € und enthält in einigen Bundesländern ein kostenloses Semesterticket.',
          'Ein international anerkannter Abschluss und ein deutscher Arbeitsmarkt mit Fachkräftemangel.',
          'Nach dem Abschluss ist dir eine 18-monatige Aufenthaltserlaubnis zur Jobsuche garantiert.',
        ],
        tip: 'Kanada und Frankreich haben kürzere Bewerbungswege, aber Deutschland ist über 5 Studienjahre günstiger.',
      },
      {
        num: 2,
        title: 'Universität vs Fachhochschule (FH/HAW)',
        summary: 'Der Unterschied ist entscheidend und beeinflusst deinen Berufsweg. Wähle nach Fachrichtung und Ziel, nicht nach dem Namen.',
        tag: 'Typen',
        bullets: [
          '**Universität (Uni):** forschungsorientiert, theoretisch, promotionsfähig, geeignet für Grundlagenwissenschaften, Medizin und Jura.',
          '**Fachhochschule (FH/HAW):** praxisorientiert, echte Projekte, Pflichtpraktikum, schnellerer Weg in den Arbeitsmarkt.',
          'Kunsthochschule / Musikhochschule: für Künstler und Musiker mit spezieller Aufnahmeprüfung.',
          'Duale Hochschule: kombiniert Hochschule und Unternehmen (bezahltes Modell).',
        ],
      },
      {
        num: 3,
        title: 'Die bekanntesten deutschen Universitäten und ihr Ranking',
        summary: 'Die besten Unis sind nicht die leichtesten beim Zulassungsverfahren. Schau auf Rankings, aber entscheide dich nach deinem Studiengang.',
        tag: 'Ranking',
        bullets: [
          '**TU München, LMU München:** die stärksten in Naturwissenschaften und Technik.',
          '**Heidelberg, Göttingen, Tübingen:** Forschungstradition in Medizin und Geisteswissenschaften.',
          '**RWTH Aachen, KIT Karlsruhe, TU Berlin:** Ingenieurwesen und Informatik.',
          '**Humboldt, FU Berlin:** Sozial- und Geisteswissenschaften.',
          '**Mannheim, Frankfurt:** Wirtschaft und Finanzen.',
        ],
        tip: 'Das Shanghai- und THE-Ranking ist als Info gut, aber deutsche Personaler schauen kaum darauf.',
      },
      {
        num: 4,
        title: 'Anerkennung des marokkanischen Abiturs (uni-assist)',
        summary: 'Vor jeder Bewerbung musst du dein Zeugnis über uni-assist oder direkt bei der Hochschule bewerten lassen. Das ist immer der erste Schritt.',
        tag: 'Anerkennung',
        bullets: [
          'Das marokkanische Abitur entspricht meist nicht direkt dem deutschen Abitur — du brauchst in der Regel ein Studienkolleg oder ein Studienjahr.',
          'uni-assist prüft deine Unterlagen und stellt eine VPD (Vorprüfungsdokumentation) aus, die du für mehrere Bewerbungen nutzen kannst.',
          'Gebühren: 75 € für die erste Hochschule + 30 € pro weiterer Hochschule im selben Semester.',
          'Manche Hochschulen (TUM, Heidelberg) prüfen selbst, ohne uni-assist.',
        ],
      },
      {
        num: 5,
        title: 'Studienkolleg — das verpflichtende Vorbereitungsjahr',
        summary: 'Wenn du in Marokko kein Studienjahr absolviert hast, brauchst du vorher ein Studienkolleg. Ein intensives Jahr, das mit der Feststellungsprüfung endet.',
        tag: 'Vorbereitung',
        bullets: [
          'Dauer: ein Jahr, an staatlichen Hochschulen kostenlos.',
          'Kurse: T (technisch), M (medizinisch), W (wirtschaftlich), G (sprachlich), S (sozialwissenschaftlich).',
          'Du brauchst B1-B2 Deutsch für die Zulassung + eine Aufnahmeprüfung.',
          'Nach bestandener Feststellungsprüfung zählt dein Zeugnis wie ein deutsches Abitur.',
        ],
        tip: 'Wenn du in Marokko ein Studienjahr erfolgreich abgeschlossen hast, kannst du das Studienkolleg eventuell überspringen und direkt in den Bachelor einsteigen.',
      },
      {
        num: 6,
        title: 'Sprachanforderungen: DSH, TestDaF, TELC, Goethe',
        summary: 'B2 reicht für deutschsprachige Programme meistens nicht. Du brauchst ein zertifiziertes C1 über eine dieser Prüfungen.',
        tag: 'Sprache',
        bullets: [
          '**TestDaF:** international am bekanntesten, an allen Hochschulen akzeptiert. Erforderliches Niveau: TDN 4 in allen Teilen.',
          '**DSH-2 oder DSH-3:** Prüfung der Hochschule selbst, meist kostenlos.',
          '**Goethe-Zertifikat C1/C2:** breit anerkannt, aber relativ teuer (230 €).',
          '**TELC C1 Hochschule:** gute Alternative, günstiger.',
          'Einige Hochschulen befreien von der Prüfung bei C1-Zertifikat + definiertem TOEFL-Level für gemischtsprachige Programme.',
        ],
      },
      {
        num: 7,
        title: 'Englischsprachige Programme — die schnelle Alternative',
        summary: 'Über 2000 deutsche Studiengänge auf Englisch, vor allem im Master. Für die Zulassung brauchst du kein Deutsch.',
        tag: 'Englisch',
        bullets: [
          'DAAD.de hat eine vollständige Datenbank englischsprachiger Programme.',
          'IELTS 6.5 oder TOEFL 90 sind das übliche Minimum.',
          'Englische Master sind viel zahlreicher als Bachelor-Programme.',
          'Am häufigsten vertreten: Ingenieurwesen, Informatik, Wirtschaft, Umweltwissenschaften.',
        ],
        tip: 'Auch wenn du auf Englisch studierst, lerne parallel Deutsch — du brauchst es im Alltag und beim Nebenjob.',
      },
      {
        num: 8,
        title: 'Bewerbungsschritte — ein Zeitplan',
        summary: 'Ein realistischer Plan: Fang etwa ein Jahr vor Studienbeginn an, um Stress und Fehler zu vermeiden.',
        tag: 'Schritte',
        bullets: [
          '12 Monate vorher: Studiengänge recherchieren, mit dem Sprachenlernen beginnen.',
          '9 Monate vorher: Unterlagen übersetzen und beglaubigen lassen + uni-assist.',
          '6 Monate vorher: Bewerbungen einreichen (Frist Wintersemester: 15. Juli).',
          '4 Monate vorher: Botschaftstermin buchen + Finanzierungsnachweis vorbereiten.',
          '2 Monate vorher: Studentenwohnheim + Krankenversicherung buchen.',
        ],
      },
      {
        num: 9,
        title: 'Das Motivationsschreiben',
        summary: 'Das wichtigste Dokument in deiner Bewerbung. Es muss eine klare Geschichte erzählen: warum du, warum dieser Studiengang, warum diese Hochschule.',
        tag: 'Unterlagen',
        bullets: [
          'Eine Seite (400–500 Wörter) auf Deutsch oder Englisch je nach Programmsprache.',
          'Beginne mit einem persönlichen Erlebnis, das dein Interesse geweckt hat — nicht mit „I have always been interested".',
          'Verknüpfe jeden Absatz mit konkreten Modulen des Studiengangs.',
          'Schließe mit einem 5-Jahres-Plan nach dem Abschluss.',
        ],
        tip: 'Lass dein Motivationsschreiben von einem Professor + Freund + deutschem Muttersprachler gegenlesen — Sprachfehler sind tödlich.',
      },
      {
        num: 10,
        title: 'Finanzierungsnachweis',
        summary: 'Deutschland verlangt einen Nachweis, dass du ein Jahr lang leben kannst. Ohne ihn kein Visum. Der Betrag ist fix und wird jährlich angepasst.',
        tag: 'Finanzierung',
        bullets: [
          'Aktueller Betrag: 11.904 € (2024) auf einem Sperrkonto auf deinen Namen.',
          'Das Sperrkonto erlaubt nur monatliche Auszahlungen (~992 €/Monat).',
          'Alternativen: offizielles Stipendium, Verpflichtungserklärung eines in Deutschland Ansässigen, Bankbürgschaft.',
          'Bekannteste Sperrkonto-Anbieter: Expatrio, Fintiba, Coracle (alle anerkannt).',
        ],
      },
      {
        num: 11,
        title: 'DAAD-Stipendium — das größte und bekannteste',
        summary: 'Der Deutsche Akademische Austauschdienst vergibt jährlich hunderte Stipendien. Kompetitiv, aber realistisch.',
        tag: 'Stipendien',
        bullets: [
          'Voll finanzierte Masterstipendien (850 €/Monat + Gebühren + Versicherung + Ticket).',
          'Promotionsstipendien (1200 €/Monat + Familie).',
          'Kurzstipendien für Forschung (3–6 Monate) während des Studiums.',
          'Die Bewerbung erfolgt üblicherweise ein Jahr vor Stipendienbeginn.',
        ],
        tip: 'Das Kernstück deiner DAAD-Bewerbung: das Research Proposal. Lies die Arbeiten deines potenziellen Betreuers, bevor du es schreibst.',
      },
      {
        num: 12,
        title: 'Stipendien politischer Stiftungen',
        summary: '13 deutsche politische Stiftungen bieten Stipendien für internationale Studierende. Weniger kompetitiv als DAAD, genauso großzügig.',
        tag: 'Stipendien',
        bullets: [
          '**Konrad-Adenauer:** christdemokratisch.',
          '**Friedrich-Ebert:** sozialdemokratisch.',
          '**Heinrich-Böll:** ökologisch.',
          '**Rosa-Luxemburg:** links.',
          '**Friedrich-Naumann:** liberal.',
          'Jede Stiftung erwartet ideologische Nähe + akademische Exzellenz + ehrenamtliches Engagement.',
        ],
      },
      {
        num: 13,
        title: 'Studentenvisum — von der Beantragung bis zum Erhalt',
        summary: 'Das Studienvisum (C oder D) wird von der deutschen Botschaft ausgestellt. In der Sommerhochsaison kann die Wartezeit bis zu 3 Monate betragen.',
        tag: 'Visum',
        bullets: [
          'Zwei Arten: Visum zur Studienbewerbung und Visum zu Studienzwecken (Zulassung bestätigt).',
          'Termin über maroc.diplo.de buchen — sehr früh.',
          'Unterlagen: Zulassung, Finanzierungsnachweis, Krankenversicherung, Übersetzungen aller Dokumente.',
          'Gebühr: 75 €. Üblicherweise für 3 Monate ausgestellt und dann in einen Aufenthaltstitel umgewandelt.',
        ],
      },
      {
        num: 14,
        title: 'Krankenversicherung für Studierende',
        summary: 'Die Krankenversicherung ist Pflicht für die Immatrikulation. Unter 30: gesetzlich (GKV). Über 30: privat (PKV).',
        tag: 'Versicherung',
        bullets: [
          'Gesetzliche Versicherung (TK, AOK, Barmer): ~120 €/Monat für Studierende, deckt fast alles ab.',
          'Private Versicherung: manchmal günstiger, aber eingeschränkter.',
          'Reiseversicherungen (Mawista, Dr. Walter) werden nur bis zu 2 Monate akzeptiert, danach musst du wechseln.',
          'TK ist bei internationalen Studierenden am beliebtesten — ordentliche englische Website und Support.',
        ],
      },
      {
        num: 15,
        title: 'Studentenwohnheim',
        summary: 'Die günstigste Option, aber die Wartelisten sind lang. Bewirb dich sofort nach Erhalt der Zulassung.',
        tag: 'Wohnen',
        bullets: [
          'Studierendenwerk ist der Träger — jede Stadt hat ihre eigene Website.',
          'Miete: 180–400 € inklusive Nebenkosten.',
          'Wartelisten: 3–12 Monate in Großstädten.',
          'Alternativen: WG (Wohngemeinschaft) über wg-gesucht.de.',
          'Achtung vor Betrug — zahle niemals, bevor du die Wohnung besichtigt oder den Vertrag gesehen hast.',
        ],
        tip: 'Buche dir für die erste Woche eine Jugendherberge oder ein Airbnb und nimm keine Wohnung unter Zeitdruck. Schnelle Entscheidung = lange Qual.',
      },
      {
        num: 16,
        title: 'Semesterimmatrikulation und Studentenausweis',
        summary: 'Nach der Ankunft musst du die Immatrikulation abschließen. Du erhältst einen Studentenausweis und ein Verkehrsticket.',
        tag: 'Immatrikulation',
        bullets: [
          'Mitnehmen: Reisepass, Visum, Anmeldung, Versicherungsnachweis, Zahlungsbeleg des Semesterbeitrags.',
          'Mit der Immatrikulation bekommst du eine Matrikelnummer — merk sie dir fürs Leben.',
          'Der Studentenausweis bringt Rabatte in Museen, Kinos und Sportclubs.',
          'In vielen Bundesländern: kostenloses Semesterticket innerhalb der Region.',
        ],
      },
      {
        num: 17,
        title: 'Nebenjob während des Studiums — die rechtlichen Grenzen',
        summary: 'Internationale Studierende dürfen 140 volle Tage oder 280 halbe Tage pro Jahr arbeiten. Mehr = Probleme bei der Verlängerung des Aufenthaltstitels.',
        tag: 'Arbeit',
        bullets: [
          'Werkstudent: spezieller Studierendenvertrag, bis zu 20 Stunden/Woche während des Semesters.',
          'Minijob: bis zu 538 €/Monat ohne Steuern und Sozialabgaben.',
          'HiWi (wissenschaftliche Hilfskraft): der beste Job an der Uni, ordentliche Bezahlung und Erfahrung.',
          'In den Semesterferien darfst du zwei volle Monate in Vollzeit arbeiten.',
        ],
      },
      {
        num: 18,
        title: 'BAföG für internationale Studierende',
        summary: 'Staatliche Förderung — halb Zuschuss, halb zinsloses Darlehen. Strenge Bedingungen für Ausländer, aber möglich.',
        tag: 'Finanzierung',
        bullets: [
          'Internationale Studierende sind nach 5 Jahren Arbeit in Deutschland oder mit einem dort wohnhaften Elternteil berechtigt.',
          'Geflüchtete und Inhaber einer Niederlassungserlaubnis sind direkt berechtigt.',
          'Monatlicher Höchstsatz: ~934 € (2024).',
          'Die Rückzahlung beginnt 5 Jahre nach Studienende.',
        ],
      },
      {
        num: 19,
        title: 'Aufenthaltstitel nach dem Abschluss',
        summary: 'Nach dem Studium stehen dir 18 Monate zur Jobsuche zu. Nutze dieses Fenster gut.',
        tag: 'Nach dem Abschluss',
        bullets: [
          'Beantrage die Umwandlung des Aufenthaltstitels 6 Wochen vor Ablauf des Studienvisums.',
          'Mitbringen: Abschlusszeugnis, Finanzierungsnachweis (Sperrkonto oder Job).',
          'Während der Suche darfst du uneingeschränkt arbeiten (Vollzeit).',
          'Sobald du einen zu deinem Abschluss passenden Job findest, wechselst du auf die Blaue Karte EU (einfachere Bedingungen als der reguläre Titel).',
        ],
      },
      {
        num: 20,
        title: 'Fatale Fehler, die du vermeiden musst',
        summary: 'Diese Fehler wiederholen sich jedes Jahr und beenden Studienträume. Vermeide sie konsequent.',
        tag: 'Warnungen',
        bullets: [
          'Das Sprachenlernen bis zur letzten Minute aufschieben — du brauchst die Sprache für die Immatrikulation und den Alltag.',
          'Sich nur an einer Hochschule bewerben — es sollten mindestens 5–10 Bewerbungen sein.',
          'Unterlagen von einem nicht vereidigten Übersetzer übersetzen lassen — sie werden abgelehnt.',
          'Das Eröffnen des Sperrkontos hinauszögern — ohne geht kein Botschaftstermin.',
          'Mehr als 140 Tage arbeiten und es beim Finanzamt offenlegen = Ablehnung der Aufenthaltsverlängerung.',
          'Keine Anmeldung innerhalb von zwei Wochen nach Ankunft — Bußgelder bis 1000 €.',
        ],
        tip: 'Tritt Facebook-Gruppen marokkanischer Studierender in Deutschland bei — 90 % der Fehler lassen sich mit einer einzigen Frage vorher vermeiden.',
      },
    ],
  },
}

const tipLabelByLoc = {
  ar: 'نصيحة',
  fr: 'Astuce',
  en: 'Tip',
  de: 'Tipp',
}

for (const loc of LOCALES) {
  const file = path.join(MESSAGES_DIR, `${loc}.json`)
  const raw = fs.readFileSync(file, 'utf8')
  const j = JSON.parse(raw)
  j.static = j.static || {}
  j.static.universities = byLoc[loc]
  j.common = j.common || {}
  if (!j.common.tipLabel) {
    j.common.tipLabel = tipLabelByLoc[loc]
  }
  fs.writeFileSync(file, JSON.stringify(j, null, 2) + '\n', 'utf8')
  console.log(`[universities] updated ${loc}.json`)
}

console.log('Done.')
