const fs = require('fs')
const path = require('path')

const ns = {
  ar: {
    pageTitle: 'تعلم اللغة الألمانية',
    pageSubtitle: 'من الصفر إلى الاحتراف — دروس مبنية خصيصاً للمغاربة، من A1 إلى C1.',
    chooseLevel: 'اختر مستواك',
    levels: {
      lessonsCount: '{n} دروس',
      comingSoon: 'قريباً',
      resume: 'متابعة ←',
      start: 'ابدأ الآن ←',
      completeFirst: 'أكمل {prev} أولاً',
      progressCount: '{done} / {total} دروس',
    },
    level: {
      backToLevels: '→ العودة إلى المستويات',
      lessonsHeading: 'الدروس',
      progress: 'التقدم',
      progressCount: '{done} / {total} دروس',
      resumeHere: '▶ متابعة من حيث توقفت — {title}',
      lessonMeta: {
        grammar: '📖 قواعد',
        vocab: '📝 مفردات ({n})',
        exercise: '✏️ تمرين ({n} أسئلة)',
      },
    },
    lesson: {
      breadcrumbAria: 'breadcrumb',
      tabs: { grammar: 'القواعد', vocab: 'المفردات', exercise: 'التمارين' },
      meta: '{n}. درس · {vocab} كلمة · {q} تمرين',
      grammarCard: {
        subtitle: 'قواعد الدرس',
        tables: 'جداول القواعد',
        rules: 'القواعد الأساسية',
        tipTitle: 'نصيحة ذهبية',
        examples: 'أمثلة تطبيقية',
        nextVocab: 'التالي: المفردات',
      },
      vocabCard: {
        heading: 'المفردات',
        sub: '{n} كلمة · اضغط على أي بطاقة لرؤية الترجمة',
        searchPh: 'ابحث...',
        noResults: 'لا توجد نتائج للبحث',
        nextEx: 'التالي: التمارين',
        gender: { der: 'مذكر', die: 'مؤنث', das: 'محايد', pl: 'جمع' },
      },
      types: {
        noun: 'اسم', verb: 'فعل', adjective: 'صفة', adverb: 'ظرف',
        phrase: 'عبارة', preposition: 'حرف جر', conjunction: 'أداة ربط',
        pronoun: 'ضمير', number: 'رقم',
      },
      exerciseCard: {
        progress: 'التقدم',
        types: {
          mcq: 'اختيار من متعدد', fill: 'أكمل الفراغ',
          drag: 'رتب الكلمات', match: 'صل بين الكلمات', speak: '🎤 تحدث',
        },
        fillPh: 'اكتب إجابتك هنا...',
        correctAnswer: '✅ الإجابة الصحيحة: ',
        correct: '✅ إجابة صحيحة!',
        submit: 'تحقق من الإجابات ({done}/{total})',
        scoreExcellent: 'ممتاز! أتقنت هذا الدرس بجدارة 🌟',
        scorePass: 'أحسنت! يمكنك الانتقال للدرس التالي.',
        scoreRetry: 'حاول مراجعة القواعد والمفردات والمحاولة مجدداً.',
        nextLesson: 'الدرس التالي: {title} ←',
        levelDone: '🎉 أكملت المستوى! العودة ←',
        tryAgain: 'حاول مجدداً',
        reviewAnswers: 'راجع الإجابات',
      },
    },
    dragDrop: {
      hint: 'اضغط على الكلمات لترتيب الجملة...',
      correctAnswer: '✅ الإجابة الصحيحة: ',
      excellent: '✅ ممتاز! الترتيب صحيح.',
    },
    matching: { de: '🇩🇪 Deutsch', ar: '🇲🇦 العربية' },
    speaking: {
      press: 'اضغط وتكلم بالألمانية',
      listening: 'جاري الاستماع... اضغط للإيقاف',
      success: 'ممتاز! النطق صحيح',
      retry: 'حاول مرة أخرى',
      heard: 'سمعت: ',
      retryBtn: 'إعادة المحاولة',
      tryAgain: 'حاول مجدداً',
      unsupported: '⚠️ متصفحك لا يدعم التعرف على الكلام. جرب Chrome أو Edge.',
    },
    audio: { listen: 'استمع للنطق' },
  },
  fr: {
    pageTitle: 'Apprendre l\'allemand',
    pageSubtitle: 'De zéro à pro — des cours conçus pour les Marocains, de A1 à C1.',
    chooseLevel: 'Choisissez votre niveau',
    levels: {
      lessonsCount: '{n} leçons',
      comingSoon: 'Bientôt',
      resume: 'Continuer →',
      start: 'Commencer →',
      completeFirst: 'Terminez d\'abord {prev}',
      progressCount: '{done} / {total} leçons',
    },
    level: {
      backToLevels: '← Retour aux niveaux',
      lessonsHeading: 'Leçons',
      progress: 'Progression',
      progressCount: '{done} / {total} leçons',
      resumeHere: '▶ Reprendre où vous vous êtes arrêté — {title}',
      lessonMeta: {
        grammar: '📖 Grammaire',
        vocab: '📝 Vocabulaire ({n})',
        exercise: '✏️ Exercice ({n} questions)',
      },
    },
    lesson: {
      breadcrumbAria: 'fil d\'Ariane',
      tabs: { grammar: 'Grammaire', vocab: 'Vocabulaire', exercise: 'Exercices' },
      meta: 'Leçon {n} · {vocab} mots · {q} exercices',
      grammarCard: {
        subtitle: 'Grammaire de la leçon',
        tables: 'Tableaux de grammaire',
        rules: 'Règles principales',
        tipTitle: 'Astuce en or',
        examples: 'Exemples pratiques',
        nextVocab: 'Suivant : Vocabulaire',
      },
      vocabCard: {
        heading: 'Vocabulaire',
        sub: '{n} mots · cliquez sur une carte pour voir la traduction',
        searchPh: 'Rechercher...',
        noResults: 'Aucun résultat',
        nextEx: 'Suivant : Exercices',
        gender: { der: 'masculin', die: 'féminin', das: 'neutre', pl: 'pluriel' },
      },
      types: {
        noun: 'nom', verb: 'verbe', adjective: 'adjectif', adverb: 'adverbe',
        phrase: 'expression', preposition: 'préposition', conjunction: 'conjonction',
        pronoun: 'pronom', number: 'nombre',
      },
      exerciseCard: {
        progress: 'Progression',
        types: {
          mcq: 'Choix multiple', fill: 'Complétez',
          drag: 'Remettez dans l\'ordre', match: 'Associez', speak: '🎤 Parler',
        },
        fillPh: 'Écrivez votre réponse ici...',
        correctAnswer: '✅ Bonne réponse : ',
        correct: '✅ Correct !',
        submit: 'Vérifier les réponses ({done}/{total})',
        scoreExcellent: 'Excellent ! Vous maîtrisez cette leçon 🌟',
        scorePass: 'Bien joué ! Vous pouvez passer à la leçon suivante.',
        scoreRetry: 'Revoyez la grammaire et le vocabulaire, puis réessayez.',
        nextLesson: 'Leçon suivante : {title} →',
        levelDone: '🎉 Niveau terminé ! Retour →',
        tryAgain: 'Réessayer',
        reviewAnswers: 'Revoir les réponses',
      },
    },
    dragDrop: {
      hint: 'Cliquez sur les mots pour ordonner la phrase...',
      correctAnswer: '✅ Bonne réponse : ',
      excellent: '✅ Excellent ! Ordre correct.',
    },
    matching: { de: '🇩🇪 Deutsch', ar: '🇲🇦 Français' },
    speaking: {
      press: 'Appuyez et parlez en allemand',
      listening: 'Écoute... appuyez pour arrêter',
      success: 'Excellent ! Prononciation correcte',
      retry: 'Réessayez',
      heard: 'Entendu : ',
      retryBtn: 'Réessayer',
      tryAgain: 'Réessayer',
      unsupported: '⚠️ Votre navigateur ne prend pas en charge la reconnaissance vocale. Essayez Chrome ou Edge.',
    },
    audio: { listen: 'Écouter la prononciation' },
  },
  en: {
    pageTitle: 'Learn German',
    pageSubtitle: 'From zero to pro — lessons built for Moroccans, from A1 to C1.',
    chooseLevel: 'Choose your level',
    levels: {
      lessonsCount: '{n} lessons',
      comingSoon: 'Coming soon',
      resume: 'Continue →',
      start: 'Start now →',
      completeFirst: 'Finish {prev} first',
      progressCount: '{done} / {total} lessons',
    },
    level: {
      backToLevels: '← Back to levels',
      lessonsHeading: 'Lessons',
      progress: 'Progress',
      progressCount: '{done} / {total} lessons',
      resumeHere: '▶ Resume where you stopped — {title}',
      lessonMeta: {
        grammar: '📖 Grammar',
        vocab: '📝 Vocabulary ({n})',
        exercise: '✏️ Exercise ({n} questions)',
      },
    },
    lesson: {
      breadcrumbAria: 'breadcrumb',
      tabs: { grammar: 'Grammar', vocab: 'Vocabulary', exercise: 'Exercises' },
      meta: 'Lesson {n} · {vocab} words · {q} exercises',
      grammarCard: {
        subtitle: 'Lesson grammar',
        tables: 'Grammar tables',
        rules: 'Core rules',
        tipTitle: 'Golden tip',
        examples: 'Worked examples',
        nextVocab: 'Next: Vocabulary',
      },
      vocabCard: {
        heading: 'Vocabulary',
        sub: '{n} words · tap any card to see the translation',
        searchPh: 'Search...',
        noResults: 'No results',
        nextEx: 'Next: Exercises',
        gender: { der: 'masculine', die: 'feminine', das: 'neuter', pl: 'plural' },
      },
      types: {
        noun: 'noun', verb: 'verb', adjective: 'adjective', adverb: 'adverb',
        phrase: 'phrase', preposition: 'preposition', conjunction: 'conjunction',
        pronoun: 'pronoun', number: 'number',
      },
      exerciseCard: {
        progress: 'Progress',
        types: {
          mcq: 'Multiple choice', fill: 'Fill the blank',
          drag: 'Arrange the words', match: 'Match', speak: '🎤 Speak',
        },
        fillPh: 'Type your answer here...',
        correctAnswer: '✅ Correct answer: ',
        correct: '✅ Correct!',
        submit: 'Check answers ({done}/{total})',
        scoreExcellent: 'Excellent! You nailed this lesson 🌟',
        scorePass: 'Nice! You can move to the next lesson.',
        scoreRetry: 'Review the grammar and vocabulary, then try again.',
        nextLesson: 'Next lesson: {title} →',
        levelDone: '🎉 Level complete! Back →',
        tryAgain: 'Try again',
        reviewAnswers: 'Review answers',
      },
    },
    dragDrop: {
      hint: 'Tap the words to build the sentence...',
      correctAnswer: '✅ Correct answer: ',
      excellent: '✅ Excellent! Correct order.',
    },
    matching: { de: '🇩🇪 Deutsch', ar: '🇲🇦 English' },
    speaking: {
      press: 'Tap and speak in German',
      listening: 'Listening... tap to stop',
      success: 'Excellent! Correct pronunciation',
      retry: 'Try again',
      heard: 'Heard: ',
      retryBtn: 'Retry',
      tryAgain: 'Try again',
      unsupported: '⚠️ Your browser doesn\'t support speech recognition. Try Chrome or Edge.',
    },
    audio: { listen: 'Listen to pronunciation' },
  },
  de: {
    pageTitle: 'Deutsch lernen',
    pageSubtitle: 'Von null zum Profi — Kurse für Marokkaner, von A1 bis C1.',
    chooseLevel: 'Wähle dein Niveau',
    levels: {
      lessonsCount: '{n} Lektionen',
      comingSoon: 'Demnächst',
      resume: 'Fortsetzen →',
      start: 'Jetzt starten →',
      completeFirst: 'Schließe zuerst {prev} ab',
      progressCount: '{done} / {total} Lektionen',
    },
    level: {
      backToLevels: '← Zurück zu den Niveaus',
      lessonsHeading: 'Lektionen',
      progress: 'Fortschritt',
      progressCount: '{done} / {total} Lektionen',
      resumeHere: '▶ Weitermachen bei — {title}',
      lessonMeta: {
        grammar: '📖 Grammatik',
        vocab: '📝 Vokabeln ({n})',
        exercise: '✏️ Übung ({n} Fragen)',
      },
    },
    lesson: {
      breadcrumbAria: 'Brotkrümel',
      tabs: { grammar: 'Grammatik', vocab: 'Vokabeln', exercise: 'Übungen' },
      meta: 'Lektion {n} · {vocab} Wörter · {q} Übungen',
      grammarCard: {
        subtitle: 'Grammatik der Lektion',
        tables: 'Grammatiktabellen',
        rules: 'Grundregeln',
        tipTitle: 'Goldener Tipp',
        examples: 'Beispielsätze',
        nextVocab: 'Weiter: Vokabeln',
      },
      vocabCard: {
        heading: 'Vokabeln',
        sub: '{n} Wörter · Tippe auf eine Karte für die Übersetzung',
        searchPh: 'Suchen...',
        noResults: 'Keine Ergebnisse',
        nextEx: 'Weiter: Übungen',
        gender: { der: 'maskulin', die: 'feminin', das: 'neutral', pl: 'Plural' },
      },
      types: {
        noun: 'Nomen', verb: 'Verb', adjective: 'Adjektiv', adverb: 'Adverb',
        phrase: 'Ausdruck', preposition: 'Präposition', conjunction: 'Konjunktion',
        pronoun: 'Pronomen', number: 'Zahl',
      },
      exerciseCard: {
        progress: 'Fortschritt',
        types: {
          mcq: 'Multiple Choice', fill: 'Lücke füllen',
          drag: 'Wörter ordnen', match: 'Zuordnen', speak: '🎤 Sprechen',
        },
        fillPh: 'Gib deine Antwort hier ein...',
        correctAnswer: '✅ Richtige Antwort: ',
        correct: '✅ Richtig!',
        submit: 'Antworten prüfen ({done}/{total})',
        scoreExcellent: 'Ausgezeichnet! Du hast diese Lektion gemeistert 🌟',
        scorePass: 'Gut gemacht! Du kannst zur nächsten Lektion.',
        scoreRetry: 'Schau dir Grammatik und Vokabeln noch einmal an und versuche es erneut.',
        nextLesson: 'Nächste Lektion: {title} →',
        levelDone: '🎉 Niveau abgeschlossen! Zurück →',
        tryAgain: 'Nochmal versuchen',
        reviewAnswers: 'Antworten ansehen',
      },
    },
    dragDrop: {
      hint: 'Tippe auf die Wörter, um den Satz zu bilden...',
      correctAnswer: '✅ Richtige Antwort: ',
      excellent: '✅ Ausgezeichnet! Richtige Reihenfolge.',
    },
    matching: { de: '🇩🇪 Deutsch', ar: '🇲🇦 Deutsch' },
    speaking: {
      press: 'Drücken und auf Deutsch sprechen',
      listening: 'Hört zu... drücken zum Stoppen',
      success: 'Ausgezeichnet! Korrekte Aussprache',
      retry: 'Versuche es nochmal',
      heard: 'Gehört: ',
      retryBtn: 'Erneut versuchen',
      tryAgain: 'Nochmal versuchen',
      unsupported: '⚠️ Dein Browser unterstützt keine Spracherkennung. Versuche Chrome oder Edge.',
    },
    audio: { listen: 'Aussprache anhören' },
  },
}

for (const loc of ['ar', 'fr', 'en', 'de']) {
  const p = path.join(__dirname, '..', 'messages', `${loc}.json`)
  const j = JSON.parse(fs.readFileSync(p, 'utf8'))
  j.learnGerman = ns[loc]
  fs.writeFileSync(p, JSON.stringify(j, null, 2) + '\n', 'utf8')
  console.log(`✓ ${loc}.json`)
}
