// Topic list for the SEO article batch.
// Each entry produces one article in 4 languages.
// `category` is the slug stored in the DB; we'll add i18n labels separately.
// `keyword` is the main long-tail SEO target (used in the generation prompt).
// `brief` is a 1-2 sentence pitch the model uses to anchor the angle.

export const ARTICLE_TOPICS = [
  // ── HEALTHCARE & INSURANCE (10) ──────────────────────────────
  { slug: 'public-health-insurance-ausbildung-germany',          category: 'healthcare', keyword: 'public health insurance Germany Ausbildung',                brief: 'Step-by-step explanation of how Gesetzliche Krankenversicherung (GKV) works for Ausbildung trainees: who pays, how much, what is covered, how to enroll on day one.' },
  { slug: 'public-vs-private-health-insurance-germany',          category: 'healthcare', keyword: 'public vs private health insurance Germany',                 brief: 'GKV vs PKV: who can choose, real cost differences, when private is worth it for an Ausbildung trainee, and the trap of switching back.' },
  { slug: 'find-hausarzt-foreigner-germany',                     category: 'healthcare', keyword: 'find a Hausarzt in Germany as a foreigner',                  brief: 'How to find a family doctor as a foreigner: Doctolib/Jameda, language-friendly practices, what to bring on the first visit, what tests are routine.' },
  { slug: 'dental-care-germany-ausbildung',                      category: 'healthcare', keyword: 'dental care Germany Ausbildung trainee cost',                brief: 'What public insurance covers in dental, what you pay out of pocket, when supplementary Zahnzusatzversicherung is worth it, finding a dentist.' },
  { slug: 'mental-health-support-germany-international',         category: 'healthcare', keyword: 'mental health Germany international trainee therapist',       brief: 'Routes to therapy through public insurance, finding Arabic/French/English-speaking therapists, online options, what to do in a crisis.' },
  { slug: 'krankschreibung-sick-leave-ausbildung',               category: 'healthcare', keyword: 'Krankschreibung Ausbildung sick leave Germany',              brief: 'How to call in sick during Ausbildung, when you need a doctor note, the new electronic AU process, what happens to your pay and vacation.' },
  { slug: 'pregnancy-mutterschutz-ausbildung-germany',           category: 'healthcare', keyword: 'pregnancy Mutterschutz Ausbildung Germany',                  brief: 'Pregnancy during Ausbildung: protections under Mutterschutzgesetz, prenatal care, financial support (Mutterschaftsgeld + Elterngeld), career impact.' },
  { slug: 'family-health-insurance-germany',                     category: 'healthcare', keyword: 'family health insurance Germany Familienversicherung',        brief: 'How spouses and children get free coverage under Familienversicherung, income limits, kids in Morocco, switching between providers.' },
  { slug: 'emergency-rooms-notaufnahme-germany',                 category: 'healthcare', keyword: 'Notaufnahme emergency room Germany when to go',              brief: 'When to call 112, when to go to Notaufnahme vs Notdienst, what to bring, how language barriers are handled, what to do for a non-life-threatening issue at night.' },
  { slug: 'switch-public-private-insurance-germany',             category: 'healthcare', keyword: 'switch from public to private insurance Germany',            brief: 'When you can switch (income threshold, Beamte status), what you gain or lose, and the one-way trap of going PKV during Ausbildung.' },

  // ── BUREAUCRACY (10) ─────────────────────────────────────────
  { slug: 'anmeldung-step-by-step-germany',                      category: 'bureaucracy', keyword: 'Anmeldung Germany step by step register address',           brief: 'Booking a Bürgeramt slot, the Wohnungsgeberbestätigung, what your landlord must sign, the Anmeldebescheinigung, and the 14-day legal deadline.' },
  { slug: 'renew-aufenthaltstitel-ausbildung',                   category: 'bureaucracy', keyword: 'renew Aufenthaltstitel Ausbildung Germany',                  brief: 'Booking the Ausländerbehörde, documents needed (contract, rental agreement, insurance proof), processing time, what to do if the slot is months away.' },
  { slug: 'anerkennung-moroccan-diploma-germany',                category: 'bureaucracy', keyword: 'Anerkennung Moroccan diploma Germany',                       brief: 'Recognizing your Moroccan high-school or vocational diploma: Zentralstelle für ausländisches Bildungswesen, Anabin database, fees, timelines.' },
  { slug: 'fuehrungszeugnis-criminal-record-certificate-germany', category: 'bureaucracy', keyword: 'Polizeiliches Führungszeugnis how to request',              brief: 'Online vs in-person request, Belegart-O for the Bürgeramt, Belegart-N for employers, fees, and how Moroccans can obtain a Moroccan equivalent for visa purposes.' },
  { slug: 'steuer-id-germany-explained',                         category: 'bureaucracy', keyword: 'Steuer-ID Germany how to get',                                brief: 'What the 11-digit Steueridentifikationsnummer is, when it arrives, why every German employer asks for it on day one, what to do if it gets lost.' },
  { slug: 'lohnsteuerklasse-ausbildung-trainees',                category: 'bureaucracy', keyword: 'Lohnsteuerklasse Ausbildung trainee right one',              brief: 'The 6 Steuerklassen explained, default classes for Ausbildung trainees, how marriage / kids change them, when switching saves real money.' },
  { slug: 'postident-id-verification-germany',                   category: 'bureaucracy', keyword: 'Postident ID verification Germany online bank',              brief: 'When you need Postident vs VideoIdent, what documents work for non-EU citizens, finding a Postfiliale, common rejection reasons.' },
  { slug: 'niederlassungserlaubnis-pr-after-ausbildung',         category: 'bureaucracy', keyword: 'Niederlassungserlaubnis after Ausbildung permanent residency', brief: 'The two-year fast-track post-Ausbildung, B1 language requirement, Rentenversicherung months, application docs and timing.' },
  { slug: 'change-address-ummeldung-germany',                    category: 'bureaucracy', keyword: 'Ummeldung change address Germany',                            brief: 'Moving to a new flat: Wohnungsgeberbestätigung from new landlord, deadline, how it cascades to taxes / car / GEZ / banks.' },
  { slug: 'family-reunification-visa-morocco-germany',           category: 'bureaucracy', keyword: 'family reunification visa Morocco Germany Familiennachzug',  brief: 'Bringing your spouse from Morocco: A1 German requirement, income proof, apartment-size rule, processing time at the Casablanca consulate.' },

  // ── FAMILY & LIFE EVENTS (8) ────────────────────────────────
  { slug: 'family-reunification-spouse-germany',                 category: 'family',     keyword: 'spouse visa Germany family reunification A1',                brief: 'The full Ehegattennachzug process for a Moroccan spouse: A1 certificate, Goethe vs telc, financial threshold, exemptions, real timelines.' },
  { slug: 'bringing-children-germany-school',                    category: 'family',     keyword: 'bring children Germany Ausbildung school',                    brief: 'Bringing minor children: Kindernachzug visa, school enrollment process, German classes for newcomer kids (Willkommensklasse), Kita waitlists.' },
  { slug: 'kindergeld-foreigner-application',                    category: 'family',     keyword: 'Kindergeld Germany foreigner application',                    brief: 'Who qualifies for Kindergeld as a non-EU resident, how to apply via Familienkasse, kids in Morocco vs in Germany, retroactive payments.' },
  { slug: 'elterngeld-during-ausbildung',                        category: 'family',     keyword: 'Elterngeld during Ausbildung parental leave',                 brief: 'Basic vs Plus Elterngeld, calculation for low Ausbildung income, partner months, how to combine with parental leave from work.' },
  { slug: 'kita-system-germany-find-spot',                       category: 'family',     keyword: 'Kita Germany find daycare spot',                              brief: 'How the Kita-Gutschein system works by Bundesland, when to apply (1 year before!), priority criteria for Ausbildung trainees, costs.' },
  { slug: 'marriage-germany-foreigners-process',                 category: 'family',     keyword: 'marriage Germany foreigner Standesamt paperwork',             brief: 'Standesamt appointment, Ehefähigkeitszeugnis from Morocco, apostille and translation requirements, costs, how the residence status changes.' },
  { slug: 'having-baby-germany-cost-bureaucracy',                category: 'family',     keyword: 'having a baby Germany cost benefits',                          brief: 'Hospital costs covered by GKV, midwife (Hebamme) system, birth registration, applying for the baby Steuer-ID and Kindergeld.' },
  { slug: 'school-system-foreign-children-germany',              category: 'family',     keyword: 'German school system foreign children Grundschule Abitur',     brief: 'Grundschule → Hauptschule/Realschule/Gymnasium pathway, when foreign kids enter, Willkommensklasse for non-German speakers, support resources.' },

  // ── WORK CULTURE & RIGHTS (8) ───────────────────────────────
  { slug: 'probezeit-ausbildung-trial-period',                   category: 'work-culture', keyword: 'Probezeit Ausbildung trial period rights',                  brief: 'How long Probezeit lasts, what either party can do (terminate without cause), 2-week notice rule, what counts as fair feedback.' },
  { slug: 'urlaubsanspruch-vacation-days-ausbildung',            category: 'work-culture', keyword: 'Urlaubsanspruch Ausbildung vacation days',                   brief: 'Statutory minimum (24 days young trainees), how Tarifvertrag changes it, planning vacation around Berufsschule, carrying days over.' },
  { slug: 'krankschreibung-sick-rules-ausbildung',               category: 'work-culture', keyword: 'Krankschreibung sick days Ausbildung rules',                 brief: 'Rules for calling in sick (call before shift, eAU, when employer needs the note), pay during sickness, what happens if you "exceed" sick days.' },
  { slug: 'mobbing-workplace-rights-germany',                    category: 'work-culture', keyword: 'mobbing workplace Germany rights what to do',                brief: 'What counts as mobbing under German law, evidence to collect, escalation chain (boss → Betriebsrat → DGB hotline → labor lawyer).' },
  { slug: 'betriebsrat-works-council-trainee',                   category: 'work-culture', keyword: 'Betriebsrat Ausbildung works council trainee',                brief: 'What a Betriebsrat does, how it protects Auszubildende, the Jugend- und Auszubildendenvertretung, how to bring concerns confidentially.' },
  { slug: 'discrimination-foreign-trainees-germany',             category: 'work-culture', keyword: 'workplace discrimination foreign trainees Germany AGG',       brief: 'AGG (anti-discrimination law) protections, evidence and witnesses, time limits for complaints, free counseling at antidiskriminierungsstelle.' },
  { slug: 'overtime-ausbildung-germany-rules',                   category: 'work-culture', keyword: 'overtime Ausbildung Germany rules limits',                   brief: 'Overtime rules for adults vs minors, daily and weekly limits under JArbSchG, compensation (extra pay or time off), what to do if pressured.' },
  { slug: 'quitting-ausbildung-process-consequences',            category: 'work-culture', keyword: 'quit Ausbildung Germany process consequences',                brief: 'Notice periods, when you can quit during Probezeit vs after, visa consequences, finding a new training spot, how to time the move.' },

  // ── TAXES & PAYCHECKS (8) ───────────────────────────────────
  { slug: 'lohnabrechnung-ausbildung-explained',                 category: 'taxes',      keyword: 'Lohnabrechnung Ausbildung paycheck explained',                brief: 'Walking through every line of an Ausbildung paycheck: brutto, Lohnsteuer, Soli, KV, RV, AV, PV, netto. Visual example with real numbers.' },
  { slug: 'steuerklassen-1-to-6-explained',                      category: 'taxes',      keyword: 'Steuerklassen 1 to 6 explained Germany',                      brief: 'All six tax classes, who falls into each, common combinations for couples (3/5 vs 4/4), how kids change Klasse 2.' },
  { slug: 'steuererklarung-ausbildung-when-how',                 category: 'taxes',      keyword: 'Steuererklärung Ausbildung when how to file',                 brief: 'Whether trainees must file (usually no, but should), the deadline, free tools (WISO, ELSTER, Taxfix), refund expectations.' },
  { slug: 'elster-foreign-trainee-guide',                        category: 'taxes',      keyword: 'ELSTER tax portal foreign trainee Germany',                  brief: 'Setting up an ELSTER account from abroad, certificate file vs ID-card login, common forms (Anlage N, Anlage Vorsorgeaufwand).' },
  { slug: 'werbungskosten-deductions-trainees',                  category: 'taxes',      keyword: 'Werbungskosten Ausbildung tax deductions',                    brief: 'Pendlerpauschale, work clothes, German classes, study supplies, exam fees — what trainees can deduct and how to track receipts.' },
  { slug: 'solidaritatszuschlag-church-tax-explained',           category: 'taxes',      keyword: 'Solidaritätszuschlag church tax Germany opt out',             brief: 'When Soli applies (mostly not anymore), how Kirchensteuer works, formal Kirchenaustritt for Moroccans never registered, savings.' },
  { slug: 'social-security-contributions-ausbildung',            category: 'taxes',      keyword: 'social security contributions Ausbildung Germany',            brief: 'KV, RV, AV, PV — what each one funds, the trainee-specific rules (employer pays everything below ~€325 brutto), what builds toward Niederlassung.' },
  { slug: 'morocco-tax-return-while-in-germany',                 category: 'taxes',      keyword: 'Morocco tax return while in Germany',                         brief: 'Whether Moroccan tax residents abroad must file, the Morocco-Germany double-tax treaty basics, what to declare, deadlines.' },

  // ── CAREER GROWTH POST-AUSBILDUNG (6) ───────────────────────
  { slug: 'ubernahme-after-ausbildung-strategy',                 category: 'career-growth', keyword: 'Übernahme after Ausbildung strategy hired',                brief: 'How to position for being kept on, salary negotiation post-Ausbildung, alternatives if not Übernommen, timing.' },
  { slug: 'permanent-residency-niederlassungserlaubnis',         category: 'career-growth', keyword: 'Niederlassungserlaubnis permanent residency apply',         brief: 'Eligibility post-Ausbildung (2 years), language requirement, Rentenversicherung months, the full document checklist.' },
  { slug: 'german-citizenship-5-year-path',                      category: 'career-growth', keyword: 'German citizenship 5 year path Ausbildung',                  brief: 'The new 2024 citizenship law: 5-year path, 3 years for "special integration", dual-citizenship now allowed, B1 + Einbürgerungstest.' },
  { slug: 'meister-techniker-fachwirt-explained',                category: 'career-growth', keyword: 'Meister Techniker Fachwirt Aufstiegsfortbildung',           brief: 'When to pursue each, costs and funding (Aufstiegs-BAföG), salary impact, time commitment, who hires.' },
  { slug: 'studying-after-ausbildung-bachelor-master',           category: 'career-growth', keyword: 'study after Ausbildung Bachelor Master Germany',             brief: 'Going to FH or Uni after Ausbildung — fast-track entry without Abitur, BAföG, dual studies, how it stacks with work experience.' },
  { slug: 'switching-jobs-after-ausbildung-visa',                category: 'career-growth', keyword: 'switch jobs after Ausbildung visa rules',                    brief: 'Changing employers post-Ausbildung: residence-permit job-search clause, Blue Card route, when to inform Ausländerbehörde.' },

  // ── DRIVER'S LICENSE & TRANSPORT (5) ────────────────────────
  { slug: 'convert-moroccan-driving-license-germany',            category: 'driving-transport', keyword: 'convert Moroccan driving license Germany',              brief: 'The 6-month conversion deadline, Theorie + Praxis exam (or full waiver?), translation requirements, Führerscheinstelle process, costs (~€450).' },
  { slug: 'deutschland-ticket-explained',                        category: 'driving-transport', keyword: 'Deutschland-Ticket €58 nationwide transit',              brief: 'What the ticket covers (regional + city, not ICE), how to buy, monthly subscription model, Job-Ticket discount, traveling with bikes.' },
  { slug: 'buying-car-germany-foreigner',                        category: 'driving-transport', keyword: 'buy a car Germany foreigner registration insurance',    brief: 'New vs used, Hauptuntersuchung (TÜV), Kfz-Steuer, mandatory Haftpflichtversicherung, registering at the Zulassungsstelle.' },
  { slug: 'cycling-rules-germany',                               category: 'driving-transport', keyword: 'cycling rules Germany helmet laws theft',                brief: 'Bike paths and one-way exemptions, helmet recommendation (not mandatory adult), lights, alcohol limit, how to register the frame against theft.' },
  { slug: 'long-distance-travel-from-germany',                   category: 'driving-transport', keyword: 'long-distance travel from Germany Flixbus ICE EasyJet',  brief: 'Comparing Flixbus, ICE Sparpreis, BlaBlaCar, low-cost airlines for European travel, when each makes sense for an Ausbildung budget.' },

  // ── RELIGION & COMMUNITY (5) ────────────────────────────────
  { slug: 'halal-food-germany-where-to-buy',                     category: 'religion-community', keyword: 'halal food Germany supermarkets restaurants',           brief: 'Big supermarket halal sections (Edeka, Rewe), Turkish/Arab grocery chains, halal restaurant directories, online butchers.' },
  { slug: 'mosques-germany-major-cities',                        category: 'religion-community', keyword: 'mosques Germany major cities directory',                 brief: 'Major mosques and Islamic centers in Berlin, Munich, Hamburg, Frankfurt, Cologne — Friday prayer times, Arabic-speaking imams.' },
  { slug: 'ramadan-germany-fasting-ausbildung',                  category: 'religion-community', keyword: 'Ramadan Germany fasting work Ausbildung',                brief: 'Long summer fasts, eating before/after work shifts, talking to your employer about adjusted hours, where to break fast.' },
  { slug: 'moroccan-diaspora-associations-germany',              category: 'religion-community', keyword: 'Moroccan diaspora associations Germany community',       brief: 'List of major Moroccan cultural associations and clubs by city, embassy and consular network, French/Arabic-language community events.' },
  { slug: 'praying-at-work-rights-germany',                      category: 'religion-community', keyword: 'praying at work Germany rights Muslim',                  brief: 'AGG protection of religious practice, asking for short breaks, finding a quiet room, real-life examples from large German employers.' },

  // ── MONEY BEYOND BANKING (5) ────────────────────────────────
  { slug: 'send-money-morocco-best-options',                     category: 'money',      keyword: 'send money to Morocco from Germany best app',                brief: 'Wise vs Western Union vs PayPal vs bank SEPA — fees, exchange rates, transfer speed, the €15k anti-money-laundering threshold.' },
  { slug: 'schufa-credit-history-foreigner',                     category: 'money',      keyword: 'SCHUFA credit history Germany foreigner build',              brief: 'What SCHUFA records, how to start a clean record from scratch, how to get a Schufa-Auskunft (free 1×/year), avoiding negative entries.' },
  { slug: 'etf-investing-basics-trainees',                       category: 'money',      keyword: 'ETF investing Germany trainee starter',                       brief: 'Sparplan basics, Trade Republic vs Scalable, world index ETFs, why €25/month for 30 years beats a savings account, tax wrapper.' },
  { slug: 'riester-rente-pension-explained',                     category: 'money',      keyword: 'Riester-Rente Germany worth it 2026',                          brief: 'How Riester works, who actually benefits in 2026, Zulagen, alternatives (private ETF), recent reforms.' },
  { slug: 'insurance-basics-germany-haftpflicht-hausrat',        category: 'money',      keyword: 'insurance Germany Haftpflicht Hausrat BU explained',           brief: 'The 3 insurances every Ausbildung trainee should consider: Privathaftpflicht (mandatory in spirit), Hausrat (depends on stuff value), Berufsunfähigkeit (long-term).' },
]
